== The Internals of Apache Kafka {{ book.version }}

Welcome to *The Internals of Apache Kafka* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Apache Kafka as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], a freelance IT consultant, software engineer and technical instructor specializing in Apache Spark, *Apache Kafka* and Kafka Streams (with Scala, sbt).

I offer software development and consultancy services with hands-on in-depth workshops and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing https://bit.ly/mastering-kafka-streams[The Internals of Kafka Streams], https://bit.ly/mastering-spark-sql[The Internals of Spark SQL], https://bit.ly/spark-structured-streaming[The Internals of Spark Structured Streaming], and https://bit.ly/mastering-apache-spark[Mastering Apache Spark] gitbooks.

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<kafka-overview.adoc#, Apache Kafka>>.
