== [[AbstractCoordinator]] AbstractCoordinator Contract

`AbstractCoordinator` is the <<contract, base>> of <<extensions, Coordinators>> that <<FIXME, FIXME>>.

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

[[extensions]]
NOTE: <<kafka-consumer-internals-ConsumerCoordinator.adoc#, ConsumerCoordinator>> is the one and only known implementation of the <<contract, AbstractCoordinator Contract>> in Apache Kafka's Consumer API.

[[contract]]
.AbstractCoordinator Contract (Abstract Methods Only)
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| metadata
a| [[metadata]]

[source, java]
----
List<ProtocolMetadata> metadata()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, sendJoinGroupRequest>>

| onJoinComplete
a| [[onJoinComplete]]

[source, java]
----
void onJoinComplete(
  int generation,
  String memberId,
  String protocol,
  ByteBuffer memberAssignment)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the request to <<initiateJoinGroup, initiateJoinGroup>> succeeded)

| onJoinPrepare
a| [[onJoinPrepare]]

[source, java]
----
void onJoinPrepare(
  int generation,
  String memberId)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the <<needsJoinPrepare, needsJoinPrepare>> flag is on)

| performAssignment
a| [[performAssignment]]

[source, java]
----
Map<String, ByteBuffer> performAssignment(
  String leaderId,
  String protocol,
  Map<String, ByteBuffer> allMemberMetadata)
----

Performs partition assignment

Used exclusively when `AbstractCoordinator` is requested to <<onJoinLeader, onJoinLeader>>

| protocolType
a| [[protocolType]]

[source, java]
----
String protocolType()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, sendJoinGroupRequest>>

|===

[[internal-registries]]
.AbstractCoordinator's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| coordinator
a| [[coordinator]] Group Coordinator (as a Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/Node.html[Node])

Initialized when `FindCoordinatorResponseHandler` is requested to <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onSuccess, onSuccess>>

| findCoordinatorFuture
| [[findCoordinatorFuture]] <<kafka-consumer-internals-RequestFuture.adoc#, ++RequestFuture<Void>++>> for <<sendFindCoordinatorRequest, sendFindCoordinatorRequest>> when <<lookupCoordinator, lookupCoordinator>>

Reset in <<clearFindCoordinatorFuture, clearFindCoordinatorFuture>>

Used in <<lookupCoordinator, lookupCoordinator>> and when `HeartbeatThread` is requested to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#run, run>>

| generation
a| [[generation]] Defaults to `NO_GENERATION`

| heartbeatThread
a| [[heartbeatThread]] <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#, HeartbeatThread>>

Initialized and immediately started when `AbstractCoordinator` is requested to <<startHeartbeatThreadIfNeeded, start a HeartbeatThread>>

| joinFuture
| [[joinFuture]] <<kafka-consumer-internals-RequestFuture.adoc#, ++RequestFuture<ByteBuffer>++>> for <<sendJoinGroupRequest, sendJoinGroupRequest>> when <<initiateJoinGroup, initiateJoinGroup>>

Reset in <<resetJoinGroupFuture, resetJoinGroupFuture>>

Used in <<rejoinNeededOrPending, rejoinNeededOrPending>> and <<initiateJoinGroup, initiateJoinGroup>>

| needsJoinPrepare
| [[needsJoinPrepare]] Flag to control whether to execute <<onJoinPrepare, onJoinPrepare>> while performing <<joinGroupIfNeeded, joinGroupIfNeeded>>

| rejoinNeeded
a| [[rejoinNeeded]]

[source, java]
----
boolean rejoinNeeded
----

Flag to control whether to <<rejoinNeededOrPending, rejoinNeededOrPending>>. Enabled (`true`) by default.

Turned off (`false`) when the <<joinFuture, joinFuture>> completed successfully in <<initiateJoinGroup, initiateJoinGroup>>

Turned on (`true`) in <<resetGeneration, resetGeneration>> and <<requestRejoin, requestRejoin>>

| state
a| [[state]] Defaults to `UNJOINED`

|===

[[logging]]
[TIP]
====
Enable `WARN`, `INFO`, or `DEBUG` logging level for `org.apache.kafka.clients.consumer.internals.AbstractCoordinator` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.consumer.internals.AbstractCoordinator=DEBUG
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[creating-instance]] Creating AbstractCoordinator Instance

`AbstractCoordinator` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] <<kafka-consumer-internals-ConsumerNetworkClient.adoc#, ConsumerNetworkClient>>
* [[groupId]] Group ID
* [[rebalanceTimeoutMs]] `rebalanceTimeoutMs`
* [[sessionTimeoutMs]] `sessionTimeoutMs`
* [[heartbeatIntervalMs]] `heartbeatIntervalMs` (or simply [[heartbeat]] a `Heartbeat` instance)
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[metricGrpPrefix]] Metric group prefix
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[leaveGroupOnClose]] `leaveGroupOnClose` flag

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

=== [[joinGroupIfNeeded]] `joinGroupIfNeeded` Method

[source, java]
----
boolean joinGroupIfNeeded(final Timer timer)
----

`joinGroupIfNeeded`...FIXME

NOTE: `joinGroupIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[initiateJoinGroup]] `initiateJoinGroup` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> initiateJoinGroup()
----

`initiateJoinGroup`...FIXME

NOTE: `initiateJoinGroup` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>.

=== [[ensureActiveGroup]] `ensureActiveGroup` Method

[source, java]
----
void ensureActiveGroup() // <1>
boolean ensureActiveGroup(final Timer timer)
----
<1> Calls the other `ensureActiveGroup` in an infinite `while` loop with an unexpiring timer

`ensureActiveGroup`...FIXME

NOTE: `ensureActiveGroup` is used exclusively when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>>.

=== [[lookupCoordinator]] Discovering Current Coordinator for Consumer Group -- `lookupCoordinator` Method

[source, java]
----
RequestFuture<Void> lookupCoordinator()
----

`lookupCoordinator` uses the <<findCoordinatorFuture, RequestFuture>> internal registry to know whether it was requested earlier but have not finished yet. In other words, the <<findCoordinatorFuture, RequestFuture>> is available when looking up a coordinator of a consumer group is in progress.

If the <<findCoordinatorFuture, RequestFuture>> internal registry is available (not a `null`), `lookupCoordinator` returns it immediately.

Otherwise, when the <<findCoordinatorFuture, RequestFuture>> internal registry is uninitialized (`null`), `lookupCoordinator` requests the <<client, ConsumerNetworkClient>> for the <<kafka-consumer-internals-ConsumerNetworkClient.adoc#leastLoadedNode, least-loaded Kafka broker>>. `lookupCoordinator` then <<sendFindCoordinatorRequest, sends a FindCoordinatorRequest to the Kafka broker>>.

`lookupCoordinator` prints out the following DEBUG message to the logs when no nodes are available and finishes with a `RequestFuture.noBrokersAvailable` failure.

```
No broker available to send FindCoordinator request
```

[NOTE]
====
`lookupCoordinator` is used when:

* `AbstractCoordinator` is requested to <<ensureCoordinatorReady, ensureCoordinatorReady>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsAsync, commitOffsetsAsync>>

* `HeartbeatThread` is requested to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#run, run>>
====

=== [[ensureCoordinatorReady]] `ensureCoordinatorReady` Method

[source, java]
----
boolean ensureCoordinatorReady(final Timer timer)
----

`ensureCoordinatorReady`...FIXME

[NOTE]
====
`ensureCoordinatorReady` is used when:

* `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>> and <<joinGroupIfNeeded, joinGroupIfNeeded>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#fetchCommittedOffsets, fetchCommittedOffsets>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#close, close>>, and <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsSync, commitOffsetsSync>>
====

=== [[sendJoinGroupRequest]] `sendJoinGroupRequest` Method

[source, java]
----
RequestFuture<ByteBuffer> sendJoinGroupRequest()
----

`sendJoinGroupRequest`...FIXME

NOTE: `sendJoinGroupRequest` is used exclusively when `AbstractCoordinator` is requested to <<initiateJoinGroup, initiateJoinGroup>>.

=== [[sendSyncGroupRequest]] `sendSyncGroupRequest` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> sendSyncGroupRequest(
  SyncGroupRequest.Builder requestBuilder)
----

`sendSyncGroupRequest`...FIXME

NOTE: `sendSyncGroupRequest` is used when...FIXME

=== [[sendFindCoordinatorRequest]] Sending FindCoordinatorRequest (to Kafka Broker) -- `sendFindCoordinatorRequest` Internal Method

[source, java]
----
RequestFuture<Void> sendFindCoordinatorRequest(Node node)
----

`sendFindCoordinatorRequest` prints out the following DEBUG message to the logs:

```
Sending FindCoordinator request to broker [node]
```

`sendFindCoordinatorRequest` creates a new <<kafka-common-requests-FindCoordinatorRequest.adoc#, FindCoordinatorRequest>> with `GROUP` type and the <<groupId, groupId>>.

In the end, `sendFindCoordinatorRequest` requests the <<client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#send, send>> the `FindCoordinatorRequest` (to the given Kafka node) and then uses a new <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#, FindCoordinatorResponseHandler>> to handle a response.

NOTE: `sendFindCoordinatorRequest` is used exclusively when `AbstractCoordinator` is requested to <<lookupCoordinator, lookupCoordinator>>.

=== [[maybeLeaveGroup]] `maybeLeaveGroup` Method

[source, java]
----
void maybeLeaveGroup()
----

`maybeLeaveGroup`...FIXME

NOTE: `maybeLeaveGroup` is used when...FIXME

=== [[sendHeartbeatRequest]] `sendHeartbeatRequest` Method

[source, java]
----
RequestFuture<Void> sendHeartbeatRequest()
----

`sendHeartbeatRequest`...FIXME

NOTE: `sendHeartbeatRequest` is used when...FIXME

=== [[onJoinLeader]] `onJoinLeader` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> onJoinLeader(JoinGroupResponse joinResponse)
----

`onJoinLeader`...FIXME

NOTE: `onJoinLeader` is used exclusively when `JoinGroupResponseHandler` is requested to <<kafka-consumer-internals-JoinGroupResponseHandler.adoc#handle, handle>>.

=== [[resetJoinGroupFuture]] `resetJoinGroupFuture` Internal Method

[source, java]
----
void resetJoinGroupFuture()
----

`resetJoinGroupFuture` simply resets the <<joinFuture, joinFuture>> internal registry (i.e. sets it to `null`).

NOTE: `resetJoinGroupFuture` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>.

=== [[clearFindCoordinatorFuture]] Clearing FindCoordinatorFuture -- `clearFindCoordinatorFuture` Internal Method

[source, java]
----
void clearFindCoordinatorFuture()
----

`clearFindCoordinatorFuture` simply resets the <<findCoordinatorFuture, findCoordinatorFuture>> internal registry (to be `null`).

NOTE: `clearFindCoordinatorFuture` is used exclusively when `FindCoordinatorResponseHandler` is requested to <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onSuccess, onSuccess>> and <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onFailure, onFailure>>.

=== [[rejoinNeededOrPending]] `rejoinNeededOrPending` Internal Method

[source, java]
----
boolean rejoinNeededOrPending()
----

`rejoinNeededOrPending` is positive (`true`) when <<rejoinNeeded, rejoinNeeded>> and <<joinFuture, joinFuture>> is initialized (i.e. not `null`).

[NOTE]
====
`rejoinNeededOrPending` is used when:

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#rejoinNeededOrPending, rejoinNeededOrPending>> and <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>

* `KafkaConsumer` is requested to <<kafka-consumer-KafkaConsumer.adoc#pollForFetches, pollForFetches>>

* `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>
====

=== [[pollHeartbeat]] `pollHeartbeat` Method

[source, java]
----
void pollHeartbeat(long now)
----

`pollHeartbeat`...FIXME

NOTE: `pollHeartbeat` is used exclusively when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for Coordinator events>>.

=== [[startHeartbeatThreadIfNeeded]] Starting HeartbeatThread -- `startHeartbeatThreadIfNeeded` Internal Method

[source, java]
----
void startHeartbeatThreadIfNeeded()
----

`startHeartbeatThreadIfNeeded`...FIXME

NOTE: `startHeartbeatThreadIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[needRejoin]] `needRejoin` Method

[source, java]
----
boolean needRejoin()
----

`needRejoin` simply returns the <<rejoinNeeded, rejoinNeeded>> flag.

NOTE: `needRejoin` is used when...FIXME

=== [[requestRejoin]] `requestRejoin` Method

[source, java]
----
void requestRejoin()
----

`requestRejoin` simply turns the <<rejoinNeeded, rejoinNeeded>> flag on.

[NOTE]
====
`requestRejoin` is used when:

* `HeartbeatResponseHandler` is requested to <<kafka-consumer-internals-HeartbeatResponseHandler.adoc#handle, handle a response>> that the consumer group is rebalancing

* `SyncGroupResponseHandler` is requested to <<kafka-consumer-internals-SyncGroupResponseHandler.adoc#handle, handle a response>> with an error
====

=== [[resetGeneration]] `resetGeneration` Method

[source, java]
----
void resetGeneration()
----

`resetGeneration` simply resets the following internal registries:

* <<generation, generation>> becomes `NO_GENERATION`

* <<rejoinNeeded, rejoinNeeded>> is turned on

* <<state, state>> is `UNJOINED`

[NOTE]
====
`resetGeneration` is used when:

* `AbstractCoordinator` is requested to <<maybeLeaveGroup, maybeLeaveGroup>>

* <<kafka-consumer-internals-HeartbeatResponseHandler.adoc#, HeartbeatResponseHandler>>, <<kafka-consumer-internals-JoinGroupResponseHandler.adoc#, JoinGroupResponseHandler>>, <<kafka-consumer-internals-SyncGroupResponseHandler.adoc#, SyncGroupResponseHandler>>, and <<kafka-consumer-internals-OffsetCommitResponseHandler.adoc#, OffsetCommitResponseHandler>> are requested to handle a response with an error (`UNKNOWN_MEMBER_ID`, `ILLEGAL_GENERATION`, or `REBALANCE_IN_PROGRESS`)
====

=== [[coordinatorUnknown]] `coordinatorUnknown` Method

[source, java]
----
boolean coordinatorUnknown()
----

`coordinatorUnknown`...FIXME

NOTE: `coordinatorUnknown` is used when...FIXME
