== Demo: ACL Authorization Using AclAuthorizer

This demo shows how to use link:kafka-security-authorizer-AclAuthorizer.adoc[AclAuthorizer] for link:kafka-security-authorization.adoc[ACL authorization].

CAUTION: The demo is not finished yet.

=== Step X. Enable ACL Authorization

Add the following to `config/server.properties`:

```
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
```

Start a Kafka broker and observe the logs. You may find the following at the very end of the startup:

```
ERROR [KafkaApi-0] Error when handling request: clientId=0, correlationId=0, api=UPDATE_METADATA, version=6, body={controller_id=0,controller_epoch=5,broker_epoch=151,topic_states=[],live_brokers=[{id=0,endpoints=[{port=9092,host=localhost,listener=PLAINTEXT,security_protocol=0,_tagged_fields={}}],rack=null,_tagged_fields={}}],_tagged_fields={}} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=0, connectionId=127.0.0.1:9092-127.0.0.1:64483-0, session=Session(User:ANONYMOUS,/127.0.0.1), listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT, buffer=null) is not authorized.
```

That's because `User:ANONYMOUS` user is not authorized to execute `UPDATE_METADATA` action (since by default no one is allowed to execute any action).

=== Step X. Allow Everyone If No ACL Found

Add the following to `config/server.properties` and restart the broker.

```
allow.everyone.if.no.acl.found=true
```

=== Step X. Define Super Users

Add the following to `config/server.properties` and restart the broker.

```
super.users=User:Bob;User:Alice
```

=== Step X. List ACLs

Use link:kafka-tools-kafka-acls.adoc[kafka-acls] CLI to list the available ACLs.

```
kafka-acls.sh \
  --bootstrap-server :9092 \
  --list
```

=== Step X. Disable Creating Topics

Use link:kafka-tools-kafka-acls.adoc[kafka-acls] CLI to disable creating topics for anyone but super users.

```
kafka-acls.sh \
  --bootstrap-server :9092 \
  --add \
  --allow-principal User:Alice \
  --operation All \
  --topic '*' \
  --cluster
```

=== Step X. Setting Up TLS/SSL - Certificate Authority (CA)

Create a directory for SSL files.

```
mkdir -p /tmp/kafka-ssl
```

NOTE: All the following commands are executed in `/tmp/kafka-ssl` directory.

```
cd /tmp/kafka-ssl
```

Generate a private key for the CA.

```
openssl genrsa -out ca.key
```

Generating a self-signed root CA.

```
$ openssl req -new -x509 -key ca.key -out ca.crt
...
Country Name (2 letter code) []:PL
State or Province Name (full name) []:
Locality Name (eg, city) []:
Organization Name (eg, company) []:Japila
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:localhost
Email Address []:
```

=== Step X. Setting Up TLS/SSL - Kafka Brokers

Generate the private key for the server.

```
openssl genrsa -out server.key
```

Create a certificate signing request (CSR).

NOTE: DistinguishedName or SubjectAltNames should be the fully-qualified domain name of a broker.

```
$ openssl req -new -key server.key -out server.csr
...
Country Name (2 letter code) []:PL
State or Province Name (full name) []:
Locality Name (eg, city) []:
Organization Name (eg, company) []:Japila
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:localhost
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
```

Sign the certificate signing request with the root CA.

```
openssl x509 \
  -req \
  -in server.csr \
  -days 3650 \
  -sha1 \
  -CAcreateserial \
  -CA ca.crt \
  -CAkey ca.key \
  -out server.crt
```

Create a SSL keystore for the Kafka broker. Each broker gets its own unique keystore.

CAUTION: FIXME How is that different from the server key `server.key` generated above?! Looks like they're similar if not the same.

```
keytool \
  -genkey \
  -alias server \
  -dname CN=localhost \
  -keystore server.keystore \
  -keyalg RSA \
  -validity 365 \
  -ext SAN=DNS:localhost
```

NOTE: `-ext SAN=DNS:localhost` configures a *SubjectAlternativeName*.

Use the following command to list the generated certificate in the SSL keystore.

```
keytool -list -v -keystore server.keystore
```

Export the server certificate.

```
keytool \
  -certreq \
  -keystore server.keystore \
  -alias server \
  -file server.unsigned.crt
```

Import the CA certificate to a SSL truststore for Kafka brokers. All brokers in a Kafka cluster should trust the CA used to sign certificates.

```
$ keytool \
  -importcert \
  -keystore server.truststore \
  -alias ca \
  -file ca.crt

Enter keystore password:
Re-enter new password:
Owner: CN=localhost, O=Japila, C=PL
Issuer: CN=localhost, O=Japila, C=PL
Serial number: b34b3f43cda5bf56
Valid from: Thu Feb 20 14:03:57 CET 2020 until: Sat Mar 21 14:03:57 CET 2020
Certificate fingerprints:
	 SHA1: A5:D4:58:E1:A5:55:F0:90:7C:E8:DD:A8:64:49:E3:61:ED:89:FD:13
	 SHA256: 71:73:AC:40:83:EE:75:B9:C2:4A:3C:5F:E5:8D:18:A2:A6:A0:25:2D:52:B4:24:96:D9:7A:C4:80:8F:32:4C:D6
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 1
Trust this certificate? [no]:  yes
Certificate was added to keystore
```

=== Step X. Setting Up TLS/SSL - Kafka Clients

Generate the private key for the client.

```
openssl genrsa -out client.key
```

Create a certificate signing request.

```
$ openssl req -new -key client.key -out client.csr
...
Country Name (2 letter code) []:PL
State or Province Name (full name) []:
Locality Name (eg, city) []:
Organization Name (eg, company) []:Japila
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:localhost
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
```

Sign the certificate.

```
openssl x509 \
  -req \
  -in client.csr \
  -days 3650 \
  -sha1 \
  -CAcreateserial \
  -CA ca.crt \
  -CAkey ca.key \
  -out client.crt
```

Export the server certificate to be signed by the CA.

```
keytool \
  -certreq \
  -alias server \
  -keystore server.keystore \
  -file server.unsigned.crt
```

Sign the Kafka broker's certificate using the root CA.

```
openssl x509 \
  -req \
  -CA ca.crt \
  -CAkey ca.key \
  -in server.unsigned.crt \
  -out server.signed.crt \
  -days 365 \
  -CAcreateserial
```

Import the CA certificate into the SSL keystore.

```
keytool \
  -import \
  -keystore server.keystore \
  -alias ca \
  -file ca.crt
```

Import the signed server certificate into the SSL keystore.

```
keytool \
  -import \
  -keystore server.keystore \
  -alias server \
  -file server.signed.crt
```

=== Step X. Setting Up TLS/SSL

TIP: Use `export KAFKA_OPTS=-Djavax.net.debug=all` to debug SSL issues. Consult the source code of Java's https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/src/java.base/share/classes/sun/security/ssl/SSLLogger.java[SSLLogger].

Configure a Kafka broker to use the SSL keystore and truststore files.

Edit `config/server.properties` to include the following properties:

```
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=true
super.users=User:Bob;User:Alice

listeners=PLAINTEXT://:9092,SSL://:9093
ssl.keystore.location=/tmp/kafka-ssl/kafka01.keystore.jks
ssl.keystore.password=123456
ssl.key.password=123456
ssl.truststore.location=/tmp/kafka-ssl/kafka.truststore.jks
ssl.truststore.password=123456
ssl.client.auth=required
```

Test the Kafka configuration.

```
openssl s_client -debug -connect localhost:9093 -tls1
```

Exit out of this command using `Ctrl+C`.

=== Step X. Using SSL for Client Authentication

TIP: Use `export KAFKA_OPTS=-Djavax.net.debug=all` to debug SSL issues.

Create the client SSL keystore.

```
keytool \
  -keystore client.keystore \
  -alias client \
  -validity 365 \
  -keyalg RSA \
  -genkey \
  -ext SAN=DNS:localhost
```

Export the client certificate.

```
keytool \
  -keystore client.keystore \
  -alias client \
  -certreq \
  -file client.unsigned.crt
```

Sign the client certificate with the CA.

```
openssl x509 \
  -req \
  -CA ca.crt \
  -CAkey ca.key \
  -in client.unsigned.crt \
  -out client.signed.crt \
  -days 365 \
  -CAcreateserial
```

Import the root CA to the client SSL keystore.

```
keytool \
  -import \
  -keystore client.keystore \
  -alias ca \
  -file ca.crt
```

Import the signed client certificate to the client SSL keystore.

```
keytool \
  -import \
  -keystore client.keystore \
  -alias client \
  -file client.signed.crt
```

Import the CA certificate to the client SSL truststore.

```
$ keytool \
  -importcert \
  -keystore client.truststore \
  -alias ca \
  -file ca.crt
```

Create `client-ssl.properties` configuration file.

```
security.protocol=SSL
ssl.truststore.location=/tmp/kafka-ssl/client.truststore
ssl.truststore.password=123456
ssl.keystore.location=/tmp/kafka-ssl/client.keystore
ssl.keystore.password=123456
ssl.key.password=123456
ssl.client.auth=required
```

Use `kafka-console-producer.sh` to send a message to the Kafka broker using SSL.

```
kafka-console-producer.sh \
  --broker-list :9093 \
  --topic test \
  --producer.config /tmp/kafka-ssl/client-ssl.properties
```
