== Overview of Kafka

http://kafka.apache.org/[Apache Kafka] is an open source project for a high-throughput distributed messaging system rethought as a distributed commit log.

Kafka comes with the following features:

1. *Topics* that are virtual groups of partitions to send messages to and read them from.

1. *Partitions* with messages -- topics can be partitioned to improve read/write performance and resiliency. You can lay out a topic (as partitions) across a cluster of machines to allow data streams larger than the capability of a single machine. Partitions are log files on disk with sequential write only. Kafka guarantees message ordering in a partition.

1. Kafka *broker* that hosts topics.

1. Kafka *cluster* that is supposed to be the central data backbone for an organization.

1. *Messages* are data in the partitions of a topic. Messages are sequentially appended to the end of the partition log file and numbered as offsets. They are persisted on disk (aka _disk-based persistence_) and replicated within the cluster to prevent data loss. It has an in-memory page cache to improve data reads. Messages are in partitions until deleted when *TTL* occurs or after *compaction*.

3. Multiple concurrent *producers* that send (aka _push_) messages to topics which is appending the messages to the end of partitions. They can batch messages before they are sent over the wire to a topic. Producers support message compression. Producers can send messages in synchronous (with acknowledgement) or asynchronous mode.

4. Multiple concurrent *consumers* read (aka _pull_) messages from topics however they want using offsets. Unlike typical messaging systems, Kafka consumers pull messages from a topic using offsets.

4. *Offsets* that are message positions in a topic to read by consumers.
