== [[Cleaner]] Cleaner

`Cleaner` is <<creating-instance, created>> exclusively for a <<kafka-log-CleanerThread.adoc#cleaner, CleanerThread>>.

`Cleaner` requires that the number of slots in the given <<offsetMap, OffsetMap>> multiplied by the given <<dupBufferLoadFactor, dupBufferLoadFactor>> is greater than 1 or the following exception is thrown:

```
offset map is too small to fit in even a single message, so log cleaning will never make progress. You can increase log.cleaner.dedupe.buffer.size or decrease log.cleaner.threads
```

[[logIdent]]
`Cleaner` uses *Cleaner [id]:* prefix for <<logging, logging>> (with the given <<id, ID>>).

[[logging]]
TIP: `Cleaner` uses <<kafka-log-LogCleaner.adoc#logging, kafka.log.LogCleaner>> logger.

=== [[creating-instance]] Creating Cleaner Instance

`Cleaner` takes the following to be created:

* [[id]] ID
* [[offsetMap]] `OffsetMap`
* [[ioBufferSize]] `ioBufferSize`
* [[maxIoBufferSize]] `maxIoBufferSize`
* [[dupBufferLoadFactor]] <<kafka-log-LogCleaner.adoc#dedupeBufferLoadFactor, dupBufferLoadFactor>> (of the <<kafka-log-LogCleaner.adoc#config, CleanerConfig>> of the parent <<kafka-log-LogCleaner.adoc#, LogCleaner>>) (default: `0.9d`)
* [[throttler]] `Throttler`
* [[time]] `Time`
* [[checkDone]] "Check Done" function (`TopicPartition => Unit`)

`Cleaner` initializes the <<internal-properties, internal properties>>.

=== [[clean]] Cleaning Log -- `clean` Method

[source, scala]
----
clean(cleanable: LogToClean): (Long, CleanerStats)
----

`clean`...FIXME

NOTE: `clean` is used exclusively when `CleanerThread` is requested to <<kafka-log-CleanerThread.adoc#cleanLog, clean a log>>.

=== [[doClean]] Cleaning Log -- `doClean` Method

[source, scala]
----
doClean(
  cleanable: LogToClean,
  deleteHorizonMs: Long): (Long, CleanerStats)
----

`doClean`...FIXME

NOTE: `doClean` is used when `Cleaner` is requested to <<clean, clean a log>>.

==== [[cleanSegments]] `cleanSegments` Internal Method

[source, scala]
----
cleanSegments(
  log: Log,
  segments: Seq[LogSegment],
  map: OffsetMap,
  deleteHorizonMs: Long,
  stats: CleanerStats,
  transactionMetadata: CleanedTransactionMetadata): Unit
----

`cleanSegments`...FIXME

NOTE: `cleanSegments` is used exclusively when `Cleaner` is requested to <<doClean, clean a log>>.

==== [[cleanInto]] `cleanInto` Internal Method

[source, scala]
----
cleanInto(
  topicPartition: TopicPartition,
  sourceRecords: FileRecords,
  dest: LogSegment,
  map: OffsetMap,
  retainDeletesAndTxnMarkers: Boolean,
  maxLogMessageSize: Int,
  transactionMetadata: CleanedTransactionMetadata,
  lastRecordsOfActiveProducers: Map[Long, LastRecord],
  stats: CleanerStats): Unit
----

`cleanInto`...FIXME

NOTE: `cleanInto` is used exclusively when `Cleaner` is requested to <<cleanSegments, cleanSegments>>.

==== [[buildOffsetMap]] `buildOffsetMap` Internal Method

[source, scala]
----
buildOffsetMap(
  log: Log,
  start: Long,
  end: Long,
  map: OffsetMap,
  stats: CleanerStats): Unit
----

`buildOffsetMap`...FIXME

NOTE: `buildOffsetMap` is used exclusively when `Cleaner` is requested to <<doClean, doClean>>.

==== [[buildOffsetMapForSegment]] `buildOffsetMapForSegment` Internal Method

[source, scala]
----
buildOffsetMapForSegment(
  topicPartition: TopicPartition,
  segment: LogSegment,
  map: OffsetMap,
  startOffset: Long,
  maxLogMessageSize: Int,
  transactionMetadata: CleanedTransactionMetadata,
  stats: CleanerStats): Boolean
----

`buildOffsetMapForSegment`...FIXME

NOTE: `buildOffsetMapForSegment` is used exclusively when `Cleaner` is requested to <<buildOffsetMap, buildOffsetMap>>.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| decompressionBufferSupplier
a| [[decompressionBufferSupplier]] FIXME

Used when...FIXME

| readBuffer
a| [[readBuffer]] FIXME

Used when...FIXME

| writeBuffer
a| [[writeBuffer]] FIXME

Used when...FIXME

|===
