== [[HeartbeatThread]] HeartbeatThread

`HeartbeatThread` is a daemon Kafka thread of execution that `AbstractCoordinator` starts to <<run, send HeartbeatRequests to the group coordinator>> regularly (aka _heartbeating_).

`HeartbeatThread` is <<creating-instance, created>> and immediately <<run, started>> exclusively for `AbstractCoordinator` when requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#startHeartbeatThreadIfNeeded, start a HeartbeatThread>> (when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>> after `KafkaConsumer` was requested to <<poll, poll for records>>).

[[name]]
`HeartbeatThread` uses *kafka-coordinator-heartbeat-thread* prefix followed by the <<kafka-consumer-internals-AbstractCoordinator.adoc#groupId, group ID>> as the thread name.

```
kafka-coordinator-heartbeat-thread | [groupId]
```

[[closed]]
`HeartbeatThread` uses `closed` flag to indicate...FIXME

[[enabled]]
`HeartbeatThread` uses `enabled` flag to indicate...FIXME

[[creating-instance]]
`HeartbeatThread` takes no arguments to be created.

=== [[run]] Starting Thread -- `run` Method

[source, java]
----
void run()
----

NOTE: `run` is part of the https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runnable.html[java.lang.Runnable] to start itself as a separately-executing thread.

`run` prints out the following DEBUG message to the logs:

```
Heartbeat thread started
```

In an infinite `while` loop, `run` does the following (infinitely):

. Checks the internal state to exit or wait:

.. Exits when <<closed, closed>>

.. Waits for `AbstractCoordinator` to wake it up when not <<enabled, enabled>>

. Requests the <<kafka-consumer-internals-AbstractCoordinator.adoc#client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#pollNoWakeup, pollNoWakeup>>

. <<kafka-consumer-internals-AbstractCoordinator.adoc#sendHeartbeatRequest, Sends a HeartbeatRequest to the group coordinator>>

. (when the response eventually arrives) Requests the <<heartbeat, Heartbeat>> to record a success (`receiveHeartbeat`) or a failure (`failHeartbeat`)

In the end, when the infinite `while` loop is terminated for any reason, `run` prints out the following DEBUG message to the logs:

```
Heartbeat thread has closed
```

WARNING: `run` does some other state control checks but they look uninteresting...to me...now.
