== [[SslAuthenticator]] SslAuthenticator

`SslAuthenticator` is an link:kafka-common-network-Authenticator.adoc[Authenticator] for link:kafka-common-network-KafkaChannel.adoc[KafkaChannel] when link:kafka-clients-CommonClientConfigs.adoc#security.protocol[security.protocol] configuration property is `SSL`.

`SslAuthenticator` is <<creating-instance, created>> (lazily as part of `Supplier<Authenticator>`) when `SslChannelBuilder` is requested to link:kafka-common-network-SslChannelBuilder.adoc#buildChannel[build a channel].

`SslAuthenticator` is an internal class of link:kafka-common-network-SslChannelBuilder.adoc[SslChannelBuilder].

=== [[creating-instance]] Creating SslAuthenticator Instance

`SslAuthenticator` takes the following to be created:

* [[configs]] Configuration properties
* [[transportLayer]] `SslTransportLayer`
* [[listenerName]] `ListenerName`
* [[sslPrincipalMapper]] link:kafka-common-security-ssl-SslPrincipalMapper.adoc[SslPrincipalMapper]

`SslAuthenticator` initializes the <<principalBuilder, KafkaPrincipalBuilder>>.

=== [[principalBuilder]] SslAuthenticator and KafkaPrincipalBuilder

[source, java]
----
KafkaPrincipalBuilder principalBuilder
----

`principalBuilder` is a `KafkaPrincipalBuilder`.

`principalBuilder` is link:kafka-common-network-ChannelBuilders.adoc#createPrincipalBuilder[created] for `SslAuthenticator` based on the given <<configs, configuration properties>>, the <<transportLayer, SslTransportLayer>> and the <<sslPrincipalMapper, SslPrincipalMapper>>.

=== [[principal]] `principal` Method

[source, java]
----
KafkaPrincipal principal()
----

NOTE: `principal` is part of the link:kafka-common-network-Authenticator.adoc#principal[Authenticator] contract to...FIXME.

`principal`...FIXME
