== [[KafkaScheduler]] KafkaScheduler

`KafkaScheduler` is a <<contract, Scheduler>> to <<schedule, schedule tasks>> in Kafka.

[[internal-registries]]
.KafkaScheduler's Internal Properties (e.g. Registries and Counters)
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[executor]] `executor`
| Java's link:https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html[ScheduledThreadPoolExecutor] used to <<schedule, schedule tasks>>.

Initialized when <<startup, `KafkaScheduler` starts up>> and shut down when <<shutdown, `KafkaScheduler` shuts down>>.
|===

[[logging]]
[TIP]
====
Enable `INFO` or `DEBUG` logging levels for `kafka.utils.KafkaScheduler` logger to see what happens in `KafkaScheduler`.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.utils.KafkaScheduler=DEBUG, stdout
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[startup]] Starting Up -- `startup` Method

[source, scala]
----
startup(): Unit
----

NOTE: `startup` is a part of <<contract, Scheduler contract>>.

When `startup` is executed, you should see the following DEBUG message in the logs:

```
DEBUG Initializing task scheduler. (kafka.utils.KafkaScheduler)
```

`startup` initializes <<executor, executor>> with `threads` threads. The name of the threads is in format of `threadNamePrefix` followed by `schedulerThreadId`, e.g. `kafka-scheduler-0`

NOTE: `threads` and `threadNamePrefix` are defined when <<creating-instance, `KafkaScheduler` is created>>.

If `KafkaScheduler` is already started, `startup` throws a `IllegalStateException` with the message:

```
This scheduler has already been started!
```

=== [[creating-instance]] Creating KafkaScheduler Instance

CAUTION: FIXME

=== [[shutdown]] `shutdown` Method

CAUTION: FIXME

=== [[ensureRunning]] `ensureRunning` Internal Method

CAUTION: FIXME

=== [[schedule]] Scheduling Tasks -- `schedule` Method

[source, scala]
----
schedule(name: String, fun: () => Unit, delay: Long, period: Long, unit: TimeUnit): Unit
----

NOTE: `schedule` is a part of <<contract, Scheduler contract>> to schedule tasks.

When `schedule` is executed, you should see the following DEBUG message in the logs:

```
DEBUG Scheduling task [name] with initial delay [delay] ms and period [period] ms. (kafka.utils.KafkaScheduler)
```

NOTE: `schedule` uses Java's link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html#convert-long-java.util.concurrent.TimeUnit-++[java.util.concurrent.TimeUnit] to convert `delay` and `period` to milliseconds.

`schedule` first <<ensureRunning, makes sure that `KafkaScheduler` is running>> (which simply means that the internal <<executor, executor>> has been initialized).

`schedule` creates an execution thread for the input `fun`.

For positive `period`, `schedule` schedules the thread every `period` after the initial `delay`. Otherwise, `schedule` schedules the thread once.

NOTE: `schedule` uses the internal <<executor, executor>> to schedule `fun` using link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.scheduleAtFixedRate] and link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#schedule-java.lang.Runnable-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.schedule] for periodic and one-off executions, respectively.

Whenever the thread is executed, and before `fun` gets triggerred, you should see the following TRACE message in the logs:

```
Beginning execution of scheduled task '[name]'.
```

After the execution thread is finished, you should see the following TRACE message in the logs:

```
Completed execution of scheduled task '[name]'.
```

In case of any exceptions, the execution thread catches them and you should see the following ERROR message in the logs:

```
Uncaught exception in scheduled task '[name]'
```

=== [[contract]] Scheduler Contract

[source, scala]
----
trait Scheduler {
  def startup(): Unit
  def shutdown(): Unit
  def isStarted: Boolean
  def schedule(name: String, fun: () => Unit, delay: Long = 0, period: Long = -1, unit: TimeUnit = TimeUnit.MILLISECONDS)
}
----

.Scheduler Contract
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `schedule`
| Schedules a task

|===
