== [[LogConfig]] LogConfig

`LogConfig` is an `AbstractConfig` for the <<properties, topic-level configuration properties>>.

`LogConfig` uses the keys that are symonyms (aliases) of the keys of link:kafka-common-TopicConfig.adoc#keys[TopicConfig]. As the link:++https://github.com/apache/kafka/blob/ac385c4c3a770728848438f28f4acb8854ffc868/clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java#L29++[TopicConfig] itself says: "_Eventually this should replace LogConfig.scala._"

[[properties]]
.LogConfig's Topic-Level Configuration Properties
[cols="30,70",options="header",width="100%"]
|===
| Name
| Description

| link:kafka-common-TopicConfig.adoc#CLEANUP_POLICY_CONFIG[cleanup.policy]
a| [[CleanupPolicyProp]][[cleanup.policy]] Cluster-wide property: link:kafka-properties.adoc#log.cleanup.policy[log.cleanup.policy]

Default: `delete`

Used when:

* `GroupCoordinator` is requested for the <<kafka-coordinator-group-GroupCoordinator.adoc#offsetsTopicConfigs, offsetsTopicConfigs>>

* `TransactionStateManager` is requested for the <<kafka-TransactionStateManager.adoc#transactionTopicConfigs, transactionTopicConfigs>>

* `LogConfig` is requested for the <<compact, compact>> and <<delete, delete>> flags

* `KafkaServer` utility is used to link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[create a default log properties for LogManager and AdminManager]

| link:kafka-common-TopicConfig.adoc#COMPRESSION_TYPE_CONFIG[compression.type]
a| [[CompressionTypeProp]][[compression.type]]

| link:kafka-common-TopicConfig.adoc#DELETE_RETENTION_MS_CONFIG[delete.retention.ms]
a| [[DeleteRetentionMsProp]][[delete.retention.ms]]

| link:kafka-common-TopicConfig.adoc#FILE_DELETE_DELAY_MS_CONFIG[file.delete.delay.ms]
a| [[FileDeleteDelayMsProp]][[fileDeleteDelayMs]][[file.delete.delay.ms]] The time (in millis) to wait before deleting a file from the filesystem. Must be at least `0`

Property: `file.delete.delay.ms`

Default: `60000`

| link:kafka-common-TopicConfig.adoc#FLUSH_MESSAGES_INTERVAL_CONFIG[flush.messages]
a| [[FlushMessagesProp]][[flushInterval]][[flush.messages]] Cluster-wide property: link:kafka-properties.adoc#log.flush.interval.messages[log.flush.interval.messages]

| link:kafka-common-TopicConfig.adoc#FLUSH_MS_CONFIG[flush.ms]
a| [[flushMs]][[FlushMsProp]][[flush.ms]] Cluster-wide property: link:kafka-properties.adoc#log.flush.interval.ms[log.flush.interval.ms]

| link:kafka-common-TopicConfig.adoc#INDEX_INTERVAL_BYTES_CONFIG[index.interval.bytes]
a| [[indexInterval]][[IndexIntervalBytesProp]][[index.interval.bytes]]

| link:kafka-common-TopicConfig.adoc#MAX_COMPACTION_LAG_MS_CONFIG[max.compaction.lag.ms]
a| [[MaxCompactionLagMsProp]][[max.compaction.lag.ms]]

| link:kafka-common-TopicConfig.adoc#MAX_MESSAGE_BYTES_CONFIG[max.message.bytes]
a| [[MaxMessageBytesProp]][[max.message.bytes]]

| link:kafka-common-TopicConfig.adoc#MESSAGE_DOWNCONVERSION_ENABLE_CONFIG[message.downconversion.enable]
a| [[MessageDownConversionEnableProp]][[message.downconversion.enable]]

| link:kafka-common-TopicConfig.adoc#MESSAGE_FORMAT_VERSION_CONFIG[message.format.version]
a| [[MessageFormatVersionProp]][[message.format.version]]

| link:kafka-common-TopicConfig.adoc#MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS_CONFIG[message.timestamp.difference.max.ms]
a| [[MessageTimestampDifferenceMaxMsProp]][[message.timestamp.difference.max.ms]]

| link:kafka-common-TopicConfig.adoc#MESSAGE_TIMESTAMP_TYPE_CONFIG[message.timestamp.type]
a| [[MessageTimestampTypeProp]][[message.timestamp.type]]

| link:kafka-common-TopicConfig.adoc#MIN_CLEANABLE_DIRTY_RATIO_CONFIG[min.cleanable.dirty.ratio]
a| [[MinCleanableDirtyRatioProp]][[min.cleanable.dirty.ratio]]

| link:kafka-common-TopicConfig.adoc#MIN_COMPACTION_LAG_MS_CONFIG[min.compaction.lag.ms]
a| [[MinCompactionLagMsProp]][[min.compaction.lag.ms]]

| link:kafka-common-TopicConfig.adoc#MIN_IN_SYNC_REPLICAS_CONFIG[min.insync.replicas]
a| [[minInSyncReplicas]][[MinInSyncReplicasProp]][[min.insync.replicas]] Cluster-wide property: link:kafka-properties.adoc#min.insync.replicas[min.insync.replicas]

Used when:

* `TransactionStateManager` is requested for link:kafka-TransactionStateManager.adoc#transactionTopicConfigs[transactionTopicConfigs]

* `KafkaServer` utility is used to link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[create a default log properties for LogManager and AdminManager] (with the value of link:kafka-server-KafkaConfig.adoc#minInSyncReplicas[KafkaConfig.minInSyncReplicas])

* `Partition` is requested to link:kafka-cluster-Partition.adoc#isUnderMinIsr[isUnderMinIsr], link:kafka-cluster-Partition.adoc#isAtMinIsr[isAtMinIsr], link:kafka-cluster-Partition.adoc#checkEnoughReplicasReachOffset[checkEnoughReplicasReachOffset], link:kafka-cluster-Partition.adoc#appendRecordsToLeader[appendRecordsToLeader]

| link:kafka-common-TopicConfig.adoc#PREALLOCATE_CONFIG[preallocate]
a| [[PreAllocateEnableProp]][[preallocate]]

| link:kafka-common-TopicConfig.adoc#RETENTION_BYTES_CONFIG[retention.bytes]
a| [[RetentionBytesProp]][[retentionSize]][[retention.bytes]]

Used when:

* `KafkaServer` utility is requested for link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[default configuration properties of logs]

* `Log` is requested to link:kafka-log-Log.adoc#deleteRetentionSizeBreachedSegments[deleteRetentionSizeBreachedSegments]

| link:kafka-common-TopicConfig.adoc#RETENTION_MS_CONFIG[retention.ms]
a| [[RetentionMsProp]][[retentionMs]][[retention.ms]] Cluster-wide property: link:kafka-properties.adoc#log.retention.ms[log.retention.ms]

Used exclusively when `Log` is requested to <<kafka-log-Log.adoc#deleteRetentionMsBreachedSegments, deleteRetentionMsBreachedSegments>>

| link:kafka-common-TopicConfig.adoc#SEGMENT_BYTES_CONFIG[segment.bytes]
a| [[SegmentBytesProp]][[segmentSize]][[segment.bytes]] Cluster-wide property: link:kafka-properties.adoc#log.segment.bytes[log.segment.bytes]

Used when:

* `GroupCoordinator` is requested for the <<kafka-coordinator-group-GroupCoordinator.adoc#offsetsTopicConfigs, offsetsTopicConfigs>>

* `TransactionStateManager` is requested for the <<kafka-TransactionStateManager.adoc#transactionTopicConfigs, transactionTopicConfigs>>

* `KafkaServer` utility is used to link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[create a default log properties for LogManager and AdminManager]

The current value is available as `LogConfig.segmentSize` and used when:

* `RollParams` utility is requested to <<kafka-log-RollParams.adoc#apply, create a RollParams>>

* `Log` is requested for the <<kafka-log-Log.adoc#initFileSize, initFileSize>> and to <<kafka-log-Log.adoc#append, append records>>

* `Cleaner` is requested to <<kafka-log-Cleaner.adoc#doClean, clean a log>>

| link:kafka-common-TopicConfig.adoc#SEGMENT_INDEX_BYTES_CONFIG[segment.index.bytes]
a| [[maxIndexSize]][[SegmentIndexBytesProp]][[segment.index.bytes]] Cluster-wide property: link:kafka-properties.adoc#log.index.size.max.bytes[log.index.size.max.bytes]

| link:kafka-common-TopicConfig.adoc#SEGMENT_JITTER_MS_CONFIG[segment.jitter.ms]
a| [[SegmentJitterMsProp]][[segmentJitterMs]][[segment.jitter.ms]]

| link:kafka-common-TopicConfig.adoc#SEGMENT_MS_CONFIG[segment.ms]
a| [[SegmentMsProp]][[segmentMs]][[segment.ms]] Cluster-wide property: link:kafka-properties.adoc#log.roll.ms[log.roll.ms]

Default: `604800000` (7 days)

Used when:

* `Log` is requested to <<kafka-log-Log.adoc#maybeRoll, maybeRoll>>

* `LogConfig` is requested for the <<randomSegmentJitter, randomSegmentJitter>> and <<maxSegmentMs, maxSegmentMs>>

* `KafkaServer` utility is used to link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[create a default log properties for LogManager and AdminManager]

| link:kafka-common-TopicConfig.adoc#UNCLEAN_LEADER_ELECTION_ENABLE_CONFIG[unclean.leader.election.enable]
a| [[UncleanLeaderElectionEnableProp]][[uncleanLeaderElectionEnable]][[unclean.leader.election.enable]] Cluster-wide property: link:kafka-properties.adoc#unclean.leader.election.enable[unclean.leader.election.enable]

Disabled (`false`) explicity for the `__transaction_state` internal topic (when `TransactionStateManager` is requested for the link:kafka-TransactionStateManager.adoc#transactionTopicConfigs[transactionTopicConfigs] for link:kafka-server-KafkaApis.adoc#createInternalTopic[KafkaApis])

Used when:

* `ZkPartitionStateMachine` is requested to link:kafka-controller-ZkPartitionStateMachine.adoc#collectUncleanLeaderElectionState[collectUncleanLeaderElectionState]

* `DynamicLogConfig` is requested to link:kafka-server-DynamicLogConfig.adoc#reconfigure[reconfigure] (and requests the `KafkaController` to link:kafka-controller-KafkaController.adoc#enableDefaultUncleanLeaderElection[enableDefaultUncleanLeaderElection])

|===

=== [[TopicConfigSynonyms]] TopicConfigSynonyms

`TopicConfigSynonyms` are the <<properties, topic-level configuration properties>> (with the highest priority) with their corresponding cluster-wide (broker-level) configuration properties.

NOTE: `TopicConfigSynonyms` uses the same configuration properties as link:kafka-server-KafkaServer.adoc#copyKafkaConfigToLog[KafkaServer.copyKafkaConfigToLog] utility.

.TopicConfigSynonyms
[cols="30,70",options="header",width="100%"]
|===
| Topic-Level Property Name
| Cluster-Wide Property Name

| <<cleanup.policy, cleanup.policy>>
| link:kafka-server-KafkaConfig.adoc#LogCleanupPolicyProp[log.cleanup.policy]

| <<compression.type, compression.type>>
| link:kafka-server-KafkaConfig.adoc#CompressionTypeProp[compression.type]

| <<delete.retention.ms, delete.retention.ms>>
| link:kafka-server-KafkaConfig.adoc#LogCleanerDeleteRetentionMsProp[log.cleaner.delete.retention.ms]

| <<file.delete.delay.ms, file.delete.delay.ms>>
| link:kafka-server-KafkaConfig.adoc#LogDeleteDelayMsProp[log.segment.delete.delay.ms]

| <<flush.messages, flush.messages>>
| link:kafka-server-KafkaConfig.adoc#LogFlushIntervalMessagesProp[log.flush.interval.messages]

| <<flush.ms, flush.ms>>
| link:kafka-server-KafkaConfig.adoc#LogFlushIntervalMsProp[log.flush.interval.ms]

| <<index.interval.bytes, index.interval.bytes>>
| link:kafka-server-KafkaConfig.adoc#LogIndexIntervalBytesProp[log.index.interval.bytes]

| <<max.compaction.lag.ms, max.compaction.lag.ms>>
| link:kafka-server-KafkaConfig.adoc#LogCleanerMaxCompactionLagMsProp[log.cleaner.max.compaction.lag.ms]

| <<max.message.bytes, max.message.bytes>>
| link:kafka-server-KafkaConfig.adoc#MessageMaxBytesProp[message.max.bytes]

| <<message.downconversion.enable, message.downconversion.enable>>
| link:kafka-server-KafkaConfig.adoc#LogMessageDownConversionEnablePro[log.message.downconversion.enable]

| <<message.format.version, message.format.version>>
| link:kafka-server-KafkaConfig.adoc#LogMessageFormatVersionProp[log.message.format.version]

| <<message.timestamp.difference.max.ms, message.timestamp.difference.max.ms>>
| link:kafka-server-KafkaConfig.adoc#LogMessageTimestampDifferenceMaxMsProp[log.message.timestamp.difference.max.ms]

| <<message.timestamp.type, message.timestamp.type>>
| link:kafka-server-KafkaConfig.adoc#LogMessageTimestampTypeProp[log.message.timestamp.type]

| <<min.cleanable.dirty.ratio, min.cleanable.dirty.ratio>>
| link:kafka-server-KafkaConfig.adoc#LogCleanerMinCleanRatioProp[log.cleaner.min.cleanable.ratio]

| <<min.compaction.lag.ms, min.compaction.lag.ms>>
| link:kafka-server-KafkaConfig.adoc#LogCleanerMinCompactionLagMsProp[log.cleaner.min.compaction.lag.ms]

| <<min.insync.replicas, min.insync.replicas>>
| link:kafka-server-KafkaConfig.adoc#MinInSyncReplicasProp[min.insync.replicas]

| <<preallocate, preallocate>>
| link:kafka-server-KafkaConfig.adoc#LogPreAllocateProp[log.preallocate]

| <<retention.bytes, retention.bytes>>
| link:kafka-server-KafkaConfig.adoc#LogRetentionBytesProp[log.retention.bytes]

| <<retention.ms, retention.ms>>
| link:kafka-server-KafkaConfig.adoc#LogRetentionTimeMillisProp[log.retention.ms]

| <<segment.bytes, segment.bytes>>
| link:kafka-server-KafkaConfig.adoc#LogSegmentBytesProp[log.segment.bytes]

| <<segment.index.bytes, segment.index.bytes>>
| link:kafka-server-KafkaConfig.adoc#LogIndexSizeMaxBytesProp[log.index.size.max.bytes]

| <<segment.jitter.ms, segment.jitter.ms>>
| link:kafka-server-KafkaConfig.adoc#LogRollTimeJitterMillisProp[log.roll.jitter.ms]

| <<segment.ms, segment.ms>>
| link:kafka-server-KafkaConfig.adoc#LogRollTimeMillisProp[log.roll.ms]

| <<unclean.leader.election.enable, unclean.leader.election.enable>>
| link:kafka-server-KafkaConfig.adoc#UncleanLeaderElectionEnableProp[unclean.leader.election.enable]

|===

[NOTE]
====
`TopicConfigSynonyms` is used when:

* `AdminManager` is requested to link:kafka-server-AdminManager.adoc#describeConfigs[describe the configuration of a topic] and link:kafka-server-AdminManager.adoc#createTopics[create topics] (and link:kafka-server-AdminManager.adoc#createTopicConfigEntry[createTopicConfigEntry])

* `DynamicLogConfig` utility is requested for the link:kafka-server-DynamicLogConfig.adoc#ReconfigurableConfigs[ReconfigurableConfigs] and the link:kafka-server-DynamicLogConfig.adoc#KafkaConfigToLogConfigName[KafkaConfigToLogConfigName]
====

=== [[randomSegmentJitter]] `randomSegmentJitter` Method

[source, scala]
----
randomSegmentJitter: Long
----

`randomSegmentJitter` is one of the following values:

* `0` if <<segmentJitterMs, segment.jitter.ms>> is `0`

* Random int value modulo the minimum of <<segmentJitterMs, segment.jitter.ms>> and <<segmentMs, segment.ms>>

NOTE: `randomSegmentJitter` is used when `LogSegment` utility is used to <<kafka-log-LogSegment.adoc#open, open a log segment>> (for the <<kafka-log-LogSegment.adoc#rollJitterMs, rollJitterMs>> property).

=== [[maxSegmentMs]] `maxSegmentMs` Method

[source, scala]
----
maxSegmentMs: Long
----

`maxSegmentMs`...FIXME

NOTE: `maxSegmentMs` is used when `RollParams` utility is used to <<kafka-log-RollParams.adoc#apply, create a RollParams instance>>.

=== [[compact]] Checking Out Whether Compact Cleanup Policy Is Enabled -- `compact` Flag

[source, scala]
----
compact: Boolean
----

`compact`...FIXME

NOTE: `compact` is used when...FIXME

=== [[delete]] Checking Out Whether Delete Cleanup Policy Is Enabled -- `delete` Flag

[source, scala]
----
delete: Boolean
----

`delete` flag is enabled (`true`) when <<kafka-log-cleanup-policies.adoc#delete, delete>> cleanup policy is part of the <<kafka-log-cleanup-policies.adoc#cleanup.policy, cleanup.policy>> configuration property. Otherwise, `delete` flag is disabled (`false`).

[NOTE]
====
`delete` is used when:

* `Partition` is requested to <<kafka-cluster-Partition.adoc#deleteRecordsOnLeader, deleteRecordsOnLeader>>

* `Log` is requested to <<kafka-log-Log.adoc#deleteOldSegments, deleteOldSegments>>

* `LogCleanerManager` utility is requested for <<kafka-log-LogCleanerManager.adoc#isCompactAndDelete, isCompactAndDelete>>
====
