== [[DynamicBrokerConfig]] DynamicBrokerConfig

`DynamicBrokerConfig` is <<creating-instance, created>> exclusively when `KafkaConfig` is <<kafka-server-KafkaConfig.adoc#dynamicConfig, created>>.

`DynamicBrokerConfig` is used to create a <<kafka-server-KafkaConfig.adoc#dynamicConfigOverride, KafkaConfig>>.

NOTE: `DynamicBrokerConfig` is <<creating-instance, created>> when <<kafka-server-KafkaConfig.adoc#dynamicConfig, KafkaConfig>> is, but the reverse is also true (!) Isn't it a dependency cycle? Not really since `KafkaConfig` will create a <<kafka-server-KafkaConfig.adoc#dynamicConfig, DynamicBrokerConfig>> unless one is provided.

[[kafkaConfig]]
[[creating-instance]]
`DynamicBrokerConfig` takes a single <<kafka-server-KafkaConfig.adoc#, KafkaConfig>> when created.

[[logging]]
[TIP]
====
Enable `ALL` logging levels for `kafka.server.DynamicBrokerConfig` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.server.DynamicBrokerConfig=ALL
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[AllDynamicConfigs]] AllDynamicConfigs

`AllDynamicConfigs` are...FIXME

[NOTE]
====
`AllDynamicConfigs` is used when:

* `AdminManager` is requested to link:kafka-server-AdminManager.adoc#createBrokerConfigEntry[createBrokerConfigEntry]

* `DynamicBrokerConfig` utility is requested for the <<DynamicPasswordConfigs, DynamicPasswordConfigs>>, to <<addDynamicConfigs, addDynamicConfigs>> and for the <<dynamicConfigUpdateModes, dynamicConfigUpdateModes>>
====

=== [[DynamicPasswordConfigs]] DynamicPasswordConfigs

`DynamicPasswordConfigs` are...FIXME

[NOTE]
====
`DynamicPasswordConfigs` is used when...FIXME
====

=== [[addDynamicConfigs]] `addDynamicConfigs` Internal Utility

[source, scala]
----
addDynamicConfigs(
  configDef: ConfigDef): Unit
----

`addDynamicConfigs`...FIXME

NOTE: `addDynamicConfigs` is used when...FIXME

=== [[dynamicConfigUpdateModes]] `dynamicConfigUpdateModes` Internal Utility

[source, scala]
----
dynamicConfigUpdateModes: util.Map[String, String]
----

`dynamicConfigUpdateModes`...FIXME

NOTE: `dynamicConfigUpdateModes` is used when...FIXME

=== [[addBrokerReconfigurable]] `addBrokerReconfigurable` Method

[source, scala]
----
addBrokerReconfigurable(reconfigurable: BrokerReconfigurable): Unit
----

`addBrokerReconfigurable`...FIXME

NOTE: `addBrokerReconfigurable` is used when...FIXME

=== [[processReconfiguration]] `processReconfiguration` Internal Method

[source, scala]
----
processReconfiguration(
  newProps: Map[String, String],
  validateOnly: Boolean): (KafkaConfig, List[BrokerReconfigurable])
----

`processReconfiguration`...FIXME

NOTE: `processReconfiguration` is used when `DynamicBrokerConfig` is requested to <<validate, validate>> (with `validateOnly` flag enabled) and <<updateCurrentConfig, updateCurrentConfig>> (with `validateOnly` flag disabled).

=== [[updateCurrentConfig]] `updateCurrentConfig` Internal Method

[source, scala]
----
updateCurrentConfig(): Unit
----

`updateCurrentConfig`...FIXME

NOTE: `updateCurrentConfig` is used when `DynamicBrokerConfig` is requested to <<updateBrokerConfig, updateBrokerConfig>> and <<updateDefaultConfig, updateDefaultConfig>>.

=== [[currentDynamicDefaultConfigs]] `currentDynamicDefaultConfigs` Method

[source, scala]
----
currentDynamicDefaultConfigs: Map[String, String]
----

`currentDynamicDefaultConfigs` simply clones the <<dynamicDefaultConfigs, dynamicDefaultConfigs>>.

NOTE: `currentDynamicDefaultConfigs` is used when `AdminManager` is requested to <<kafka-server-AdminManager.adoc#configSynonyms, configSynonyms>> and <<kafka-server-AdminManager.adoc#describeConfigs, describeConfigs>>.

=== [[initialize]] Initializing (Fetching Broker Configuration From Zookeeper) -- `initialize` Method

[source, scala]
----
initialize(zkClient: KafkaZkClient): Unit
----

`initialize` creates a new <<kafka-server-KafkaConfig.adoc#creating-instance, KafkaConfig>> (with the <<kafka-server-KafkaConfig.adoc#props, properties>> of the initial <<kafkaConfig, KafkaConfig>>) that becomes the <<currentConfig, currentConfig>>.

`initialize` creates a `AdminZkClient` (with the input <<kafka-zk-KafkaZkClient.adoc#, KafkaZkClient>>).

`initialize` requests the `AdminZkClient` to <<kafka-zk-AdminZkClient.adoc#fetchEntityConfig, fetch the default configuration>> for *brokers* entities and <<updateDefaultConfig, updateDefaultConfig>>

`initialize` requests the `AdminZkClient` to <<kafka-zk-AdminZkClient.adoc#fetchEntityConfig, fetch the configuration>> for the broker by the <<kafka-properties.adoc#broker.id, broker.id>>.

`initialize` <<maybeReEncodePasswords, maybeReEncodePasswords>> in the broker configuration and <<updateBrokerConfig, updateBrokerConfig>> with the <<kafka-properties.adoc#broker.id, broker.id>>.

NOTE: `initialize` is used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>.

=== [[updateDefaultConfig]] `updateDefaultConfig` Method

[source, scala]
----
updateDefaultConfig(persistentProps: Properties): Unit
----

`updateDefaultConfig`...FIXME

[NOTE]
====
`updateDefaultConfig` is used when:

* `BrokerConfigHandler` is requested to <<kafka-server-BrokerConfigHandler.adoc#processConfigChanges, processConfigChanges>>

* `DynamicBrokerConfig` is requested to <<initialize, initialize>>
====

=== [[updateBrokerConfig]] `updateBrokerConfig` Method

[source, scala]
----
updateBrokerConfig(
  brokerId: Int,
  persistentProps: Properties): Unit
----

`updateBrokerConfig`...FIXME

[NOTE]
====
`updateBrokerConfig` is used when:

* `BrokerConfigHandler` is requested to <<kafka-server-BrokerConfigHandler.adoc#processConfigChanges, processConfigChanges>>

* `DynamicBrokerConfig` is requested to <<initialize, initialize>>
====

=== [[maybeReEncodePasswords]] `maybeReEncodePasswords` Internal Method

[source, scala]
----
maybeReEncodePasswords(persistentProps: Properties, adminZkClient: AdminZkClient): Properties
----

`maybeReEncodePasswords`...FIXME

NOTE: `maybeReEncodePasswords` is used when...FIXME

=== [[addReconfigurables]] Registering (Adding) Reconfigurables For KafkaServer -- `addReconfigurables` Method

[source, scala]
----
addReconfigurables(kafkaServer: KafkaServer): Unit
----

`addReconfigurables` registers (_adds_) <<addBrokerReconfigurable, broker>> and <<addReconfigurable, regular>> reconfigurables.

Internally, `addReconfigurables` creates a <<kafka-server-DynamicThreadPool.adoc#, DynamicThreadPool>> with the input <<kafka-server-KafkaServer.adoc#, KafkaServer>> and <<addBrokerReconfigurable, addBrokerReconfigurable>>.

`addReconfigurables` <<addBrokerReconfigurable, addBrokerReconfigurable>> with the <<kafka-log-LogCleaner.adoc#, LogCleaner>> (if configured).

`addReconfigurables` creates a <<kafka-server-DynamicLogConfig.adoc#, DynamicThreadPool>> with the <<kafka-server-KafkaServer.adoc#logManager, LogManager>> and the input <<kafka-server-KafkaServer.adoc#, KafkaServer>>, and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicMetricsReporters.adoc#, DynamicMetricsReporters>> for the <<kafka-server-KafkaConfig.adoc#brokerId, broker>> and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicClientQuotaCallback.adoc#, DynamicClientQuotaCallback>> for the <<kafka-server-KafkaConfig.adoc#brokerId, broker>> and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicListenerConfig.adoc#, DynamicListenerConfig>> with the input <<kafka-server-KafkaServer.adoc#, KafkaServer>> and <<addBrokerReconfigurable, addBrokerReconfigurable>>.

NOTE: `addReconfigurables` is used exclusively  when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>.

=== [[validate]] `validate` Method

[source, scala]
----
validate(props: Properties, perBrokerConfig: Boolean): Unit
----

`validate`...FIXME

NOTE: `validate` is used exclusively when `AdminManager` is requested to <<kafka-server-AdminManager.adoc#alterConfigs, alterConfigs>> (when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleAlterConfigsRequest, handleAlterConfigsRequest>>).

=== [[maybeReconfigure]] `maybeReconfigure` Method

[source, scala]
----
maybeReconfigure(
  reconfigurable: Reconfigurable,
  oldConfig: KafkaConfig,
  newConfig: util.Map[String, _]): Unit
----

`maybeReconfigure`...FIXME

[NOTE]
====
`maybeReconfigure` is used when:

* `DynamicMetricsReporters` is requested to <<kafka-server-DynamicMetricsReporters.adoc#reconfigure, reconfigure>>

* `DynamicClientQuotaCallback` is requested to <<kafka-server-DynamicClientQuotaCallback.adoc#reconfigure, reconfigure>>
====

=== [[processReconfigurable]] `processReconfigurable` Method

[source, scala]
----
processReconfigurable(
  reconfigurable: Reconfigurable,
  updatedConfigNames: Set[String],
  allNewConfigs: util.Map[String, _],
  newCustomConfigs: util.Map[String, Object],
  validateOnly: Boolean): Unit
----

`processReconfigurable`...FIXME

NOTE: `processReconfigurable` is used when `DynamicBrokerConfig` is requested to <<processReconfiguration, processReconfiguration>> and <<processListenerReconfigurable, processListenerReconfigurable>>.

=== [[processListenerReconfigurable]] `processListenerReconfigurable` Internal Method

[source, scala]
----
processListenerReconfigurable(
  listenerReconfigurable: ListenerReconfigurable,
  newConfig: KafkaConfig,
  customConfigs: util.Map[String, Object],
  validateOnly: Boolean,
  reloadOnly:  Boolean): Unit
----

`processListenerReconfigurable`...FIXME

NOTE: `processListenerReconfigurable` is used when `DynamicBrokerConfig` is requested to <<reloadUpdatedFilesWithoutConfigChange, reloadUpdatedFilesWithoutConfigChange>> and <<processReconfiguration, processReconfiguration>>.

=== [[reloadUpdatedFilesWithoutConfigChange]] `reloadUpdatedFilesWithoutConfigChange` Internal Method

[source, scala]
----
reloadUpdatedFilesWithoutConfigChange(newProps: Properties): Unit
----

`reloadUpdatedFilesWithoutConfigChange`...FIXME

NOTE: `reloadUpdatedFilesWithoutConfigChange` is used exclusively when `AdminManager` is requested to <<kafka-server-AdminManager.adoc#alterConfigs, alterConfigs>> (when `KafkaApis` is requested to handle a <<kafka-server-KafkaApis.adoc#AlterConfigs, AlterConfigs>> request).

=== [[clear]] `clear` Method

[source, scala]
----
clear(): Unit
----

`clear`...FIXME

NOTE: `clear` is used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#shutdown, shut down>>.

=== [[validatedKafkaProps]] `validatedKafkaProps` Method

[source, scala]
----
validatedKafkaProps(
  propsOverride: Properties,
  perBrokerConfig: Boolean): Map[String, String]
----

`validatedKafkaProps`...FIXME

NOTE: `validatedKafkaProps` is used when...FIXME

=== [[addReconfigurable]] Registering Reconfigurable -- `addReconfigurable` Method

[source, scala]
----
addReconfigurable(
  reconfigurable: Reconfigurable): Unit
----

`addReconfigurable` <<verifyReconfigurableConfigs, verifyReconfigurableConfigs>> of the link:kafka-common-Reconfigurable.adoc#reconfigurableConfigs[Reconfigurable].

In the end, `addReconfigurable` adds the `Reconfigurable` to the <<reconfigurables, reconfigurables>> internal registry.

[NOTE]
====
`addReconfigurable` is used when:

* `DynamicBrokerConfig` is requested to <<addReconfigurables, addReconfigurables>>

* `KafkaConfig` is requested to link:kafka-server-KafkaConfig.adoc#addReconfigurable[add a Reconfigurable]
====

=== [[verifyReconfigurableConfigs]] `verifyReconfigurableConfigs` Internal Method

[source, scala]
----
verifyReconfigurableConfigs(
  configNames: Set[String]): Unit
----

`verifyReconfigurableConfigs`...FIXME

NOTE: `verifyReconfigurableConfigs` is used when...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| brokerReconfigurables
a| [[brokerReconfigurables]] <<kafka-server-BrokerReconfigurable.adoc#, BrokerReconfigurables>>

New reconfigurables registered in <<addBrokerReconfigurable, addBrokerReconfigurable>>

All removed in <<clear, clear>>

Used in <<processReconfiguration, processReconfiguration>>

| currentConfig
a| [[currentConfig]] Current <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>

Initialized with the input <<kafkaConfig, KafkaConfig>>.

Used when...FIXME

| dynamicDefaultConfigs
a| [[dynamicDefaultConfigs]] Dynamic configurations

Cleared and immediately updated in <<updateDefaultConfig, updateDefaultConfig>>

Used in <<validatedKafkaProps, validatedKafkaProps>> and <<updateCurrentConfig, updateCurrentConfig>>

Cleared when `DynamicBrokerConfig` is requested to <<clear, clear>>

Available using <<currentDynamicDefaultConfigs, currentDynamicDefaultConfigs>>

| reconfigurables
a| [[reconfigurables]] link:kafka-common-Reconfigurable.adoc[Reconfigurables]

|===
