== [[ConsumerConfig]] ConsumerConfig -- Configuration Properties for KafkaConsumer

`ConsumerConfig` is a Apache Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/config/AbstractConfig.html[AbstractConfig] for the <<properties, configuration properties>> of a <<kafka-consumer-KafkaConsumer.adoc#, KafkaConsumer>>.

[source, scala]
----
import org.apache.kafka.clients.consumer.ConsumerConfig

val conf = new java.util.Properties()
conf.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, ":9092,localhost:9192")
import org.apache.kafka.common.serialization.Serdes
conf.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, Serdes.String.deserializer.getClass)
conf.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, Serdes.String.deserializer.getClass)

import org.apache.kafka.clients.consumer.KafkaConsumer
val consumer = new KafkaConsumer[String, String](conf)
----

[[properties]]
.ConsumerConfig's Configuration Properties
[cols="1,3",options="header",width="100%"]
|===
| Name, Property, Default Value
| Description

| `BOOTSTRAP_SERVERS_CONFIG`

a| [[BOOTSTRAP_SERVERS_CONFIG]]

| `GROUP_ID_CONFIG`

a| [[GROUP_ID_CONFIG]]

| `METADATA_MAX_AGE_CONFIG`

`metadata.max.age.ms`

Default: 5 mins

a| [[METADATA_MAX_AGE_CONFIG]][[metadata.max.age.ms]] The period of time (in milliseconds) after which we force a refresh of metadata even if we haven't seen any partition leadership changes. That is to proactively discover any new brokers or partitions.

| `PARTITION_ASSIGNMENT_STRATEGY_CONFIG`

`partition.assignment.strategy`

Default: <<kafka-consumer-RangeAssignor.adoc#, RangeAssignor>>

a| [[PARTITION_ASSIGNMENT_STRATEGY_CONFIG]][[partition.assignment.strategy]] The class name of the partition assignment strategy that the client will use to distribute partition ownership amongst consumer instances when group management is used

TIP: Read up https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal[Kafka Client-side Assignment Proposal] on the group management in Apache Kafka's Consumer API.

Used when:

* `KafkaConsumer` is <<kafka-consumer-KafkaConsumer.adoc#assignors, created>>

* Kafka Streams' `StreamsConfig` is requested to `getMainConsumerConfigs`

NOTE: Required for `KafkaConsumer` to <<kafka-consumer-KafkaConsumer.adoc#subscribe, subscribe to topics>>

| `REQUEST_TIMEOUT_MS_CONFIG`

`request.timeout.ms`

Default: `30000` ms

a| [[REQUEST_TIMEOUT_MS_CONFIG]][[request.timeout.ms]] How long (in millis) a Kafka client waits for a response to a request.

If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.

Must be at least `0`

|===
