== [[KafkaServer]] KafkaServer

CAUTION: FIXME

`KafkaServer` acts as a Kafka broker.

`KafkaServer` <<creating-instance, registers itself in the JMX system>> under *kafka.server*.

[[internal-registries]]
.KafkaServer's Internal Registries and Counters
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[brokerState]] `brokerState`
| `BrokerState`

| [[_brokerTopicStats]] `_brokerTopicStats`
| `BrokerTopicStats`

| [[_clusterId]] `_clusterId`
| Cluster ID

| [[kafkaScheduler]] `kafkaScheduler`
| link:kafka-KafkaScheduler.adoc[KafkaScheduler] with...FIXME

| [[logContext]] `logContext`
| `LogContext`

| [[replicaManager]] `replicaManager`
| link:kafka-ReplicaManager.adoc[ReplicaManager]

| [[reporters]] `reporters`
| Collection of link:kafka-MetricsReporter.adoc[MetricsReporter]

Used when...FIXME

| [[quotaManagers]] `quotaManagers`
| `QuotaManagers`

| [[zkUtils]] `zkUtils`
| `ZkUtils`
|===

=== [[getBrokerIdAndOfflineDirs]] Getting Broker ID and Initial Offline Directories -- `getBrokerIdAndOfflineDirs` Internal Method

CAUTION: FIXME

=== [[getOrGenerateClusterId]] `getOrGenerateClusterId` Internal Method

CAUTION: FIXME

=== [[initZk]] `initZk` Internal Method

CAUTION: FIXME

=== [[startup]] `startup` Method

[source, scala]
----
startup(): Unit
----

`startup` starts a single Kafka server.

Internally, `startup` first prints out the following INFO message to the logs:

```
INFO starting (kafka.server.KafkaServer)
```

`startup` sets <<brokerState, BrokerState>> as `Starting`.

`startup` requests <<kafkaScheduler, KafkaScheduler>> to link:kafka-KafkaScheduler.adoc#startup[start].

`startup` <<initZk, connects to Zookeeper>> (and initializes <<zkUtils, ZkUtils>>).

`startup` <<getOrGenerateClusterId, getOrGenerateClusterId>> (that is recorded as <<_clusterId, cluster id>>).

You should see the following INFO message in the logs:

```
INFO Cluster ID = [clusterId] (kafka.server.KafkaServer)
```

`startup` <<getBrokerIdAndOfflineDirs, gets broker id and initial offline directories>>.

`startup` creates a `LogContext` with *[KafkaServer id=[brokerId]]* prefix.

`startup` creates and configures metrics.

1. Requests <<config, KafkaConfig>> for link:kafka-KafkaConfig.adoc#getConfiguredInstances[configured instances] of metric reporters

1. Adds a `JmxReporter` (with *kafka.server* prefix)

1. Creates a `MetricConfig`

1. Initializes <<metrics, Metrics>> internal registry

`startup` registers broker topic metrics (by initializing <<_brokerTopicStats, BrokerTopicStats>>).

`startup` initializes <<quotaManagers, QuotaManagers>>.

`startup` <<notifyClusterListeners, notifies cluster resource listeners>> (from <<kafkaMetricsReporters, KafkaMetricsReporters>> and the configured instances of metric reporters).

CAUTION: FIXME `logDirFailureChannel`

`startup` link:kafka-ReplicaManager.adoc#creating-instance[creates a `ReplicaManager`] and link:kafka-ReplicaManager.adoc#startup[starts it] right afterwards.

`startup` link:kafka-KafkaController.adoc#creating-instance[creates a `KafkaController`] and link:kafka-KafkaController.adoc#startup[starts it].

`startup` link:kafka-AdminManager.adoc#creating-instance[creates a `AdminManager`].

`startup` link:kafka-KafkaApis.adoc#creating-instance[creates a `KafkaApis`].

In the end, you should see the following INFO message in the logs:

```
INFO [Kafka Server 0], started (kafka.server.KafkaServer)
```

NOTE: The INFO message above uses so-called *log ident* with the value of `broker.id` property and is always in the format ``[Kafka Server [brokerId]], `` after a Kafka server has fully started.

CAUTION: FIXME

NOTE: `startup` is used exclusively when link:kafka-KafkaServerStartable.adoc#startup[`KafkaServerStartable` is started].

=== [[notifyClusterListeners]] `notifyClusterListeners` Method

CAUTION: FIXME

=== [[creating-instance]] Creating KafkaServer Instance

`KafkaServer` takes the following when created:

1. link:kafka-KafkaConfig.adoc[KafkaConfig]
1. `Time` (defaults to `Time.SYSTEM`)
1. `threadNamePrefix` (defaults to no prefix)
1. [[kafkaMetricsReporters]] A collection of link:kafka-KafkaMetricsReporter.adoc[KafkaMetricsReporters] (defaults to no reporters)

CAUTION: FIXME

NOTE: `KafkaServer` is created when link:kafka-KafkaServerStartable.adoc#creating-instance[`KafkaServerStartable` is created].
