== [[Metadata]] Metadata

`Metadata`...FIXME

`Metadata` is <<creating-instance, created>> when:

* `KafkaConsumer` is link:kafka-KafkaConsumer.adoc#creating-instance[created]
** link:kafka-properties-retry-backoff-ms.adoc[retry.backoff.ms] for <<refreshBackoffMs, refreshBackoffMs>>
** link:kafka-properties.adoc#metadata.max.age.ms[metadata.max.age.ms] for <<metadataExpireMs, metadataExpireMs>>
** <<allowAutoTopicCreation, allowAutoTopicCreation>> flag enabled
** <<topicExpiryEnabled, topicExpiryEnabled>> flag disabled
* `KafkaProducer` is link:kafka-KafkaProducer.adoc#creating-instance[created]
** link:kafka-properties-retry-backoff-ms.adoc[retry.backoff.ms] for <<refreshBackoffMs, refreshBackoffMs>>
** link:kafka-properties.adoc#metadata.max.age.ms[metadata.max.age.ms] for <<metadataExpireMs, metadataExpireMs>>
** <<allowAutoTopicCreation, allowAutoTopicCreation>> flag enabled
** <<topicExpiryEnabled, topicExpiryEnabled>> flag enabled
* `KafkaAdminClient` is link:kafka-KafkaAdminClient.adoc#creating-instance[created]
** link:kafka-properties-retry-backoff-ms.adoc[retry.backoff.ms] for <<refreshBackoffMs, refreshBackoffMs>>
** link:kafka-properties.adoc#metadata.max.age.ms[metadata.max.age.ms] for <<metadataExpireMs, metadataExpireMs>>
* `AdminClient` is link:kafka-AdminClient.adoc#create[created]

[[internal-registries]]
.Metadata's Internal Properties (e.g. Registries and Counters)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[cluster]] `cluster`
a| link:kafka-Cluster.adoc[Cluster] with a subset of the nodes and topic partitions in a Kafka cluster.

* Empty (with no nodes and no topic partitions) when `Metadata` is <<creating-instance, created>>

* <<update, Updated>> when:
** `DefaultMetadataUpdater` link:kafka-DefaultMetadataUpdater.adoc#handleCompletedMetadataResponse[handles MetadataResponse]
** `KafkaConsumer`, `KafkaProducer`, `KafkaAdminClient` and `AdminClient` are created and update the cluster with a "bootstrap" cluster with bootstrap brokers

* Can be accessed using <<fetch, fetch>>

| [[listeners]] `listeners`
|

| [[lastRefreshMs]] `lastRefreshMs`
a| The time (in millis) of the last successful <<update, update>> (and <<failedUpdate, failed update>>)

* Used in <<timeToNextUpdate, timeToNextUpdate>>

* Starts `0` when `Metadata` is <<creating-instance, created>>

* Reset (to `0`) in <<requestUpdateForNewTopics, requestUpdateForNewTopics>>

| [[lastSuccessfulRefreshMs]] `lastSuccessfulRefreshMs`
|

| [[needMetadataForAllTopics-flag]] `needMetadataForAllTopics`
a| Flag...FIXME

* Disabled (i.e. `false`) when `Metadata` is <<creating-instance, created>>

* Updated when `Metadata` is requested to <<needMetadataForAllTopics, set state to indicate that metadata for all topics in Kafka cluster is required>>

| [[needUpdate]] `needUpdate`
a| Flag...FIXME

| [[version]] `version`
|
|===

[[logging]]
[TIP]
====
Enable `DEBUG` or `TRACE` logging levels for `org.apache.kafka.clients.Metadata` logger to see what happens inside.

Add the following line to `config/tools-log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.Metadata=TRACE
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[getClusterForCurrentTopics]] `getClusterForCurrentTopics` Internal Method

[source, java]
----
Cluster getClusterForCurrentTopics(Cluster cluster)
----

`getClusterForCurrentTopics`...FIXME

NOTE: `getClusterForCurrentTopics` is used when...FIXME

=== [[timeToNextUpdate]] `timeToNextUpdate` Method

[source, java]
----
synchronized long timeToNextUpdate(long nowMs)
----

`timeToNextUpdate`...FIXME

[NOTE]
====
`timeToNextUpdate` is used when:

* `ConsumerNetworkClient` link:kafka-ConsumerNetworkClient.adoc#ensureFreshMetadata[ensureFreshMetadata]

* `DefaultMetadataUpdater` (of `NetworkClient`) link:kafka-DefaultMetadataUpdater.adoc#isUpdateDue[isUpdateDue] and link:kafka-DefaultMetadataUpdater.adoc#maybeUpdate[maybeUpdate]
====

=== [[add]] `add` Method

[source, java]
----
synchronized void add(String topic)
----

`add`...FIXME

NOTE: `add` is used when...FIXME

=== [[requestUpdate]] `requestUpdate` Method

[source, java]
----
synchronized int requestUpdate()
----

`requestUpdate`...FIXME

NOTE: `requestUpdate` is used when...FIXME

=== [[awaitUpdate]] `awaitUpdate` Method

[source, java]
----
synchronized void awaitUpdate(
  final int lastVersion,
  final long maxWaitMs) throws InterruptedException
----

`awaitUpdate`...FIXME

NOTE: `awaitUpdate` is used when...FIXME

=== [[fetch]] Getting Current Cluster Information -- `fetch` Method

[source, scala]
----
synchronized Cluster fetch()
----

`fetch` returns current <<cluster, cluster>> information.

NOTE: `fetch` is used when...FIXME

=== [[setTopics]] Setting Topics to Maintain -- `setTopics` Method

CAUTION: FIXME

=== [[update]] Updating Cluster Metadata -- `update` Method

[source, java]
----
synchronized void update(Cluster cluster, Set<String> unavailableTopics, long now)
----

`update` turns <<needUpdate, needUpdate>> off and increments <<version, version>>.

`update` sets <<lastRefreshMs, lastRefreshMs>> and <<lastSuccessfulRefreshMs, lastSuccessfulRefreshMs>> internal registries to the input `now`.

(only when <<topicExpiryEnabled, topicExpiryEnabled>> is enabled, e.g. link:kafka-KafkaProducer.adoc#creating-instance[KafkaProducer]) `update`...FIXME

`update` notifies <<listeners, listeners>> that the link:kafka-Metadata-Listener.adoc#onMetadataUpdate[metadata has been updated].

`update` does <<getClusterForCurrentTopics, getClusterForCurrentTopics>> for the `cluster` when <<needMetadataForAllTopics, needMetadataForAllTopics>> flag is on and turns <<needUpdate, needUpdate>> flag off (that may have been turned on...FIXME).

`update` sets the <<cluster, cluster>> to the input `cluster`.

`update` prints out the cluster ID and notifies <<clusterResourceListeners, clusterResourceListeners>> that link:kafka-ClusterResourceListener.adoc#onUpdate[cluster has changed] (only for a link:kafka-Cluster.adoc#isBootstrapConfigured[non-bootstrap cluster]).

```
Cluster ID: [clusterId]
```

[NOTE]
====
`update` is used when:

* `DefaultMetadataUpdater` link:kafka-DefaultMetadataUpdater.adoc#handleCompletedMetadataResponse[handles MetadataResponse]

* `KafkaConsumer` is link:kafka-KafkaConsumer.adoc#creating-instance[created] (and updates the cluster with a "bootstrap" cluster with bootstrap servers)
* `KafkaProducer` is link:kafka-KafkaProducer.adoc#creating-instance[created] (and updates the cluster with a "bootstrap" cluster with bootstrap servers)
* `KafkaAdminClient` is link:kafka-KafkaAdminClient.adoc#creating-instance[created] (and updates the cluster with a "bootstrap" cluster with bootstrap brokers)
* `AdminClient` is link:kafka-AdminClient.adoc#create[created] (and updates the cluster with a "bootstrap" cluster with bootstrap brokers)
====

=== [[creating-instance]] Creating Metadata Instance

`Metadata` takes the following when created:

* [[refreshBackoffMs]] `refreshBackoffMs`
* [[metadataExpireMs]] `metadataExpireMs`
* [[allowAutoTopicCreation]] `allowAutoTopicCreation` flag
* [[topicExpiryEnabled]] `topicExpiryEnabled` flag
* [[clusterResourceListeners]] link:kafka-ClusterResourceListener.adoc[ClusterResourceListeners]

`Metadata` initializes the <<internal-registries, internal registries and counters>>.

=== [[needMetadataForAllTopics-method]] Conditionally Requesting Update For New Topics (for KafkaConsumer) -- `needMetadataForAllTopics` Method

[source, java]
----
synchronized void needMetadataForAllTopics(boolean needMetadataForAllTopics)
----

`needMetadataForAllTopics` <<requestUpdateForNewTopics, requestUpdateForNewTopics>> when the input `needMetadataForAllTopics` flag is enabled (i.e. `true`) and the current <<needMetadataForAllTopics, needMetadataForAllTopics>> is disabled (i.e. `false`).

`needMetadataForAllTopics` sets <<needMetadataForAllTopics, needMetadataForAllTopics>> to be the input `needMetadataForAllTopics`.

[NOTE]
====
`needMetadataForAllTopics` is used when `KafkaConsumer`:

* link:kafka-KafkaConsumer.adoc#subscribe-pattern[Subscribes to topics matching specified pattern] (and `needMetadataForAllTopics` flag is then enabled)

* link:kafka-KafkaConsumer.adoc#unsubscribe[Unsubscribes from topics] (and `needMetadataForAllTopics` flag is then disabled)
====

=== [[requestUpdateForNewTopics]] `requestUpdateForNewTopics` Internal Method

[source, java]
----
synchronized void requestUpdateForNewTopics()
----

`requestUpdateForNewTopics` sets <<lastRefreshMs, lastRefreshMs>> to `0` and <<requestUpdate, requests update>>.

[NOTE]
====
`requestUpdateForNewTopics` is used when `Metadata`:

* <<add, add>>

* <<needMetadataForAllTopics-method, needMetadataForAllTopics>>

* <<setTopics, setTopics>>
====
