== [[KafkaConsumer]] KafkaConsumer

`KafkaConsumer` is...FIXME

[source, scala]
----
// sandbox/kafka-sandbox
val props = new Properties()
props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092")
props.put(ConsumerConfig.GROUP_ID_CONFIG, "my-kafka-consumer")
props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, classOf[StringDeserializer].getName)
props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, classOf[StringDeserializer].getName)

val consumer = new KafkaConsumer[String, String](props)
----

NOTE: `KafkaConsumer` is not safe for multi-threaded access and so you should use a single thread per instance.

[[internal-registries]]
.KafkaConsumer's Internal Registries and Counters
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[client]] `client`
| `ConsumerNetworkClient`

Used when...FIXME

| [[fetcher]] `fetcher`
| `Fetcher`

Used when...FIXME

| [[interceptors]] `interceptors`
| `ConsumerInterceptors` that holds link:kafka-ConsumerInterceptor.adoc[ConsumerInterceptor] instances (defined using link:kafka-properties.adoc#interceptor.classes[interceptor.classes] setting).

Used when...FIXME

| [[metadata]] `metadata`
| link:kafka-Metadata.adoc[Metadata]

Created right when `KafkaConsumer` is <<creating-instance, created>>.

Used when...FIXME

| [[retryBackoffMs]] `retryBackoffMs`
| link:kafka-properties-retry-backoff-ms.adoc[retry.backoff.ms] property or a user-defined value

| [[subscriptions]] `subscriptions`
| `SubscriptionState` for link:kafka-properties.adoc#auto.offset.reset[auto.offset.reset] setting.

Created when `KafkaConsumer` <<creating-instance, is created>>.
|===

[TIP]
====
Enable `DEBUG` or `TRACE` logging levels for `org.apache.kafka.clients.consumer.KafkaConsumer` logger to see what happens inside.

Add the following line to `config/tools-log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.consumer.KafkaConsumer=TRACE
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[pollOnce]] Polling Once for ConsumerRecords per TopicPartition -- `pollOnce` Internal Method

CAUTION: FIXME

=== [[poll]] Poll Specified Milliseconds For ConsumerRecords per TopicPartitions -- `poll` Method

[source, java]
----
ConsumerRecords<K, V> poll(long timeout)
----

`poll` polls for new records until `timeout` expires.

NOTE: The input `timeout` should be `0` or greater and is the milliseconds to poll for records.

Internally, `poll` <<pollOnce, polls once>> (for ConsumerRecords per TopicPartitions).

If there are records fetched, `poll` checks <<fetcher, Fetcher>> for `sendFetches` or <<client, ConsumerNetworkClient>> for `pendingRequestCount` and, when either is positive, requests `ConsumerNetworkClient` to `pollNoWakeup`.

CAUTION: FIXME Make the above more user-friendly

`poll` returns the fetched `ConsumerRecords` when no `interceptors` are defined or passes them on to `ConsumerInterceptors` using `onConsume`

CAUTION: FIXME Make the above more user-friendly, e.g. when could `interceptors` be empty?

NOTE: `poll` is a part of link:kafka-consumers.adoc#poll[Consumer contract] to...FIXME

=== [[creating-instance]] Creating KafkaConsumer Instance

`KafkaConsumer` takes the following when created:

* [[config]] link:kafka-ConsumerConfig.adoc[ConsumerConfig]
* [[keyDeserializer]] `Deserializer` for the keys
* [[valueDeserializer]] `Deserializer` for the values

`KafkaConsumer` initializes the <<internal-registries, internal registries and counters>>.

NOTE: `KafkaConsumer` offers other methods to create itself, but they all eventually use the 3-argument constructor.

When created, you should see the following messages in the logs:

```
DEBUG Starting the Kafka consumer (org.apache.kafka.clients.consumer.KafkaConsumer)
```

`KafkaConsumer` sets the internal `requestTimeoutMs` to <<request_timeout_ms, request.timeout.ms>> that has to be greater than link:kafka-properties.adoc#session_timeout_ms[session.timeout.ms] and link:kafka-properties.adoc#fetch_max_wait_ms[fetch.max.wait.ms] (you get `ConfigException` otherwise).

`clientId` property is set to link:kafka-properties.adoc#client.id[client.id] if defined or auto-generated. It is used for metrics with the tag `client-id` being `clientId`.

`metrics` property is set to the configured link:kafka-MetricsReporter.adoc[metrics reporters].

`KafkaConsumer` sets the internal <<retryBackoffMs, retryBackoffMs>> to the value of link:kafka-properties.adoc#retry.backoff.ms[retry.backoff.ms] property.

CAUTION: FIXME Finish me!

`KafkaConsumer` creates the internal <<metadata, Metadata>> with the following arguments:

1. <<retryBackoffMs, retryBackoffMs>>
1. link:kafka-properties.adoc#metadata.max.age.ms[metadata.max.age.ms]
1. `allowAutoTopicCreation` enabled
1. `topicExpiryEnabled` disabled
1. `ClusterResourceListeners` with user-defined list of link:kafka-ConsumerInterceptor.adoc[ConsumerInterceptors] in link:kafka-properties.adoc#interceptor.classes[interceptor.classes] property

CAUTION: FIXME Finish me!

`KafkaConsumer` creates a link:kafka-NetworkClient.adoc[NetworkClient] with...FIXME

CAUTION: FIXME Finish me!

When successfully created, you should see the following DEBUG in the logs:

```
DEBUG Kafka consumer created (org.apache.kafka.clients.consumer.KafkaConsumer)
```

Any issues while creating a `KafkaConsumer` are reported as `KafkaException`.

```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
```
