== [[OffsetIndex]] OffsetIndex -- Index Of Offsets Of Log Segment

`OffsetIndex` is an <<kafka-log-AbstractIndex.adoc#, index>> of the offsets of a <<kafka-log-LogSegment.adoc#lazyOffsetIndex, LogSegment>>.

[[entrySize]]
`OffsetIndex` uses <<kafka-log-AbstractIndex.adoc#entrySize, entrySize>> of 8 bytes (_8-byte offset index entries_).

`OffsetIndex` is <<creating-instance, created>> when:

* Lazily for a <<kafka-log-LogSegment.adoc#open, log segment>> (via <<kafka-log-LazyIndex.adoc#forOffset, forOffset>> utility that defers loading the underlying index file until needed)

* <<kafka-tools-DumpLogSegments.adoc#, DumpLogSegments>> tool is used (to dump the <<kafka-tools-DumpLogSegments.adoc#dumpIndex, offset>> and <<kafka-tools-DumpLogSegments.adoc#dumpTimeIndex, time>> indices of a log segment)

[[logging]]
[TIP]
====
Enable `ALL` logging level for `kafka.log.OffsetIndex` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.log.OffsetIndex=ALL
```

Refer to <<kafka-logging.adoc#, Logging>>.
====

=== [[creating-instance]] Creating OffsetIndex Instance

`OffsetIndex` takes the following to be created:

* [[_file]] Underlying https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/File.html[File]
* [[baseOffset]] Base offset
* [[maxIndexSize]] `maxIndexSize` (default: `-1`)
* [[writable]] `writable` flag (default: `true`)

`OffsetIndex` initializes the <<internal-properties, internal properties>>.

While being created, `OffsetIndex` prints out the following DEBUG message to the logs:

[options="wrap"]
----
Loaded index file [absolutePath] with maxEntries = [maxEntries], maxIndexSize = [maxIndexSize], entries = [_entries], lastOffset = [_lastOffset], file position = [position]
----

=== [[append]] `append` Method

[source, scala]
----
append(
  offset: Long,
  position: Int): Unit
----

`append`...FIXME

NOTE: `append` is used when `LogSegment` is requested to <<kafka-log-LogSegment.adoc#append, append>> and <<kafka-log-LogSegment.adoc#recover, recover>>.

=== [[lookup]] `lookup` Method

[source, scala]
----
lookup(
  targetOffset: Long): OffsetPosition
----

`lookup`...FIXME

NOTE: `lookup` is used when...FIXME

=== [[fetchUpperBoundOffset]] `fetchUpperBoundOffset` Method

[source, scala]
----
fetchUpperBoundOffset(
  fetchOffset: OffsetPosition,
  fetchSize: Int): Option[OffsetPosition]
----

`fetchUpperBoundOffset`...FIXME

NOTE: `fetchUpperBoundOffset` is used when `Log` is requested to <<kafka-log-Log.adoc#addAbortedTransactions, addAbortedTransactions>>.

=== [[truncateTo]] `truncateTo` Method

[source, scala]
----
truncateTo(
  offset: Long): Unit
----

NOTE: `truncateTo` is part of the <<kafka-log-AbstractIndex.adoc#truncateTo, AbstractIndex Contract>> to...FIXME.

`truncateTo`...FIXME

=== [[lastEntry]] `lastEntry` Internal Method

[source, scala]
----
lastEntry: OffsetPosition
----

`lastEntry`...FIXME

NOTE: `lastEntry` is used when...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| _lastOffset
a| [[_lastOffset]] The `offset` of the <<lastEntry, last OffsetPosition>>

Used when...FIXME

|===
