== [[MetadataUpdater]] MetadataUpdater Contract

`MetadataUpdater` is the <<contract, abstraction>> of <<implementations, FIXME>> that <<FIXME, FIXME>>.

[[contract]]
.MetadataUpdater Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| close
a| [[close]]

[source, java]
----
void close()
----

Used when...FIXME

| fetchNodes
a| [[fetchNodes]]

[source, java]
----
List<Node> fetchNodes()
----

Used when...FIXME

| handleAuthenticationFailure
a| [[handleAuthenticationFailure]]

[source, java]
----
void handleAuthenticationFailure(AuthenticationException exception)
----

Used when...FIXME

| handleCompletedMetadataResponse
a| [[handleCompletedMetadataResponse]]

[source, java]
----
void handleCompletedMetadataResponse(
  RequestHeader requestHeader,
  long now,
  MetadataResponse metadataResponse)
----

Used when...FIXME

| handleDisconnection
a| [[handleDisconnection]]

[source, java]
----
void handleDisconnection(String destination)
----

Used when...FIXME

| isUpdateDue
a| [[isUpdateDue]]

[source, java]
----
boolean isUpdateDue(long now)
----

Used when...FIXME

| maybeUpdate
a| [[maybeUpdate]]

[source, java]
----
long maybeUpdate(long now)
----

Starts a cluster metadata update if needed and possible.

Used when `NetworkClient` is requested to link:kafka-clients-NetworkClient.adoc#poll[read and write to sockets].

| requestUpdate
a| [[requestUpdate]]

[source, java]
----
void requestUpdate()
----

Schedules an update of the current cluster metadata

Used when `NetworkClient` is requested to <<kafka-clients-NetworkClient.adoc#handleTimedOutRequests, handleTimedOutRequests>>, <<kafka-clients-NetworkClient.adoc#handleDisconnections, handleDisconnections>> and <<kafka-clients-NetworkClient.adoc#initiateConnect, establish a connection to a broker node>>
|===
