== [[AbstractFetcherManager]] AbstractFetcherManager

[[T]]
`AbstractFetcherManager` is the <<contract, abstraction>> of <<implementations, fetcher thread managers>> that can <<createFetcherThread, create fetcher threads>> (for <<kafka-server-ReplicaManager.adoc#, ReplicaManager>>).

NOTE: `AbstractFetcherManager` is an abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractFetcherManagers>>.

[[contract]]
.AbstractFetcherManager Contract (Abstract Methods)
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| createFetcherThread
a| [[createFetcherThread]]

[source, scala]
----
// T is AbstractFetcherThread or subclasses
createFetcherThread(
  fetcherId: Int,
  sourceBroker: BrokerEndPoint): T
----

Creates a link:kafka-server-AbstractFetcherThread.adoc[fetcher thread]

Used when `AbstractFetcherManager` is requested to <<addFetcherForPartitions, addFetcherForPartitions>>

|===

[[implementations]]
.AbstractFetcherManagers
[cols="30,70",options="header",width="100%"]
|===
| AbstractFetcherManager
| Description

| link:kafka-server-ReplicaAlterLogDirsManager.adoc[ReplicaAlterLogDirsManager]
| [[ReplicaAlterLogDirsManager]]

| link:kafka-server-ReplicaFetcherManager.adoc[ReplicaFetcherManager]
| [[ReplicaFetcherManager]]

|===

=== [[KafkaMetricsGroup]][[metrics]] Performance Metrics

<<implementations, AbstractFetcherManagers>> are link:kafka-metrics-KafkaMetricsGroup.adoc[KafkaMetricsGroups] with the following performance metrics.

.AbstractFetcherManager's Performance Metrics
[cols="30m,70",options="header",width="100%"]
|===
| Metric Name
| Description

| DeadThreadCount
| [[DeadThreadCount]]

| FailedPartitionsCount
| [[FailedPartitionsCount]]

| MaxLag
| [[MaxLag]]

| MinFetchRate
| [[MinFetchRate]]

|===

The performance metrics are registered in *kafka.server:type=* group with the `type` being the name of a <<implementations, AbstractFetcherManager>>.

=== [[creating-instance]] Creating AbstractFetcherManager Instance

`AbstractFetcherManager` takes the following to be created:

* [[name]] Log Prefix
* [[clientId]] Client ID (for a tag in <<metrics, performance metrics>>)
* [[numFetchers]] link:kafka-properties.adoc#num.replica.fetchers[num.replica.fetchers]

`AbstractFetcherManager` initializes the <<internal-properties, internal properties>>.

=== [[addFetcherForPartitions]] `addFetcherForPartitions` Method

[source, scala]
----
addFetcherForPartitions(
  partitionAndOffsets: Map[TopicPartition, InitialFetchState]): Unit
----

`addFetcherForPartitions`...FIXME

[NOTE]
====
`addFetcherForPartitions` is used when:

* `AbstractFetcherManager` is requested to <<resizeThreadPool, resizeThreadPool>> (when `DynamicThreadPool` is requested to link:kafka-server-DynamicThreadPool.adoc#reconfigure[reconfigure])

* `ReplicaManager` is requested to link:kafka-server-ReplicaManager.adoc#alterReplicaLogDirs[alterReplicaLogDirs], link:kafka-server-ReplicaManager.adoc#becomeLeaderOrFollower[becomeLeaderOrFollower] and link:kafka-server-ReplicaManager.adoc#makeFollowers[makeFollowers]
====

=== [[resizeThreadPool]] `resizeThreadPool` Method

[source, scala]
----
resizeThreadPool(newSize: Int): Unit
----

`resizeThreadPool` prints out the following INFO message to the logs:

```
Resizing fetcher thread pool size from [currentSize] to [newSize]
```

`resizeThreadPool`...FIXME

NOTE: `resizeThreadPool` is used exclusively when `DynamicThreadPool` is requested to <<kafka-server-DynamicThreadPool.adoc#reconfigure, reconfigure>>.

=== [[getFetcherId]] Finding Fetcher Thread ID -- `getFetcherId` Method

[source, scala]
----
getFetcherId(
  topicPartition: TopicPartition): Int
----

`getFetcherId` calculates a hash of the topic and partition (from the given `TopicPartition`) modulo (`%`) the <<numFetchersPerBroker, numFetchersPerBroker>>.

NOTE: `getFetcherId` is used when `AbstractFetcherManager` is requested to <<markPartitionsForTruncation, markPartitionsForTruncation>> and <<addFetcherForPartitions, addFetcherForPartitions>>.

=== [[getFetcher]] `getFetcher` Method

[source, scala]
----
getFetcher(topicPartition: TopicPartition): Option[T]
----

`getFetcher`...FIXME

NOTE: `getFetcher` is used when...FIXME

=== [[markPartitionsForTruncation]] `markPartitionsForTruncation` Method

[source, scala]
----
markPartitionsForTruncation(
  brokerId: Int,
  topicPartition: TopicPartition,
  truncationOffset: Long): Unit
----

`markPartitionsForTruncation`...FIXME

NOTE: `markPartitionsForTruncation` is used when...FIXME

=== [[removeFetcherForPartitions]] `removeFetcherForPartitions` Method

[source, scala]
----
removeFetcherForPartitions(
  partitions: Set[TopicPartition]): Unit
----

`removeFetcherForPartitions`...FIXME

[NOTE]
====
`removeFetcherForPartitions` is used when:

* `AbstractFetcherManager` is requested to <<resizeThreadPool, resizeThreadPool>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#stopReplicas, stopReplicas>>, <<kafka-server-ReplicaManager.adoc#alterReplicaLogDirs, alterReplicaLogDirs>>, <<kafka-server-ReplicaManager.adoc#makeLeaders, makeLeaders>>, <<kafka-server-ReplicaManager.adoc#makeFollowers, makeFollowers>>, and <<kafka-server-ReplicaManager.adoc#handleLogDirFailure, handleLogDirFailure>>
====

=== [[closeAllFetchers]] `closeAllFetchers` Method

[source, scala]
----
closeAllFetchers(): Unit
----

`closeAllFetchers` requests the <<fetcherThreadMap, fetcher threads>> to link:kafka-ShutdownableThread.adoc#initiateShutdown[initiateShutdown].

`closeAllFetchers` requests the <<fetcherThreadMap, fetcher threads>> to link:kafka-server-AbstractFetcherThread.adoc#shutdown[shutdown].

In the end, `closeAllFetchers` removes (_clears_) all entries from the <<fetcherThreadMap, fetcherThreadMap>> internal registry.

NOTE: `closeAllFetchers` is used when link:kafka-server-ReplicaAlterLogDirsManager.adoc#shutdown[ReplicaAlterLogDirsManager] and link:kafka-server-ReplicaAlterLogDirsManager.adoc#shutdown[ReplicaFetcherManager] are requested to shut down.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| fetcherThreadMap
a| [[fetcherThreadMap]] link:kafka-server-AbstractFetcherThread.adoc[AbstractFetcherThreads] by (a pair of) broker ID and fetcher ID

| numFetchersPerBroker
a| [[numFetchersPerBroker]] Number of fetcher threads per broker

Initialized with the given <<numFetchers, numFetchers>> when `AbstractFetcherManager` is created

Resized in <<resizeThreadPool, resizeThreadPool>>

Used in <<getFetcherId, getFetcherId>>

|===
