== [[ChannelBuilders]] ChannelBuilders Utility

`ChannelBuilders` utility is used for the following:

* <<createPrincipalBuilder, Creating a KafkaPrincipalBuilder (per principal.builder.class configuration property)>>

* ...

=== [[clientChannelBuilder]] Creating ChannelBuilder (for Kafka Clients and Inter-Broker Communication) -- `clientChannelBuilder` Method

[source, java]
----
ChannelBuilder clientChannelBuilder(
  SecurityProtocol securityProtocol,
  JaasContext.Type contextType,
  AbstractConfig config,
  ListenerName listenerName,
  String clientSaslMechanism,
  Time time,
  boolean saslHandshakeRequestEnable)
----

`clientChannelBuilder`...FIXME

[NOTE]
====
`clientChannelBuilder` is used when:

* `ClientUtils` utility is used to link:kafka-clients-ClientUtils.adoc#createChannelBuilder[create a ChannelBuilder] (with `CLIENT` JAAS context type and `null` listener name)

* `ControllerChannelManager` is requested to link:kafka-controller-ControllerChannelManager.adoc#addNewBroker[register a new broker]

* `TransactionMarkerChannelManager` is link:kafka-TransactionMarkerChannelManager.adoc#apply[created] (for a link:kafka-TransactionCoordinator.adoc[TransactionCoordinator])

* `KafkaServer` is requested to link:kafka-server-KafkaServer.adoc#controlledShutdown[controlledShutdown]

* link:kafka-server-ReplicaFetcherBlockingSend.adoc[ReplicaFetcherBlockingSend] is created
====

=== [[serverChannelBuilder]] `serverChannelBuilder` Method

[source, java]
----
ChannelBuilder serverChannelBuilder(
  ListenerName listenerName,
  boolean isInterBrokerListener,
  SecurityProtocol securityProtocol,
  AbstractConfig config,
  CredentialCache credentialCache,
  DelegationTokenCache tokenCache,
  Time time)
----

`serverChannelBuilder`...FIXME

NOTE: `serverChannelBuilder` is used when link:kafka-network-SocketServer-Processor.adoc[Processor] is created (and creates a link:kafka-network-SocketServer-Processor.adoc#selector[Selector]).

=== [[createPrincipalBuilder]] Creating KafkaPrincipalBuilder Per principal.builder.class Configuration Property -- `createPrincipalBuilder` Utility

[source, java]
----
KafkaPrincipalBuilder createPrincipalBuilder(
  Map<String, ?> configs,
  TransportLayer transportLayer,
  Authenticator authenticator,
  KerberosShortNamer kerberosShortNamer,
  SslPrincipalMapper sslPrincipalMapper)
----

`createPrincipalBuilder` reads the link:kafka-properties.adoc#principal.builder.class[principal.builder.class] configuration property and creates a link:kafka-common-security-auth-KafkaPrincipalBuilder.adoc[KafkaPrincipalBuilder]:

* For no class defined (`null`), `createPrincipalBuilder` creates a link:kafka-common-security-authenticator-DefaultKafkaPrincipalBuilder.adoc[DefaultKafkaPrincipalBuilder] (with the `KerberosShortNamer` and `SslPrincipalMapper`)

* For a link:kafka-common-security-auth-KafkaPrincipalBuilder.adoc[KafkaPrincipalBuilder] implementation, `createPrincipalBuilder` creates an instance

* For a `PrincipalBuilder` implementation, `createPrincipalBuilder` creates an instance

For a builder that is also a link:kafka-common-Configurable.adoc[Configurable], `createPrincipalBuilder` requests it to link:kafka-common-Configurable.adoc#configure[configure] (with the given `configs`).

`createPrincipalBuilder` throws an `InvalidConfigurationException` for any other implementation:

[options="wrap"]
----
Type [principalBuilderClassName] is not an instance of org.apache.kafka.common.security.auth.PrincipalBuilder or org.apache.kafka.common.security.auth.KafkaPrincipalBuilder
----

NOTE: `createPrincipalBuilder` is used for creating the link:kafka-common-network-Authenticator.adoc[Authenticators] (i.e. `PlaintextAuthenticator`, link:kafka-common-network-SslChannelBuilder-SslAuthenticator.adoc[SslAuthenticator], and `SaslServerAuthenticator`).

=== [[create]] `create` Internal Utility

[source, java]
----
ChannelBuilder create(
  SecurityProtocol securityProtocol,
  Mode mode,
  JaasContext.Type contextType,
  AbstractConfig config,
  ListenerName listenerName,
  boolean isInterBrokerListener,
  String clientSaslMechanism,
  boolean saslHandshakeRequestEnable,
  CredentialCache credentialCache,
  DelegationTokenCache tokenCache,
  Time time)
----

`create`...FIXME

NOTE: `create` is used when `ChannelBuilders` utility is requested to <<clientChannelBuilder, clientChannelBuilder>> (`CLIENT` mode) and <<serverChannelBuilder, serverChannelBuilder>> (`SERVER` mode).
