== [[JoinGroupResponseHandler]] JoinGroupResponseHandler

`JoinGroupResponseHandler` is a concrete <<kafka-consumer-internals-CoordinatorResponseHandler.adoc#, CoordinatorResponseHandler>> to <<handle, handle a successful JoinGroupResponse from a group coordinator>> (and convert it to a `ByteBuffer`).

NOTE: `JoinGroupResponseHandler` is a Java private class of <<kafka-consumer-internals-AbstractCoordinator.adoc#, AbstractCoordinator>> and so can only be used by <<kafka-consumer-internals-AbstractCoordinator.adoc#extensions, AbstractCoordinators>>.

`JoinGroupResponseHandler` is <<creating-instance, created>> exclusively when `AbstractCoordinator` is requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#sendJoinGroupRequest, send a JoinGroupRequest to the group coordinator>> (when requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#initiateJoinGroup, initiateJoinGroup>> when <<kafka-consumer-internals-AbstractCoordinator.adoc#joinGroupIfNeeded, joinGroupIfNeeded>> which is when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>>).

[[creating-instance]]
`JoinGroupResponseHandler` takes no arguments to be created.

=== [[handle]] Handling Successful Response From Group Coordinator -- `handle` Method

[source, java]
----
void handle(
  JoinGroupResponse joinResponse,
  RequestFuture<ByteBuffer> future)
----

NOTE: `handle` is part of the <<kafka-consumer-internals-CoordinatorResponseHandler.adoc#handle, CoordinatorResponseHandler Contract>> to handle a successful response from a group coordinator.

`handle` branches off per the error in the given <<kafka-common-requests-JoinGroupResponse.adoc#, JoinGroupResponse>>.

==== [[handle-NONE]] No Errors

`handle` prints out the following DEBUG message to the logs:

```
Received successful JoinGroup response: [joinResponse]
```

`handle` requests the <<kafka-consumer-internals-AbstractCoordinator.adoc#sensors, GroupCoordinatorMetrics>> for the <<kafka-consumer-internals-AbstractCoordinator-GroupCoordinatorMetrics.adoc#joinLatency, joinLatency>> sensor to record the request latency.

When in `REBALANCING` <<kafka-consumer-internals-AbstractCoordinator.adoc#state, state>>, `handle` creates a new <<generation, Generation>> (with the generation ID, the member ID, and the group protocol from the given `JoinGroupResponse`).

In the end, `handle` checks if the given `JoinGroupResponse` is for the leader of the consumer group or a follower and <<kafka-consumer-internals-AbstractCoordinator.adoc#onJoinLeader, performs partition assignment and notifies the group coordinator>> or <<kafka-consumer-internals-AbstractCoordinator.adoc#onJoinFollower, onJoinFollower>>, respectively.

When not in `REBALANCING` <<kafka-consumer-internals-AbstractCoordinator.adoc#state, state>>, `handle` requests the raises the given `RequestFuture<ByteBuffer>` to raise a `UnjoinedGroupException`.

CAUTION: There are other errors, but of little interest currently (aka _FIXME_).
