== [[KafkaAdminClient]] KafkaAdminClient

`KafkaAdminClient` is a link:kafka-AdminClient.adoc[AdminClient] that...FIXME

`KafkaAdminClient` is <<creating-instance, created>> when...FIXME

=== [[describeTopics]] `describeTopics` Method

[source, java]
----
DescribeTopicsResult describeTopics(
  final Collection<String> topicNames,
  DescribeTopicsOptions options)
----

`describeTopics`...FIXME

NOTE: `describeTopics` is used when...FIXME

=== [[alterReplicaLogDirs]] `alterReplicaLogDirs` Method

[source, java]
----
AlterReplicaLogDirsResult alterReplicaLogDirs(
  Map<TopicPartitionReplica, String> replicaAssignment,
  final AlterReplicaLogDirsOptions options)
----

`alterReplicaLogDirs`...FIXME

NOTE: `alterReplicaLogDirs` is used when...FIXME

=== [[creating-instance]] Creating KafkaAdminClient Instance

`KafkaAdminClient` takes the following when created:

* [[config]] `AdminClientConfig`
* [[clientId]] client ID
* [[sanitizedClientId]] sanitized client ID
* [[time]] `Time`
* [[metadata]] link:kafka-Metadata.adoc[Metadata]
* [[metrics]] `Metrics`
* [[client]] link:kafka-KafkaClient.adoc[KafkaClient]
* [[timeoutProcessorFactory]] `TimeoutProcessorFactory`
* [[logContext]] `LogContext`

`KafkaAdminClient` initializes the <<internal-registries, internal registries and counters>>.

=== [[alterConfigs]] `alterConfigs` Method

[source, java]
----
AlterConfigsResult alterConfigs(
  Map<ConfigResource, Config> configs,
  final AlterConfigsOptions options)
// Private API
Map<ConfigResource, KafkaFutureImpl<Void>> alterConfigs(
  Map<ConfigResource, Config> configs,
  final AlterConfigsOptions options,
  Collection<ConfigResource> resources,
  NodeProvider nodeProvider)
----

NOTE: `alterConfigs` is part of the <<kafka-AdminClient.adoc#alterConfigs, AdminClient Contract>> to...FIXME.

`alterConfigs`...FIXME

=== [[describeCluster]] `describeCluster` Method

[source, java]
----
DescribeClusterResult describeCluster(DescribeClusterOptions options)
----

NOTE: `describeCluster` is part of the <<kafka-AdminClient.adoc#describeCluster, AdminClient Contract>> to...FIXME.

`describeCluster`...FIXME

=== [[deleteRecords]] `deleteRecords` Method

[source, java]
----
DeleteRecordsResult deleteRecords(
  final Map<TopicPartition, RecordsToDelete> recordsToDelete,
  final DeleteRecordsOptions options)
----

NOTE: `deleteRecords` is part of the <<kafka-AdminClient.adoc#deleteRecords, AdminClient Contract>> to...FIXME.

`deleteRecords`...FIXME

=== [[listConsumerGroups]] `listConsumerGroups` Method

[source, java]
----
ListConsumerGroupsResult listConsumerGroups(ListConsumerGroupsOptions options)
----

NOTE: `listConsumerGroups` is part of the <<kafka-AdminClient.adoc#listConsumerGroups, AdminClient Contract>> to...FIXME.

`listConsumerGroups`...FIXME

=== [[listTopics]] `listTopics` Method

[source, java]
----
ListTopicsResult listTopics(final ListTopicsOptions options)
----

NOTE: `listTopics` is part of the <<kafka-AdminClient.adoc#listTopics, AdminClient Contract>> to...FIXME.

`listTopics`...FIXME

=== [[describeConsumerGroups]] `describeConsumerGroups` Method

[source, java]
----
DescribeConsumerGroupsResult describeConsumerGroups(
  final Collection<String> groupIds,
  final DescribeConsumerGroupsOptions options)
----

NOTE: `describeConsumerGroups` is part of the <<kafka-AdminClient.adoc#describeConsumerGroups, AdminClient Contract>> to...FIXME.

`describeConsumerGroups`...FIXME

=== [[listConsumerGroupOffsets]] `listConsumerGroupOffsets` Method

[source, java]
----
ListConsumerGroupOffsetsResult listConsumerGroupOffsets(
  final String groupId,
  final ListConsumerGroupOffsetsOptions options)
----

NOTE: `listConsumerGroupOffsets` is part of the <<kafka-AdminClient.adoc#listConsumerGroupOffsets, AdminClient Contract>> to...FIXME.

`listConsumerGroupOffsets`...FIXME

=== [[deleteConsumerGroups]] `deleteConsumerGroups` Method

[source, java]
----
DeleteConsumerGroupsResult deleteConsumerGroups(
  Collection<String> groupIds,
  DeleteConsumerGroupsOptions options)
----

NOTE: `deleteConsumerGroups` is part of the <<kafka-AdminClient.adoc#deleteConsumerGroups, AdminClient Contract>> to...FIXME.

`deleteConsumerGroups`...FIXME
