== [[PartitionLeaderElectionAlgorithms]] PartitionLeaderElectionAlgorithms Utility

`PartitionLeaderElectionAlgorithms` is a utility with the algorithms for link:kafka-partition-leader-election.adoc[partition leader election]:

* <<controlledShutdownPartitionLeaderElection, controlledShutdownPartitionLeaderElection>>

* <<offlinePartitionLeaderElection, offlinePartitionLeaderElection>>

* <<preferredReplicaPartitionLeaderElection, preferredReplicaPartitionLeaderElection>>

* <<reassignPartitionLeaderElection, reassignPartitionLeaderElection>>

=== [[controlledShutdownPartitionLeaderElection]] `controlledShutdownPartitionLeaderElection` Utility

[source, scala]
----
controlledShutdownPartitionLeaderElection(
  assignment: Seq[Int],
  isr: Seq[Int],
  liveReplicas: Set[Int],
  shuttingDownBrokers: Set[Int]): Option[Int]
----

`controlledShutdownPartitionLeaderElection`...FIXME

NOTE: `controlledShutdownPartitionLeaderElection` is used when `Election` utility is used to link:kafka-controller-Election.adoc#leaderForControlledShutdown[leaderForControlledShutdown].

=== [[offlinePartitionLeaderElection]] `offlinePartitionLeaderElection` Utility

[source, scala]
----
offlinePartitionLeaderElection(
  assignment: Seq[Int],
  isr: Seq[Int],
  liveReplicas: Set[Int],
  uncleanLeaderElectionEnabled: Boolean,
  controllerContext: ControllerContext): Option[Int]
----

`offlinePartitionLeaderElection`...FIXME

NOTE: `offlinePartitionLeaderElection` is used when `Election` utility is used to link:kafka-controller-Election.adoc#leaderForOffline[leaderForOffline].

=== [[preferredReplicaPartitionLeaderElection]] `preferredReplicaPartitionLeaderElection` Utility

[source, scala]
----
preferredReplicaPartitionLeaderElection(
  assignment: Seq[Int],
  isr: Seq[Int],
  liveReplicas: Set[Int]): Option[Int]
----

`preferredReplicaPartitionLeaderElection`...FIXME

NOTE: `preferredReplicaPartitionLeaderElection` is used when `Election` utility is used to link:kafka-controller-Election.adoc#leaderForPreferredReplica[leaderForPreferredReplica].

=== [[reassignPartitionLeaderElection]] `reassignPartitionLeaderElection` Utility

[source, scala]
----
reassignPartitionLeaderElection(
  reassignment: Seq[Int],
  isr: Seq[Int],
  liveReplicas: Set[Int]): Option[Int]
----

`reassignPartitionLeaderElection`...FIXME

NOTE: `reassignPartitionLeaderElection` is used when `Election` utility is used to link:kafka-controller-Election.adoc#leaderForReassign[leaderForReassign].
