== [[MetadataRequest]] MetadataRequest

[[METADATA]][[creating-instance]]
`MetadataRequest` is a <<kafka-common-requests-AbstractRequest.adoc#, request>> with *METADATA* API key and the following properties:

* [[data]] `MetadataRequestData`
* [[version]] Version

`MetadataRequest` is <<creating-instance, created>> when:

* `MetadataRequest.Builder` is requested to <<build, build a MetadataRequest>>

* `MetadataRequest` is requested to <<parse, a byte buffer>>

* `AbstractRequest` is requested to <<kafka-common-requests-AbstractRequest.adoc#parseRequest, parse a request>> (with the <<METADATA, Metadata>> API key)

`MetadataRequest` can be <<creating-instance, created>> using the following factory methods:

* <<allTopics, MetadataRequest.Builder.allTopics>>

* <<Builder, MetadataRequest.Builder>>

[source, scala]
----
import org.apache.kafka.common.requests.MetadataRequest

val r = MetadataRequest.Builder.allTopics
scala> println(r)
(type=MetadataRequest, topics=<ALL>)

import collection.JavaConverters._
val topics = Seq("t1", "t2").asJava
val allowAutoTopicCreation = false
val r = new MetadataRequest.Builder(topics, allowAutoTopicCreation)
scala> println(r)
(type=MetadataRequest, topics=t1,t2)
----

=== [[allTopics]] Create MetadataRequest.Builder for All Topics -- `allTopics` Static Factory Method

[source, java]
----
// MetadataRequest.Builder.allTopics
Builder allTopics()
----

`allTopics` creates a new <<MetadataRequest, MetadataRequest>> for all topics and `allowAutoTopicCreation` flag enabled.

[NOTE]
====
`allTopics` is used when:

* `Metadata` is requested to <<kafka-clients-Metadata.adoc#newMetadataRequestBuilder, newMetadataRequestBuilder>>

* `KafkaAdminClient` is requested to <<kafka-KafkaAdminClient.adoc#listTopics, listTopics>> and <<kafka-KafkaAdminClient.adoc#describeTopics, describeTopics>>

* `ConsumerMetadata` is requested to `newMetadataRequestBuilder`

* `Fetcher` is requested to <<kafka-consumer-internals-Fetcher.adoc#getAllTopicMetadata, getAllTopicMetadata>>
====

=== [[MetadataRequest.Builder]][[Builder]][[build]] `MetadataRequest.Builder` Factory Object

`UpdateMetadataRequest` comes with a concrete <<kafka-common-requests-AbstractRequest.adoc#Builder, AbstractRequest.Builder>> factory object that can <<kafka-common-requests-AbstractRequest-Builder.adoc#build, build>> a <<MetadataRequest, MetadataRequest>>.

[source, java]
----
MetadataRequest build(short version)
----

`UpdateMetadataRequest.Builder` is used when...FIXME
