== [[SubscriptionState]] SubscriptionState

`SubscriptionState` allows for tracking the topics, partitions, and offsets assigned to a Kafka consumer.

[[internal-registries]]
.SubscriptionState's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[listener]] `listener`
a| link:kafka-consumer-ConsumerRebalanceListener.adoc[ConsumerRebalanceListener] for notifications about partition assignment changes

Used exclusively when `ConsumerCoordinator` is notified about:

* link:kafka-consumer-ConsumerCoordinator.adoc#onJoinComplete[onJoinComplete] (that triggers link:kafka-consumer-ConsumerRebalanceListener.adoc#onPartitionsAssigned[ConsumerRebalanceListener.onPartitionsAssigned])
* link:kafka-consumer-ConsumerCoordinator.adoc#onJoinPrepare[onJoinPrepare] (that triggers link:kafka-consumer-ConsumerRebalanceListener.adoc#onPartitionsRevoked[ConsumerRebalanceListener.onPartitionsRevoked])
|===

=== [[subscribe]] `subscribe` Method

[source, java]
----
void subscribe(Pattern pattern, ConsumerRebalanceListener listener)
----

`subscribe`...FIXME

NOTE: `subscribe` is used exclusively when `KafkaConsumer` is requested to link:kafka-consumer-KafkaConsumer.adoc#subscribe[subscribe to the topics that match a pattern with a ConsumerRebalanceListener].
