== [[KafkaPrincipalBuilder]] KafkaPrincipalBuilder

`KafkaPrincipalBuilder` is the <<contract, abstraction>> of <<implementations, principal builders>> that can <<build, build a KafkaPrincipal>> for link:kafka-security-ssl-authentication-and-authorization.adoc[authentication].

NOTE: link:kafka-common-Configurable.adoc[Configurable] and `java.io.Closeable` interfaces are respected if implemented.

`KafkaPrincipalBuilder` is configured by the link:kafka-properties.adoc#principal.builder.class[principal.builder.class] configuration property.

[[contract]]
.KafkaPrincipalBuilder Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| build
a| [[build]]

[source, java]
----
KafkaPrincipal build(
  AuthenticationContext context)
----

Builds a link:kafka-common-security-auth-KafkaPrincipal.adoc[KafkaPrincipal] for the `AuthenticationContext`

Used when:

* `PlaintextAuthenticator` is requested for a `principal`

* `SaslServerAuthenticator` is requested for a `principal`

* `SslAuthenticator` is requested for a link:kafka-common-network-SslChannelBuilder-SslAuthenticator.adoc#principal[principal]

|===

[[implementations]]
NOTE: link:kafka-common-security-authenticator-DefaultKafkaPrincipalBuilder.adoc[DefaultKafkaPrincipalBuilder] is the default and only known `KafkaPrincipalBuilder` in Apache Kafka.
