== [[SaslChannelBuilder]] SaslChannelBuilder

`SaslChannelBuilder` is a link:kafka-common-network-ChannelBuilder.adoc[ChannelBuilder] for SSL channels on Kafka clients and brokers.

`SaslChannelBuilder` is a `ListenerReconfigurable`.

`SaslChannelBuilder` is <<creating-instance, created>> when `ChannelBuilders` utility is used to link:kafka-common-network-ChannelBuilders.adoc#create[create a ChannelBuilder] for `SASL_SSL` or `SASL_PLAINTEXT` security protocols.

=== [[creating-instance]] Creating SaslChannelBuilder Instance

`SaslChannelBuilder` takes the following to be created:

* [[mode]] `Mode` (i.e. `CLIENT` or `SERVER`)
* [[jaasContexts]] Lookup table of `JaasContexts` by name
* [[securityProtocol]] `SecurityProtocol`
* [[listenerName]] Listener name (only for `SERVER` channel builder)
* [[isInterBrokerListener]] `isInterBrokerListener` flag
* [[clientSaslMechanism]] `clientSaslMechanism` text
* [[handshakeRequestEnable]] `handshakeRequestEnable` flag
* [[credentialCache]] `CredentialCache`
* [[tokenCache]] `DelegationTokenCache`
* [[time]] `Time`

`SaslChannelBuilder` initializes the <<internal-properties, internal properties>>.

=== [[configure]] `configure` Method

[source, java]
----
void configure(
  Map<String, ?> configs)
----

NOTE: `configure` is part of the link:kafka-common-Configurable.adoc#configure[Configurable] contract to pass configurations.

`configure`...FIXME

=== [[buildChannel]] Creating KafkaChannel -- `buildChannel` Method

[source, java]
----
KafkaChannel buildChannel(
  String id,
  SelectionKey key,
  int maxReceiveSize,
  MemoryPool memoryPool)
----

NOTE: `buildChannel` is part of the link:kafka-common-network-ChannelBuilder.adoc#buildChannel[ChannelBuilder] contract to build a `KafkaChannel`.

`buildChannel`...FIXME

=== [[buildTransportLayer]] `buildTransportLayer` Method

[source, java]
----
TransportLayer buildTransportLayer(
  String id,
  SelectionKey key,
  SocketChannel socketChannel)
----

`buildTransportLayer`...FIXME

NOTE: `buildTransportLayer` is used when `SaslChannelBuilder` is requested to <<buildChannel, buildChannel>>.
