== [[ZkReplicaStateMachine]] ZkReplicaStateMachine

`ZkReplicaStateMachine` is...FIXME

=== [[getTopicPartitionStatesFromZk]] `getTopicPartitionStatesFromZk` Internal Method

[source, scala]
----
getTopicPartitionStatesFromZk(partitions: Seq[TopicPartition]):
  (Map[TopicPartition, LeaderAndIsr],
   Seq[TopicPartition],
   Map[TopicPartition, Exception])
----

`getTopicPartitionStatesFromZk`...FIXME

NOTE: `getTopicPartitionStatesFromZk` is used exclusively when `ZkReplicaStateMachine` is requested to <<doRemoveReplicasFromIsr, doRemoveReplicasFromIsr>>.

=== [[doRemoveReplicasFromIsr]] `doRemoveReplicasFromIsr` Internal Method

[source, scala]
----
doRemoveReplicasFromIsr(
  replicaId: Int,
  partitions: Seq[TopicPartition]):
(Map[TopicPartition, LeaderIsrAndControllerEpoch],
 Seq[TopicPartition],
 Map[TopicPartition, Exception])
----

`doRemoveReplicasFromIsr`...FIXME

NOTE: `doRemoveReplicasFromIsr` is used exclusively when `ZkReplicaStateMachine` is requested to <<removeReplicasFromIsr, removeReplicasFromIsr>>.

=== [[removeReplicasFromIsr]] `removeReplicasFromIsr` Internal Method

[source, scala]
----
removeReplicasFromIsr(
  replicaId: Int,
  partitions: Seq[TopicPartition]):
Map[TopicPartition, LeaderIsrAndControllerEpoch]
----

`removeReplicasFromIsr`...FIXME

NOTE: `removeReplicasFromIsr` is used exclusively when `ZkReplicaStateMachine` is requested to <<doHandleStateChanges, doHandleStateChanges>>.

=== [[doHandleStateChanges]] `doHandleStateChanges` Internal Method

[source, scala]
----
doHandleStateChanges(
  replicaId: Int,
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState): Unit
----

`doHandleStateChanges`...FIXME

NOTE: `doHandleStateChanges` is used exclusively when `ZkReplicaStateMachine` is requested to <<handleStateChanges, handleStateChanges>>.

=== [[handleStateChanges]] `handleStateChanges` Method

[source, scala]
----
handleStateChanges(
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState): Unit
----

NOTE: `handleStateChanges` is part of the <<kafka-controller-ReplicaStateMachine.adoc#handleStateChanges, ReplicaStateMachine Contract>> to...FIXME.

`handleStateChanges`...FIXME
