== [[LogConfig]] LogConfig

`LogConfig` is a Apache Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/config/AbstractConfig.html[AbstractConfig] for the <<properties, configuration properties>> of a...FIXME

[[properties]]
.LogConfig's Configuration Properties
[cols="1,3",options="header",width="100%"]
|===
| Name / Default Value / Property
| Description

| CleanupPolicyProp

Default: `delete`

Property: <<kafka-common-TopicConfig.adoc#CLEANUP_POLICY_CONFIG, cleanup.policy>>

a| [[CleanupPolicyProp]][[cleanup.policy]] Refer to <<kafka-properties.adoc#log.cleanup.policy, log.cleanup.policy>>

Synonym of <<kafka-server-KafkaConfig.adoc#LogCleanupPolicyProp, log.cleanup.policy>>

Used when:

* `GroupCoordinator` is requested for the <<kafka-coordinator-group-GroupCoordinator.adoc#offsetsTopicConfigs, offsetsTopicConfigs>>

* `TransactionStateManager` is requested for the <<kafka-TransactionStateManager.adoc#transactionTopicConfigs, transactionTopicConfigs>>

* `LogConfig` is requested for the <<compact, compact>> and <<delete, delete>> flags

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#copyKafkaConfigToLog, copyKafkaConfigToLog>>

| FileDeleteDelayMsProp

Default: `60000`

Property: `file.delete.delay.ms`

a| [[file.delete.delay.ms]][[FileDeleteDelayMsProp]][[fileDeleteDelayMs]] The time (in millis) to wait before deleting a file from the filesystem

Must be at least `0`

| SegmentIndexBytesProp

Default: `10 * 1024 * 1024`

Property: `segment.index.bytes`

a| [[segment.index.bytes]][[maxIndexSize]][[SegmentIndexBytesProp]] Size of the index that maps offsets to file positions. We preallocate this index file and shrink it only after log rolls.

You generally should not need to change this setting.

Must be at least `0`

|===

=== [[compact]] Checking Out Whether Compact Cleanup Policy Is Enabled -- `compact` Flag

[source, scala]
----
compact: Boolean
----

`compact`...FIXME

NOTE: `compact` is used when...FIXME

=== [[delete]] Checking Out Whether Delete Cleanup Policy Is Enabled -- `delete` Flag

[source, scala]
----
delete: Boolean
----

`delete`...FIXME

NOTE: `delete` is used when...FIXME
