== [[LeaderAndIsrRequest]] LeaderAndIsrRequest

[[LEADER_AND_ISR]][[creating-instance]]
`LeaderAndIsrRequest` is a <<kafka-controller-AbstractControlRequest.adoc#, controller request>> with *LeaderAndIsr* API key and the following properties:

* [[controllerId]] Controller ID
* [[controllerEpoch]] Controller Epoch
* [[brokerEpoch]] Broker Epoch
* [[partitionStates]] `PartitionStates` by `TopicPartition` (`Map<TopicPartition, PartitionState>`)
* [[liveLeaders]] *Live leaders* (brokers with leaders)
* [[version]] Version

`LeaderAndIsrRequest` is <<creating-instance, created>> (via <<build, build>> factory method) when:

* `AbstractRequest` is requested to <<kafka-common-requests-AbstractRequest.adoc#parseRequest, parse a request>> (with the <<LEADER_AND_ISR, LeaderAndIsr>> API key)

* `LeaderAndIsrRequest` is requested to <<parse, parse a byte buffer>>

* `LeaderAndIsrRequest.Builder` is requested to <<build, build a LeaderAndIsrRequest>> (when `ControllerBrokerRequestBatch` is requested to <<kafka-controller-AbstractControllerBrokerRequestBatch.adoc#sendRequestsToBrokers, sendRequestsToBrokers>>)

=== [[LeaderAndIsrRequest.Builder]][[Builder]][[build]] `LeaderAndIsrRequest.Builder` Factory Object

`LeaderAndIsrRequest` comes with a concrete <<kafka-common-requests-AbstractRequest.adoc#Builder, AbstractRequest.Builder>> factory object that can <<kafka-common-requests-AbstractRequest-Builder.adoc#build, build>> a <<LeaderAndIsrRequest, LeaderAndIsrRequest>>.

[source, java]
----
LeaderAndIsrRequest build(short version)
----

`LeaderAndIsrRequest.Builder` is used exclusively when `AbstractControllerBrokerRequestBatch` is requested to <<kafka-controller-AbstractControllerBrokerRequestBatch.adoc#sendLeaderAndIsrRequest, send LeaderAndIsr requests out to all brokers>>.

=== [[parse]] Creating LeaderAndIsrRequest from Byte Buffer -- `parse` Factory Method

[source, java]
----
LeaderAndIsrRequest parse(
  ByteBuffer buffer,
  short version)
----

`parse` simply creates a <<LeaderAndIsrRequest, LeaderAndIsrRequest>>.

NOTE: `parse` is used when...FIXME
