== [[ConsumerNetworkClient]] ConsumerNetworkClient

`ConsumerNetworkClient` is a high-level Kafka consumer that...FIXME

`ConsumerNetworkClient` is <<creating-instance, created>> for link:kafka-clients-consumer-KafkaConsumer.adoc#client[KafkaConsumer] and link:kafka-AdminClient.adoc[AdminClient].

[[internal-registries]]
.ConsumerNetworkClient's Internal Properties (e.g. Registries and Counters)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[pendingCompletion]] `pendingCompletion`
|

| [[unsent]] `unsent`
| `UnsentRequests` with pending requests per node that have not been sent yet (i.e. awaiting transmission).
|===

[[logging]]
[TIP]
====
Enable `DEBUG` logging level for `org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient=DEBUG
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[checkDisconnects]] `checkDisconnects` Internal Method

[source, java]
----
void checkDisconnects(long now)
----

`checkDisconnects`...FIXME

NOTE: `checkDisconnects` is used exclusively when `ConsumerNetworkClient` is requested to <<poll, poll>>.

=== [[send]] "Sending" Request to Broker -- `send` Method

[source, java]
----
RequestFuture<ClientResponse> send(Node node, AbstractRequest.Builder<?> requestBuilder)
----

`send` creates a `RequestFutureCompletionHandler` and requests the <<client, KafkaClient>> for a link:kafka-clients-KafkaClient.adoc#newClientRequest[new ClientRequest] (with the `RequestFutureCompletionHandler` and expecting a response).

`send` records the new `ClientRequest` with the `node` in <<unsent, unsent>> internal registry.

`send` requests the <<client, KafkaClient>> to link:kafka-clients-KafkaClient.adoc#wakeup[wake up].

NOTE: `send` is used...FIXME

=== [[wakeup]] `wakeup` Method

[source, scala]
----
void wakeup()
----

`wakeup` prints out the following DEBUG message to the logs:

```
Received user wakeup
```

`wakeup` turns the internal <<wakeup, wakeup>> flag on and requests <<client, KafkaClient>> to link:kafka-clients-KafkaClient.adoc#wakeup[wakeup]

NOTE: `wakeup` is used when...FIXME

=== [[ensureFreshMetadata]] Ensuring Fresh Metadata (and Possibly Blocking Until It Refreshes) -- `ensureFreshMetadata` Method

[source, java]
----
void ensureFreshMetadata()
----

`ensureFreshMetadata` <<awaitMetadataUpdate, waits for metadata update>> when <<metadata, Metadata>> was requested for link:kafka-clients-Metadata.adoc#updateRequested[update] or link:kafka-clients-Metadata.adoc#timeToNextUpdate[time to the next update] is now.

NOTE: `ensureFreshMetadata` is used when `ConsumerCoordinator` does link:kafka-consumer-internals-ConsumerCoordinator.adoc#onJoinComplete[onJoinComplete], link:kafka-consumer-internals-ConsumerCoordinator.adoc#performAssignment[performAssignment] and link:kafka-consumer-internals-ConsumerCoordinator.adoc#poll[poll].

=== [[pendingRequestCount]] `pendingRequestCount` Method

CAUTION: FIXME

=== [[leastLoadedNode]] `leastLoadedNode` Method

CAUTION: FIXME

=== [[poll]] `poll` Method

[source, java]
----
void poll(long timeout)
void poll(long timeout, long now, PollCondition pollCondition)
void poll(long timeout, long now, PollCondition pollCondition, boolean disableWakeup)
void poll(RequestFuture<?> future)
boolean poll(RequestFuture<?> future, long timeout)
----

`poll`...FIXME

[NOTE]
====
`poll` is used when:

* `KafkaConsumer` link:kafka-clients-consumer-KafkaConsumer.adoc#pollOnce[polls once]
* `ConsumerNetworkClient` does <<pollNoWakeup, pollNoWakeup>>, <<awaitMetadataUpdate, awaitMetadataUpdate>>, <<awaitPendingRequests, awaitPendingRequests>>
* `AbstractCoordinator` does `ensureCoordinatorReady` and `joinGroupIfNeeded`
* `ConsumerCoordinator` link:kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsSync[commitOffsetsSync] and link:kafka-consumer-internals-ConsumerCoordinator.adoc#fetchCommittedOffsets[fetchCommittedOffsets]
* `Fetcher` is requested for link:kafka-Fetcher.adoc#getTopicMetadata[topic metadata] or link:kafka-Fetcher.adoc#retrieveOffsetsByTimes[retrieveOffsetsByTimes]
====

=== [[awaitMetadataUpdate]] Waiting for Metadata Update -- `awaitMetadataUpdate` Method

[source, java]
----
boolean awaitMetadataUpdate(long timeout)
----

`awaitMetadataUpdate`...FIXME

NOTE: `awaitMetadataUpdate` is used when...FIXME

=== [[awaitPendingRequests]] `awaitPendingRequests` Method

CAUTION: FIXME

=== [[pollNoWakeup]] `pollNoWakeup` Method

[source, java]
----
void pollNoWakeup()
----

`pollNoWakeup`...FIXME

[NOTE]
====
`pollNoWakeup` is used when:

* `KafkaConsumer` link:kafka-clients-consumer-KafkaConsumer.adoc#poll[polls]
* `AbstractCoordinator` does `maybeLeaveGroup`
* `HeartbeatThread` runs
* `ConsumerCoordinator` does `commitOffsetsAsync`
====

=== [[creating-instance]] Creating ConsumerNetworkClient Instance

`ConsumerNetworkClient` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] link:kafka-clients-KafkaClient.adoc[KafkaClient]
* [[metadata]] link:kafka-clients-Metadata.adoc[Metadata]
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[requestTimeoutMs]] `requestTimeoutMs`

`ConsumerNetworkClient` initializes the <<internal-registries, internal registries and counters>>.
