== [[BrokerReconfigurable]] BrokerReconfigurable Contract -- Reconfigurable Broker Services

`BrokerReconfigurable` is the <<contract, contract>> of <<implementations, reconfigurable broker services>> that allow for <<reconfigure, self-reconfiguration>>.

`BrokerReconfigurable` interface is used exclusively by <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>>.

[[contract]]
.BrokerReconfigurable Contract
[cols="1m,2",options="header",width="100%"]
|===
| Property
| Description

| reconfigurableConfigs
a| [[reconfigurableConfigs]]

[source, scala]
----
reconfigurableConfigs: Set[String]
----

Dynamic configurations

Used when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#addBrokerReconfigurable, addBrokerReconfigurable>> and <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>

| reconfigure
a| [[reconfigure]]

[source, scala]
----
reconfigure(oldConfig: KafkaConfig, newConfig: KafkaConfig): Unit
----

Used exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#updateCurrentConfig, updateCurrentConfig>>

| validateReconfiguration
a| [[validateReconfiguration]]

[source, scala]
----
validateReconfiguration(newConfig: KafkaConfig): Unit
----

Used exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>
|===

[[implementations]]
.BrokerReconfigurables (Direct Implementations)
[cols="1,2",options="header",width="100%"]
|===
| BrokerReconfigurable
| Description

| <<kafka-server-DynamicConnectionQuota.adoc#, DynamicConnectionQuota>>
| [[DynamicConnectionQuota]]

| <<kafka-server-DynamicListenerConfig.adoc#, DynamicListenerConfig>>
| [[DynamicListenerConfig]]

| <<kafka-server-DynamicThreadPool.adoc#, DynamicThreadPool>>
| [[DynamicThreadPool]]

| <<kafka-log-LogCleaner.adoc#, LogCleaner>>
| [[LogCleaner]]

|===
