== [[ReassignPartitionsCommand]] ReassignPartitionsCommand

`ReassignPartitionsCommand` is...FIXME

=== [[main]] Starting ReassignPartitionsCommand on Command Line -- `main` Entry Method

[source, scala]
----
main(args: Array[String]): Unit
----

`main`...FIXME

=== [[executeAssignment]] `executeAssignment` Method

[source, scala]
----
executeAssignment(
  zkUtils: ZkUtils,
  adminClientOpt: Option[AdminClient],
  opts: ReassignPartitionsCommand.ReassignPartitionsCommandOptions): Unit

executeAssignment(
  zkUtils: ZkUtils,
  adminClientOpt: Option[AdminClient],
  reassignmentJsonString: String,
  throttle: ReassignPartitionsCommand.Throttle,
  timeoutMs: Long = 10000L): Unit
----

`executeAssignment`...FIXME

NOTE: `executeAssignment` is used exclusively when `ReassignPartitionsCommand` is <<main, started on command line>> with `execute` option.

=== [[reassignPartitions]] `reassignPartitions` Method

[source, scala]
----
reassignPartitions(throttle: Throttle = NoThrottle, timeoutMs: Long = 10000L): Boolean
----

`reassignPartitions`...FIXME

NOTE: `reassignPartitions` is used exclusively when `ReassignPartitionsCommand` <<executeAssignment, executeAssignment>>.

=== [[alterReplicaLogDirsIgnoreReplicaNotAvailable]] `alterReplicaLogDirsIgnoreReplicaNotAvailable` Internal Method

[source, scala]
----
alterReplicaLogDirsIgnoreReplicaNotAvailable(
  replicaAssignment: Map[TopicPartitionReplica, String],
  adminClient: JAdminClient,
  timeoutMs: Long): Set[TopicPartitionReplica]
----

`alterReplicaLogDirsIgnoreReplicaNotAvailable`...FIXME

NOTE: `alterReplicaLogDirsIgnoreReplicaNotAvailable` is used exclusively when `ReassignPartitionsCommand` <<reassignPartitions, reassignPartitions>>

=== [[generateAssignment]] `generateAssignment` Method

[source, scala]
----
generateAssignment(
  zkClient: KafkaZkClient,
  brokerListToReassign: Seq[Int],
  topicsToMoveJsonString: String,
  disableRackAware: Boolean)
: (Map[TopicPartition, Seq[Int]], Map[TopicPartition, Seq[Int]])
----

`generateAssignment`...FIXME

NOTE: `generateAssignment` is used when...FIXME

=== [[verifyAssignment]] `verifyAssignment` Method

[source, scala]
----
verifyAssignment(
  zkClient: KafkaZkClient,
  adminClientOpt: Option[JAdminClient],
  jsonString: String): Unit
----

`verifyAssignment`...FIXME

NOTE: `verifyAssignment` is used when...FIXME

=== [[parseAndValidate]] `parseAndValidate` Method

[source, scala]
----
parseAndValidate(
  zkClient: KafkaZkClient,
  reassignmentJsonString: String)
: (Seq[(TopicPartition, Seq[Int])], Map[TopicPartitionReplica, String])
----

`parseAndValidate`...FIXME

NOTE: `parseAndValidate` is used when...FIXME

=== [[removeThrottle]] `removeThrottle` Method

[source, scala]
----
removeThrottle(
  zkClient: KafkaZkClient,
  reassignedPartitionsStatus: Map[TopicPartition, ReassignmentStatus],
  replicasReassignmentStatus: Map[TopicPartitionReplica, ReassignmentStatus],
  adminZkClient: AdminZkClient): Unit
----

`removeThrottle`...FIXME

NOTE: `removeThrottle` is used when...FIXME
