== [[ProducerConfig]] ProducerConfig

`ProducerConfig` is the configuration of a <<kafka-KafkaProducer.adoc#, Kafka Producer>>.

`ProducerConfig` is <<creating-instance, created>> when:

* ...

[[configuration-values]]
.ProducerConfig's Configuration Properties
[cols="1m,1,1m,2",options="header",width="100%"]
|===
| Name
| Default Value
| Kafka Property
| Description

| CLIENT_ID_CONFIG
| (empty)
| client.id
a| [[CLIENT_ID_CONFIG]]

An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

| INTERCEPTOR_CLASSES_CONFIG
|
|
a| [[INTERCEPTOR_CLASSES_CONFIG]]

| MAX_REQUEST_SIZE_CONFIG
|
| max.request.size
a| [[MAX_REQUEST_SIZE_CONFIG]] The maximum size of a request in bytes. This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests. This is also effectively a cap on the maximum record batch size.

Note that the server has its own cap on record batch size which may be different.

| METRICS_NUM_SAMPLES_CONFIG
|
| metrics.num.samples
a| [[METRICS_NUM_SAMPLES_CONFIG]] The number of samples maintained to compute metrics (for <<kafka-KafkaProducer.adoc#, Kafka producers>>). Must be at least `1`.

| METRICS_RECORDING_LEVEL_CONFIG
|
| metrics.recording.level
a| [[METRICS_RECORDING_LEVEL_CONFIG]] The name of highest recording level for metrics. Must be one of the following: `INFO` or `DEBUG`.

| METRIC_REPORTER_CLASSES_CONFIG
|
| metric.reporters
a| [[METRIC_REPORTER_CLASSES_CONFIG]] The class names of the <<kafka-MetricsReporter.adoc#, MetricsReporters>> that will be notified of new metric creation.

The <<kafka-MetricsReporter.adoc#JmxReporter, JmxReporter>> is always included to register JMX statistics.

| METRICS_SAMPLE_WINDOW_MS_CONFIG
|
| metrics.sample.window.ms
a| [[METRICS_SAMPLE_WINDOW_MS_CONFIG]] The window of time a metrics sample is computed over (for <<kafka-KafkaProducer.adoc#, Kafka producers>>).

| RETRY_BACKOFF_MS_CONFIG
|
| retry.backoff.ms
a| [[RETRY_BACKOFF_MS_CONFIG]] The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.
|===
