== [[KafkaScheduler]] KafkaScheduler

`KafkaScheduler` is a concrete <<kafka-Scheduler.adoc#, Scheduler>> to <<schedule, schedule tasks>> in Apache Kafka.

`KafkaScheduler` is <<creating-instance, created>> when:

* `KafkaController` is <<kafka-KafkaController.adoc#, created>> (and initializes <<kafka-KafkaController.adoc#kafkaScheduler, kafkaScheduler>> and <<kafka-KafkaController.adoc#tokenCleanScheduler, tokenCleanScheduler>>)

* `GroupMetadataManager` is <<kafka-GroupMetadataManager.adoc#scheduler, created>>

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#startup, start up>>

* `ZooKeeperClient` is <<kafka-KafkaServer.adoc#expiryScheduler, created>>

`KafkaScheduler` is used to create a <<kafka-LogManager.adoc#apply, LogManager>> and a <<kafka-TransactionCoordinator.adoc#apply, TransactionCoordinator>>.

[[internal-registries]]
.KafkaScheduler's Internal Properties (e.g. Registries and Counters)
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[executor]] `executor`
| Java's link:https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html[ScheduledThreadPoolExecutor] used to <<schedule, schedule tasks>>.

Initialized when <<startup, `KafkaScheduler` starts up>> and shut down when <<shutdown, `KafkaScheduler` shuts down>>.
|===

[[logging]]
[TIP]
====
Enable `INFO` or `DEBUG` logging levels for `kafka.utils.KafkaScheduler` logger to see what happens in `KafkaScheduler`.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.utils.KafkaScheduler=DEBUG, stdout
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[startup]] Starting Up -- `startup` Method

[source, scala]
----
startup(): Unit
----

NOTE: `startup` is a part of <<contract, Scheduler contract>>.

When `startup` is executed, you should see the following DEBUG message in the logs:

```
DEBUG Initializing task scheduler. (kafka.utils.KafkaScheduler)
```

`startup` initializes <<executor, executor>> with `threads` threads. The name of the threads is in format of `threadNamePrefix` followed by `schedulerThreadId`, e.g. `kafka-scheduler-0`

NOTE: `threads` and `threadNamePrefix` are defined when <<creating-instance, `KafkaScheduler` is created>>.

If `KafkaScheduler` is already started, `startup` throws a `IllegalStateException` with the message:

```
This scheduler has already been started!
```

=== [[shutdown]] `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

NOTE: `shutdown` is part of the <<kafka-Scheduler.adoc#shutdown, Scheduler Contract>> to...FIXME.

`shutdown`...FIXME

=== [[ensureRunning]] `ensureRunning` Internal Method

[source, scala]
----
ensureRunning(): Unit
----

`ensureRunning`...FIXME

NOTE: `ensureRunning` is used when...FIXME

=== [[schedule]] Scheduling Tasks -- `schedule` Method

[source, scala]
----
def schedule(
  name: String,
  fun: () => Unit,
  delay: Long = 0,
  period: Long = -1,
  unit: TimeUnit = TimeUnit.MILLISECONDS)
----

NOTE: `schedule` is part of the <<kafka-Scheduler.adoc#schedule, Scheduler Contract>> to schedule a task.

When `schedule` is executed, you should see the following DEBUG message in the logs:

```
DEBUG Scheduling task [name] with initial delay [delay] ms and period [period] ms. (kafka.utils.KafkaScheduler)
```

NOTE: `schedule` uses Java's link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html#convert-long-java.util.concurrent.TimeUnit-++[java.util.concurrent.TimeUnit] to convert `delay` and `period` to milliseconds.

`schedule` first <<ensureRunning, makes sure that `KafkaScheduler` is running>> (which simply means that the internal <<executor, executor>> has been initialized).

`schedule` creates an execution thread for the input `fun`.

For positive `period`, `schedule` schedules the thread every `period` after the initial `delay`. Otherwise, `schedule` schedules the thread once.

NOTE: `schedule` uses the internal <<executor, executor>> to schedule `fun` using link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.scheduleAtFixedRate] and link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#schedule-java.lang.Runnable-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.schedule] for periodic and one-off executions, respectively.

Whenever the thread is executed, and before `fun` gets triggerred, you should see the following TRACE message in the logs:

```
Beginning execution of scheduled task '[name]'.
```

After the execution thread is finished, you should see the following TRACE message in the logs:

```
Completed execution of scheduled task '[name]'.
```

In case of any exceptions, the execution thread catches them and you should see the following ERROR message in the logs:

```
Uncaught exception in scheduled task '[name]'
```

=== [[creating-instance]] Creating KafkaScheduler Instance

`KafkaScheduler` takes the following when created:

* [[threads]] Number of threads
* [[threadNamePrefix]] Thread name prefix (default: `kafka-scheduler-`)
* [[daemon]] `daemon` flag (default: `true`)

`KafkaScheduler` initializes the <<internal-registries, internal registries and counters>>.
