== Partition Leader Election

*Partition Leader Election* is a process of electing a broker to be the leader of a partition.

Use link:kafka-tools-kafka-leader-election.adoc[kafka-leader-election.sh] utility for <<preferred-partition-leader-election, preferred>> or <<unclean-partition-leader-election, unclean>> leader election.

TIP: Consult link:kafka-demo-using-kafka-leader-election.adoc[Demo: Using kafka-leader-election.sh].

NOTE: `kafka-preferred-replica-election.sh` tool has been deprecated since Kafka 2.4.0 (cf. link:++https://cwiki.apache.org/confluence/display/KAFKA/KIP-460%3A+Admin+Leader+Election+RPC++[KIP-460: Admin Leader Election RPC]).

Observe `state.change.logger` (default: `state-change.log`) to trace the process in the logs.

Internally, Kafka controller uses link:kafka-controller-Election.adoc[Election] utility (and link:kafka-controller-PartitionLeaderElectionAlgorithms.adoc[PartitionLeaderElectionAlgorithms]) for the algorithms for partition leader election.

=== [[preferred-partition-leader-election]] Preferred Partition Leader Election

*Preferred Partition Leader Election* is...FIXME

=== [[unclean-partition-leader-election]] Unclean Partition Leader Election

*Unclean Partition Leader Election* allows a non-ISR replica to be elected as a partition leader (as the last resort, even though doing so may result in data loss).

link:kafka-properties.adoc#unclean.leader.election.enable[unclean.leader.election.enable] configuration property is used to enable it cluster-wide (for any topic) or per topic.

Enable INFO logging level for link:kafka-controller-KafkaController.adoc#logging[kafka.controller.KafkaController] logger to observe the link:kafka-controller-KafkaController.adoc#processUncleanLeaderElectionEnable[process] in the logs.
