== [[DefaultMetadataUpdater]] DefaultMetadataUpdater

`DefaultMetadataUpdater` is a <<kafka-clients-MetadataUpdater.adoc#, MetadataUpdater>> that `NetworkClient` uses to...FIXME

[[creating-instance]]
[[metadata]]
`DefaultMetadataUpdater` takes a single <<kafka-clients-Metadata.adoc#, Metadata>> when created.

`DefaultMetadataUpdater` is <<creating-instance, created>> exclusively for a <<kafka-clients-NetworkClient.adoc#metadataUpdater, NetworkClient>>.

[[internal-registries]]
.DefaultMetadataUpdater's Internal Properties (e.g. Registries and Counters)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| metadataFetchInProgress
a| [[metadataFetchInProgress]] Flag to control whether a cluster metadata update is in progress, i.e. FIXME

* Disabled when `DefaultMetadataUpdater` is <<creating-instance, created>>

* Turned on exclusively when `DefaultMetadataUpdater` does <<maybeUpdate-long-node, maybeUpdate>> (with a timestamp and a broker node)

* Turned off when `DefaultMetadataUpdater` handles <<handleCompletedMetadataResponse, completed metadata response>>, <<handleDisconnection, disconnection>> or <<handleAuthenticationFailure, authentication failure>>

|===

[[logging]]
[TIP]
====
Enable `WARN`, `DEBUG` or `TRACE` logging levels for `org.apache.kafka.clients.NetworkClient` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.NetworkClient=DEBUG
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[isUpdateDue]] `isUpdateDue` Method

CAUTION: FIXME

=== [[maybeUpdate-long]] `maybeUpdate` Internal Method (with timestamp only)

[source, java]
----
maybeUpdate(long now)
----

NOTE: `maybeUpdate` is a part of link:kafka-clients-MetadataUpdater.adoc#maybeUpdate[MetadataUpdater Contract].

`maybeUpdate` requests <<metadata, Metadata>> for link:kafka-clients-Metadata.adoc#timeToNextUpdate[timeToNextUpdate] (with the input `now`).

`maybeUpdate` takes link:kafka-clients-NetworkClient.adoc#requestTimeoutMs[requestTimeoutMs] for the time to wait till metadata fetch in progress finishes if <<metadataFetchInProgress, metadataFetchInProgress>> flag is turned on or `0` otherwise.

`maybeUpdate` takes the maximum of the two values above to check if the current cluster metadata has expired.

If not, `maybeUpdate` gives the maximum value (that says how long to wait till the current cluster metadata expires).

Otherwise, `maybeUpdate` <<leastLoadedNode, selects the node>> to request a cluster metadata from and <<maybeUpdate-long-node, maybeUpdate>> (with the input `now` timestamp and the node).

If no node was found, `maybeUpdate` prints out the following DEBUG message to the logs and gives link:kafka-clients-NetworkClient.adoc#reconnectBackoffMs[reconnectBackoffMs].

```
Give up sending metadata request since no node is available
```

=== [[maybeUpdate-long-node]] `maybeUpdate` Internal Method (with timestamp and node)

[source, java]
----
long maybeUpdate(long now, Node node)
----

`maybeUpdate`...FIXME

NOTE: `maybeUpdate` is used exclusively when `DefaultMetadataUpdater` is requested to <<maybeUpdate-long, maybeUpdate>> (with the timestamp only).

=== [[handleAuthenticationFailure]] `handleAuthenticationFailure` Callback Method

[source, java]
----
void handleAuthenticationFailure(AuthenticationException exception)
----

NOTE: `handleAuthenticationFailure` is a part of link:kafka-clients-MetadataUpdater.adoc#handleAuthenticationFailure[MetadataUpdater Contract].

`handleCompletedMetadataResponse` turns link:kafka-clients-NetworkClient.adoc#metadataFetchInProgress[metadataFetchInProgress] flag off.

`handleCompletedMetadataResponse` asks <<metadata, Metadata>> whether link:kafka-clients-Metadata.adoc#updateRequested[metadata update was requested] and if so requests it to link:kafka-clients-Metadata.adoc#failedUpdate[record a failure] (passing on the `exception`).

=== [[handleCompletedMetadataResponse]] `handleCompletedMetadataResponse` Callback Method

[source, java]
----
void handleCompletedMetadataResponse(RequestHeader requestHeader, long now, MetadataResponse response)
----

NOTE: `handleCompletedMetadataResponse` is a part of link:kafka-clients-MetadataUpdater.adoc#handleCompletedMetadataResponse[MetadataUpdater Contract].

`handleCompletedMetadataResponse` turns <<metadataFetchInProgress, metadataFetchInProgress>> flag off.

`handleCompletedMetadataResponse` takes the link:kafka-common-requests-MetadataResponse.adoc#cluster[cluster] from the `response`.

`handleCompletedMetadataResponse` requests <<metadata, Metadata>> to link:kafka-clients-Metadata.adoc#update[update] (with the cluster and unavailable topics) when there is at least one node in the cluster.

When there are no nodes in the cluster, `handleCompletedMetadataResponse` prints out the following TRACE message to the logs and requests <<metadata, Metadata>> to link:kafka-clients-Metadata.adoc#failedUpdate[record a failure] (with no exception).

```
Ignoring empty metadata response with correlation id [correlationId].
```

In case `response` has errors, `handleCompletedMetadataResponse` prints out the following WARN message to the logs:

```
Error while fetching metadata with correlation id [correlationId] : [errors]"
```

=== [[maybeUpdate]] `maybeUpdate` Method

[source, java]
----
long maybeUpdate(long now)
----

NOTE: `maybeUpdate` is part of the <<kafka-clients-MetadataUpdater.adoc#maybeUpdate, MetadataUpdater Contract>> to...FIXME.

`maybeUpdate`...FIXME

==== [[maybeUpdate-internal]] `maybeUpdate` Internal Method

[source, java]
----
long maybeUpdate(long now, Node node)
----

`maybeUpdate`...FIXME

NOTE: `maybeUpdate` is used exclusively when `DefaultMetadataUpdater` is requested to <<kafka-clients-DefaultMetadataUpdater.adoc#maybeUpdate, maybeUpdate>>.

=== [[requestUpdate]] Scheduling Update Of Cluster Metadata -- `requestUpdate` Method

[source, java]
----
void requestUpdate()
----

NOTE: `requestUpdate` is part of the <<kafka-clients-MetadataUpdater.adoc#requestUpdate, MetadataUpdater Contract>> to schedule an update of the current cluster metadata.

`requestUpdate` simply requests the <<metadata, Metadata>> for a <<kafka-clients-Metadata.adoc#requestUpdate, metadata update>>.
