== [[PreferredReplicaLeaderElectionCommand]] PreferredReplicaLeaderElectionCommand Standalone Application

`kafka.admin.PreferredReplicaLeaderElectionCommand` is a <<main, standalone application>> to trigger <<electPreferredLeaders, preferred replica leader election>> for all or <<path-to-json-file, some partitions>>.

`PreferredReplicaLeaderElectionCommand` uses <<kafka-clients-admin-AdminClient.adoc#, AdminClient>> internally and is simply a command-line front-end to <<kafka-clients-admin-AdminClient.adoc#electPreferredLeaders, AdminClient.electPreferredLeaders>>.

`PreferredReplicaLeaderElectionCommand` is usually executed on command line using <<kafka-tools-kafka-preferred-replica-election.adoc#, kafka-preferred-replica-election.sh>> shell script (that simply uses `kafka-run-class` shell script to launch the command).

[[options]]
[[PreferredReplicaLeaderElectionCommandOptions]]
.Options
[cols="30m,70",options="header",width="100%"]
|===
| Option
| Description

| admin.config
a| [[admin.config]][[admin-config]] Config properties file to pass to the admin client

| bootstrap-server
a| [[bootstrap-server]] *(required)* Brokers to connect to as a comma-separated list of `host:port` URLs

| help
a| [[help]] Prints usage information

| path-to-json-file
a| [[path-to-json-file]] JSON file with partitions for preferred replica leader election

Default: `(empty)` (all partitions)

The format of the JSON file should be as follows:

```
{ "partitions":
  [
    { "topic": "foo", "partition": 1 },
    { "topic": "foobar", "partition": 2 }
  ]
}
```

The JSON file should not be empty and has no duplicate partitions (or `AdminOperationException` is thrown)

| version
a| [[version]] Displays Kafka version

|===

TIP: Read https://cwiki.apache.org/confluence/display/KAFKA/KIP-183+-+Change+PreferredReplicaLeaderElectionCommand+to+use+AdminClient[KIP-183 - Change PreferredReplicaLeaderElectionCommand to use AdminClient].

=== [[main]] Executing Standalone Application -- `main` Method

[source, scala]
----
main(args: Array[String]): Unit
----

`main` is the entry point of the `PreferredReplicaLeaderElectionCommand` standalone application when launched on command line (e.g. using <<kafka-tools-kafka-preferred-replica-election.adoc#, kafka-preferred-replica-election.sh>> shell script).

Internally, `main` simply <<run, run>> (with the default timeout of `30000`).

=== [[run]] `run` Object Method

[source, scala]
----
run(
  args: Array[String],
  timeout: Int = 30000): Unit
----

`run` reads the <<PreferredReplicaLeaderElectionCommandOptions, options>> from the command line.

`run` prints out the following for no <<options, command-line options>>, <<help, --help>> or <<version, --version>>:

[options="wrap"]
----
This tool helps to causes leadership for each partition to be transferred back to the 'preferred replica', it can be used to balance leadership among the servers.
----

`run` creates a new `AdminClientCommand` (with the <<admin-config, admin.config>> properties file when specified).

In the end, `run` requests the `AdminClientCommand` to <<electPreferredLeaders, electPreferredLeaders>> and then <<close, close>>.

NOTE: `run` is used exclusively when `PreferredReplicaLeaderElectionCommand` command-line application is <<main, executed>>.

=== [[electPreferredLeaders]] `electPreferredLeaders` Method

[source, scala]
----
electPreferredLeaders(
  partitionsFromUser: Option[Set[TopicPartition]]): Unit
----

`electPreferredLeaders` prints out the following DEBUG message to the logs:

```
Calling AdminClient.electPreferredLeaders([partitions])
```

`electPreferredLeaders` creates a new <<kafka-clients-admin-AdminClient.adoc#create, AdminClient>> and requests to <<kafka-clients-admin-AdminClient.adoc#electPreferredLeaders, electPreferredLeaders>>.

NOTE: `electPreferredLeaders` is used exclusively when `PreferredReplicaLeaderElectionCommand` is requested to <<run, run>>.

=== [[close]] Closing AdminClient -- `close` Method

[source, scala]
----
close(): Unit
----

`close` prints out the following DEBUG message to the logs and requests the `AdminClient` to <<kafka-clients-admin-AdminClient.adoc#close, close>>.

```
Closing AdminClient
```

NOTE: `close` is used exclusively when `PreferredReplicaLeaderElectionCommand` is requested to <<run, run>>.
