== [[SslEngineBuilder]] SslEngineBuilder

`SslEngineBuilder` is used to <<createSslEngine, create a SSLEngine>> (for link:kafka-common-security-ssl-SslFactory.adoc[SslFactory] that adds a reconfiguration layer atop).

`SslEngineBuilder` is <<creating-instance, created>> when `SslFactory` is requested to link:kafka-common-security-ssl-SslFactory.adoc#configure[configure] and link:kafka-common-security-ssl-SslFactory.adoc#reconfigure[reconfigure] (indirectly via link:kafka-common-security-ssl-SslFactory.adoc#createNewSslEngineBuilder[createNewSslEngineBuilder]).

[[logging]]
[TIP]
====
Enable `ALL` logging level for `org.apache.kafka.common.security.ssl.SslEngineBuilder` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.common.security.ssl.SslEngineBuilder=ALL
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[creating-instance]] Creating SslEngineBuilder Instance

`SslEngineBuilder` takes the following to be created:

* [[configs]] Configuration properties

`SslEngineBuilder` initializes the <<internal-properties, internal properties>>.

=== [[keystore]] SSL Key Store -- `keystore` Internal Property

[source, java]
----
SecurityStore keystore
----

`keystore` is <<createKeystore, created>> (alongside `SslEngineBuilder`) based on the following configuration properties:

* link:kafka-common-config-SslConfigs.adoc#SSL_KEYSTORE_TYPE_CONFIG[ssl.keystore.type]
* link:kafka-common-config-SslConfigs.adoc#SSL_KEYSTORE_LOCATION_CONFIG[ssl.keystore.location]
* link:kafka-common-config-SslConfigs.adoc#SSL_KEYSTORE_PASSWORD_CONFIG[ssl.keystore.password]
* link:kafka-common-config-SslConfigs.adoc#SSL_KEY_PASSWORD_CONFIG[ssl.key.password]

`keystore` is used...FIXME

=== [[truststore]] SSL Trust Store -- `truststore` Internal Property

[source, java]
----
SecurityStore truststore
----

Used when...FIXME

=== [[createSslEngine]] Creating SSLEngine -- `createSslEngine` Method

[source, java]
----
SSLEngine createSslEngine(
  Mode mode,
  String peerHost,
  int peerPort,
  String endpointIdentification)
----

`createSslEngine` requests the <<sslContext, SSLContext>> to create a new Java https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLEngine.html[SSLEngine] (for the advisory peer information, i.e. `peerHost` and `peerPort`) that is configured using...FIXME

If <<cipherSuites, enabled cipher suites>> and <<enabledProtocols, enabled protocol versions>> are configured, `createSslEngine` requests the `SSLEngine` to use them.

For `SERVER` mode, `createSslEngine` requests the `SSLEngine` to be in the server mode and configures it for *client authentication* based on the <<sslClientAuth, SslClientAuth>>:

* `REQUIRED` for client authentication required

* `REQUESTED` for client authentication requested (optional client authentication)

* `NONE` for no client authentication

For `CLIENT` mode, `createSslEngine` requests the `SSLEngine` to be in the client mode and sets the endpoint identification algorithm (to prevent man-in-the-middle attacks) based on the given `endpointIdentification`.

[NOTE]
====
`createSslEngine` is used when:

* `SslFactory` is requested to link:kafka-common-security-ssl-SslFactory.adoc#createSslEngine[createSslEngine]

* `SslEngineValidator` is requested to `createSslEngineForValidation`
====

=== [[createKeystore]] `createKeystore` Internal Utility

[source, java]
----
SecurityStore createKeystore(
  String type,
  String path,
  Password password,
  Password keyPassword)
----

`createKeystore`...FIXME

NOTE: `createKeystore` is used when `SslEngineBuilder` is <<creating-instance, created>>.

=== [[createTruststore]] `createTruststore` Internal Utility

[source, java]
----
SecurityStore createTruststore(
  String type,
  String path,
  Password password)
----

`createTruststore`...FIXME

NOTE: `createTruststore` is used when `SslEngineBuilder` is <<creating-instance, created>>.

=== [[createSSLContext]] `createSSLContext` Internal Method

[source, java]
----
SSLContext createSSLContext()
----

`createSSLContext`...FIXME

NOTE: `createSSLContext` is used when `SslEngineBuilder` is <<creating-instance, created>>.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| cipherSuites
a| [[cipherSuites]] Enabled cipher suites to use on a <<createSslEngine, SSLEngine>>.

| enabledProtocols
a| [[enabledProtocols]] Enabled protocol versions to use on a <<createSslEngine, SSLEngine>>.

| sslClientAuth
a| [[sslClientAuth]] Client authentication (`SslClientAuth`)

| sslContext
a| [[sslContext]] Java's https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLContext.html[SSLContext]

|===
