== [[ControllerContext]] ControllerContext

`ControllerContext` is the context of an active <<kafka-controller-KafkaController.adoc#, KafkaController>> (and is <<creating-instance, created>> right when `KafkaController` is <<kafka-controller-KafkaController.adoc#controllerContext, created>>).

[[creating-instance]]
`ControllerContext` takes no input arguments to be created.

=== [[allPartitions]] `allPartitions` Method

[source, scala]
----
allPartitions: Set[TopicPartition]
----

`allPartitions` converts the <<partitionReplicaAssignmentUnderlying, partitionReplicaAssignmentUnderlying>> into `TopicPartitions`, i.e. `allPartitions` takes the partitions for the topics and simply creates new `TopicPartitions`.

[NOTE]
====
`allPartitions` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderAndIsrCache, updateLeaderAndIsrCache>>, <<kafka-controller-KafkaController.adoc#checkAndTriggerAutoLeaderRebalance, checkAndTriggerAutoLeaderRebalance>>, and <<kafka-controller-KafkaController.adoc#updateMetrics, updateMetrics>>

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#initializePartitionState, initializePartitionState>>

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#initializeReplicaState, initializeReplicaState>>
====

=== [[updatePartitionReplicaAssignment]] `updatePartitionReplicaAssignment` Method

[source, scala]
----
updatePartitionReplicaAssignment(topicPartition: TopicPartition, newReplicas: Seq[Int]): Unit
----

`updatePartitionReplicaAssignment` simply updates the <<partitionReplicaAssignmentUnderlying, partitionReplicaAssignmentUnderlying>> registry with `newReplicas` for the topic and the partition (of a given `TopicPartition`).

[NOTE]
====
`updatePartitionReplicaAssignment` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#initializeControllerContext, initializeControllerContext>>, <<kafka-controller-KafkaController.adoc#moveReassignedPartitionLeaderIfRequired, moveReassignedPartitionLeaderIfRequired>>, <<kafka-controller-KafkaController.adoc#updateAssignedReplicasForPartition, updateAssignedReplicasForPartition>>, and at <<kafka-controller-ControllerEvent.adoc#TopicChange, TopicChange>> and <<kafka-controller-ControllerEvent.adoc#PartitionModifications, PartitionModifications>> controller events

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#doHandleStateChanges, doHandleStateChanges>>
====

=== [[partitionsOnBroker]] `partitionsOnBroker` Method

[source, scala]
----
partitionsOnBroker(brokerId: Int): Set[TopicPartition]
----

`partitionsOnBroker`...FIXME

NOTE: `partitionsOnBroker` is used when...FIXME

=== [[replicasOnBrokers]] `replicasOnBrokers` Method

[source, scala]
----
replicasOnBrokers(
  brokerIds: Set[Int]): Set[PartitionAndReplica]
----

`replicasOnBrokers`...FIXME

NOTE: `replicasOnBrokers` is used when...FIXME

=== [[replicasForTopic]] `replicasForTopic` Method

[source, scala]
----
replicasForTopic(topic: String): Set[PartitionAndReplica]
----

`replicasForTopic`...FIXME

NOTE: `replicasForTopic` is used when...FIXME

=== [[partitionsForTopic]] `partitionsForTopic` Method

[source, scala]
----
partitionsForTopic(topic: String): collection.Set[TopicPartition]
----

`partitionsForTopic`...FIXME

NOTE: `partitionsForTopic` is used when...FIXME

=== [[removeTopic]] `removeTopic` Method

[source, scala]
----
removeTopic(topic: String): Unit
----

`removeTopic`...FIXME

NOTE: `removeTopic` is used when...FIXME

=== [[isReplicaOnline]] `isReplicaOnline` Method

[source, scala]
----
isReplicaOnline(
  brokerId: Int,
  topicPartition: TopicPartition,
  includeShuttingDownBrokers: Boolean = false): Boolean
----

`isReplicaOnline`...FIXME

NOTE: `isReplicaOnline` is used when...FIXME

=== [[allLiveReplicas]] `allLiveReplicas` Method

[source, scala]
----
allLiveReplicas(): Set[PartitionAndReplica]
----

`allLiveReplicas`...FIXME

NOTE: `allLiveReplicas` is used when...FIXME

=== [[onlineAndOfflineReplicas]] `onlineAndOfflineReplicas` Method

[source, scala]
----
onlineAndOfflineReplicas: (Set[PartitionAndReplica], Set[PartitionAndReplica])
----

`onlineAndOfflineReplicas`...FIXME

NOTE: `onlineAndOfflineReplicas` is used exclusively when `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#startup, start up>>.

=== [[addLiveBrokersAndEpochs]] `addLiveBrokersAndEpochs` Method

[source, scala]
----
addLiveBrokersAndEpochs(
  brokerAndEpochs: Map[Broker, Long]): Unit
----

`addLiveBrokersAndEpochs`...FIXME

NOTE: `addLiveBrokersAndEpochs` is used when...FIXME

=== [[removeLiveBrokers]] `removeLiveBrokers` Method

[source, scala]
----
removeLiveBrokers(
  brokerIds: Set[Int]): Unit
----

`removeLiveBrokers`...FIXME

NOTE: `removeLiveBrokers` is used when...FIXME

=== [[partitionReplicaAssignment]] `partitionReplicaAssignment` Method

[source, scala]
----
partitionReplicaAssignment(
  topicPartition: TopicPartition): Seq[Int]
----

`partitionReplicaAssignment` finds the brokers with the replicas of the given partition (aka _partition replica assignment_).

Internally, `partitionReplicaAssignment` finds broker IDs of the replicas of the given partition (`TopicPartition`) in the <<partitionAssignments, partitionAssignments>> internal registry.

`partitionReplicaAssignment` returns an empty collection when no topic or partition are found.

NOTE: `partitionReplicaAssignment` is used when...FIXME

=== [[putReplicaStateIfNotExists]] `putReplicaStateIfNotExists` Method

[source, scala]
----
putReplicaStateIfNotExists(
  replica: PartitionAndReplica,
  state: ReplicaState): Unit
----

`putReplicaStateIfNotExists` simply adds the replica to the <<replicaStates, replicaStates>> internal registry unless available already.

NOTE: `putReplicaStateIfNotExists` is used exclusively when `ZkReplicaStateMachine` is requested to <<kafka-controller-ZkReplicaStateMachine.adoc#doHandleStateChanges, handle state changes of partition replicas>>.

=== [[checkValidReplicaStateChange]] `checkValidReplicaStateChange` Method

[source, scala]
----
checkValidReplicaStateChange(
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState
): (Seq[PartitionAndReplica], Seq[PartitionAndReplica])
----

For every replica (in the given replicas), `checkValidReplicaStateChange` <<isValidReplicaStateTransition, isValidReplicaStateTransition>> with the target state (`ReplicaState`).

NOTE: `checkValidReplicaStateChange` is used exclusively when `ZkReplicaStateMachine` is requested to <<kafka-controller-ZkReplicaStateMachine.adoc#doHandleStateChanges, handle replica state changes>>.

=== [[checkValidPartitionStateChange]] `checkValidPartitionStateChange` Method

[source, scala]
----
checkValidPartitionStateChange(
  partitions: Seq[TopicPartition],
  targetState: PartitionState
): (Seq[TopicPartition], Seq[TopicPartition])
----

For every replica (in the given replicas), `checkValidPartitionStateChange` <<isValidPartitionStateTransition, isValidPartitionStateTransition>> with the target state (`PartitionState`).

NOTE: `checkValidPartitionStateChange` is used exclusively when `ZkReplicaStateMachine` is requested to <<kafka-controller-ZkPartitionStateMachine.adoc#doHandleStateChanges, handle partition state changes>>.

=== [[putPartitionStateIfNotExists]] `putPartitionStateIfNotExists` Method

[source, scala]
----
putPartitionStateIfNotExists(
  partition: TopicPartition,
  state: PartitionState): Unit
----

`putPartitionStateIfNotExists`...FIXME

NOTE: `putPartitionStateIfNotExists` is used when...FIXME

=== [[isValidReplicaStateTransition]] `isValidReplicaStateTransition` Internal Method

[source, scala]
----
isValidReplicaStateTransition(
  replica: PartitionAndReplica,
  targetState: ReplicaState): Boolean
----

`isValidReplicaStateTransition`...FIXME

NOTE: `isValidReplicaStateTransition` is used when...FIXME

=== [[isValidPartitionStateTransition]] `isValidPartitionStateTransition` Internal Method

[source, scala]
----
isValidPartitionStateTransition(
  partition: TopicPartition,
  targetState: PartitionState): Boolean
----

`isValidPartitionStateTransition`...FIXME

NOTE: `isValidPartitionStateTransition` is used when...FIXME

=== [[putPartitionState]] `putPartitionState` Method

[source, scala]
----
putPartitionState(
  partition: TopicPartition,
  targetState: PartitionState): Unit
----

`putPartitionState`...FIXME

NOTE: `putPartitionState` is used when...FIXME

=== [[partitionsInStates]] Finding Partitions by Given States -- `partitionsInStates` Method

[source, scala]
----
partitionsInStates(
  states: Set[PartitionState]): Set[TopicPartition]
partitionsInStates(
  topic: String, states: Set[PartitionState]): Set[TopicPartition]
----

`partitionsInStates` uses the <<partitionStates, partitionStates>> internal registry to find all of the `TopicPartitions` (of the topic if defined) in the given `PartitionStates`.

NOTE: `partitionsInStates` is used when `PartitionStateMachine` is requested to link:kafka-controller-PartitionStateMachine.adoc#triggerOnlinePartitionStateChange[triggerOnlinePartitionStateChange].

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| allTopics
a| [[allTopics]]

| epoch
a| [[epoch]] Current controller epoch

| epochZkVersion
a| [[epochZkVersion]]

| liveBrokerEpochs
a| [[liveBrokerEpochs]][[liveOrShuttingDownBrokerIds]][[liveBrokerIdAndEpochs]] (Live and shutting down) Broker IDs and the current epoch

[source, scala]
----
liveBrokerEpochs: Map[Int, Long]
----

| liveBrokers
a| [[liveBrokers]]

| offlinePartitionCount
a| [[offlinePartitionCount]]

| partitionAssignments
a| [[partitionAssignments]] Broker IDs of partition replicas (`Map[String, Map[Int, Seq[Int]]]`)

| partitionLeadershipInfo
a| [[partitionLeadershipInfo]]

[source, scala]
----
partitionLeadershipInfo: mutable.Map[TopicPartition, LeaderIsrAndControllerEpoch]
----

| partitionsBeingReassigned
a| [[partitionsBeingReassigned]]

| partitionStates
a| [[partitionStates]]

| replicasOnOfflineDirs
a| [[replicasOnOfflineDirs]]

| replicaStates
a| [[replicaStates]][[putReplicaState]] `ReplicaStates` of `PartitionAndReplica` (`Map[PartitionAndReplica, ReplicaState]`)

| shuttingDownBrokerIds
a| [[shuttingDownBrokerIds]]

| stats
a| [[stats]][[rateAndTimeMetrics]][[ControllerStats]] `ControllerStats` with `UncleanLeaderElectionsPerSec` meter metric and `KafkaTimers` for every <<kafka-controller-ControllerState.adoc#, ControllerState>> (except <<kafka-controller-ControllerState.adoc#Idle, Idle>> state)

`stats` is used exclusively to create the <<kafka-controller-KafkaController.adoc#eventManager, ControllerEventManager>> (of <<kafka-controller-KafkaController.adoc#, KafkaController>>) that is then used to collect the times (metrics) of <<kafka-controller-ControllerEventThread.adoc#doWork, processing every ControllerEvent>> (except <<kafka-controller-ControllerEvent.adoc#ShutdownEventThread, ShutdownEventThread>>)

* Every `ControllerState` has the <<kafka-controller-ControllerState.adoc#rateAndTimeMetricName, RateAndTimeMs>> metric defined (except <<kafka-controller-ControllerState.adoc#Idle, Idle>> state)

The timer metric name pattern is *kafka.controller:type=ControllerStats,name=*.

| topicsIneligibleForDeletion
a| [[topicsIneligibleForDeletion]]

| topicsToBeDeleted
a| [[topicsToBeDeleted]][[isTopicQueuedUpForDeletion]]

| topicsWithDeletionStarted
a| [[topicsWithDeletionStarted]]

|===
