== [[BrokerReconfigurable]] BrokerReconfigurable Contract -- Reconfigurable Broker Services

`BrokerReconfigurable` is the <<contract, contract>> of <<implementations, reconfigurable broker services>> that allow for <<reconfigure, self-reconfiguration>>.

`BrokerReconfigurable` interface is used exclusively by <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>>.

[[contract]]
.BrokerReconfigurable Contract
[cols="1m,2",options="header",width="100%"]
|===
| Property
| Description

| reconfigurableConfigs
a| [[reconfigurableConfigs]]

[source, scala]
----
reconfigurableConfigs: Set[String]
----

Dynamic configurations

Used when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#addBrokerReconfigurable, addBrokerReconfigurable>> and <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>

| reconfigure
a| [[reconfigure]]

[source, scala]
----
reconfigure(oldConfig: KafkaConfig, newConfig: KafkaConfig): Unit
----

Used exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#updateCurrentConfig, updateCurrentConfig>>

| validateReconfiguration
a| [[validateReconfiguration]]

[source, scala]
----
validateReconfiguration(newConfig: KafkaConfig): Unit
----

Used exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>
|===

[[implementations]]
.BrokerReconfigurables
[cols="1,2",options="header",width="100%"]
|===
| BrokerReconfigurable
| Dynamic Configurations

| <<kafka-server-DynamicConnectionQuota.adoc#, DynamicConnectionQuota>>
a| [[DynamicConnectionQuota]]

<<kafka-properties.adoc#max.connections.per.ip, max.connections.per.ip>>

<<kafka-properties.adoc#max.connections.per.ip.overrides, max.connections.per.ip.overrides>>

| <<kafka-server-DynamicListenerConfig.adoc#, DynamicListenerConfig>>
a| [[DynamicListenerConfig]]

| <<kafka-server-DynamicThreadPool.adoc#, DynamicThreadPool>>
a| [[DynamicThreadPool]]

<<kafka-properties.adoc#num.io.threads, num.io.threads>>

<<kafka-properties.adoc#num.network.threads, num.network.threads>>

<<kafka-properties.adoc#num.replica.fetchers, num.replica.fetchers>>

<<kafka-properties.adoc#num.recovery.threads.per.data.dir, num.recovery.threads.per.data.dir>>

<<kafka-properties.adoc#background.threads, background.threads>>

| <<kafka-log-LogCleaner.adoc#, LogCleaner>>
a| [[LogCleaner]]

|===
