== [[ConsumerGroupCommand]] ConsumerGroupCommand

`ConsumerGroupCommand` is a <<main, standalone command-line application>> that is used for the following actions:

* Listing all consumer groups (<<list, --list>> option)
* Describing a consumer group (`--describe` option)
* Resetting consumer group offsets (`--reset-offsets` option)
* (only for the old Zookeeper-based consumer API) Deleting consumer group info (`--delete` option)

`ConsumerGroupCommand` can be <<main, executed>> as link:kafka-tools-kafka-consumer-groups.adoc[kafka-consumer-groups.sh] shell script.

[NOTE]
====
Quoting http://kafka.apache.org/documentation/#upgrade_9[Kafka 0.9.0.0]:

> The `kafka-consumer-offset-checker.sh` (`kafka.tools.ConsumerOffsetChecker`) has been deprecated. Going forward, please use `kafka-consumer-groups.sh` (`kafka.admin.ConsumerGroupCommand`) for this functionality.
====

=== [[main]] `main` Method

[source, scala]
----
main(args: Array[String]): Unit
----

`main` parses and checks the command-line arguments (using `ConsumerGroupCommandOptions`).

`main`...FIXME

NOTE: `main` creates the old `ZkConsumerGroupService` when `--zookeeper` option for the old client API is used.

`main` branches per option used.

* <<list, --list>> option
* Describing a consumer group (`--describe` option)
* Resetting consumer group offsets (`--reset-offsets` option)

CAUTION: FIXME

==== [[list]] list Option

`main` simply...FIXME
