`GroupCoordinator` is used (in <<kafka-server-KafkaApis.adoc#, KafkaApis>>) for <<handleGroupImmigration, handleGroupImmigration>>, <<handleGroupEmigration, handleGroupEmigration>>, <<handleDeletedPartitions, handleDeletedPartitions>>, <<handleCommitOffsets, handleCommitOffsets>>, <<handleFetchOffsets, handleFetchOffsets>>, <<handleDescribeGroup, handleDescribeGroup>>, <<handleListGroups, handleListGroups>>, <<handleJoinGroup, handleJoinGroup>>, <<handleSyncGroup, handleSyncGroup>>, <<handleDeleteGroups, handleDeleteGroups>>, <<handleLeaveGroup, handleLeaveGroup>>, <<handleHeartbeat, handleHeartbeat>>, <<handleTxnCommitOffsets, handleTxnCommitOffsets>> and <<scheduleHandleTxnCompletion, scheduleHandleTxnCompletion>> (that all simply request the <<groupManager, GroupMetadataManager>> to handle them).

[[isActive]]
`GroupCoordinator` manages the <<groupManager, GroupMetadataManager>>. `GroupCoordinator` uses `isActive` flag to control whether the <<groupManager, GroupMetadataManager>> was requested to <<kafka-coordinator-group-GroupMetadataManager.adoc#startup, start up>> (when `GroupCoordinator` <<startup, was>>) that is used in <<handleListGroups, handleListGroups>> and <<validateGroupStatus, validateGroupStatus>>.

=== [[partitionFor]] `partitionFor` Method

[source, scala]
----
partitionFor(group: String): Int
----

`partitionFor` simply requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#partitionFor, partitionFor>> the given `group` ID.

[NOTE]
====
`partitionFor` is used when:

* `KafkaApis` is requested to handle an <<kafka-server-KafkaApis.adoc#handleAddOffsetsToTxnRequest, AddOffsetsToTxn>> and <<kafka-server-KafkaApis.adoc#handleFindCoordinatorRequest, FindCoordinatorRequest>> requests

* `GroupCoordinator` is requested to <<prepareRebalance, prepareRebalance>> and <<onCompleteJoin, onCompleteJoin>>
====

=== [[handleCommitOffsets]] `handleCommitOffsets` Method

[source, scala]
----
handleCommitOffsets(
  groupId: String,
  memberId: String,
  generationId: Int,
  offsetMetadata: immutable.Map[TopicPartition, OffsetAndMetadata],
  responseCallback: immutable.Map[TopicPartition, Errors] => Unit): Unit
----

`handleCommitOffsets` firstly <<validateGroupStatus, validateGroupStatus>> (for the given `groupId` and `OFFSET_COMMIT` API key).

`handleCommitOffsets` requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#getGroup, get the metadata of the group>> (by the given `groupId`) and then <<doCommitOffsets, doCommitOffsets>>.

If the <<groupManager, GroupMetadataManager>> could not <<kafka-coordinator-group-GroupMetadataManager.adoc#getGroup, getGroup>>, `handleCommitOffsets`...FIXME

In case of an error while <<validateGroupStatus, validateGroupStatus>>, `handleCommitOffsets`...FIXME

NOTE: `handleCommitOffsets` is used exclusively when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleOffsetCommitRequest, handle an OffsetCommitRequest>>.

[source, scala]
----
handleGroupImmigration(offsetTopicPartitionId: Int): Unit
----

`handleGroupImmigration` simply requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#scheduleLoadGroupAndOffsets, scheduleLoadGroupAndOffsets>> (for the given offset and with the <<onGroupLoaded, onGroupLoaded>> callback)

NOTE: `handleGroupImmigration` is used exclusively when `KafkaApis` is requested to handle a <<kafka-server-KafkaApis.adoc#handleLeaderAndIsrRequest, LeaderAndIsrRequest>>.

=== [[handleGroupEmigration]] `handleGroupEmigration` Method

[source, scala]
----
handleGroupEmigration(offsetTopicPartitionId: Int): Unit
----

`handleGroupEmigration` simply requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#removeGroupsForPartition, removeGroupsForPartition>> (for the given offset and with the <<onGroupUnloaded, onGroupUnloaded>> callback).

NOTE: `handleGroupEmigration` is used when `KafkaApis` is requested to handle a <<kafka-server-KafkaApis.adoc#handleLeaderAndIsrRequest, LeaderAndIsrRequest>> and a <<kafka-server-KafkaApis.adoc#handleStopReplicaRequest, StopReplicaRequest>>.

=== [[handleDeletedPartitions]] Handling Deleted Partitions -- `handleDeletedPartitions` Method

[source, scala]
----
handleDeletedPartitions(
  topicPartitions: Seq[TopicPartition]): Unit
----

`handleDeletedPartitions` simply requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#cleanupGroupMetadata, cleanupGroupMetadata>> and...FIXME

NOTE: `handleDeletedPartitions` is used when...FIXME

=== [[handleJoinGroup]] `handleJoinGroup` Method

[source, scala]
----
handleJoinGroup(
  groupId: String,
  memberId: String,
  clientId: String,
  clientHost: String,
  rebalanceTimeoutMs: Int,
  sessionTimeoutMs: Int,
  protocolType: String,
  protocols: List[(String, Array[Byte])],
  responseCallback: JoinCallback): Unit
----

`handleJoinGroup` starts by <<validateGroupStatus, validating the status>> of the group and the coordinator itself. In case of an error, `handleJoinGroup` uses the given `JoinCallback` to report it back and returns.

`handleJoinGroup` validates the group configuration, namely the given `sessionTimeoutMs`. In case of an error, `handleJoinGroup` uses the given `JoinCallback` to report a `INVALID_SESSION_TIMEOUT` error back and returns.

`handleJoinGroup` requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#getGroup, getGroup>> by the given `groupId`.

If the group could not be found and the given `memberId` is defined (i.e. not empty), `handleJoinGroup` uses the given `JoinCallback` to report a `UNKNOWN_MEMBER_ID` error back and returns.

If the group could not be found and the given `memberId` is undefined (i.e. empty) or simply the group is available, `handleJoinGroup` requests the <<groupManager, GroupMetadataManager>> to <<kafka-coordinator-group-GroupMetadataManager.adoc#addGroup, addGroup>> followed by <<doJoinGroup, doJoinGroup>>.

NOTE: `handleJoinGroup` is used exclusively when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleJoinGroupRequest, handle a JoinGroupRequest>>.
