== [[AbstractCoordinator]] AbstractCoordinator Contract

`AbstractCoordinator` is the <<contract, base>> of <<extensions, Coordinators>> that <<FIXME, FIXME>>.

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

[[extensions]]
NOTE: <<kafka-consumer-internals-ConsumerCoordinator.adoc#, ConsumerCoordinator>> is the one and only known implementation of the <<contract, AbstractCoordinator Contract>> in Apache Kafka's Consumer API.

[[contract]]
.AbstractCoordinator Contract (Abstract Methods Only)
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| metadata
a| [[metadata]]

[source, java]
----
List<ProtocolMetadata> metadata()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, sendJoinGroupRequest>>

| onJoinComplete
a| [[onJoinComplete]]

[source, java]
----
void onJoinComplete(
  int generation,
  String memberId,
  String protocol,
  ByteBuffer memberAssignment)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the request to <<initiateJoinGroup, initiateJoinGroup>> succeeded)

| onJoinPrepare
a| [[onJoinPrepare]]

[source, java]
----
void onJoinPrepare(
  int generation,
  String memberId)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the <<needsJoinPrepare, needsJoinPrepare>> flag is on)

| performAssignment
a| [[performAssignment]]

[source, java]
----
Map<String, ByteBuffer> performAssignment(
  String leaderId,
  String protocol,
  Map<String, ByteBuffer> allMemberMetadata)
----

Used exclusively when `AbstractCoordinator` is requested to <<onJoinLeader, onJoinLeader>>

| protocolType
a| [[protocolType]]

[source, java]
----
String protocolType()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, sendJoinGroupRequest>>

|===

[[internal-registries]]
.AbstractCoordinator's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| heartbeatThread
| [[heartbeatThread]] `HeartbeatThread`

| joinFuture
| [[joinFuture]] <<kafka-consumer-internals-RequestFuture.adoc#, ++RequestFuture<ByteBuffer>++>> for...FIXME

Initialized in <<initiateJoinGroup, initiateJoinGroup>> (as the result of <<sendJoinGroupRequest, sendJoinGroupRequest>>)

Reset in <<resetJoinGroupFuture, resetJoinGroupFuture>>

Used in <<rejoinNeededOrPending, rejoinNeededOrPending>> and <<initiateJoinGroup, initiateJoinGroup>>

| needsJoinPrepare
| [[needsJoinPrepare]] Flag to control whether to execute <<onJoinPrepare, onJoinPrepare>> while performing <<joinGroupIfNeeded, joinGroupIfNeeded>>

| rejoinNeeded
| [[rejoinNeeded]] Flag to control whether to...FIXME

|===

=== [[creating-instance]] Creating AbstractCoordinator Instance

`AbstractCoordinator` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] <<kafka-consumer-internals-ConsumerNetworkClient.adoc#, ConsumerNetworkClient>>
* [[groupId]] Group ID
* [[rebalanceTimeoutMs]] `rebalanceTimeoutMs`
* [[sessionTimeoutMs]] `sessionTimeoutMs`
* [[heartbeatIntervalMs]] `heartbeatIntervalMs` (or simply [[heartbeat]] a `Heartbeat` instance)
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[metricGrpPrefix]] Metric group prefix
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[leaveGroupOnClose]] `leaveGroupOnClose` flag

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

=== [[joinGroupIfNeeded]] `joinGroupIfNeeded` Method

[source, java]
----
boolean joinGroupIfNeeded(final Timer timer)
----

`joinGroupIfNeeded`...FIXME

NOTE: `joinGroupIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[initiateJoinGroup]] `initiateJoinGroup` Internal Method

[source, java]
----
synchronized RequestFuture<ByteBuffer> initiateJoinGroup()
----

`initiateJoinGroup`...FIXME

NOTE: `initiateJoinGroup` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (when a rejoin is <<rejoinNeeded, needed>> or <<joinFuture, still in progress and incomplete>>).

=== [[ensureActiveGroup]] `ensureActiveGroup` Method

[source, java]
----
void ensureActiveGroup()
boolean ensureActiveGroup(final Timer timer)
----

`ensureActiveGroup`...FIXME

NOTE: `ensureActiveGroup` is used when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>>.

=== [[lookupCoordinator]] `lookupCoordinator` Method

[source, java]
----
RequestFuture<Void> lookupCoordinator()
----

`lookupCoordinator`...FIXME

[NOTE]
====
`lookupCoordinator` is used when:

* `AbstractCoordinator` is requested to <<ensureCoordinatorReady, ensureCoordinatorReady>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsAsync, commitOffsetsAsync>>

* `HeartbeatThread` is requested to run
====

=== [[ensureCoordinatorReady]] `ensureCoordinatorReady` Method

[source, java]
----
boolean ensureCoordinatorReady(final Timer timer)
----

`ensureCoordinatorReady`...FIXME

[NOTE]
====
`ensureCoordinatorReady` is used when:

* `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>> and <<joinGroupIfNeeded, joinGroupIfNeeded>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#fetchCommittedOffsets, fetchCommittedOffsets>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#close, close>>, and <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsSync, commitOffsetsSync>>
====

=== [[sendJoinGroupRequest]] `sendJoinGroupRequest` Method

[source, java]
----
RequestFuture<ByteBuffer> sendJoinGroupRequest()
----

`sendJoinGroupRequest`...FIXME

NOTE: `sendJoinGroupRequest` is used when...FIXME

=== [[sendSyncGroupRequest]] `sendSyncGroupRequest` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> sendSyncGroupRequest(
  SyncGroupRequest.Builder requestBuilder)
----

`sendSyncGroupRequest`...FIXME

NOTE: `sendSyncGroupRequest` is used when...FIXME

=== [[sendFindCoordinatorRequest]] `sendFindCoordinatorRequest` Internal Method

[source, java]
----
RequestFuture<Void> sendFindCoordinatorRequest(Node node)
----

`sendFindCoordinatorRequest`...FIXME

NOTE: `sendFindCoordinatorRequest` is used when...FIXME

=== [[maybeLeaveGroup]] `maybeLeaveGroup` Method

[source, java]
----
void maybeLeaveGroup()
----

`maybeLeaveGroup`...FIXME

NOTE: `maybeLeaveGroup` is used when...FIXME

=== [[sendHeartbeatRequest]] `sendHeartbeatRequest` Method

[source, java]
----
RequestFuture<Void> sendHeartbeatRequest()
----

`sendHeartbeatRequest`...FIXME

NOTE: `sendHeartbeatRequest` is used when...FIXME

=== [[onJoinLeader]] `onJoinLeader` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> onJoinLeader(JoinGroupResponse joinResponse)
----

`onJoinLeader`...FIXME

NOTE: `onJoinLeader` is used when...FIXME

=== [[resetJoinGroupFuture]] `resetJoinGroupFuture` Internal Method

[source, java]
----
void resetJoinGroupFuture()
----

`resetJoinGroupFuture` simply resets the <<joinFuture, joinFuture>> internal registry (i.e. sets it to `null`).

NOTE: `resetJoinGroupFuture` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>.

=== [[rejoinNeededOrPending]] `rejoinNeededOrPending` Internal Method

[source, java]
----
boolean rejoinNeededOrPending()
----

`rejoinNeededOrPending` is positive (`true`) when <<rejoinNeeded, rejoinNeeded>> and <<joinFuture, joinFuture>> is initialized (i.e. not `null`).

[NOTE]
====
`rejoinNeededOrPending` is used when:

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#rejoinNeededOrPending, rejoinNeededOrPending>> and <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>

* `KafkaConsumer` is requested to <<kafka-consumer-KafkaConsumer.adoc#pollForFetches, pollForFetches>>

* `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>
====

=== [[pollHeartbeat]] `pollHeartbeat` Method

[source, java]
----
void pollHeartbeat(long now)
----

`pollHeartbeat`...FIXME

NOTE: `pollHeartbeat` is used when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for Coordinator events>>.

=== [[startHeartbeatThreadIfNeeded]] `startHeartbeatThreadIfNeeded` Internal Method

[source, java]
----
void startHeartbeatThreadIfNeeded()
----

`startHeartbeatThreadIfNeeded`...FIXME

NOTE: `startHeartbeatThreadIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.
