== [[RecordAccumulator]] RecordAccumulator

`RecordAccumulator` is <<creating-instance, created>> exclusively when `KafkaProducer` is <<kafka-producer-KafkaProducer.adoc#accumulator, created>>.

`KafkaProducer` uses the following configuration properties to create a `RecordAccumulator`:

* <<kafka-producer-ProducerConfig.adoc#batch.size, batch.size>> for the <<batchSize, batchSize>>

* <<kafka-producer-ProducerConfig.adoc#linger.ms, linger.ms>> for the <<lingerMs, lingerMs>>

* <<kafka-producer-ProducerConfig.adoc#retry.backoff.ms, retry.backoff.ms>> for the <<retryBackoffMs, retryBackoffMs>>

=== [[creating-instance]] Creating RecordAccumulator Instance

`RecordAccumulator` takes the following to be created:

* [[logContext]] `LogContext`
* [[batchSize]] `batchSize`
* [[compression]] `CompressionType`
* [[lingerMs]] `lingerMs`
* [[retryBackoffMs]] `retryBackoffMs`
* [[deliveryTimeoutMs]] `deliveryTimeoutMs`
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[metricGrpName]] Metric group name (e.g. <<kafka-producer-KafkaProducer.adoc#PRODUCER_METRIC_GROUP_NAME, producer-metrics>>)
* [[time]] `Time`
* [[apiVersions]] `ApiVersions`
* [[transactionManager]] <<kafka-producer-internals-TransactionManager.adoc#, TransactionManager>>
* [[bufferPool]] `BufferPool`

`RecordAccumulator` initializes the <<internal-properties, internal properties>>.

When created, `RecordAccumulator` <<registerMetrics, registerMetrics>> (with the <<metrics, Metrics>> and the <<metricGrpName, metric group name>>).

==== [[registerMetrics]] `registerMetrics` Method

[source, java]
----
void registerMetrics()
----

`registerMetrics`...FIXME

NOTE: `registerMetrics` is used exclusively when `RecordAccumulator` is <<creating-instance, created>>.

=== [[close]] `close` Method

[source, java]
----
void close()
----

`close`...FIXME

NOTE: `close` is used when...FIXME

=== [[append]] `append` Method

[source, java]
----
RecordAppendResult append(
  TopicPartition tp,
  long timestamp,
  byte[] key,
  byte[] value,
  Header[] headers,
  Callback callback,
  long maxTimeToBlock) throws InterruptedException
----

`append`...FIXME

`append` <<tryAppend, tryAppend>>.

`append`...FIXME

NOTE: `append` is used exclusively when `KafkaProducer` is requested to <<kafka-producer-KafkaProducer.adoc#doSend, send a ProducerRecord to a Kafka Cluster asynchronously>>.

==== [[tryAppend]] `tryAppend` Internal Method

[source, java]
----
RecordAppendResult tryAppend(
  long timestamp,
  byte[] key,
  byte[] value,
  Header[] headers,
  Callback callback,
  Deque<ProducerBatch> deque)
----

`tryAppend`...FIXME

NOTE: `tryAppend` is used exclusively when `RecordAccumulator` is requested to <<append, append>>.

=== [[abortIncompleteBatches]] Aborting Incomplete Batches -- `abortIncompleteBatches` Method

[source, java]
----
void abortIncompleteBatches()
----

`abortIncompleteBatches`...FIXME

NOTE: `abortIncompleteBatches` is used exclusively when `Sender` is requested to <<kafka-producer-internals-Sender.adoc#run, run>> (and forced to close while shutting down).

=== [[reenqueue]] `reenqueue` Method

[source, java]
----
void reenqueue(
  ProducerBatch batch,
  long now)
----

`reenqueue`...FIXME

NOTE: `reenqueue` is used exclusively when `Sender` is requested to <<kafka-producer-internals-Sender.adoc#reenqueueBatch, reenqueueBatch>>.

=== [[splitAndReenqueue]] `splitAndReenqueue` Method

[source, java]
----
int splitAndReenqueue(ProducerBatch bigBatch)
----

`splitAndReenqueue`...FIXME

NOTE: `splitAndReenqueue` is used exclusively when `Sender` is requested to <<kafka-producer-internals-Sender.adoc#completeBatch, completeBatch>>.

=== [[getOrCreateDeque]] Looking Up Or Creating New Deque For TopicPartition -- `getOrCreateDeque` Internal Method

[source, java]
----
Deque<ProducerBatch> getOrCreateDeque(TopicPartition tp)
----

`getOrCreateDeque`...FIXME

NOTE: `getOrCreateDeque` is used when `RecordAccumulator` is requested to <<append, append>>, <<reenqueue, reenqueue>>, and <<splitAndReenqueue, splitAndReenqueue>>.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| appendsInProgress
a| [[appendsInProgress]] https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/atomic/AtomicInteger.html[java.util.concurrent.atomic.AtomicInteger] to keep track of the number of <<append, appending threads>>

* Starts at `0` when `RecordAccumulator` is <<creating-instance, created>>

* Increments and decrements when `RecordAccumulator` is requested to <<append, append>> (just after it is requested and right before it finishes)

Used exclusively when `RecordAccumulator` is requested to <<abortIncompleteBatches, abort incomplete batches>>

|===
