== [[ReplicaStateMachine]] ReplicaStateMachine

`ReplicaStateMachine` is...FIXME

=== [[handleStateChanges]] `handleStateChanges` Method

[source, scala]
----
handleStateChanges(
  replicas: Set[PartitionAndReplica],
  targetState: ReplicaState,
  callbacks: Callbacks): Unit
----

`handleStateChanges`...FIXME

NOTE: `handleStateChanges` is used when...FIXME

=== [[shutdown]] `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

`shutdown`...FIXME

NOTE: `shutdown` is used when...FIXME

=== [[startup]] `startup` Method

[source, scala]
----
startup(): Unit
----

`startup`...FIXME

NOTE: `startup` is used when...FIXME

=== [[getTopicPartitionStatesFromZk]] `getTopicPartitionStatesFromZk` Internal Method

[source, scala]
----
getTopicPartitionStatesFromZk(partitions: Seq[TopicPartition])
: (Map[TopicPartition, LeaderAndIsr], Seq[TopicPartition], Map[TopicPartition, Exception])
----

`getTopicPartitionStatesFromZk`...FIXME

NOTE: `getTopicPartitionStatesFromZk` is used when...FIXME

=== [[initializeReplicaState]] `initializeReplicaState` Internal Method

[source, scala]
----
initializeReplicaState(): Unit
----

`initializeReplicaState`...FIXME

NOTE: `initializeReplicaState` is used when...FIXME

=== [[doHandleStateChanges]] `doHandleStateChanges` Internal Method

[source, scala]
----
doHandleStateChanges(
  replicaId: Int,
  partitions: Seq[TopicPartition],
  targetState: ReplicaState,
  callbacks: Callbacks): Unit
----

`doHandleStateChanges`...FIXME

NOTE: `doHandleStateChanges` is used when...FIXME
