== [[ReplicaFetcherManager]] ReplicaFetcherManager

`ReplicaFetcherManager` is a <<kafka-server-AbstractFetcherManager.adoc#, AbstractFetcherManager>> of <<kafka-server-ReplicaFetcherThread.adoc#, ReplicaFetcherThreads>> that...FIXME (describe properties)

`ReplicaFetcherManager` is <<creating-instance, created>> exclusively when `ReplicaManager` is requested to link:kafka-server-ReplicaManager.adoc#createReplicaFetcherManager[create one] (which is when `ReplicaManager` is link:kafka-server-ReplicaManager.adoc#replicaFetcherManager[created]).

=== [[creating-instance]] Creating ReplicaFetcherManager Instance

`ReplicaFetcherManager` takes the following to be created:

* [[brokerConfig]] link:kafka-server-KafkaConfig.adoc[KafkaConfig]
* [[replicaManager]] link:kafka-server-ReplicaManager.adoc[ReplicaManager]
* [[metrics]] link:kafka-Metrics.adoc[Metrics]
* [[time]] `Time`
* [[threadNamePrefix]] Thread name prefix (undefined by default)
* [[quotaManager]] link:kafka-server-ReplicationQuotaManager.adoc[ReplicationQuotaManager]

=== [[createFetcherThread]] Creating ReplicaFetcherThread -- `createFetcherThread` Method

[source, scala]
----
createFetcherThread(
  fetcherId: Int,
  sourceBroker: BrokerEndPoint): ReplicaFetcherThread
----

NOTE: `createFetcherThread` is part of the link:kafka-server-AbstractFetcherManager.adoc#createFetcherThread[AbstractFetcherManager] contract to...FIXME.

`createFetcherThread` creates a link:kafka-server-ReplicaFetcherThread.adoc[ReplicaFetcherThread] with the thread name (that uses the <<threadNamePrefix, threadNamePrefix>> if defined, the given `fetcherId` and the id of the `BrokerEndPoint`) as follows:

```
[prefix]ReplicaFetcherThread-[fetcherId]-[sourceBrokerId]
```

=== [[shutdown]] `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

`shutdown` prints out the following INFO message to the logs:

```
shutting down
```

`shutdown` link:kafka-server-AbstractFetcherManager.adoc#closeAllFetchers[closeAllFetchers].

In the end, `shutdown` prints out the following INFO message to the logs:

```
shutdown completed
```

NOTE: `shutdown` is used when...FIXME
