== [[bootstrap.servers]] bootstrap.servers Property

`bootstrap.servers` is a comma-separated list of host and port pairs that are the addresses of the Kafka brokers in a "bootstrap" link:kafka-brokers.adoc[Kafka cluster] that a Kafka client connects to initially to bootstrap itself.

A host and port pair uses `:` as the separator.

```
localhost:9092
localhost:9092,another.host:9092
```

`bootstrap.servers` provides the initial hosts that act as the starting point for a Kafka client to discover the full set of alive servers in the cluster.

NOTE: Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list does not have to contain the full set of servers (you may want more than one, though, in case a server is down).

NOTE: Clients (producers or consumers) make use of all servers irrespective of which servers are specified in `bootstrap.servers` for bootstrapping.

TIP: Use `org.apache.kafka.clients.CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG` public value to refer to the property.
