== Controller Broker

*Controller Broker* (<<kafka-controller-KafkaController.adoc#, KafkaController>>) is a Kafka service that runs on every broker in a Kafka cluster, but only one can be <<isActive, active>> (_elected_) at any point in time.

The process of promoting a broker to be the active controller is called <<kafka-feature-controller-election.adoc#, Kafka Controller Election>>.

Quoting https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Controller+Internals[Kafka Controller Internals]:

> In a Kafka cluster, one of the brokers serves as the controller, which is responsible for managing the states of partitions and replicas and for performing administrative tasks like reassigning partitions.

Kafka Controller registers <<kafka-controller-KafkaController.adoc#znode-change-handlers, handlers>> to be notified about changes in Zookeeper and propagate them across brokers in a Kafka cluster.

=== [[lifecycle]] Lifecycle

When <<kafka-controller-KafkaController.adoc#startup, started>>, `KafkaController` emits <<kafka-controller-ControllerEvent.adoc#Startup, Startup>> controller event. That starts <<kafka-controller-KafkaController.adoc#elect, controller election>> (on the <<kafka-controller-ControllerEventThread.adoc#, controller-event-thread>>).

During controller election, one `KafkaController` becomes <<kafka-controller-KafkaController.adoc#isActive, active>> (_elected_) and <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>>. The <<kafka-controller-KafkaController.adoc#controllerContext, ControllerContext>> is built on what is available in Zookeeper.

While in <<kafka-controller-KafkaController.adoc#initializeControllerContext, initializeControllerContext>>, `KafkaController` <<kafka-controller-KafkaController.adoc#updateLeaderAndIsrCache, updateLeaderAndIsrCache>> (and <<kafka-zk-KafkaZkClient.adoc#getTopicPartitionStates, reads partition state>> from `/brokers/topics/[topic]/partitions/[partition]/state` paths in Zookeeper that is then stored as <<kafka-controller-ControllerContext.adoc#partitionLeadershipInfo, partitionLeadershipInfo>> of the <<kafka-controller-KafkaController.adoc#controllerContext, ControllerContext>>).
