== [[Log]] Partition Log

`Log` is a *partition log* that...FIXME

`Log` is <<creating-instance, created>> when...FIXME

=== [[creating-instance]] Creating Log Instance

`Log` takes the following when created:

* [[dir]] Directory
* [[config]] `LogConfig`
* [[logStartOffset]] `logStartOffset`
* [[recoveryPoint]] `recoveryPoint`
* [[scheduler]] <<kafka-Scheduler.adoc#, Scheduler>>
* [[brokerTopicStats]] <<kafka-server-BrokerTopicStats.adoc#, BrokerTopicStats>>
* [[time]] `Time`
* [[maxProducerIdExpirationMs]] `maxProducerIdExpirationMs`
* [[producerIdExpirationCheckIntervalMs]] `producerIdExpirationCheckIntervalMs`
* [[topicPartition]] `TopicPartition`
* [[producerStateManager]] `ProducerStateManager`
* [[logDirFailureChannel]] `LogDirFailureChannel`

`Log` initializes the <<internal-registries, internal registries and counters>>.

While being created, `Log`...FIXME

=== [[apply]] Creating Log Instance -- `apply` Factory Method

[source, scala]
----
apply(
  dir: File,
  config: LogConfig,
  logStartOffset: Long,
  recoveryPoint: Long,
  scheduler: Scheduler,
  brokerTopicStats: BrokerTopicStats,
  time: Time = Time.SYSTEM,
  maxProducerIdExpirationMs: Int,
  producerIdExpirationCheckIntervalMs: Int,
  logDirFailureChannel: LogDirFailureChannel): Log
----

`apply`...FIXME

NOTE: `apply` is used when `LogManager` is requested to <<kafka-LogManager.adoc#loadLog, loadLog>> and <<kafka-LogManager.adoc#getOrCreateLog, getOrCreateLog>>.

=== [[roll]] `roll` Method

[source, scala]
----
roll(expectedNextOffset: Long = 0): LogSegment
----

`roll`...FIXME

NOTE: `roll` is used when...FIXME

=== [[asyncDeleteSegment]] `asyncDeleteSegment` Method

[source, scala]
----
asyncDeleteSegment(segment: LogSegment): Unit
----

`asyncDeleteSegment`...FIXME

NOTE: `asyncDeleteSegment` is used when...FIXME

=== [[flush]] `flush` Method

[source, scala]
----
flush(offset: Long): Unit
----

`flush`...FIXME

NOTE: `flush` is used when...FIXME

=== [[deleteSeg]] `deleteSeg` Internal Method

[source, scala]
----
deleteSeg(): Unit
----

`deleteSeg`...FIXME

NOTE: `deleteSeg` is used when...FIXME
