== [[ZkPartitionStateStore]] ZkPartitionStateStore

`ZkPartitionStateStore` is a link:kafka-cluster-PartitionStateStore.adoc[state store] for a <<topicPartition, TopicPartition>> (as link:kafka-cluster-Partition.adoc#stateStore[Partition]).

`ZkPartitionStateStore` uses ZooKeeper as the state storage (using a <<zkClient, KafkaZkClient>>).

`ZkPartitionStateStore` is <<creating-instance, created>> for a link:kafka-cluster-Partition.adoc#apply[Partition].

=== [[creating-instance]] Creating ZkPartitionStateStore Instance

`ZkPartitionStateStore` takes the following to be created:

* [[topicPartition]] `TopicPartition`
* [[zkClient]] link:kafka-zk-KafkaZkClient.adoc[KafkaZkClient]
* [[replicaManager]] link:kafka-server-ReplicaManager.adoc[ReplicaManager]

=== [[fetchTopicConfig]] Reading Topic Configuration (/config/topics ZNode) -- `fetchTopicConfig` Method

[source, scala]
----
fetchTopicConfig(): Properties
----

NOTE: `fetchTopicConfig` is part of the link:kafka-cluster-PartitionStateStore.adoc#fetchTopicConfig[PartitionStateStore] contract to...FIXME.

`fetchTopicConfig` reads the configuration properties from `/config/topics/[topic]` znode in ZooKeeper (deserialized from JSON).

Internally, `fetchTopicConfig` creates a new link:kafka-zk-AdminZkClient.adoc[AdminZkClient] with the <<zkClient, KafkaZkClient>>.

`fetchTopicConfig` requests the `AdminZkClient` to link:kafka-zk-AdminZkClient.adoc#fetchEntityConfig[read an entity configuration from ZooKeeper] for `topics` entity for the `topic` of the <<topicPartition, TopicPartition>>.
