== [[Partition]] Partition

A Kafka topic is spread across a Kafka cluster as a virtual group of one or more *partitions*.

A single partition of a topic (*topic partition*) can be replicated across a Kafka cluster to one or more Kafka brokers.

A topic partition has one partition leader node and zero or more replicas.

Kafka producers publish messages to topic leaders as do Kafka consumers consume them from.

*In-Sync Replicas* are brokers that...FIXME

*Offline Replicas* are...FIXME

`Partition` is...FIXME

[[internal-registries]]
.Partition's Internal Properties (e.g. Registries and Counters)
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[leaderReplicaIdOpt]] `leaderReplicaIdOpt`
| Optional leader replica ID
|===

=== [[maybeExpandIsr]] `maybeExpandIsr` Method

[source, scala]
----
FIXME
----

`maybeExpandIsr`...FIXME

NOTE: `maybeExpandIsr` is used exclusively when `Partition` does <<updateReplicaLogReadResult, updateReplicaLogReadResult>>.

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

[source, scala]
----
maybeShrinkIsr(replicaMaxLagTimeMs: Long): Unit
----

`maybeShrinkIsr`...FIXME

NOTE: `maybeShrinkIsr` is used exclusively when `ReplicaManager` link:kafka-ReplicaManager.adoc#maybeShrinkIsr[maybeShrinkIsr].

=== [[updateReplicaLogReadResult]] `updateReplicaLogReadResult` Method

[source, scala]
----
updateReplicaLogReadResult(replica: Replica, logReadResult: LogReadResult): Boolean
----

`updateReplicaLogReadResult`...FIXME

NOTE: `updateReplicaLogReadResult` is used exclusively when `ReplicaManager` link:kafka-ReplicaManager.adoc#updateFollowerLogReadResults[updateFollowerLogReadResults].

=== [[updateIsr]] `updateIsr` Internal Method

[source, scala]
----
updateIsr(newIsr: Set[Replica]): Unit
----

`updateIsr`...FIXME

NOTE: `updateIsr` is used when `Partition` is requested to <<maybeExpandIsr, expand>> or <<maybeShrinkIsr, shrink>> the ISR.

=== [[makeLeader]] `makeLeader` Method

[source, scala]
----
makeLeader(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeLeader`...FIXME

NOTE: `makeLeader` is used...FIXME

=== [[makeFollower]] `makeFollower` Method

[source, scala]
----
makeFollower(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeFollower`...FIXME

NOTE: `makeFollower` is used...FIXME

=== [[leaderReplicaIfLocal]] `leaderReplicaIfLocal` Method

[source, scala]
----
leaderReplicaIfLocal: Option[Replica]
----

`leaderReplicaIfLocal` gives...FIXME

NOTE: `leaderReplicaIfLocal` is used...FIXME

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

CAUTION: FIXME

=== [[creating-instance]] Creating Partition Instance

`Partition` takes the following when created:

* [[topic]] Topic name
* [[partitionId]] Partition ID
* [[time]] `Time`
* [[replicaManager]] link:kafka-ReplicaManager.adoc[ReplicaManager]
* [[isOffline]] `isOffline` flag (disabled by default)

`Partition` initializes the <<internal-registries, internal registries and counters>>.
