== Broker -- Kafka Server

NOTE: Given https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/KafkaServer.scala#L89[the scaladoc of `KafkaServer`] a *Kafka server*, a *Kafka broker* and a *Kafka node* all refer to the same concept and are hence considered synonyms.

A *Kafka broker* is a Kafka server that hosts link:kafka-topics.adoc[topics].

You can <<starting-broker, start a single Kafka broker>> using `kafka-server-start.sh` script.

=== [[starting-broker]] Starting Kafka Broker

Start Zookeeper.

```
./bin/zookeeper-server-start.sh config/zookeeper.properties
```

Only when Zookeeper is up and running you can start a Kafka server (that will connect to Zookeeper).

```
./bin/kafka-server-start.sh config/server.properties
```

TIP: Read <<kafka-server-start-script, kafka-server-start.sh script>>.

=== [[kafka-server-start-script]] `kafka-server-start.sh` script

`kafka-server-start.sh` starts a link:kafka-Kafka.adoc[Kafka broker].

```
$ ./bin/kafka-server-start.sh
USAGE: ./bin/kafka-server-start.sh [-daemon] server.properties [--override property=value]*
```

NOTE: Before you run `kafka-server-start.sh` make sure that Zookeeper is up and running. Use `zookeeper-server-start` shell script.

`kafka-server-start.sh` uses `config/log4j.properties` for logging configuration that you can override using `KAFKA_LOG4J_OPTS` environment variable.

```
KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:config/log4j.properties"
```

`kafka-server-start.sh` accepts `KAFKA_HEAP_OPTS` and `EXTRA_ARGS` environment variables.

Command-line options:

1. `-name` -- defaults to `kafkaServer` when in daemon mode.
1. `-loggc` -- enabled when in daemon mode.
1. `-daemon` -- enables daemon mode.
1. `--override property=value` -- `value` that should override the value set for `property` in `server.properties` file.

```
$ ./bin/kafka-server-start.sh config/server.properties --override broker.id=100
...
INFO [KafkaServer id=100] started (kafka.server.KafkaServer)
```
