== [[KafkaRequestHandler]] KafkaRequestHandler

`KafkaRequestHandler` is a thread of execution (i.e. Java's https://docs.oracle.com/javase/9/docs/api/java/lang/Runnable.html[Runnable]) that handles Kafka requests (i.e. `ShutdownRequests` directly while the others routes to <<apis, KafkaApis>>).

`KafkaRequestHandler` is <<creating-instance, created>>...FIXME

[[logIdent]]
`logIdent` is *[Kafka Request Handler [id] on Broker [brokerId]]*.

=== [[run]] Starting Thread -- `run` Method

[source, scala]
----
run(): Unit
----

CAUTION: FIXME

NOTE: `run` is used when `KafkaRequestHandlerPool` is link:kafka-KafkaRequestHandlerPool.adoc#creating-instance[created].

=== [[creating-instance]] Creating KafkaRequestHandler Instance

`KafkaRequestHandler` takes the following when created:

* [[id]] ID
* [[brokerId]] Broker ID
* [[aggregateIdleMeter]] Aggregate Idle `Meter`
* [[totalHandlerThreads]] Total number of handler threads
* [[requestChannel]] `RequestChannel`
* [[apis]] link:kafka-KafkaApis.adoc[KafkaApis]
* [[time]] `Time`

`KafkaRequestHandler` initializes the <<internal-registries, internal registries and counters>>.
