== [[ProducerBatch]] ProducerBatch

`ProducerBatch` is...FIXME

`ProducerBatch` is <<creating-instance, created>> when:

* `RecordAccumulator` is requested to <<kafka-producer-internals-RecordAccumulator.adoc#append, append>>

* `ProducerBatch` is requested to <<split, split>>

[[logging]]
[TIP]
====
Enable `ALL` logging level for `org.apache.kafka.clients.producer.internals.ProducerBatch` logger to see what happens inside.

Add the following line to `config/tools-log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.producer.internals.ProducerBatch=ALL
```

Refer to <<kafka-logging.adoc#, Logging>>.
====

=== [[creating-instance]] Creating ProducerBatch Instance

`ProducerBatch` takes the following to be created:

* [[tp]] `TopicPartition`
* [[recordsBuilder]] <<kafka-common-record-MemoryRecordsBuilder.adoc#, MemoryRecordsBuilder>>
* [[createdMs]] `createdMs`
* [[isSplitBatch]] `isSplitBatch` flag (default: `false`)

`ProducerBatch` initializes the <<internal-properties, internal properties>>.

=== [[split]] `split` Method

[source, java]
----
Deque<ProducerBatch> split(int splitBatchSize)
----

`split`...FIXME

NOTE: `split` is used exclusively when `RecordAccumulator` is requested to <<kafka-producer-internals-RecordAccumulator.adoc#splitAndReenqueue, splitAndReenqueue>>.

==== [[createBatchOffAccumulatorForRecord]] `createBatchOffAccumulatorForRecord` Internal Method

[source, java]
----
ProducerBatch createBatchOffAccumulatorForRecord(
  Record record,
  int batchSize)
----

`createBatchOffAccumulatorForRecord`...FIXME

NOTE: `createBatchOffAccumulatorForRecord` is used exclusively when `ProducerBatch` is requested to <<split, split>>.
