== [[ClusterResourceListener]] ClusterResourceListener (and ClusterResourceListeners Collection)

`ClusterResourceListener` is the <<contract, contract>> for objects that want to be notified about <<onUpdate, changes in the Cluster metadata>>.

[[contract]]
[[onUpdate]]
[source, java]
----
package org.apache.kafka.common;

public interface ClusterResourceListener {
  void onUpdate(ClusterResource clusterResource);
}
----

[[registering-listeners]]
You can register a `ClusterResourceListener` for the following Kafka services:

* `KafkaServer` to get notified once at link:notifyClusterListeners#notifyClusterListeners[startup]
* `KafkaProducer` to get notified when it is link:kafka-KafkaProducer.adoc#creating-instance[created] and...FIXME
* `KafkaConsumer` to get notified when it is link:kafka-KafkaProducer.adoc#creating-instance[created] and...FIXME

=== [[ClusterResourceListeners]] ClusterResourceListeners Collection

`ClusterResourceListeners` collection holds zero or more `ClusterResourceListener` objects and uses them as one.

`ClusterResourceListeners` is used mainly by link:kafka-Metadata.adoc#clusterResourceListeners[Metadata] that manages and notifies <<registering-listeners, registered listeners>> when a cluster metadata change occurs.
