== [[ControllerContext]] ControllerContext

`ControllerContext` is the context of a <<kafka-controller-KafkaController.adoc#controllerContext, KafkaController>> (and is <<creating-instance, created>> exclusively when `KafkaController` is <<kafka-controller-KafkaController.adoc#controllerContext, created>>).

[[registries]]
.ControllerContext's Registries
[cols="1m,3",options="header",width="100%"]
|===
| Name
| Description

| allTopics
a| [[allTopics]]

| controllerChannelManager
a| [[controllerChannelManager]] <<kafka-controller-ControllerChannelManager.adoc#, ControllerChannelManager>>

| epoch
a| [[epoch]]

| epochZkVersion
a| [[epochZkVersion]]

| liveBrokers
a| [[liveBrokers]]

| liveBrokerIds
a| [[liveBrokerIds]]

| liveBrokersUnderlying
a| [[liveBrokersUnderlying]]

| liveBrokerIdsUnderlying
a| [[liveBrokerIdsUnderlying]]

| liveOrShuttingDownBrokerIds
a| [[liveOrShuttingDownBrokerIds]]

| liveOrShuttingDownBrokers
a| [[liveOrShuttingDownBrokers]]

| partitionsBeingReassigned
a| [[partitionsBeingReassigned]]

| partitionLeadershipInfo
a| [[partitionLeadershipInfo]]

[source, scala]
----
partitionLeadershipInfo: mutable.Map[TopicPartition, LeaderIsrAndControllerEpoch]
----

| partitionReplicaAssignmentUnderlying
a| [[partitionReplicaAssignmentUnderlying]]

[source, scala]
----
// topic -> (partition -> replica broker IDs)
partitionReplicaAssignmentUnderlying: mutable.Map[String, mutable.Map[Int, Seq[Int]]]
----

`partitionReplicaAssignmentUnderlying` is updated exclusively when `ControllerContext` is requested to <<updatePartitionReplicaAssignment, updatePartitionReplicaAssignment>>

| replicasOnOfflineDirs
a| [[replicasOnOfflineDirs]]

| shuttingDownBrokerIds
a| [[shuttingDownBrokerIds]]

| stats
a| [[stats]][[rateAndTimeMetrics]][[ControllerStats]] `ControllerStats` with `UncleanLeaderElectionsPerSec` meter metric and `KafkaTimers` for every <<kafka-controller-ControllerState.adoc#, ControllerState>> (except <<kafka-controller-ControllerState.adoc#Idle, Idle>> state)

`stats` is used exclusively to create the <<kafka-controller-KafkaController.adoc#eventManager, ControllerEventManager>> (of <<kafka-controller-KafkaController.adoc#, KafkaController>>) that is then used to collect the times (metrics) of <<kafka-controller-ControllerEventThread.adoc#doWork, processing every ControllerEvent>> (except <<kafka-controller-ControllerEvent.adoc#ShutdownEventThread, ShutdownEventThread>>)

* Every `ControllerState` has the <<kafka-controller-ControllerState.adoc#rateAndTimeMetricName, RateAndTimeMs>> metric defined (except <<kafka-controller-ControllerState.adoc#Idle, Idle>> state)

The timer metric name pattern is *kafka.controller:type=ControllerStats,name=*.

|===

[[creating-instance]]
`ControllerContext` takes no input arguments when created.

=== [[allPartitions]] `allPartitions` Method

[source, scala]
----
allPartitions: Set[TopicPartition]
----

`allPartitions` converts the <<partitionReplicaAssignmentUnderlying, partitionReplicaAssignmentUnderlying>> into `TopicPartitions`, i.e. `allPartitions` takes the partitions for the topics and simply creates new `TopicPartitions`.

[NOTE]
====
`allPartitions` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderAndIsrCache, updateLeaderAndIsrCache>>, <<kafka-controller-KafkaController.adoc#checkAndTriggerAutoLeaderRebalance, checkAndTriggerAutoLeaderRebalance>>, and <<kafka-controller-KafkaController.adoc#updateMetrics, updateMetrics>>

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#initializePartitionState, initializePartitionState>>

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#initializeReplicaState, initializeReplicaState>>
====

=== [[updatePartitionReplicaAssignment]] `updatePartitionReplicaAssignment` Method

[source, scala]
----
updatePartitionReplicaAssignment(topicPartition: TopicPartition, newReplicas: Seq[Int]): Unit
----

`updatePartitionReplicaAssignment` simply updates the <<partitionReplicaAssignmentUnderlying, partitionReplicaAssignmentUnderlying>> registry with `newReplicas` for the topic and the partition (of a given `TopicPartition`).

[NOTE]
====
`updatePartitionReplicaAssignment` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#initializeControllerContext, initializeControllerContext>>, <<kafka-controller-KafkaController.adoc#moveReassignedPartitionLeaderIfRequired, moveReassignedPartitionLeaderIfRequired>>, <<kafka-controller-KafkaController.adoc#updateAssignedReplicasForPartition, updateAssignedReplicasForPartition>>, and at <<kafka-controller-ControllerEvent.adoc#TopicChange, TopicChange>> and <<kafka-controller-ControllerEvent.adoc#PartitionModifications, PartitionModifications>> controller events

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#doHandleStateChanges, doHandleStateChanges>>
====

=== [[partitionsOnBroker]] `partitionsOnBroker` Method

[source, scala]
----
partitionsOnBroker(brokerId: Int): Set[TopicPartition]
----

`partitionsOnBroker`...FIXME

NOTE: `partitionsOnBroker` is used when...FIXME

=== [[replicasOnBrokers]] `replicasOnBrokers` Method

[source, scala]
----
replicasOnBrokers(brokerIds: Set[Int]): Set[PartitionAndReplica]
----

`replicasOnBrokers`...FIXME

NOTE: `replicasOnBrokers` is used when...FIXME

=== [[replicasForTopic]] `replicasForTopic` Method

[source, scala]
----
replicasForTopic(topic: String): Set[PartitionAndReplica]
----

`replicasForTopic`...FIXME

NOTE: `replicasForTopic` is used when...FIXME

=== [[partitionsForTopic]] `partitionsForTopic` Method

[source, scala]
----
partitionsForTopic(topic: String): collection.Set[TopicPartition]
----

`partitionsForTopic`...FIXME

NOTE: `partitionsForTopic` is used when...FIXME

=== [[removeTopic]] `removeTopic` Method

[source, scala]
----
removeTopic(topic: String): Unit
----

`removeTopic`...FIXME

NOTE: `removeTopic` is used when...FIXME

=== [[isReplicaOnline]] `isReplicaOnline` Method

[source, scala]
----
isReplicaOnline(
  brokerId: Int,
  topicPartition: TopicPartition,
  includeShuttingDownBrokers: Boolean = false): Boolean
----

`isReplicaOnline`...FIXME

NOTE: `isReplicaOnline` is used when...FIXME
