== [[LogConfig]] LogConfig

`LogConfig` is a Apache Kafka https://kafka.apache.org/24/javadoc/org/apache/kafka/common/config/AbstractConfig.html[AbstractConfig] for the <<properties, configuration properties>> of a...FIXME

[[properties]]
.LogConfig's Configuration Properties
[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| CleanupPolicyProp
a| [[CleanupPolicyProp]][[cleanup.policy]] <<kafka-common-TopicConfig.adoc#CLEANUP_POLICY_CONFIG, cleanup.policy>>

Default: `delete`

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.cleanup.policy, log.cleanup.policy>>

Used when:

* `GroupCoordinator` is requested for the <<kafka-coordinator-group-GroupCoordinator.adoc#offsetsTopicConfigs, offsetsTopicConfigs>>

* `TransactionStateManager` is requested for the <<kafka-TransactionStateManager.adoc#transactionTopicConfigs, transactionTopicConfigs>>

* `LogConfig` is requested for the <<compact, compact>> and <<delete, delete>> flags

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#copyKafkaConfigToLog, copyKafkaConfigToLog>>

| CompressionTypeProp
a| [[CompressionTypeProp]]

| DeleteRetentionMsProp
a| [[DeleteRetentionMsProp]]

| FileDeleteDelayMsProp
a| [[file.delete.delay.ms]][[FileDeleteDelayMsProp]][[fileDeleteDelayMs]] The time (in millis) to wait before deleting a file from the filesystem. Must be at least `0`

Property: `file.delete.delay.ms`

Default: `60000`

| flushMs
a| [[flushMs]][[FlushMsProp]] <<kafka-common-TopicConfig.adoc#FLUSH_MS_CONFIG, flush.ms>>

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.flush.interval.ms, log.flush.interval.ms>>

| FlushMessagesProp
a| [[FlushMessagesProp]][[flushInterval]] <<kafka-common-TopicConfig.adoc#FLUSH_MESSAGES_INTERVAL_CONFIG, flush.messages>>

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.flush.interval.messages, log.flush.interval.messages>>

| indexInterval
a| [[indexInterval]][[IndexIntervalBytesProp]] <<kafka-common-TopicConfig.adoc#INDEX_INTERVAL_BYTES_CONFIG, index.interval.bytes>>

| MaxMessageBytesProp
a| [[MaxMessageBytesProp]]

| MaxCompactionLagMsProp
a| [[MaxCompactionLagMsProp]]

| MessageDownConversionEnableProp
a| [[MessageDownConversionEnableProp]]

| MessageFormatVersionProp
a| [[MessageFormatVersionProp]]

| MessageTimestampDifferenceMaxMsProp
a| [[MessageTimestampDifferenceMaxMsProp]]

| MessageTimestampTypeProp
a| [[MessageTimestampTypeProp]]

| MinCleanableDirtyRatioProp
a| [[MinCleanableDirtyRatioProp]]

| MinCompactionLagMsProp
a| [[MinCompactionLagMsProp]]

| MinInSyncReplicasProp
a| [[MinInSyncReplicasProp]]

| PreAllocateEnableProp
a| [[PreAllocateEnableProp]]

| RetentionBytesProp
a| [[RetentionBytesProp]]

| RetentionMsProp
a| [[RetentionMsProp]][[retentionMs]] <<kafka-common-TopicConfig.adoc#RETENTION_MS_CONFIG, retention.ms>>

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.retention.ms, log.retention.ms>>

Used exclusively when `Log` is requested to <<kafka-log-Log.adoc#deleteRetentionMsBreachedSegments, deleteRetentionMsBreachedSegments>>

| RetentionBytesProp
a| [[RetentionBytesProp]][[retentionSize]] <<kafka-common-TopicConfig.adoc#RETENTION_BYTES_CONFIG, retention.bytes>>

Default: `-1L`

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.retention.bytes, log.retention.bytes>>

Used exclusively when `Log` is requested to <<kafka-log-Log.adoc#deleteRetentionSizeBreachedSegments, deleteRetentionSizeBreachedSegments>>

| SegmentBytesProp
a| [[SegmentBytesProp]][[segmentSize]] <<kafka-common-TopicConfig.adoc#SEGMENT_BYTES_CONFIG, segment.bytes>>

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.segment.bytes, log.segment.bytes>>

Used when:

* `GroupCoordinator` is requested for the <<kafka-coordinator-group-GroupCoordinator.adoc#offsetsTopicConfigs, offsetsTopicConfigs>>

* `TransactionStateManager` is requested for the <<kafka-TransactionStateManager.adoc#transactionTopicConfigs, transactionTopicConfigs>>

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#copyKafkaConfigToLog, copyKafkaConfigToLog>>

The current value is available as `LogConfig.segmentSize` and used when:

* `RollParams` utility is requested to <<kafka-log-RollParams.adoc#apply, create a RollParams>>

* `Log` is requested for the <<kafka-log-Log.adoc#initFileSize, initFileSize>> and to <<kafka-log-Log.adoc#append, append records>>

* `Cleaner` is requested to <<kafka-log-Cleaner.adoc#doClean, clean a log>>

| SegmentIndexBytesProp
a| [[segment.index.bytes]][[maxIndexSize]][[SegmentIndexBytesProp]] <<kafka-common-TopicConfig.adoc#SEGMENT_INDEX_BYTES_CONFIG, segment.index.bytes>>

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-properties.adoc#log.index.size.max.bytes, log.index.size.max.bytes>>

| SegmentJitterMsProp
a| [[SegmentJitterMsProp]][[segmentJitterMs]] <<kafka-common-TopicConfig.adoc#SEGMENT_JITTER_MS_CONFIG, segment.jitter.ms>>

| SegmentMsProp
a| [[SegmentMsProp]][[segmentMs]] <<kafka-common-TopicConfig.adoc#SEGMENT_MS_CONFIG, segment.ms>>

Default: `604800000` (7 days)

Cluster-wide property (`TopicConfigSynonyms`): <<kafka-server-KafkaConfig.adoc#LogRollTimeMillisProp, log.roll.ms>>

Used when:

* `Log` is requested to <<kafka-log-Log.adoc#maybeRoll, maybeRoll>>

* `LogConfig` is requested for the <<randomSegmentJitter, randomSegmentJitter>> and <<maxSegmentMs, maxSegmentMs>>

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#copyKafkaConfigToLog, copyKafkaConfigToLog>>

| UncleanLeaderElectionEnableProp
a| [[UncleanLeaderElectionEnableProp]]

|===

=== [[randomSegmentJitter]] `randomSegmentJitter` Method

[source, scala]
----
randomSegmentJitter: Long
----

`randomSegmentJitter` is one of the following values:

* `0` if <<segmentJitterMs, segment.jitter.ms>> is `0`

* Random int value modulo the minimum of <<segmentJitterMs, segment.jitter.ms>> and <<segmentMs, segment.ms>>

NOTE: `randomSegmentJitter` is used when `LogSegment` utility is used to <<kafka-log-LogSegment.adoc#open, open a log segment>> (for the <<kafka-log-LogSegment.adoc#rollJitterMs, rollJitterMs>> property).

=== [[maxSegmentMs]] `maxSegmentMs` Method

[source, scala]
----
maxSegmentMs: Long
----

`maxSegmentMs`...FIXME

NOTE: `maxSegmentMs` is used when `RollParams` utility is used to <<kafka-log-RollParams.adoc#apply, create a RollParams instance>>.

=== [[compact]] Checking Out Whether Compact Cleanup Policy Is Enabled -- `compact` Flag

[source, scala]
----
compact: Boolean
----

`compact`...FIXME

NOTE: `compact` is used when...FIXME

=== [[delete]] Checking Out Whether Delete Cleanup Policy Is Enabled -- `delete` Flag

[source, scala]
----
delete: Boolean
----

`delete` flag is enabled (`true`) when <<kafka-log-cleanup-policies.adoc#delete, delete>> cleanup policy is part of the <<kafka-log-cleanup-policies.adoc#cleanup.policy, cleanup.policy>> configuration property. Otherwise, `delete` flag is disabled (`false`).

[NOTE]
====
`delete` is used when:

* `Partition` is requested to <<kafka-cluster-Partition.adoc#deleteRecordsOnLeader, deleteRecordsOnLeader>>

* `Log` is requested to <<kafka-log-Log.adoc#deleteOldSegments, deleteOldSegments>>

* `LogCleanerManager` utility is requested for <<kafka-log-LogCleanerManager.adoc#isCompactAndDelete, isCompactAndDelete>>
====
