== [[ReplicaStateMachine]] ReplicaStateMachine

`ReplicaStateMachine` is <<creating-instance, created>> exclusively for a <<kafka-controller-KafkaController.adoc#replicaStateMachine, KafkaController>> that uses it for the following:

* FIXME

`ReplicaStateMachine` is <<startup, started>> when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>> (when `KafkaController` is requested for <<elect, controller election>> and a broker is successfully elected as the controller).

`ReplicaStateMachine` is <<shutdown, shut down>> when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerResignation, resign as the active controller>>.

[[logIdent]]
`ReplicaStateMachine` uses *[ReplicaStateMachine controllerId=[brokerID]]* as the logging prefix (aka `logIdent`).

[[logging]]
[TIP]
====
Enable `INFO` or `ERROR` logging levels for `kafka.controller.ReplicaStateMachine` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.kafka.controller.ReplicaStateMachine=INFO
```

Refer to link:kafka-logging.adoc[Logging].

---

Please note that Kafka comes with a preconfigured `kafka.controller` logger in `config/log4j.properties`:

```
log4j.appender.controllerAppender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.controllerAppender.DatePattern='.'yyyy-MM-dd-HH
log4j.appender.controllerAppender.File=${kafka.logs.dir}/controller.log
log4j.appender.controllerAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.controllerAppender.layout.ConversionPattern=[%d] %p %m (%c)%n

log4j.logger.kafka.controller=TRACE, controllerAppender
log4j.additivity.kafka.controller=false
```

That means that the logs of `ReplicaStateMachine` go to `logs/controller.log` file at `TRACE` logging level and are not added to the main logs (per `log4j.additivity` being off).
====

=== [[handleStateChanges]] `handleStateChanges` Method

[source, scala]
----
handleStateChanges(
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState,
  callbacks: Callbacks = new Callbacks()): Unit
----

`handleStateChanges`...FIXME

[NOTE]
====
`handleStateChanges` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onBrokerLogDirFailure, onBrokerLogDirFailure>>, <<kafka-controller-KafkaController.adoc#onBrokerStartup, onBrokerStartup>>, <<kafka-controller-KafkaController.adoc#onReplicasBecomeOffline, onReplicasBecomeOffline>>, <<kafka-controller-KafkaController.adoc#onNewPartitionCreation, onNewPartitionCreation>>, <<kafka-controller-KafkaController.adoc#onPartitionReassignment, onPartitionReassignment>>, <<kafka-controller-KafkaController.adoc#stopOldReplicasOfReassignedPartition, stopOldReplicasOfReassignedPartition>>, <<kafka-controller-KafkaController.adoc#startNewReplicasForReassignedPartition, startNewReplicasForReassignedPartition>>, and process a <<kafka-controller-KafkaController.adoc#ControlledShutdown, ControlledShutdown>> controller event

* `ReplicaStateMachine` is requested to <<startup, start up>>

* `TopicDeletionManager` is requested to <<kafka-controller-TopicDeletionManager.adoc#failReplicaDeletion, failReplicaDeletion>>, <<kafka-controller-TopicDeletionManager.adoc#completeReplicaDeletion, completeReplicaDeletion>>, <<kafka-controller-TopicDeletionManager.adoc#markTopicForDeletionRetry, markTopicForDeletionRetry>>, <<kafka-controller-TopicDeletionManager.adoc#completeDeleteTopic, completeDeleteTopic>>, and <<kafka-controller-TopicDeletionManager.adoc#startReplicaDeletion, startReplicaDeletion>>
====

=== [[shutdown]] `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

`shutdown`...FIXME

NOTE: `shutdown` is used when...FIXME

=== [[startup]] `startup` Method

[source, scala]
----
startup(): Unit
----

`startup` prints out the following INFO message to the logs:

```
Initializing replica state
```

`startup` <<initializeReplicaState, initializeReplicaState>>.

`startup` prints out the following INFO message to the logs:

```
Triggering online replica state changes
```

`startup` <<handleStateChanges, handleStateChanges>> with the <<kafka-controller-ControllerContext.adoc#allLiveReplicas, live replicas>> (from the <<controllerContext, ControllerContext>>) and `OnlineReplica` target state.

In the end, `startup` prints out the following INFO message to the logs:

```
Started replica state machine with initial state -> [replicaState]
```

NOTE: `startup` is used exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>> (when a `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#elect, elect>> and a broker is successfully elected as the controller).

=== [[getTopicPartitionStatesFromZk]] `getTopicPartitionStatesFromZk` Internal Method

[source, scala]
----
getTopicPartitionStatesFromZk(partitions: Seq[TopicPartition])
: (Map[TopicPartition, LeaderAndIsr], Seq[TopicPartition], Map[TopicPartition, Exception])
----

`getTopicPartitionStatesFromZk`...FIXME

NOTE: `getTopicPartitionStatesFromZk` is used when...FIXME

=== [[initializeReplicaState]] `initializeReplicaState` Internal Method

[source, scala]
----
initializeReplicaState(): Unit
----

`initializeReplicaState`...FIXME

NOTE: `initializeReplicaState` is used exclusively when `ReplicaStateMachine` is requested to <<startup, start up>>.

=== [[doHandleStateChanges]] `doHandleStateChanges` Internal Method

[source, scala]
----
doHandleStateChanges(
  replicaId: Int,
  partitions: Seq[TopicPartition],
  targetState: ReplicaState,
  callbacks: Callbacks): Unit
----

`doHandleStateChanges`...FIXME

NOTE: `doHandleStateChanges` is used exclusively when `ReplicaStateMachine` is requested to <<handleStateChanges, handleStateChanges>>.

=== [[creating-instance]] Creating ReplicaStateMachine Instance

`ReplicaStateMachine` takes the following to be created:

* [[config]] <<kafka-KafkaConfig.adoc#, KafkaConfig>>
* [[stateChangeLogger]] `StateChangeLogger`
* [[controllerContext]] <<kafka-controller-ControllerContext.adoc#, ControllerContext>>
* [[topicDeletionManager]] <<kafka-controller-TopicDeletionManager.adoc#, TopicDeletionManager>>
* [[zkClient]] <<kafka-zk-KafkaZkClient.adoc#, KafkaZkClient>>
* [[replicaState]] `PartitionAndReplica` with `ReplicaState` (`mutable.Map[PartitionAndReplica, ReplicaState]`)
* [[controllerBrokerRequestBatch]] <<kafka-controller-ControllerBrokerRequestBatch.adoc#, ControllerBrokerRequestBatch>>
