== Broker -- Kafka Server

NOTE: Given https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/KafkaServer.scala#L89[the scaladoc of `KafkaServer`], it _appears_ that a *Kafka server*, a *Kafka broker* and a *Kafka node* refer to the same concept.

=== Starting Broker

Start Zookeeper.

```
./bin/zookeeper-server-start.sh config/zookeeper.properties
```

Only when Zookeeper is running you can start a Kafka server (that will connect to Zookeeper).

```
./bin/kafka-server-start.sh config/server.properties
```

=== kafka-server-start.sh script

`kafka-server-start.sh` starts a Kafka server.

```
$ ./bin/kafka-server-start.sh
USAGE: ./bin/kafka-server-start.sh [-daemon] server.properties [--override property=value]*
```

It uses `config/log4j.properties` for logging configuration but you can override it using `KAFKA_LOG4J_OPTS` environment variable.

```
KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:config/log4j.properties"
```

`kafka-server-start.sh` accepts `KAFKA_HEAP_OPTS` and `EXTRA_ARGS` environment variables.

Command-line options:

1. `-name` -- defaults to `kafkaServer` when in daemon mode.
2. `-loggc` -- enabled when in daemon mode.
3. `-daemon` -- enables daemon mode.
4. `--override property=value` -- `value` that should override the value set for `property` in `server.properties` file.

=== [[KafkaServerStartable]] KafkaServerStartable

=== [[KafkaConfig]] KafkaConfig

=== [[KafkaServer]] KafkaServer
