== [[KafkaAdminClient]] KafkaAdminClient

`KafkaAdminClient` is the default and only known <<kafka-clients-admin-AdminClient.adoc#, AdminClient>> that is used in <<kafka-tools.adoc#, Kafka administration utilities>>.

[[logging]]
[TIP]
====
Enable `ALL` logging level for `org.apache.kafka.clients.admin.KafkaAdminClient` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.admin.KafkaAdminClient=ALL
```

Refer to <<kafka-logging.adoc#, Logging>>.
====

=== [[creating-instance]] Creating KafkaAdminClient Instance

`KafkaAdminClient` takes the following to be created:

* [[config]] `AdminClientConfig`
* [[clientId]] Client ID
* [[time]] `Time`
* [[metadataManager]] <<kafka-clients-admin-internals-AdminMetadataManager.adoc#, AdminMetadataManager>>
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[client]] <<kafka-clients-KafkaClient.adoc#, KafkaClient>>
* [[timeoutProcessorFactory]] `TimeoutProcessorFactory`
* [[logContext]] `LogContext`

`KafkaAdminClient` initializes the <<internal-properties, internal properties>>.

=== [[createInternal]] Creating KafkaAdminClient Instance -- `createInternal` Factory Method

[source, java]
----
KafkaAdminClient createInternal(
  AdminClientConfig config,
  TimeoutProcessorFactory timeoutProcessorFactory)
----

`createInternal`...FIXME

NOTE: `createInternal` is used exclusively when `AdminClient` object is requested to <<kafka-clients-admin-AdminClient.adoc#create, create an AdminClient>> (for link:kafka-tools.adoc[Kafka administration utilities]).

=== [[electPreferredLeaders]] Triggerring Preferred Replica Leader Election -- `electPreferredLeaders` Method

[source, java]
----
ElectPreferredLeadersResult electPreferredLeaders(
  Collection<TopicPartition> partitions,
  ElectPreferredLeadersOptions options)
----

NOTE: `electPreferredLeaders` is part of the <<kafka-clients-admin-AdminClient.adoc#electPreferredLeaders, AdminClient Contract>> to trigger <<kafka-feature-preferred-replica-leader-election.adoc#, preferred replica leader election>>.

`electPreferredLeaders` creates a *electPreferredLeaders* call that simply uses <<kafka-common-requests-ElectPreferredLeadersRequest.adoc#Builder, ElectPreferredLeadersRequest.Builder>> to <<kafka-common-requests-ElectPreferredLeadersRequest.adoc#toRequestData, serialize partitions into a ElectPreferredLeadersRequest>> and, when a response comes in, requests the `ElectPreferredLeadersRequest` to <<kafka-common-requests-ElectPreferredLeadersRequest.adoc#fromResponseData, deserialize it>>.

In the end, `electPreferredLeaders` requests the <<runnable, AdminClientRunnable>> to <<kafka-clients-admin-KafkaAdminClient-AdminClientRunnable.adoc#call, enqueue>> the `electPreferredLeaders` call.

=== [[describeTopics]] `describeTopics` Method

[source, java]
----
DescribeTopicsResult describeTopics(
  Collection<String> topicNames,
  DescribeTopicsOptions options)
----

`describeTopics`...FIXME

NOTE: `describeTopics` is used when...FIXME

=== [[alterReplicaLogDirs]] `alterReplicaLogDirs` Method

[source, java]
----
AlterReplicaLogDirsResult alterReplicaLogDirs(
  Map<TopicPartitionReplica, String> replicaAssignment,
  AlterReplicaLogDirsOptions options)
----

`alterReplicaLogDirs`...FIXME

NOTE: `alterReplicaLogDirs` is used when...FIXME

=== [[alterConfigs]] `alterConfigs` Method

[source, java]
----
AlterConfigsResult alterConfigs(
  Map<ConfigResource, Config> configs,
  AlterConfigsOptions options)
// Private API
Map<ConfigResource, KafkaFutureImpl<Void>> alterConfigs(
  Map<ConfigResource, Config> configs,
  AlterConfigsOptions options,
  Collection<ConfigResource> resources,
  NodeProvider nodeProvider)
----

NOTE: `alterConfigs` is part of the <<kafka-clients-admin-AdminClient.adoc#alterConfigs, AdminClient Contract>> to...FIXME.

`alterConfigs`...FIXME

=== [[describeCluster]] `describeCluster` Method

[source, java]
----
DescribeClusterResult describeCluster(
  DescribeClusterOptions options)
----

NOTE: `describeCluster` is part of the <<kafka-clients-admin-AdminClient.adoc#describeCluster, AdminClient Contract>> to...FIXME.

`describeCluster`...FIXME

=== [[deleteRecords]] `deleteRecords` Method

[source, java]
----
DeleteRecordsResult deleteRecords(
  Map<TopicPartition, RecordsToDelete> recordsToDelete,
  DeleteRecordsOptions options)
----

NOTE: `deleteRecords` is part of the <<kafka-clients-admin-AdminClient.adoc#deleteRecords, AdminClient Contract>> to...FIXME.

`deleteRecords`...FIXME

=== [[listConsumerGroups]] `listConsumerGroups` Method

[source, java]
----
ListConsumerGroupsResult listConsumerGroups(
  ListConsumerGroupsOptions options)
----

NOTE: `listConsumerGroups` is part of the <<kafka-clients-admin-AdminClient.adoc#listConsumerGroups, AdminClient Contract>> to...FIXME.

`listConsumerGroups`...FIXME

=== [[listTopics]] `listTopics` Method

[source, java]
----
ListTopicsResult listTopics(
  ListTopicsOptions options)
----

NOTE: `listTopics` is part of the <<kafka-clients-admin-AdminClient.adoc#listTopics, AdminClient Contract>> to...FIXME.

`listTopics`...FIXME

=== [[describeConsumerGroups]] `describeConsumerGroups` Method

[source, java]
----
DescribeConsumerGroupsResult describeConsumerGroups(
  Collection<String> groupIds,
  DescribeConsumerGroupsOptions options)
----

NOTE: `describeConsumerGroups` is part of the <<kafka-clients-admin-AdminClient.adoc#describeConsumerGroups, AdminClient Contract>> to...FIXME.

`describeConsumerGroups`...FIXME

=== [[listConsumerGroupOffsets]] `listConsumerGroupOffsets` Method

[source, java]
----
ListConsumerGroupOffsetsResult listConsumerGroupOffsets(
  String groupId,
  ListConsumerGroupOffsetsOptions options)
----

NOTE: `listConsumerGroupOffsets` is part of the <<kafka-clients-admin-AdminClient.adoc#listConsumerGroupOffsets, AdminClient Contract>> to...FIXME.

`listConsumerGroupOffsets`...FIXME

=== [[deleteConsumerGroups]] `deleteConsumerGroups` Method

[source, java]
----
DeleteConsumerGroupsResult deleteConsumerGroups(
  Collection<String> groupIds,
  DeleteConsumerGroupsOptions options)
----

NOTE: `deleteConsumerGroups` is part of the <<kafka-clients-admin-AdminClient.adoc#deleteConsumerGroups, AdminClient Contract>> to...FIXME.

`deleteConsumerGroups`...FIXME

=== [[createTopics]] `createTopics` Method

[source, java]
----
CreateTopicsResult createTopics(
  Collection<NewTopic> newTopics,
  CreateTopicsOptions options)
----

NOTE: `createTopics` is part of the <<kafka-clients-admin-AdminClient.adoc#createTopics, AdminClient Contract>> to...FIXME.

`createTopics`...FIXME

=== [[deleteTopics]] `deleteTopics` Method

[source, java]
----
DeleteTopicsResult deleteTopics(
  Collection<String> topicNames,
  DeleteTopicsOptions options)
----

NOTE: `deleteTopics` is part of the <<kafka-clients-admin-AdminClient.adoc#deleteTopics, AdminClient Contract>> to...FIXME.

`deleteTopics`...FIXME

=== [[createPartitions]] `createPartitions` Method

[source, java]
----
CreatePartitionsResult createPartitions(
  Map<String, NewPartitions> newPartitions,
  CreatePartitionsOptions options)
----

NOTE: `createPartitions` is part of the <<kafka-clients-admin-AdminClient.adoc#createPartitions, AdminClient Contract>> to...FIXME.

`createPartitions`...FIXME

=== [[describeConfigs]] Describing Configuration Of Specified Resources (Topics and Brokers) -- `describeConfigs` Method

[source, java]
----
DescribeConfigsResult describeConfigs(
  Collection<ConfigResource> configResources,
  DescribeConfigsOptions options)
----

NOTE: `describeConfigs` is part of the <<kafka-clients-admin-AdminClient.adoc#describeConfigs, AdminClient Contract>> to describe the configuration of the specified resources.

`describeConfigs`...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| runnable
a| [[runnable]] <<kafka-clients-admin-KafkaAdminClient-AdminClientRunnable.adoc#, AdminClientRunnable>>

Used to create the daemon <<thread, KafkaThread>>

| thread
a| [[thread]] Java's Thread

Used when...FIXME

|===
