== [[DynamicConfigManager]] DynamicConfigManager

`DynamicConfigManager` is...FIXME

`DynamicConfigManager` uses the <<ConfigChangedNotificationHandler, ConfigChangedNotificationHandler>> to <<ConfigChangedNotificationHandler-processNotification, process config change notifications>>.

`DynamicConfigManager` is <<creating-instance, created>> exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>.

[[internal-registries]]
.DynamicConfigManager's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| adminZkClient
a| [[adminZkClient]] <<kafka-zk-AdminZkClient.adoc#, AdminZkClient>> (for the <<zkClient, KafkaZkClient>>)

Used when...FIXME
|===

=== [[startup]] `startup` Method

[source, scala]
----
startup
----

`startup`...FIXME

NOTE: `startup` is used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>.

=== [[creating-instance]] Creating DynamicConfigManager Instance

`DynamicConfigManager` takes the following when created:

* [[zkClient]] <<kafka-zk-KafkaZkClient.adoc#, KafkaZkClient>>
* [[configHandlers]] <<kafka-server-ConfigHandler.adoc#, ConfigHandlers>> by name
* [[changeExpirationMs]] `changeExpirationMs` (default: `15 mins`)
* [[time]] `Time`

`DynamicConfigManager` initializes the <<internal-registries, internal registries and counters>>.

=== [[ConfigChangedNotificationHandler]] ConfigChangedNotificationHandler Object

`ConfigChangedNotificationHandler` is a <<kafka-common-NotificationHandler.adoc#, NotificationHandler>> that <<ConfigChangedNotificationHandler-processNotification, processNotification>>.

==== [[processNotification]][[ConfigChangedNotificationHandler-processNotification]] Processing Config Change Notifications -- `processNotification` Method

[source, scala]
----
processNotification(jsonBytes: Array[Byte]): Unit
----

NOTE: `processNotification` is part of the <<kafka-common-NotificationHandler.adoc#processNotification, NotificationHandler Contract>> to handle a change notification.

`processNotification`...FIXME

==== [[processEntityConfigChangeVersion1]][[ConfigChangedNotificationHandler-processEntityConfigChangeVersion1]] `processEntityConfigChangeVersion1` Internal Method

[source, scala]
----
processEntityConfigChangeVersion1(jsonBytes: Array[Byte], js: JsonObject): Unit
----

`processEntityConfigChangeVersion1`...FIXME

NOTE: `processEntityConfigChangeVersion1` is used when...FIXME

==== [[processEntityConfigChangeVersion2]][[ConfigChangedNotificationHandler-processEntityConfigChangeVersion2]] `processEntityConfigChangeVersion2` Internal Method

[source, scala]
----
processEntityConfigChangeVersion2(jsonBytes: Array[Byte], js: JsonObject): Unit
----

`processEntityConfigChangeVersion2`...FIXME

NOTE: `processEntityConfigChangeVersion2` is used when...FIXME
