== [[KafkaServer]] KafkaServer

CAUTION: FIXME

`KafkaServer` acts as a Kafka broker.

`KafkaServer` <<creating-instance, registers itself in the JMX system>> under *kafka.server*.

[[internal-registries]]
.KafkaServer's Internal Registries and Counters
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[reporters]] `reporters`
| Collection of `MetricsReporter`

Used when...FIXME
|===

=== [[startup]] `startup` Method

[source, scala]
----
startup(): Unit
----

`startup` starts a single Kafka server.

When `startup` starts, you should see the following INFO message in the logs:

```
INFO starting (kafka.server.KafkaServer)
```

`startup` link:kafka-KafkaScheduler.adoc#startup[starts `KafkaScheduler`].

You should see the following INFO message in the logs:

```
INFO Cluster ID = [clusterId] (kafka.server.KafkaServer)
```

`startup` <<notifyClusterListeners, notifies cluster change listeners>>.

`startup` link:kafka-ReplicaManager.adoc#creating-instance[creates a `ReplicaManager`] and link:kafka-ReplicaManager.adoc#startup[starts it] right afterwards.

`startup` link:kafka-KafkaController.adoc#creating-instance[creates a `KafkaController`] and link:kafka-KafkaController.adoc#startup[starts it].

`startup` link:kafka-AdminManager.adoc#creating-instance[creates a `AdminManager`].

`startup` link:kafka-KafkaApis.adoc#creating-instance[creates a `KafkaApis`].

In the end, you should see the following INFO message in the logs:

```
INFO [Kafka Server 0], started (kafka.server.KafkaServer)
```

NOTE: The INFO message above uses so-called *log ident* with the value of `broker.id` property and is always in the format ``[Kafka Server [brokerId]], `` after a Kafka server has fully started.

CAUTION: FIXME

NOTE: `startup` is used exclusively when link:kafka-KafkaServerStartable.adoc#startup[`KafkaServerStartable` is started].

=== [[notifyClusterListeners]] `notifyClusterListeners` Method

CAUTION: FIXME

=== [[creating-instance]] Creating KafkaServer Instance

`KafkaServer` takes the following when created:

1. link:kafka-KafkaConfig.adoc[KafkaConfig]
2. `Time` (defaults to `Time.SYSTEM`)
3. `threadNamePrefix` (defaults to no prefix)
4. `kafkaMetricsReporters` -- a collection of link:kafka-KafkaMetricsReporter.adoc[KafkaMetricsReporter] (defaults to no reporters)

CAUTION: FIXME

NOTE: `KafkaServer` is created when link:kafka-KafkaServerStartable.adoc#creating-instance[`KafkaServerStartable` is created].
