== Overview of Kafka

http://kafka.apache.org/[Apache Kafka] is an open source project for a distributed publish-subscribe messaging system rethought as a distributed commit log.

Kafka stores link:kafka-messages.adoc[messages] in link:kafka-topics.adoc[topics] that are link:kafka-topics.adoc#partitions[partitioned] and replicated across multiple link:kafka-brokers.adoc[brokers] in a cluster. link:kafka-producers.adoc[Producers] send messages to topics from which link:kafka-consumers.adoc[consumers] read.

*Language Agnostic* -- producers and consumers use binary protocol to talk to a Kafka cluster.

Messages are byte arrays (with String, JSON, and Avro being the most common formats). If a message has a key, Kafka makes sure that all messages of the same key are in the same partition.

Consumers may be grouped in a link:kafka-consumers.adoc#consumer-group[consumer group] with multiple consumers. Each consumer in a consumer group will read messages from a unique subset of partitions in each topic they subscribe to. Each message is delivered to one consumer in the group, and all messages with the same key arrive at the same consumer.

*Durability* -- Kafka does not track which messages were read by each consumer. Kafka keeps all messages for a finite amount of time, and it is consumers' responsibility to track their location per topic, i.e. link:kafka-messages.adoc#offsets[offsets].

It is worth to note that Kafka is often compared to the following open source projects:

1. http://activemq.apache.org/[Apache ActiveMQ] and https://www.rabbitmq.com/[RabbitMQ] given they are message broker systems, too.

2. http://flume.apache.org/[Apache Flume] for its ingestion capabilities designed to send data to https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html[HDFS] and https://hbase.apache.org/[Apache HBase].
