== [[ZkUtils]] ZkUtils

`ZkUtils` is...FIXME

=== [[subscribeChildChanges]] `subscribeChildChanges` Method

[source, scala]
----
subscribeChildChanges(path: String, listener: IZkChildListener): Option[Seq[String]]
----

`subscribeChildChanges`...FIXME

NOTE: `subscribeChildChanges` is used...

=== [[registerBrokerInZk]] `registerBrokerInZk` Method

[source, scala]
----
registerBrokerInZk(
  id: Int,
  host: String,
  port: Int,
  advertisedEndpoints: Seq[EndPoint],
  jmxPort: Int,
  rack: Option[String],
  apiVersion: ApiVersion): Unit
----

`registerBrokerInZk`...FIXME

NOTE: `registerBrokerInZk` is used exclusively when `KafkaHealthcheck` is requested to link:kafka-KafkaHealthcheck.adoc#register[register].

=== [[getTopicPartitionCount]] `getTopicPartitionCount` Method

[source, scala]
----
getTopicPartitionCount(topic: String): Option[Int]
----

`getTopicPartitionCount`...FIXME

[NOTE]
====
`getTopicPartitionCount` is used when:

1. `GroupMetadataManager` is requested for link:kafka-GroupMetadataManager.adoc#getGroupMetadataTopicPartitionCount[getGroupMetadataTopicPartitionCount] of `__consumer_offsets` topic

1. `TransactionStateManager` is requested for link:kafka-TransactionStateManager.adoc#getTransactionTopicPartitionCount[getTransactionTopicPartitionCount] of `__transaction_state` topic
====
