== [[AbstractFetcherThread]] AbstractFetcherThread

`AbstractFetcherThread` is the <<contract, extension>> of the <<kafka-ShutdownableThread.adoc#, ShutdownableThread contract>> for <<implementations, fetcher threads>> that <<maybeTruncate, maybeTruncate>> followed by <<maybeFetch, maybeFetch>> repeatedly (while <<doWork, doing the work>>) until <<shutdown, shut down>>.

NOTE: `AbstractFetcherThread` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractFetcherThreads>>.

[[contract]]
.AbstractFetcherThread Contract (Abstract Methods)
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| buildFetch
a| [[buildFetch]]

[source, scala]
----
buildFetch(
  partitionMap: Map[TopicPartition, PartitionFetchState]
): ResultWithPartitions[Option[FetchRequest.Builder]]
----

Used exclusively when `AbstractFetcherThread` is requested to <<maybeFetch, maybeFetch>>.

| endOffsetForEpoch
a| [[endOffsetForEpoch]]

[source, scala]
----
endOffsetForEpoch(
  topicPartition: TopicPartition,
  epoch: Int): Option[OffsetAndEpoch]
----

Used exclusively when `AbstractFetcherThread` is requested to <<getOffsetTruncationState, getOffsetTruncationState>>.

| fetchEarliestOffsetFromLeader
a| [[fetchEarliestOffsetFromLeader]]

[source, scala]
----
fetchEarliestOffsetFromLeader(
  topicPartition: TopicPartition,
  currentLeaderEpoch: Int): Long
----

Used exclusively when `AbstractFetcherThread` is requested to <<fetchOffsetAndTruncate, fetchOffsetAndTruncate>>.

| fetchEpochEndOffsets
a| [[fetchEpochEndOffsets]]

[source, scala]
----
fetchEpochEndOffsets(
  partitions: Map[TopicPartition, EpochData]
): Map[TopicPartition, EpochEndOffset]
----

Used exclusively when `AbstractFetcherThread` is requested to <<truncateToEpochEndOffsets, truncateToEpochEndOffsets>>.

| fetchFromLeader
a| [[fetchFromLeader]]

[source, scala]
----
fetchFromLeader(
  fetchRequest: FetchRequest.Builder
): Seq[(TopicPartition, FetchData)]
----

Used exclusively when `AbstractFetcherThread` is requested to <<processFetchRequest, processFetchRequest>>.

| fetchLatestOffsetFromLeader
a| [[fetchLatestOffsetFromLeader]]

[source, scala]
----
fetchLatestOffsetFromLeader(
  topicPartition: TopicPartition,
  currentLeaderEpoch: Int): Long
----

Used exclusively when `AbstractFetcherThread` is requested to <<fetchOffsetAndTruncate, fetchOffsetAndTruncate>>.

| isOffsetForLeaderEpochSupported
a| [[isOffsetForLeaderEpochSupported]]

[source, scala]
----
isOffsetForLeaderEpochSupported: Boolean
----

Used exclusively when `AbstractFetcherThread` is requested to <<fetchTruncatingPartitions, fetchTruncatingPartitions>>.

| latestEpoch
a| [[latestEpoch]]

[source, scala]
----
latestEpoch(topicPartition: TopicPartition): Option[Int]
----

Used exclusively when `AbstractFetcherThread` is requested to <<fetchTruncatingPartitions, fetchTruncatingPartitions>>.

| logEndOffset
a| [[logEndOffset]]

[source, scala]
----
logEndOffset(topicPartition: TopicPartition): Long
----

Used when `AbstractFetcherThread` is requested to <<getOffsetTruncationState, getOffsetTruncationState>> and <<fetchOffsetAndTruncate, fetchOffsetAndTruncate>>.

| processPartitionData
a| [[processPartitionData]]

[source, scala]
----
processPartitionData(
  topicPartition: TopicPartition,
  fetchOffset: Long,
  partitionData: FetchData): Option[LogAppendInfo]
----

Used exclusively when `AbstractFetcherThread` is requested to <<processFetchRequest, processFetchRequest>>.

| truncate
a| [[truncate]]

[source, scala]
----
truncate(
  topicPartition: TopicPartition,
  truncationState: OffsetTruncationState): Unit
----

Used when `AbstractFetcherThread` is requested to <<truncateToHighWatermark, truncateToHighWatermark>>, <<maybeTruncateToEpochEndOffsets, maybeTruncateToEpochEndOffsets>>, and <<fetchOffsetAndTruncate, fetchOffsetAndTruncate>>.

| truncateFullyAndStartAt
a| [[truncateFullyAndStartAt]]

[source, scala]
----
truncateFullyAndStartAt(
  topicPartition: TopicPartition,
  offset: Long): Unit
----

Used exclusively when `AbstractFetcherThread` is requested to <<fetchOffsetAndTruncate, fetchOffsetAndTruncate>>.

|===

[[implementations]]
.AbstractFetcherThreads
[cols="1,3",options="header",width="100%"]
|===
| AbstractFetcherThread
| Description

| <<kafka-server-ReplicaAlterLogDirsThread.adoc#, ReplicaAlterLogDirsThread>>
| [[ReplicaAlterLogDirsThread]]

| <<kafka-server-ReplicaFetcherThread.adoc#, ReplicaFetcherThread>>
| [[ReplicaFetcherThread]]

|===

[[internal-registries]]
.AbstractFetcherThread's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,3",options="header",width="100%"]
|===
| Name
| Description

| partitionStates
a| [[partitionStates]] `TopicPartitions` with their `PartitionFetchState` (`PartitionStates[PartitionFetchState]`)

* A `TopicPartition` is removed in <<onPartitionFenced, onPartitionFenced>> and <<removePartitions, removePartitions>>

* `PartitionFetchState` updated in <<processFetchRequest, processFetchRequest>>, <<markPartitionsForTruncation, markPartitionsForTruncation>>, <<addPartitions, addPartitions>>, <<updateFetchOffsetAndMaybeMarkTruncationComplete, updateFetchOffsetAndMaybeMarkTruncationComplete>>, <<handleOutOfRangeError, handleOutOfRangeError>>, <<delayPartitions, delayPartitions>>

Used when...FIXME

|===

=== [[creating-instance]] Creating AbstractFetcherThread Instance

`AbstractFetcherThread` takes the following to be created:

* [[name]] Thread Name
* [[clientId]] Client ID
* [[sourceBroker]] `BrokerEndPoint`
* [[fetchBackOffMs]] `fetchBackOffMs` (default: `0`)
* [[isInterruptible]] `isInterruptible` flag (default: `true`)

`AbstractFetcherThread` initializes the <<internal-registries, internal registries and counters>>.

=== [[doWork]] `doWork` Method

[source, scala]
----
doWork(): Unit
----

NOTE: `doWork` is part of the <<kafka-ShutdownableThread.adoc#doWork, ShutdownableThread Contract>> to do the work.

`doWork` simply <<maybeTruncate, maybeTruncate>> followed by <<maybeFetch, maybeFetch>>.

=== [[maybeTruncate]] `maybeTruncate` Internal Method

[source, scala]
----
maybeTruncate(): Unit
----

`maybeTruncate` <<fetchTruncatingPartitions, fetchTruncatingPartitions>>.

`maybeTruncate`...FIXME

NOTE: `maybeTruncate` is used exclusively when `AbstractFetcherThread` is requested to <<doWork, do the work>>.

=== [[maybeFetch]] `maybeFetch` Internal Method

[source, scala]
----
maybeFetch(): Unit
----

`maybeFetch`...FIXME

NOTE: `maybeFetch` is used exclusively when `AbstractFetcherThread` is requested to <<doWork, do the work>>.

=== [[fetchTruncatingPartitions]] `fetchTruncatingPartitions` Internal Method

[source, scala]
----
fetchTruncatingPartitions(): (Map[TopicPartition, EpochData], Set[TopicPartition])
----

`fetchTruncatingPartitions`...FIXME

NOTE: `fetchTruncatingPartitions` is used exclusively when `AbstractFetcherThread` is requested to <<maybeTruncate, maybeTruncate>>.

=== [[onPartitionFenced]] `onPartitionFenced` Internal Method

[source, scala]
----
onPartitionFenced(tp: TopicPartition): Unit
----

`onPartitionFenced`...FIXME

NOTE: `onPartitionFenced` is used when `AbstractFetcherThread` is requested to <<maybeTruncateToEpochEndOffsets, maybeTruncateToEpochEndOffsets>>, <<processFetchRequest, processFetchRequest>>, and <<handleOutOfRangeError, handleOutOfRangeError>>.

=== [[maybeTruncateToEpochEndOffsets]] `maybeTruncateToEpochEndOffsets` Internal Method

[source, scala]
----
maybeTruncateToEpochEndOffsets(
  fetchedEpochs: Map[TopicPartition, EpochEndOffset]
): ResultWithPartitions[Map[TopicPartition, OffsetTruncationState]]
----

`maybeTruncateToEpochEndOffsets`...FIXME

NOTE: `maybeTruncateToEpochEndOffsets` is used exclusively when `AbstractFetcherThread` is requested to <<truncateToEpochEndOffsets, truncateToEpochEndOffsets>>.

=== [[processFetchRequest]] `processFetchRequest` Internal Method

[source, scala]
----
processFetchRequest(
  fetchStates: Map[TopicPartition, PartitionFetchState],
  fetchRequest: FetchRequest.Builder): Unit
----

`processFetchRequest`...FIXME

NOTE: `processFetchRequest` is used exclusively when `AbstractFetcherThread` is requested to <<maybeFetch, maybeFetch>>.

=== [[handleOutOfRangeError]] `handleOutOfRangeError` Internal Method

[source, scala]
----
handleOutOfRangeError(
  topicPartition: TopicPartition,
  fetchState: PartitionFetchState): Boolean
----

`handleOutOfRangeError`...FIXME

NOTE: `handleOutOfRangeError` is used exclusively when `AbstractFetcherThread` is requested to <<processFetchRequest, processFetchRequest>>.

=== [[markPartitionsForTruncation]] `markPartitionsForTruncation` Method

[source, scala]
----
markPartitionsForTruncation(
  topicPartition: TopicPartition,
  truncationOffset: Long): Unit
markPartitionsForTruncation(
  brokerId: Int,
  topicPartition: TopicPartition,
  truncationOffset: Long): Unit
----

`markPartitionsForTruncation`...FIXME

NOTE: `markPartitionsForTruncation` is used when...FIXME

=== [[addPartitions]] `addPartitions` Method

[source, scala]
----
addPartitions(initialFetchStates: Map[TopicPartition, OffsetAndEpoch])
----

`addPartitions`...FIXME

NOTE: `addPartitions` is used exclusively when `AbstractFetcherManager` is requested to <<kafka-server-AbstractFetcherManager.adoc#addFetcherForPartitions, addFetcherForPartitions>>.

=== [[updateFetchOffsetAndMaybeMarkTruncationComplete]] `updateFetchOffsetAndMaybeMarkTruncationComplete` Internal Method

[source, scala]
----
updateFetchOffsetAndMaybeMarkTruncationComplete(
  fetchOffsets: Map[TopicPartition, OffsetTruncationState]): Unit
----

`updateFetchOffsetAndMaybeMarkTruncationComplete`...FIXME

NOTE: `updateFetchOffsetAndMaybeMarkTruncationComplete` is used when `AbstractFetcherThread` is requested to <<truncateToEpochEndOffsets, truncateToEpochEndOffsets>> and <<truncateToHighWatermark, truncateToHighWatermark>>.

=== [[truncateToEpochEndOffsets]] `truncateToEpochEndOffsets` Internal Method

[source, scala]
----
truncateToEpochEndOffsets(
  latestEpochsForPartitions: Map[TopicPartition, EpochData]): Unit
----

`truncateToEpochEndOffsets`...FIXME

NOTE: `truncateToEpochEndOffsets` is used exclusively when `AbstractFetcherThread` is requested to <<maybeTruncate, maybeTruncate>>.

=== [[truncateToHighWatermark]] `truncateToHighWatermark` Internal Method

[source, scala]
----
truncateToHighWatermark(partitions: Set[TopicPartition]): Unit
----

`truncateToHighWatermark`...FIXME

NOTE: `truncateToHighWatermark` is used exclusively when `AbstractFetcherThread` is requested to <<maybeTruncate, maybeTruncate>>.

=== [[partitionsAndOffsets]] `partitionsAndOffsets` Method

[source, scala]
----
partitionsAndOffsets: Map[TopicPartition, InitialFetchState]
----

`partitionsAndOffsets`...FIXME

NOTE: `partitionsAndOffsets` is used exclusively when `AbstractFetcherManager` is requested to <<kafka-server-AbstractFetcherManager.adoc#resizeThreadPool, resizeThreadPool>>.

=== [[getOffsetTruncationState]] `getOffsetTruncationState` Internal Method

[source, scala]
----
getOffsetTruncationState(
  tp: TopicPartition,
  leaderEpochOffset: EpochEndOffset): OffsetTruncationState
----

`getOffsetTruncationState`...FIXME

NOTE: `getOffsetTruncationState` is used exclusively when `AbstractFetcherThread` is requested to <<maybeTruncateToEpochEndOffsets, maybeTruncateToEpochEndOffsets>>.

=== [[fetchOffsetAndTruncate]] `fetchOffsetAndTruncate` Method

[source, scala]
----
fetchOffsetAndTruncate(
  topicPartition: TopicPartition,
  currentLeaderEpoch: Int): Long
----

`fetchOffsetAndTruncate`...FIXME

NOTE: `fetchOffsetAndTruncate` is used exclusively when `AbstractFetcherThread` is requested to <<addPartitions, addPartitions>> and <<handleOutOfRangeError, handleOutOfRangeError>>.
