== [[ZkReplicaStateMachine]] ZkReplicaStateMachine

`ZkReplicaStateMachine` is a concrete <<kafka-controller-ReplicaStateMachine.adoc#, ReplicaStateMachine>> to <<handleStateChanges, handleStateChanges>>.

`ZkReplicaStateMachine` is <<creating-instance, created>> exclusively for <<kafka-controller-KafkaController.adoc#, KafkaController>>.

[[logIdent]]
`ZkReplicaStateMachine` uses *[ReplicaStateMachine controllerId=[brokerId]]* as the logging prefix (aka `logIdent`).

[[logging]]
[TIP]
====
Enable `ALL` logging levels for `kafka.controller.ZkReplicaStateMachine` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.controller.ZkReplicaStateMachine=ALL
```

Refer to <<kafka-logging.adoc#, Logging>>.
====

=== [[creating-instance]] Creating ZkReplicaStateMachine Instance

`ZkReplicaStateMachine` takes the following to be created:

* [[config]] <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>
* [[stateChangeLogger]] `StateChangeLogger`
* [[controllerContext]] <<kafka-controller-ControllerContext.adoc#, ControllerContext>>
* [[zkClient]] <<kafka-zk-KafkaZkClient.adoc#, KafkaZkClient>>
* [[controllerBrokerRequestBatch]] <<kafka-controller-ControllerBrokerRequestBatch.adoc#, ControllerBrokerRequestBatch>>

=== [[handleStateChanges]] `handleStateChanges` Method

[source, scala]
----
handleStateChanges(
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState): Unit
----

NOTE: `handleStateChanges` is part of the <<kafka-controller-ReplicaStateMachine.adoc#handleStateChanges, ReplicaStateMachine Contract>> to...FIXME.

`handleStateChanges` requests the <<controllerBrokerRequestBatch, ControllerBrokerRequestBatch>> to <<kafka-controller-AbstractControllerBrokerRequestBatch.adoc#newBatch, prepare a new batch>>.

`handleStateChanges` groups the `PartitionAndReplica` by replica ID and for every group <<doHandleStateChanges, doHandleStateChanges>>.

In the end, `handleStateChanges` requests the <<controllerBrokerRequestBatch, ControllerBrokerRequestBatch>> to <<kafka-controller-AbstractControllerBrokerRequestBatch.adoc#sendRequestsToBrokers, sendRequestsToBrokers>>.

In case of a `ControllerMovedException`, `handleStateChanges` prints out the following ERROR message to the logs and re-throws the exception.

```
Controller moved to another broker when moving some replicas to [targetState] state
```

In case of any other error (`Throwable`), `handleStateChanges` simply prints out the following ERROR message to the logs:

```
Error while moving some replicas to [targetState] state
```

`handleStateChanges` does nothing and returns when there are no `PartitionAndReplica` to work on (i.e. the given replicas is empty).

=== [[doHandleStateChanges]] `doHandleStateChanges` Internal Method

[source, scala]
----
doHandleStateChanges(
  replicaId: Int,
  replicas: Seq[PartitionAndReplica],
  targetState: ReplicaState): Unit
----

`doHandleStateChanges`...FIXME

NOTE: `doHandleStateChanges` is used exclusively when `ZkReplicaStateMachine` is requested to <<handleStateChanges, handleStateChanges>>.

=== [[doRemoveReplicasFromIsr]] `doRemoveReplicasFromIsr` Internal Method

[source, scala]
----
doRemoveReplicasFromIsr(
  replicaId: Int,
  partitions: Seq[TopicPartition]):
(Map[TopicPartition, LeaderIsrAndControllerEpoch],
 Seq[TopicPartition],
 Map[TopicPartition, Exception])
----

`doRemoveReplicasFromIsr`...FIXME

NOTE: `doRemoveReplicasFromIsr` is used exclusively when `ZkReplicaStateMachine` is requested to <<removeReplicasFromIsr, removeReplicasFromIsr>>.

=== [[getTopicPartitionStatesFromZk]] `getTopicPartitionStatesFromZk` Internal Method

[source, scala]
----
getTopicPartitionStatesFromZk(partitions: Seq[TopicPartition]):
  (Map[TopicPartition, LeaderAndIsr],
   Seq[TopicPartition],
   Map[TopicPartition, Exception])
----

`getTopicPartitionStatesFromZk`...FIXME

NOTE: `getTopicPartitionStatesFromZk` is used exclusively when `ZkReplicaStateMachine` is requested to <<doRemoveReplicasFromIsr, doRemoveReplicasFromIsr>>.

=== [[logFailedStateChange]] `logFailedStateChange` Internal Method

[source, scala]
----
logFailedStateChange(
  replica: PartitionAndReplica,
  currState: ReplicaState,
  targetState: ReplicaState,
  t: Throwable): Unit
----

`logFailedStateChange`...FIXME

NOTE: `logFailedStateChange` is used when `ZkReplicaStateMachine` is requested to...FIXME

=== [[logInvalidTransition]] `logInvalidTransition` Internal Method

[source, scala]
----
logInvalidTransition(
  replica: PartitionAndReplica,
  targetState: ReplicaState): Unit
----

`logInvalidTransition`...FIXME

NOTE: `logInvalidTransition` is used exclusively when `ZkReplicaStateMachine` is requested to <<doHandleStateChanges, doHandleStateChanges>>.

=== [[logSuccessfulTransition]] `logSuccessfulTransition` Internal Method

[source, scala]
----
logSuccessfulTransition(
  replicaId: Int,
  partition: TopicPartition,
  currState: ReplicaState,
  targetState: ReplicaState): Unit
----

`logSuccessfulTransition`...FIXME

NOTE: `logSuccessfulTransition` is used when `ZkReplicaStateMachine` is requested to...FIXME

=== [[removeReplicasFromIsr]] `removeReplicasFromIsr` Internal Method

[source, scala]
----
removeReplicasFromIsr(
  replicaId: Int,
  partitions: Seq[TopicPartition]):
Map[TopicPartition, LeaderIsrAndControllerEpoch]
----

`removeReplicasFromIsr`...FIXME

NOTE: `removeReplicasFromIsr` is used exclusively when `ZkReplicaStateMachine` is requested to <<doHandleStateChanges, doHandleStateChanges>>.
