== [[MetadataCache]] MetadataCache

`MetadataCache` is...FIXME

`MetadataCache` is <<creating-instance, created>> exclusively for <<kafka-server-KafkaServer.adoc#metadataCache, KafkaServer>> (when <<kafka-server-KafkaServer.adoc#startup, started>>).

[[brokerId]]
[[creating-instance]]
`MetadataCache` takes a single broker ID when created.

[[contains]]
`MetadataCache` maintains the <<metadataSnapshot, metadataSnapshot>> and is used to...FIXME

[[getControllerId]]
`MetadataCache` tracks the `controllerId`...FIXME

[[internal-registries]]
.MetadataCache's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| metadataSnapshot
a| [[metadataSnapshot]] `MetadataSnapshot`

`metadataSnapshot` is updated when `MetadataCache` is requested to <<updateMetadata, updateMetadata>>

| partitionMetadataLock
| [[partitionMetadataLock]] Java's https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html[ReentrantReadWriteLock]

| stateChangeLogger
a| [[stateChangeLogger]] link:kafka-controller-StateChangeLogger.adoc[StateChangeLogger]
|===

[[logIdent]]
`MetadataCache` uses *[MetadataCache brokerId=[brokerId]]* as the logging prefix (aka `logIdent`).

[[logging]]
[TIP]
====
Enable `DEBUG` or `ERROR` logging level for `kafka.server.MetadataCache` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.server.MetadataCache=DEBUG
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[getAllTopics]] `getAllTopics` Method

[source, scala]
----
getAllTopics(): Set[String]
----

`getAllTopics`...FIXME

NOTE: `getAllTopics` is used when...FIXME

=== [[getTopicMetadata]] `getTopicMetadata` Method

[source, scala]
----
getTopicMetadata(
  topics: Set[String],
  listenerName: ListenerName,
  errorUnavailableEndpoints: Boolean = false,
  errorUnavailableListeners: Boolean = false): Seq[MetadataResponse.TopicMetadata]
----

`getTopicMetadata`...FIXME

NOTE: `getTopicMetadata` is used when...FIXME

=== [[getAliveBrokers]] `getAliveBrokers` Method

[source, scala]
----
getAliveBrokers: Seq[Broker]
----

`getAliveBrokers`...FIXME

NOTE: `getAliveBrokers` is used when...FIXME

=== [[updateMetadata]] Updating Metadata (and Returning Deleted Partitions) -- `updateMetadata` Method

[source, scala]
----
updateMetadata(
  correlationId: Int,
  updateMetadataRequest: UpdateMetadataRequest): Seq[TopicPartition]
----

`updateMetadata`...FIXME

NOTE: `updateMetadata` is used exclusively when `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#maybeUpdateMetadataCache, maybeUpdateMetadataCache>>.

=== [[getClusterMetadata]] `getClusterMetadata` Method

[source, scala]
----
getClusterMetadata(clusterId: String, listenerName: ListenerName): Cluster
----

`getClusterMetadata`...FIXME

NOTE: `getClusterMetadata` is used exclusively when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleUpdateMetadataRequest, handle an UpdateMetadata request>>.

=== [[getPartitionReplicaEndpoints]] `getPartitionReplicaEndpoints` Method

[source, scala]
----
getPartitionReplicaEndpoints(
  tp: TopicPartition,
  listenerName: ListenerName): Map[Int, Node]
----

`getPartitionReplicaEndpoints`...FIXME

NOTE: `getPartitionReplicaEndpoints` is used when `ReplicaManager` is requested to link:kafka-server-ReplicaManager.adoc#findPreferredReadReplica[findPreferredReadReplica].
