== [[Scheduler]] Scheduler Contract

`Scheduler` is the <<contract, contract>> of <<implementations, task schedulers>> that allow for <<schedule, scheduling tasks>>.

NOTE: <<kafka-server-scheduled-tasks.adoc#, Kafka Server and Periodic Tasks>> describes the scheduled tasks.

[[contract]]
[source, scala]
----
package kafka.utils

trait Scheduler {
  def isStarted: Boolean
  def shutdown()
  def schedule(
    name: String,
    fun: () => Unit,
    delay: Long = 0,
    period: Long = -1,
    unit: TimeUnit = TimeUnit.MILLISECONDS)
  def startup()
}
----

.Scheduler Contract
[cols="1m,2",options="header",width="100%"]
|===
| Property
| Description

| isStarted
a| [[isStarted]] Flag that indicates whether the scheduler has been started or not

Used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerResignation, onControllerResignation>>

* `GroupMetadataManager` is requested to <<kafka-GroupMetadataManager.adoc#shutdown, shutdown>>

* `LogManager` is requested to <<kafka-LogManager.adoc#deleteLogs, deleteLogs>>

* `KafkaScheduler` is requested to <<kafka-KafkaScheduler.adoc#startup, startup>> and <<kafka-KafkaScheduler.adoc#ensureRunning, ensureRunning>>

| shutdown
a| [[shutdown]] Shuts down the scheduler. When this method is complete no more executions of background tasks will occur.

Used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerResignation, onControllerResignation>>

* `GroupMetadataManager` is requested to <<kafka-GroupMetadataManager.adoc#shutdown, shutdown>>

* `TransactionCoordinator` is requested to <<kafka-TransactionCoordinator.adoc#shutdown, shutdown>>

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#shutdown, shutdown>>

* `ZooKeeperClient` is requested to <<kafka-ZooKeeperClient.adoc#close, close>>

| schedule
a| [[schedule]] Schedules a task

Used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>> and <<kafka-controller-KafkaController.adoc#scheduleAutoLeaderRebalanceTask, scheduleAutoLeaderRebalanceTask>>

* `GroupMetadataManager` is requested to <<kafka-GroupMetadataManager.adoc#startup, start up>>, <<kafka-GroupMetadataManager.adoc#scheduleLoadGroupAndOffsets, scheduleLoadGroupAndOffsets>>, <<kafka-GroupMetadataManager.adoc#removeGroupsForPartition, removeGroupsForPartition>> and <<kafka-GroupMetadataManager.adoc#scheduleHandleTxnCompletion, scheduleHandleTxnCompletion>>

* `TransactionCoordinator` is requested to <<kafka-TransactionCoordinator.adoc#startup, start up>>

* `TransactionStateManager` is requested to <<kafka-TransactionStateManager.adoc#enableTransactionalIdExpiration, enableTransactionalIdExpiration>>, <<kafka-TransactionStateManager.adoc#loadTransactionsForTxnTopicPartition, loadTransactionsForTxnTopicPartition>> and <<kafka-TransactionStateManager.adoc#removeTransactionsForTxnTopicPartition, removeTransactionsForTxnTopicPartition>>

* `Log` is <<kafka-Log.adoc#creating-instance, created>> and requested to <<kafka-Log.adoc#roll, roll>> and <<kafka-Log.adoc#asyncDeleteSegment, asyncDeleteSegment>>

* `LogManager` is requested to <<kafka-LogManager.adoc#startup, start up>> and <<kafka-LogManager.adoc#deleteLogs, deleteLogs>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#startHighWaterMarksCheckPointThread, startHighWaterMarksCheckPointThread>> and <<kafka-server-ReplicaManager.adoc#startup, startup>>

* `KafkaScheduler` is requested to <<kafka-KafkaScheduler.adoc#scheduleOnce, scheduleOnce>>

| startup
a| [[startup]] Initializes the scheduler so it is ready to schedule tasks

Used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>>

* `GroupMetadataManager` is requested to <<kafka-GroupMetadataManager.adoc#startup, start up>>

* `TransactionCoordinator` is requested to <<kafka-TransactionCoordinator.adoc#startup, start up>>

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#startup>>

* `ZooKeeperClient` is <<kafka-ZooKeeperClient.adoc#creating-instance, created>>
|===

[[implementations]]
NOTE: <<kafka-KafkaScheduler.adoc#, KafkaScheduler>> is the one and only known implementation of the <<contract, Scheduler Contract>> in Apache Kafka.
