== [[TopicConfig]] TopicConfig -- Topic-Level Configuration Keys

`TopicConfig` are the <<keys, keys>> for a *topic-level configuration* of a topic (and override link:kafka-server-KafkaConfig.adoc[cluster-wide defaults] that are mostly different by names with `log.` prefix).

[[note-replace-LogConfig]]
NOTE: As the link:++https://github.com/apache/kafka/blob/ac385c4c3a770728848438f28f4acb8854ffc868/clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java#L29++[TopicConfig] itself says: "_Eventually this should replace LogConfig.scala._"

Import `org.apache.kafka.common.config.TopicConfig` to reference the keys.

[source, scala]
----
import org.apache.kafka.common.config.TopicConfig
assert(TopicConfig.CLEANUP_POLICY_CONFIG == "cleanup.policy")
----

[[keys]]
.Keys
[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| CLEANUP_POLICY_CONFIG
a| [[cleanup.policy]][[CLEANUP_POLICY_CONFIG]] cleanup.policy

Used when:

* `LogConfig` is requested for <<kafka-log-LogConfig.adoc#CleanupPolicyProp, LogConfig.CleanupPolicyProp>>

* (Kafka Streams) `RepartitionTopicConfig` is requested for `REPARTITION_TOPIC_DEFAULT_OVERRIDES`

* (Kafka Streams) `UnwindowedChangelogTopicConfig` is requested for `UNWINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES`

* (Kafka Streams) `WindowedChangelogTopicConfig` is requested for `WINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES`

| COMPRESSION_TYPE_CONFIG
a| [[compression.type]][[COMPRESSION_TYPE_CONFIG]] compression.type

| DELETE_RETENTION_MS_CONFIG
a| [[delete.retention.ms]][[DELETE_RETENTION_MS_CONFIG]] delete.retention.ms

| FILE_DELETE_DELAY_MS_CONFIG
a| [[file.delete.delay.ms]][[FILE_DELETE_DELAY_MS_CONFIG]] file.delete.delay.ms

| FLUSH_MESSAGES_INTERVAL_CONFIG
a| [[flush.messages]][[FLUSH_MESSAGES_INTERVAL_CONFIG]] flush.messages

| FLUSH_MS_CONFIG
a| [[flush.ms]][[FLUSH_MS_CONFIG]] flush.ms

| INDEX_INTERVAL_BYTES_CONFIG
a| [[index.interval.bytes]][[INDEX_INTERVAL_BYTES_CONFIG]] index.interval.bytes

| MAX_COMPACTION_LAG_MS_CONFIG
a| [[max.compaction.lag.ms]][[MAX_COMPACTION_LAG_MS_CONFIG]] max.compaction.lag.ms

| MAX_MESSAGE_BYTES_CONFIG
a| [[max.message.bytes]][[MAX_MESSAGE_BYTES_CONFIG]] max.message.bytes

| MESSAGE_DOWNCONVERSION_ENABLE_CONFIG
a| [[message.downconversion.enable]][[MESSAGE_DOWNCONVERSION_ENABLE_CONFIG]] message.downconversion.enable

| MESSAGE_FORMAT_VERSION_CONFIG
a| [[message.format.version]][[MESSAGE_FORMAT_VERSION_CONFIG]] message.format.version

| MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS_CONFIG
a| [[message.timestamp.difference.max.ms]][[MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS_CONFIG]] message.timestamp.difference.max.ms

| MESSAGE_TIMESTAMP_TYPE_CONFIG
a| [[message.timestamp.type]][[MESSAGE_TIMESTAMP_TYPE_CONFIG]] message.timestamp.type

| MIN_CLEANABLE_DIRTY_RATIO_CONFIG
a| [[min.cleanable.dirty.ratio]][[MIN_CLEANABLE_DIRTY_RATIO_CONFIG]] min.cleanable.dirty.ratio

| MIN_COMPACTION_LAG_MS_CONFIG
a| [[min.compaction.lag.ms]][[MIN_COMPACTION_LAG_MS_CONFIG]] min.compaction.lag.ms

| MIN_IN_SYNC_REPLICAS_CONFIG
a| [[min.insync.replicas]][[MIN_IN_SYNC_REPLICAS_CONFIG]] link:kafka-properties.adoc#min.insync.replicas[min.insync.replicas]

Used when:

* link:kafka-admin-TopicCommand.adoc[TopicCommand] is executed

* Alias for link:kafka-log-LogConfig.adoc#MinInSyncReplicasProp[LogConfig.MinInSyncReplicasProp]

| PREALLOCATE_CONFIG
a| [[preallocate]][[PREALLOCATE_CONFIG]] preallocate

| RETENTION_BYTES_CONFIG
a| [[retention.bytes]][[RETENTION_BYTES_CONFIG]] Maximum size (in bytes) of a partition to grow before discarding old log segments and free up space for topics with link:kafka-log-cleanup-policies.adoc#delete[delete] retention policy.

Default: `-1L` (no size limit)

By default there is no size limit only a time limit. Since this limit is enforced at the partition level, multiply it by the number of partitions to compute the topic retention in bytes.

Alias of link:kafka-log-LogConfig.adoc#RetentionBytesProp[LogConfig.RetentionBytesProp]

Cluster-wide property: link:kafka-properties.adoc#log.retention.bytes[log.retention.bytes]

Used exclusively when `Log` is requested to <<kafka-log-Log.adoc#deleteRetentionSizeBreachedSegments, deleteRetentionSizeBreachedSegments>>

| RETENTION_MS_CONFIG
a| [[retention.ms]][[RETENTION_MS_CONFIG]] retention.ms

| SEGMENT_BYTES_CONFIG
a| [[segment.bytes]][[SEGMENT_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentBytesProp, LogConfig.SegmentBytesProp>>

Used when:

* (Kafka Streams) `StreamsConfig` is requested to `getMainConsumerConfigs`

* (Kafka Streams) `RepartitionTopicConfig` is requested for `REPARTITION_TOPIC_DEFAULT_OVERRIDES`

| SEGMENT_INDEX_BYTES_CONFIG
a| [[segment.index.bytes]][[SEGMENT_INDEX_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentIndexBytesProp, LogConfig.SegmentIndexBytesProp>>

| SEGMENT_JITTER_MS_CONFIG
a| [[segment.jitter.ms]][[SEGMENT_JITTER_MS_CONFIG]] segment.jitter.ms

| SEGMENT_MS_CONFIG
a| [[segment.ms]][[SEGMENT_MS_CONFIG]] segment.ms

| UNCLEAN_LEADER_ELECTION_ENABLE_CONFIG
a| [[unclean.leader.election.enable]][[UNCLEAN_LEADER_ELECTION_ENABLE_CONFIG]] unclean.leader.election.enable

|===
