== [[HeartbeatThread]] HeartbeatThread

`HeartbeatThread` is a daemon Kafka thread of execution that `AbstractCoordinator` starts to <<run, send HeartbeatRequests to the group coordinator>> (aka _heartbeating_) regularly every <<kafka-consumer-ConsumerConfig.adoc#REQUEST_TIMEOUT_MS_CONFIG, request.timeout.ms>> (default: `30000` ms).

`HeartbeatThread` is <<creating-instance, created>> and immediately <<run, started>> exclusively for `AbstractCoordinator` when requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#startHeartbeatThreadIfNeeded, start a HeartbeatThread>> (when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>> after `KafkaConsumer` was requested to <<poll, poll for records>>).

[[name]]
`HeartbeatThread` uses *kafka-coordinator-heartbeat-thread* prefix followed by the <<kafka-consumer-internals-AbstractCoordinator.adoc#groupId, group ID>> as the thread name.

```
kafka-coordinator-heartbeat-thread | [groupId]
```

[[closed]]
`HeartbeatThread` uses `closed` flag to indicate...FIXME

[[enabled]]
`HeartbeatThread` uses `enabled` flag to indicate whether to wait for <<kafka-consumer-internals-AbstractCoordinator.adoc#, AbstractCoordinator>> to notify it (_release_). The flag is off (`false`) initially and can be turned on (`true`) and off by <<enable, enable>> or <<disable, disable>>, respectively.

[[creating-instance]]
`HeartbeatThread` takes no arguments to be created.

=== [[run]] Starting Thread -- `run` Method

[source, java]
----
void run()
----

NOTE: `run` is part of the https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runnable.html[java.lang.Runnable] to start itself as a separately-executing thread.

`run` prints out the following DEBUG message to the logs:

```
Heartbeat thread started
```

In an infinite `while` loop, `run` does the following (infinitely):

. Checks the internal state to exit or wait:

.. Exits when <<closed, closed>>

.. Waits for `AbstractCoordinator` to wake it up when not <<enabled, enabled>>

. Requests the <<kafka-consumer-internals-AbstractCoordinator.adoc#client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#pollNoWakeup, pollNoWakeup>>

. <<kafka-consumer-internals-AbstractCoordinator.adoc#sendHeartbeatRequest, Sends a HeartbeatRequest to the group coordinator>>

. (when the response eventually arrives) Requests the <<heartbeat, Heartbeat>> to record a success (`receiveHeartbeat`) or a failure (`failHeartbeat`)

In the end, when the infinite `while` loop is terminated for any reason, `run` prints out the following DEBUG message to the logs:

```
Heartbeat thread has closed
```

WARNING: `run` does some other state control checks but they look uninteresting...to me...now.

=== [[disable]] Disabling HeartbeatThread -- `disable` Method

[source, java]
----
void disable()
----

`disable` prints out the following DEBUG message to the logs and turns the <<enabled, enabled>> flag off (`false`).

```
Disabling heartbeat thread
```

[NOTE]
====
`disable` is used when:

* `AbstractCoordinator` is requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#disableHeartbeatThread, disableHeartbeatThread>>

* `HeartbeatThread` is requested to <<run, run>> (when in `UNJOINED` or `REBALANCING` <<kafka-consumer-internals-AbstractCoordinator.adoc#state, states>>)
====

=== [[enable]] Enabling HeartbeatThread -- `enable` Method

[source, java]
----
void enable()
----

`enable` prints out the following DEBUG message to the logs:

```
Enabling heartbeat thread
```

`enable` turns the <<enabled, enabled>> flag on (`true`) and requests the <<kafka-consumer-internals-AbstractCoordinator.adoc#heartbeat, Heartbeat>> to `resetTimeouts`.

In the end, `enable` notifies (_wakes up_) the owning <<kafka-consumer-internals-AbstractCoordinator.adoc#, AbstractCoordinator>>.

NOTE: `enable` is used exclusively when `AbstractCoordinator` is requested to <<kafka-consumer-internals-AbstractCoordinator.adoc#initiateJoinGroup, initiateJoinGroup>>.
