== [[KafkaConfig]] KafkaConfig

`KafkaConfig` is the configuration of a Kafka broker and the services.

`KafkaConfig` is <<creating-instance, created>> when:

* `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#initialize, initialize>> and <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>

* `KafkaConfig` is requested to <<fromProps, fromProps>> and <<apply, apply>>

[[configuration-values]]
.KafkaConfig's Configuration Values
[cols="1m,2",options="header",width="100%"]
|===
| Value
| Kafka Property

| advertisedListeners
a| [[advertisedListeners]][[AdvertisedListenersProp]] <<kafka-properties.adoc#advertised.listeners, advertised.listeners>>

Used when:

* `DynamicListenerConfig` is requested to <<kafka-server-DynamicListenerConfig.adoc#validateReconfiguration, validate reconfiguration>>

* `KafkaConfig` is requested to <<validateValues, validateValues>>

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#createBrokerInfo, createBrokerInfo>> (when <<kafka-server-KafkaServer.adoc#startup, started>>)

| autoCreateTopicsEnable
a| [[autoCreateTopicsEnable]] <<kafka-properties.adoc#auto.create.topics.enable, auto.create.topics.enable>>

Used when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#getTopicMetadata, getTopicMetadata>> and <<kafka-server-KafkaApis.adoc#handleTopicMetadataRequest, handleTopicMetadataRequest>>

| autoLeaderRebalanceEnable
a| [[autoLeaderRebalanceEnable]] <<kafka-properties.adoc#auto.leader.rebalance.enable, auto.leader.rebalance.enable>>

Used exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>>

| backgroundThreads
a| [[backgroundThreads]][[BackgroundThreadsProp]] <<kafka-properties.adoc#background.threads, background.threads>>

| brokerId
a| [[brokerId]] <<kafka-properties.adoc#broker.id, broker.id>>

| brokerIdGenerationEnable
a| [[brokerIdGenerationEnable]] <<kafka-properties.adoc#broker.id.generation.enable, broker.id.generation.enable>>

Used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#getBrokerIdAndOfflineDirs, getBrokerIdAndOfflineDirs>>

| connectionsMaxIdleMs
a| [[connectionsMaxIdleMs]] <<kafka-properties.adoc#connections.max.idle.ms, connections.max.idle.ms>>

Used when:

* `TransactionMarkerChannelManager` is created

* `SocketServer` is requested to <<kafka-network-SocketServer.adoc#newProcessor, create a new network processor thread>>

* `ReplicaFetcherBlockingSend` is <<kafka-server-ReplicaFetcherBlockingSend.adoc#networkClient, created>>

| deleteTopicEnable
| [[deleteTopicEnable]] link:kafka-properties.adoc#delete.topic.enable[delete.topic.enable]

| failedAuthenticationDelayMs
a| [[failedAuthenticationDelayMs]] <<kafka-properties.adoc#connection.failed.authentication.delay.ms, connection.failed.authentication.delay.ms>>

Used exclusively when `SocketServer` is requested to <<kafka-network-SocketServer.adoc#newProcessor, create a new network processor thread>>

| hostName
| [[hostName]] link:kafka-properties.adoc#host.name[host.name]

| interBrokerListenerName
a| [[interBrokerListenerName]]

| interBrokerSecurityProtocol
a| [[interBrokerSecurityProtocol]]

| leaderImbalanceCheckIntervalSeconds
a| [[leaderImbalanceCheckIntervalSeconds]] <<kafka-properties.adoc#leader.imbalance.check.interval.seconds, leader.imbalance.check.interval.seconds>>

Used exclusively when `ControllerEventThread` is requested to process a <<kafka-controller-ControllerEvent.adoc#AutoPreferredReplicaLeaderElection, AutoPreferredReplicaLeaderElection>> event (while <<kafka-controller-ControllerEventThread.adoc#doWork, processing controller events>>)

| listeners
a| [[listeners]][[ListenersProp]] <<kafka-properties.adoc#listeners, listeners>> (see <<getListeners, getListeners>>)

| listenerSecurityProtocolMap
a| [[listenerSecurityProtocolMap]][[ListenerSecurityProtocolMapProp]] <<kafka-properties.adoc#listener.security.protocol.map, listener.security.protocol.map>>

| logCleanerThreads
a| [[logCleanerThreads]][[LogCleanerThreadsProp]] <<kafka-properties.adoc#log.cleaner.threads, log.cleaner.threads>>

| logCleanerDedupeBufferSize
a| [[logCleanerDedupeBufferSize]][[LogCleanerDedupeBufferSizeProp]] <<kafka-properties.adoc#log.cleaner.dedupe.buffer.size, log.cleaner.dedupe.buffer.size>>

| logCleanerDedupeBufferLoadFactor
a| [[logCleanerDedupeBufferLoadFactor]][[LogCleanerDedupeBufferLoadFactorProp]] <<kafka-properties.adoc#log.cleaner.io.buffer.load.factor, log.cleaner.io.buffer.load.factor>>

| logCleanerIoBufferSize
a| [[logCleanerIoBufferSize]][[LogCleanerIoBufferSizeProp]] <<kafka-properties.adoc#log.cleaner.io.buffer.size, log.cleaner.io.buffer.size>>

| logCleanerIoMaxBytesPerSecond
a| [[logCleanerIoMaxBytesPerSecond]][[LogCleanerIoMaxBytesPerSecondProp]] <<kafka-properties.adoc#log.cleaner.io.max.bytes.per.second, log.cleaner.io.max.bytes.per.second>>

| logCleanerBackoffMs
a| [[logCleanerBackoffMs]][[LogCleanerBackoffMsProp]] <<kafka-properties.adoc#log.cleaner.backoff.ms, log.cleaner.backoff.ms>>

| logCleanerEnable
a| [[logCleanerEnable]][[LogCleanerEnableProp]] <<kafka-properties.adoc#log.cleaner.enable, log.cleaner.enable>>

| logDirs
a| [[logDirs]] <<kafka-properties.adoc#log.dirs, log.dirs>> or <<kafka-properties.adoc#log.dir, log.dir>>

At least one log directory must be defined via <<kafka-properties.adoc#log.dirs, log.dirs>> or <<kafka-properties.adoc#log.dir, log.dir>> properties.

Used when:

* `LogManager` is <<kafka-log-LogManager.adoc#logDirs, created>>

* `LogDirFailureChannel` is created (when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>)

* `KafkaConfig` is requested to <<getNumReplicaAlterLogDirsThreads, getNumReplicaAlterLogDirsThreads>>

* `KafkaServer` is <<kafka-server-KafkaServer.adoc#brokerMetadataCheckpoints, created>> and is requested to <<kafka-server-KafkaServer.adoc#getBrokerIdAndOfflineDirs, getBrokerIdAndOfflineDirs>> and <<kafka-server-KafkaServer.adoc#checkpointBrokerId, checkpointBrokerId>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#describeLogDirs, describeLogDirs>>

| maxConnectionsPerIp
a| [[maxConnectionsPerIp]][[MaxConnectionsPerIpProp]] <<kafka-properties.adoc#max.connections.per.ip, max.connections.per.ip>>

Used exclusively when `SocketServer` is requested to <<kafka-network-SocketServer.adoc#startup, start up>>

| maxConnectionsPerIpOverrides
a| [[maxConnectionsPerIpOverrides]][[MaxConnectionsPerIpOverridesProp]] <<kafka-properties.adoc#max.connections.per.ip.overrides, max.connections.per.ip.overrides>>

Used exclusively when `SocketServer` is requested to <<kafka-network-SocketServer.adoc#startup, start up>>

| maxReservedBrokerId
a| [[maxReservedBrokerId]] <<kafka-properties.adoc#reserved.broker.max.id, reserved.broker.max.id>>

Used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#generateBrokerId, generateBrokerId>>

| messageMaxBytes
a| [[messageMaxBytes]][[MessageMaxBytesProp]] <<kafka-properties.adoc#message.max.bytes, message.max.bytes>>

| numIoThreads
a| [[numIoThreads]][[NumIoThreadsProp]] <<kafka-properties.adoc#num.io.threads, num.io.threads>>

| numNetworkThreads
a| [[numNetworkThreads]][[NumNetworkThreadsProp]] <<kafka-properties.adoc#num.network.threads, num.network.threads>>

| numRecoveryThreadsPerDataDir
a| [[numRecoveryThreadsPerDataDir]][[NumRecoveryThreadsPerDataDirProp]] <<kafka-properties.adoc#num.recovery.threads.per.data.dir, num.recovery.threads.per.data.dir>>

Used exclusively when `LogManager` is <<kafka-log-LogManager.adoc#apply, created>>

| numReplicaFetchers
a| [[numReplicaFetchers]][[NumReplicaFetchersProp]] <<kafka-properties.adoc#num.replica.fetchers, num.replica.fetchers>>

| port
| [[port]] link:kafka-properties.adoc#port[port]

| PrincipalBuilderClassProp
a| [[PrincipalBuilderClassProp]] <<kafka-properties.adoc#principal.builder.class, principal.builder.class>>

| replicaLagTimeMaxMs
a| [[replicaLagTimeMaxMs]]

| replicaFetchBackoffMs
a| [[replicaFetchBackoffMs]][[ReplicaFetchBackoffMsProp]] <<kafka-properties.adoc#replica.fetch.backoff.ms, replica.fetch.backoff.ms>>

Used as <<kafka-server-AbstractFetcherThread.adoc#fetchBackOffMs, fetchBackOffMs>> for <<kafka-server-ReplicaAlterLogDirsThread.adoc#, ReplicaAlterLogDirsThread>> and <<kafka-server-ReplicaFetcherThread.adoc#, ReplicaFetcherThread>>

| SaslMechanismInterBrokerProtocolProp
a| [[SaslMechanismInterBrokerProtocolProp]] <<kafka-properties.adoc#sasl.mechanism.inter.broker.protocol, sasl.mechanism.inter.broker.protocol>>

| SaslJaasConfigProp
a| [[SaslJaasConfigProp]] <<kafka-properties.adoc#sasl.jaas.config, sasl.jaas.config>>

| SaslEnabledMechanismsProp
a| [[SaslEnabledMechanismsProp]] <<kafka-properties.adoc#sasl.enabled.mechanisms, sasl.enabled.mechanisms>>

| SaslKerberosServiceNameProp
a| [[SaslKerberosServiceNameProp]] <<kafka-properties.adoc#sasl.kerberos.service.name, sasl.kerberos.service.name>>

| SaslKerberosKinitCmdProp
a| [[SaslKerberosKinitCmdProp]] <<kafka-properties.adoc#sasl.kerberos.kinit.cmd, sasl.kerberos.kinit.cmd>>

| SaslKerberosTicketRenewWindowFactorProp
a| [[SaslKerberosTicketRenewWindowFactorProp]] <<kafka-properties.adoc#sasl.kerberos.ticket.renew.window.factor, sasl.kerberos.ticket.renew.window.factor>>

| SaslKerberosTicketRenewJitterProp
a| [[SaslKerberosTicketRenewJitterProp]] <<kafka-properties.adoc#sasl.kerberos.ticket.renew.jitter, sasl.kerberos.ticket.renew.jitter>>

| SaslKerberosMinTimeBeforeReloginProp
a| [[SaslKerberosMinTimeBeforeReloginProp]] <<kafka-properties.adoc#sasl.kerberos.min.time.before.relogin, sasl.kerberos.min.time.before.relogin>>

| SaslKerberosPrincipalToLocalRulesProp
a| [[SaslKerberosPrincipalToLocalRulesProp]] <<kafka-properties.adoc#sasl.kerberos.principal.to.local.rules, sasl.kerberos.principal.to.local.rules>>

| SaslLoginRefreshWindowFactorProp
a| [[SaslLoginRefreshWindowFactorProp]] <<kafka-properties.adoc#sasl.login.refresh.window.factor, sasl.login.refresh.window.factor>>

| SaslLoginRefreshWindowJitterProp
a| [[SaslLoginRefreshWindowJitterProp]] <<kafka-properties.adoc#sasl.login.refresh.window.jitter, sasl.login.refresh.window.jitter>>

| SaslLoginRefreshMinPeriodSecondsProp
a| [[SaslLoginRefreshMinPeriodSecondsProp]] <<kafka-properties.adoc#sasl.login.refresh.min.period.seconds, sasl.login.refresh.min.period.seconds>>

| SaslLoginRefreshBufferSecondsProp
a| [[SaslLoginRefreshBufferSecondsProp]] <<kafka-properties.adoc#sasl.login.refresh.buffer.seconds, sasl.login.refresh.buffer.seconds>>

| SslProtocolProp
a| [[SslProtocolProp]] <<kafka-properties.adoc#ssl.protocol, ssl.protocol>>

| SslProviderProp
a| [[SslProviderProp]] <<kafka-properties.adoc#ssl.provider, ssl.provider>>

| SslCipherSuitesProp
a| [[SslCipherSuitesProp]] <<kafka-properties.adoc#ssl.cipher.suites, ssl.cipher.suites>>

| SslEnabledProtocolsProp
a| [[SslEnabledProtocolsProp]] <<kafka-properties.adoc#ssl.enabled.protocols, ssl.enabled.protocols>>

| SslKeystoreTypeProp
a| [[SslKeystoreTypeProp]] <<kafka-properties.adoc#ssl.keystore.type, ssl.keystore.type>>

| SslKeystoreLocationProp
a| [[SslKeystoreLocationProp]] <<kafka-properties.adoc#ssl.keystore.location, ssl.keystore.location>>

| SslKeystorePasswordProp
a| [[SslKeystorePasswordProp]] <<kafka-properties.adoc#ssl.keystore.password, ssl.keystore.password>>

| SslKeyPasswordProp
a| [[SslKeyPasswordProp]] <<kafka-properties.adoc#ssl.key.password, ssl.key.password>>

| SslTruststoreTypeProp
a| [[SslTruststoreTypeProp]] <<kafka-properties.adoc#ssl.truststore.type, ssl.truststore.type>>

| SslTruststoreLocationProp
a| [[SslTruststoreLocationProp]] <<kafka-properties.adoc#ssl.truststore.location, ssl.truststore.location>>

| SslTruststorePasswordProp
a| [[SslTruststorePasswordProp]] <<kafka-properties.adoc#ssl.truststore.password, ssl.truststore.password>>

| SslKeyManagerAlgorithmProp
a| [[SslKeyManagerAlgorithmProp]] <<kafka-properties.adoc#ssl.keymanager.algorithm, ssl.keymanager.algorithm>>

| SslTrustManagerAlgorithmProp
a| [[SslTrustManagerAlgorithmProp]] <<kafka-properties.adoc#ssl.trustmanager.algorithm, ssl.trustmanager.algorithm>>

| SslEndpointIdentificationAlgorithmProp
a| [[SslEndpointIdentificationAlgorithmProp]] <<kafka-properties.adoc#ssl.endpoint.identification.algorithm, ssl.endpoint.identification.algorithm>>

| SslSecureRandomImplementationProp
a| [[SslSecureRandomImplementationProp]] <<kafka-properties.adoc#ssl.secure.random.implementation, ssl.secure.random.implementation>>

| SslClientAuthProp
a| [[SslClientAuthProp]] <<kafka-properties.adoc#ssl.client.auth, ssl.client.auth>>

| socketRequestMaxBytes
a| [[socketRequestMaxBytes]] <<kafka-properties.adoc#socket.request.max.bytes, socket.request.max.bytes>>

Used when `SocketServer` is <<kafka-network-SocketServer.adoc#memoryPool, created>> and requested to <<kafka-network-SocketServer.adoc#newProcessor, create a new network processor thread>>

| tokenAuthEnabled
a| [[tokenAuthEnabled]] <<kafka-properties.adoc#delegation.token.master.key, delegation.token.master.key>>

| transactionMaxTimeoutMs
a| [[transactionMaxTimeoutMs]] <<kafka-properties.adoc#transaction.max.timeout.ms, transaction.max.timeout.ms>>

Used exclusively when <<kafka-TransactionCoordinator.adoc#, TransactionCoordinator>> is created

| queuedMaxRequests
a| [[queuedMaxRequests]] <<kafka-properties.adoc#queued.max.requests, queued.max.requests>>

Used exclusively when `SocketServer` is <<kafka-network-SocketServer.adoc#maxQueuedRequests, created>>

| zkConnect
a| [[zkConnect]] <<kafka-properties.adoc#zookeeper.connect, zookeeper.connect>>

Used when:

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkConnectionTimeoutMs
a| [[zkConnectionTimeoutMs]] <<kafka-properties.adoc#zookeeper.connection.timeout.ms, zookeeper.connection.timeout.ms>> when set or <<kafka-properties.adoc#zookeeper.session.timeout.ms, zookeeper.session.timeout.ms>>

Used when:

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkEnableSecureAcls
a| [[zkEnableSecureAcls]] <<kafka-properties.adoc#zookeeper.set.acl, zookeeper.set.acl>>

Used when:

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkMaxInFlightRequests
a| [[zkMaxInFlightRequests]] <<kafka-properties.adoc#zookeeper.max.in.flight.requests, zookeeper.max.in.flight.requests>>

Used when:

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkSessionTimeoutMs
a| [[zkSessionTimeoutMs]] <<kafka-properties.adoc#zookeeper.session.timeout.ms, zookeeper.session.timeout.ms>>

Used when:

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

|===

[[internal-registries]]
.KafkaConfig's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,3",options="header",width="100%"]
|===
| Name
| Description

| dynamicConfig
a| [[dynamicConfig]] <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>> (that could be <<dynamicConfigOverride, provided>> or will be <<kafka-server-DynamicBrokerConfig.adoc#creating-instance, created from scratch>>)

Used when:

* `AdminManager` is requested to <<kafka-server-AdminManager.adoc#describeConfigs, describeConfigs>> (for `BROKER` resources), <<kafka-server-AdminManager.adoc#alterConfigs, alterConfigs>> and <<kafka-server-AdminManager.adoc#configSynonyms, configSynonyms>>

* `BrokerConfigHandler` is requested to <<kafka-server-BrokerConfigHandler.adoc#processConfigChanges, processConfigChanges>>

* `DynamicMetricsReporters` is <<kafka-server-DynamicMetricsReporters.adoc#dynamicConfig, created>>

* `DynamicClientQuotaCallback` is <<kafka-server-DynamicClientQuotaCallback.adoc#reconfigure, reconfigure>>

* `KafkaConfig` is requested to <<addReconfigurable, addReconfigurable>>

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>

|===

=== [[getListeners]] Creating Listeners -- `getListeners` Internal Method

[source, scala]
----
getListeners: Seq[EndPoint]
----

`getListeners` creates the `EndPoints` if defined using link:kafka-properties.adoc#listeners[listeners] Kafka property or defaults to `PLAINTEXT://[hostName]:[port]` (for <<hostName, hostName>> and <<port, port>> Kafka properties).

NOTE: `getListeners` is used when `KafkaConfig` is <<listeners, created>> and for <<getAdvertisedListeners, getAdvertisedListeners>>.

=== [[getNumReplicaAlterLogDirsThreads]] `getNumReplicaAlterLogDirsThreads` Method

[source, scala]
----
getNumReplicaAlterLogDirsThreads: Int
----

`getNumReplicaAlterLogDirsThreads`...FIXME

NOTE: `getNumReplicaAlterLogDirsThreads` is used when...FIXME

=== [[creating-instance]] Creating KafkaConfig Instance

`KafkaConfig` takes the following when created:

* [[props]] Key-value properties
* [[doLog]] `doLog` flag
* [[dynamicConfigOverride]] <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>>

`KafkaConfig` initializes the <<internal-registries, internal registries and counters>>.

=== [[fromProps]] Creating KafkaConfig From Java Properties -- `fromProps` Object Method

[source, scala]
----
fromProps(props: Properties): KafkaConfig // <1>
fromProps(props: Properties, doLog: Boolean): KafkaConfig
fromProps(defaults: Properties, overrides: Properties): KafkaConfig // <2>
fromProps(defaults: Properties, overrides: Properties, doLog: Boolean): KafkaConfig // <3>
----
<1> Seems to be used in tests only
<2> Seems to be used in tests only
<3> Seems to be used in tests only

`fromProps`...FIXME

[NOTE]
====
`fromProps` is used when:

* `KafkaServerStartable` is requested to <<kafka-KafkaServerStartable.adoc#fromProps, create a KafkaServerStartable from Java Properties>>

* `SimpleAclAuthorizer` is requested to `configure` itself
====

=== [[apply]] Creating KafkaConfig -- `apply` Factory Method

[source, scala]
----
apply(props: java.util.Map[_, _]): KafkaConfig
----

`apply` simply creates a <<creating-instance, KafkaConfig>> with the `props` and the <<doLog, doLog>> flag on.

NOTE: `apply` seems to be used in tests only.

=== [[addReconfigurable]] `addReconfigurable` Method

[source, scala]
----
addReconfigurable(reconfigurable: Reconfigurable): Unit
----

`addReconfigurable`...FIXME

NOTE: `addReconfigurable` is used when...FIXME

=== [[validateValues]] `validateValues` Internal Method

[source, scala]
----
validateValues(): Unit
----

`validateValues`...FIXME

NOTE: `validateValues` is used when...FIXME

=== [[getInterBrokerListenerNameAndSecurityProtocol]] `getInterBrokerListenerNameAndSecurityProtocol` Internal Method

[source, scala]
----
getInterBrokerListenerNameAndSecurityProtocol: (ListenerName, SecurityProtocol)
----

`getInterBrokerListenerNameAndSecurityProtocol`...FIXME

NOTE: `getInterBrokerListenerNameAndSecurityProtocol` is used when `KafkaConfig` is requested for <<interBrokerListenerName, interBrokerListenerName>> and <<interBrokerSecurityProtocol, interBrokerSecurityProtocol>>.
