== [[KafkaProducer]] KafkaProducer

`KafkaProducer` is one of the main parts of the public API of Apache Kafka to write Kafka clients that publish records to a Kafka cluster.

`KafkaProducer` is <<creating-instance, created>> when...FIXME

[[internal-registries]]
.KafkaProducer's Internal Properties (e.g. Registries and Counters)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[sender]] `sender`
a| link:kafka-Sender.adoc[Sender] with the following:

* ...FIXME

| [[ioThread]] `ioThread`
a| Thread of execution...FIXME
|===

=== [[configureClusterResourceListeners]] `configureClusterResourceListeners` Internal Method

[source, java]
----
ClusterResourceListeners configureClusterResourceListeners(
  Serializer<K> keySerializer,
  Serializer<V> valueSerializer,
  List<?>... candidateLists)
----

`configureClusterResourceListeners`...FIXME

NOTE: `configureClusterResourceListeners` is used when...FIXME

=== [[creating-instance]] Creating KafkaProducer Instance

`KafkaProducer` takes the following when created:

* FIXME

`KafkaProducer` initializes the <<internal-registries, internal registries and counters>>.
