== [[ConsumerNetworkClient]] ConsumerNetworkClient

`ConsumerNetworkClient` is a high-level Kafka consumer that...FIXME

`ConsumerNetworkClient` is <<creating-instance, created>> for link:kafka-KafkaConsumer.adoc#client[KafkaConsumer] and link:kafka-AdminClient.adoc[AdminClient] (and `WorkerGroupMember`).

[[internal-registries]]
.ConsumerNetworkClient's Internal Properties (e.g. Registries and Counters)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[pendingCompletion]] `pendingCompletion`
|
|===

[[logging]]
[TIP]
====
Enable `DEBUG` logging level for `org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient` logger to see what happens inside.

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient=DEBUG, stdout
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[wakeup]] `wakeup` Method

[source, scala]
----
void wakeup()
----

`wakeup` prints out the following DEBUG message to the logs:

```
Received user wakeup
```

`wakeup` turns the internal <<wakeup, wakeup>> flag on and requests <<client, KafkaClient>> to link:kafka-KafkaClient.adoc#wakeup[wakeup]

NOTE: `wakeup` is used when...FIXME

=== [[ensureFreshMetadata]] `ensureFreshMetadata` Method

CAUTION: FIXME

=== [[send]] `send` Method

CAUTION: FIXME

=== [[pendingRequestCount]] `pendingRequestCount` Method

CAUTION: FIXME

=== [[leastLoadedNode]] `leastLoadedNode` Method

CAUTION: FIXME

=== [[poll]] `poll` Method

[source, java]
----
void poll(long timeout)
void poll(long timeout, long now, PollCondition pollCondition)
void poll(long timeout, long now, PollCondition pollCondition, boolean disableWakeup)
void poll(RequestFuture<?> future)
boolean poll(RequestFuture<?> future, long timeout)
----

`poll`...FIXME

[NOTE]
====
`poll` is used when:

* `KafkaConsumer` link:kafka-KafkaConsumer.adoc#pollOnce[polls once]
* `ConsumerNetworkClient` does <<pollNoWakeup, pollNoWakeup>>, <<awaitMetadataUpdate, awaitMetadataUpdate>>, <<awaitPendingRequests, awaitPendingRequests>>
* `AbstractCoordinator` does `ensureCoordinatorReady` and `joinGroupIfNeeded`
* `ConsumerCoordinator` link:kafka-ConsumerCoordinator.adoc#commitOffsetsSync[commitOffsetsSync] and link:kafka-ConsumerCoordinator.adoc#fetchCommittedOffsets[fetchCommittedOffsets]
* `Fetcher` is requested for link:kafka-Fetcher.adoc#getTopicMetadata[topic metadata] or link:kafka-Fetcher.adoc#retrieveOffsetsByTimes[retrieveOffsetsByTimes]
====

=== [[awaitMetadataUpdate]] `awaitMetadataUpdate` Method

CAUTION: FIXME

=== [[awaitPendingRequests]] `awaitPendingRequests` Method

CAUTION: FIXME

=== [[pollNoWakeup]] `pollNoWakeup` Method

[source, java]
----
void pollNoWakeup()
----

`pollNoWakeup`...FIXME

[NOTE]
====
`pollNoWakeup` is used when:

* `KafkaConsumer` link:kafka-KafkaConsumer.adoc#poll[polls]
* `AbstractCoordinator` does `maybeLeaveGroup`
* `HeartbeatThread` runs
* `ConsumerCoordinator` does `commitOffsetsAsync`
====

=== [[creating-instance]] Creating ConsumerNetworkClient Instance

`ConsumerNetworkClient` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] link:kafka-KafkaClient.adoc[KafkaClient]
* [[metadata]] link:kafka-Metadata.adoc[Metadata]
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[requestTimeoutMs]] `requestTimeoutMs`

`ConsumerNetworkClient` initializes the <<internal-registries, internal registries and counters>>.
