== [[DefaultMetadataUpdater]] DefaultMetadataUpdater

`DefaultMetadataUpdater` is a link:kafka-MetadataUpdater.adoc[MetadataUpdater] that `NetworkClient` uses to...FIXME

[[logging]]
[TIP]
====
Enable `DEBUG` logging level for `org.apache.kafka.clients.NetworkClient` logger to see what happens inside.

Add the following line to `config/tools-log4j.properties` (for Kafka tools):

```
log4j.logger.org.apache.kafka.clients.NetworkClient=DEBUG
```

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.NetworkClient=DEBUG, stdout
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[isUpdateDue]] `isUpdateDue` Method

CAUTION: FIXME

=== [[maybeUpdate]] `maybeUpdate` Internal Method

[source, java]
----
long maybeUpdate(long now, Node node)
----

CAUTION: FIXME

=== [[handleCompletedMetadataResponse]] `handleCompletedMetadataResponse` Callback Method

[source, java]
----
handleCompletedMetadataResponse(RequestHeader requestHeader, long now, MetadataResponse response)
----

NOTE: `handleCompletedMetadataResponse` is a part of link:kafka-MetadataUpdater.adoc#handleCompletedMetadataResponse[MetadataUpdater Contract].

`handleCompletedMetadataResponse` turns <<metadataFetchInProgress, metadataFetchInProgress>> flag off.

`handleCompletedMetadataResponse` takes the link:kafka-MetadataResponse.adoc#cluster[cluster] from the `response`.
