== [[AbstractControlRequest]] AbstractControlRequest

`AbstractControlRequest` is the extension of the <<kafka-common-requests-AbstractRequest.adoc#, AbstractRequest contract>> for <<implementations, requests>> that <<kafka-controller-KafkaController.adoc#, KafkaController>> uses to propage broker and partition state changes to all brokers in a Kafka cluster.

[[implementations]]
.AbstractControlRequests
[cols="30,70",options="header",width="100%"]
|===
| AbstractControlRequest
| Description

| <<kafka-common-requests-LeaderAndIsrRequest.adoc#, LeaderAndIsrRequest>>
| [[LeaderAndIsrRequest]]

| StopReplicaRequest
| [[StopReplicaRequest]]

| <<kafka-common-requests-UpdateMetadataRequest.adoc#, UpdateMetadataRequest>>
| [[UpdateMetadataRequest]]

|===

=== [[creating-instance]] Creating AbstractControlRequest Instance

`AbstractControlRequest` takes the following to be created:

* [[api]] `ApiKeys`
* [[version]] Version
* [[controllerId]] Controller ID
* [[controllerEpoch]] Controller Epoch
* [[brokerEpoch]] Broker Epoch

`AbstractControlRequest` initializes the <<internal-properties, internal properties>>.

NOTE: `AbstractControlRequest` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractControlRequests>>.
