== [[ZkUtils]] ZkUtils

`ZkUtils` is...FIXME

=== [[subscribeChildChanges]] `subscribeChildChanges` Method

[source, scala]
----
subscribeChildChanges(path: String, listener: IZkChildListener): Option[Seq[String]]
----

`subscribeChildChanges`...FIXME

NOTE: `subscribeChildChanges` is used...FIXME

=== [[registerBrokerInZk]] `registerBrokerInZk` Method

[source, scala]
----
registerBrokerInZk(
  id: Int,
  host: String,
  port: Int,
  advertisedEndpoints: Seq[EndPoint],
  jmxPort: Int,
  rack: Option[String],
  apiVersion: ApiVersion): Unit
----

`registerBrokerInZk`...FIXME

NOTE: `registerBrokerInZk` is used exclusively when `KafkaHealthcheck` is requested to link:kafka-KafkaHealthcheck.adoc#register[register].

=== [[getTopicPartitionCount]] `getTopicPartitionCount` Method

[source, scala]
----
getTopicPartitionCount(topic: String): Option[Int]
----

`getTopicPartitionCount`...FIXME

[NOTE]
====
`getTopicPartitionCount` is used when:

1. `GroupMetadataManager` is requested for link:kafka-GroupMetadataManager.adoc#getGroupMetadataTopicPartitionCount[getGroupMetadataTopicPartitionCount] of `__consumer_offsets` topic

1. `TransactionStateManager` is requested for link:kafka-TransactionStateManager.adoc#getTransactionTopicPartitionCount[getTransactionTopicPartitionCount] of `__transaction_state` topic
====

=== [[controllerZkData]] Creating JSON with Broker ID -- `controllerZkData` Method

[source, scala]
----
controllerZkData(brokerId: Int, timestamp: Long): String
----

`controllerZkData` creates a JSON with the following fields:

* `"version":1`
* `"brokerid":[brokerId]`
* `"timestamp":[timestamp]`

[source, scala]
----
import kafka.utils._
scala> ZkUtils.controllerZkData(1, System.currentTimeMillis())
res0: String = {"version":1,"brokerid":1,"timestamp":"1506161225262"}
----

NOTE: `controllerZkData` is used exclusively when `KafkaController` is requested for link:kafka-KafkaController.adoc#elect[elect].
