== [[PartitionStateMachine]] PartitionStateMachine

`PartitionStateMachine` is the <<contract, base>> of <<extensions, Partition State Machines>> that can <<handleStateChanges, handleStateChanges>>, be <<startup, started up>> and <<shutdown, shut down>> in the end.

[[contract]]
.PartitionStateMachine Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| handleStateChanges
a| [[handleStateChanges]]

[source, scala]
----
handleStateChanges(
  partitions: Seq[TopicPartition],
  targetState: PartitionState,
  leaderElectionStrategy: Option[PartitionLeaderElectionStrategy]
): Map[TopicPartition, Throwable]
----

Handles state changes of partitions (_partition state changes_)

<<PartitionLeaderElectionStrategy, PartitionLeaderElectionStrategy>> is undefined (`None`) by default

Used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onReplicasBecomeOffline, onReplicasBecomeOffline>>, <<kafka-controller-KafkaController.adoc#onNewPartitionCreation, onNewPartitionCreation>>, <<kafka-controller-KafkaController.adoc#onNewPartitionCreation, onNewPartitionCreation>>, <<kafka-controller-KafkaController.adoc#onPreferredReplicaElection, onPreferredReplicaElection>>, <<kafka-controller-KafkaController.adoc#moveReassignedPartitionLeaderIfRequired, moveReassignedPartitionLeaderIfRequired>>, and <<kafka-controller-KafkaController.adoc#doControlledShutdown, doControlledShutdown>>

* `PartitionStateMachine` is requested to <<triggerOnlineStateChangeForPartitions, triggerOnlineStateChangeForPartitions>>

* `TopicDeletionManager` is requested to <<kafka-controller-TopicDeletionManager.adoc#onTopicDeletion, onTopicDeletion>>

|===

[[implementations]]
NOTE: <<kafka-controller-ZkPartitionStateMachine.adoc#, ZkPartitionStateMachine>> is the default and only known implementation of the <<contract, PartitionStateMachine Contract>> in Apache Kafka.

[[creating-instance]][[controllerContext]]
`PartitionStateMachine` takes a single <<kafka-controller-ControllerContext.adoc#, ControllerContext>> to be created.

NOTE: `PartitionStateMachine` is a Scala abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete PartitionStateMachines>>.

=== [[PartitionLeaderElectionStrategy]] PartitionLeaderElectionStrategy

.PartitionLeaderElectionStrategies
[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| ControlledShutdownPartitionLeaderElectionStrategy
a| [[ControlledShutdownPartitionLeaderElectionStrategy]]

| OfflinePartitionLeaderElectionStrategy
a| [[OfflinePartitionLeaderElectionStrategy]] Accepts `allowUnclean` flag

Handled by `ZkPartitionStateMachine` when requested to link:kafka-controller-ZkPartitionStateMachine.adoc#doElectLeaderForPartitions[doElectLeaderForPartitions]

Used when:

* `KafkaController` is requested to link:kafka-controller-KafkaController.adoc#onNewPartitionCreation[onNewPartitionCreation] (with the `allowUnclean` flag off), link:kafka-controller-KafkaController.adoc#onReplicaElection[onReplicaElection] (with the `allowUnclean` flag on for the admin client)

* `PartitionStateMachine` is requested to <<triggerOnlineStateChangeForPartitions, triggerOnlineStateChangeForPartitions>> (with the `allowUnclean` flag off)

| PreferredReplicaPartitionLeaderElectionStrategy
a| [[PreferredReplicaPartitionLeaderElectionStrategy]] `KafkaController` is requested for <<kafka-controller-KafkaController.adoc#onPreferredReplicaElection, preferred replica leader election>> that in turn triggers `ZkPartitionStateMachine` to <<kafka-controller-ZkPartitionStateMachine.adoc#leaderForPreferredReplica, leaderForPreferredReplica>>

| ReassignPartitionLeaderElectionStrategy
a| [[ReassignPartitionLeaderElectionStrategy]]

|===

=== [[triggerOnlinePartitionStateChange]] `triggerOnlinePartitionStateChange` Method

[source, scala]
----
triggerOnlinePartitionStateChange(): Unit
triggerOnlinePartitionStateChange(
  topic: String): Unit // <1>
----
<1> Uses the partitions of the given topic only

`triggerOnlinePartitionStateChange` requests the <<controllerContext, ControllerContext>> for the link:kafka-controller-ControllerContext.adoc#partitionsInStates[partitions in the states]: `OfflinePartition` and `NewPartition`.

With the topic specified, `triggerOnlinePartitionStateChange` requests the <<controllerContext, ControllerContext>> for the link:kafka-controller-ControllerContext.adoc#partitionsInStates[partitions of the topic in the states]: `OfflinePartition` and `NewPartition`.

In the end, `triggerOnlinePartitionStateChange` <<triggerOnlineStateChangeForPartitions, triggers online state change for the partitions>>.

[NOTE]
====
`triggerOnlinePartitionStateChange` is used when:

* `KafkaController` is requested to link:kafka-controller-KafkaController.adoc#onBrokerStartup[onBrokerStartup], link:kafka-controller-KafkaController.adoc#onReplicasBecomeOffline[onReplicasBecomeOffline], link:kafka-controller-KafkaController.adoc#processUncleanLeaderElectionEnable[processUncleanLeaderElectionEnable], link:kafka-controller-KafkaController.adoc#processTopicUncleanLeaderElectionEnable[processTopicUncleanLeaderElectionEnable]

* `PartitionStateMachine` is requested to <<startup, start up>>
====

=== [[triggerOnlineStateChangeForPartitions]] `triggerOnlineStateChangeForPartitions` Internal Method

[source, scala]
----
triggerOnlineStateChangeForPartitions(
  partitions: collection.Set[TopicPartition]): Unit
----

`triggerOnlineStateChangeForPartitions` filters out the partitions of the link:kafka-controller-ControllerContext.adoc#isTopicQueuedUpForDeletion[topics to be deleted] and tries to <<handleStateChanges, move the partitions>> to `OnlinePartition` state with <<OfflinePartitionLeaderElectionStrategy, OfflinePartitionLeaderElectionStrategy>> (with `allowUnclean` flag off).

NOTE: `triggerOnlineStateChangeForPartitions` is used when `PartitionStateMachine` is requested to <<triggerOnlinePartitionStateChange, triggerOnlinePartitionStateChange>>.

=== [[shutdown]] Shutting Down -- `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

`shutdown` simply prints out the following INFO message to the logs:

```
Stopped partition state machine
```

NOTE: `shutdown` is used exclusively when is requested to <<kafka-controller-KafkaController.adoc#onControllerResignation, resign as the active controller>>

=== [[startup]] Starting Up (On Active Controller) -- `startup` Method

[source, scala]
----
startup(): Unit
----

`startup` prints out the following INFO message to the logs:

```
Initializing partition state
```

`startup` <<initializePartitionState, initializePartitionState>>.

`startup` prints out the following INFO message to the logs:

```
Triggering online partition state changes
```

`startup` <<triggerOnlinePartitionStateChange, triggerOnlinePartitionStateChange>>.

In the end, `startup` prints out the following INFO message to the logs:

```
Started partition state machine with initial state -> [partitionStates]
```

NOTE: `startup` is used exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>> (when a broker is successfully elected as the controller).

=== [[initializePartitionState]] `initializePartitionState` Internal Method

[source, scala]
----
initializePartitionState(): Unit
----

`initializePartitionState` requests the <<controllerContext, ControllerContext>> for <<kafka-controller-ControllerContext.adoc#allPartitions, all partitions>> (across all the brokers in the Kafka cluster).

For every `TopicPartition`, `initializePartitionState` requests the <<controllerContext, ControllerContext>> for the `LeaderIsrAndControllerEpoch` metadata (using the <<kafka-controller-ControllerContext.adoc#partitionLeadershipInfo, partitionLeadershipInfo>> internal registry).

`initializePartitionState` <<changeStateTo, changeStateTo>> of a `TopicPartition` as follows:

* `OnlinePartition` when the <<controllerContext, ControllerContext>> says that the <<kafka-controller-ControllerContext.adoc#isReplicaOnline, replica is online>> (for the leader ISR and the `TopicPartition`)

* `OfflinePartition` when the <<controllerContext, ControllerContext>> says that the <<kafka-controller-ControllerContext.adoc#isReplicaOnline, replica is not online>> (for the leader ISR and the `TopicPartition`)

* `NewPartition` when the <<controllerContext, ControllerContext>> has no metadata about the `TopicPartition`

NOTE: `initializePartitionState` is used exclusively when `PartitionStateMachine` is requested to <<startup, start up on the active controller>>.
