== [[Authorizer]] Authorizer

`Authorizer` is the <<contract, abstraction>> of <<implementations, authorizers>> that can <<authorize, authorize a principal to perform an operation on a resource>>.

`Authorizer` is a <<kafka-common-Configurable.adoc#, Configurable>> and can <<kafka-common-Configurable.adoc#configure, take configuration parameters>> when instantiated (by reflection).

A concrete <<implementations, authorizer>> is used for authorization (in <<kafka-server-KafkaApis.adoc#authorize, KafkaApis>>) per <<kafka-properties.adoc#authorizer.class.name, authorizer.class.name>> configuration property.

[[implementations]]
NOTE: <<kafka-security-SimpleAclAuthorizer.adoc#, SimpleAclAuthorizer>> is the only known `Authorizer` in Apache Kafka.

[[contract]]
.Authorizer Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| addAcls
a| [[addAcls]]

[source, scala]
----
addAcls(
  acls: Set[Acl],
  resource: Resource): Unit
----

Adds ACLs for a resource

Used when:

* `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleCreateAcls, handle a CreateAcls request>>

* `AclCommand` administration utility is requested to <<kafka-admin-AclCommand.adoc#add, add an ACL>>

| authorize
a| [[authorize]]

[source, scala]
----
authorize(
  session: Session,
  operation: Operation,
  resource: Resource): Boolean
----

Authorizes a principal to perform an operation on a resource

Used when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#authorize, authorize a principal for an operation on a resource>>

| close
a| [[close]]

[source, scala]
----
close(): Unit
----

Closes the authorizer

Used when:

* `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#shutdown, shut down>>

* `AclCommand` administration utility is requested to <<kafka-admin-AclCommand.adoc#add, add>>, <<kafka-admin-AclCommand.adoc#remove, remove>>, and <<kafka-admin-AclCommand.adoc#list, list>> ACLs

| getAcls
a| [[getAcls]]

[source, scala]
----
getAcls(): Map[Resource, Set[Acl]]
getAcls(
  principal: KafkaPrincipal): Map[Resource, Set[Acl]]
getAcls(
  resource: Resource): Set[Acl]
----

Gets ACLs (all, for a principal or a resource)

Used when:

* `AclCommand` administration utility is executed

* `KafkaApis` is requested to handle <<kafka-server-KafkaApis.adoc#handleDescribeAcls, DescribeAcls>> and <<handleDeleteAcls, DeleteAcls>> requests

| removeAcls
a| [[removeAcls]]

[source, scala]
----
removeAcls(
  resource: Resource): Boolean
removeAcls(
  acls: Set[Acl],
  resource: Resource): Boolean
----

Removes ACLs on a resource

Used when:

* `AclCommand` administration utility is requested to <<kafka-admin-AclCommand.adoc#remove, remove ACLs>>

* `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#handleDeleteAcls, handle a DeleteAcls request>>

|===
