== Demo: SSL Authentication

The demo shows how to use SSL/TLS for authentication so no connection can be established between Kafka clients (consumers and producers) and brokers unless a valid certificate is provided.

NOTE: The demo is a follow-up to link:kafka-demo-securing-communication-between-clients-and-brokers.adoc[Demo: Securing Communication Between Clients and Brokers Using SSL]. Please finish it first before this demo.

The demo is made up of the following steps:

. <<step-1, Generate Certificate for Client Authentication>>
. <<step-2, Sign Client Certificate (Using CA)>>
. <<step-3, Import Certificates to Client Keystore>>
. <<step-4, Import CA Certificate to Broker Truststore>>
. <<step-5, Require Client Authorization Using SSL on Kafka Brokers>>
. <<step-6, Configure SSL Authentication for Kafka Client>>

=== [[step-1]] Generate Certificate for Client Authentication

Generate the keys and certificate of a Kafka client to be authenticated as *jacek*.

```
$ keytool \
  -genkey \
  -keystore jacek.keystore \
  -alias jacek \
  -dname CN=jacek \
  -keyalg RSA \
  -validity 365
Enter keystore password: 123456
Re-enter new password: 123456
```

You should now have one more file in the directory:

* `jacek.keystore`

Use `keytool` to print out the content of the keystore.

```
keytool -list -v -keystore jacek.keystore
```

=== [[step-2]] Sign Client Certificate (Using CA)

Create a certificate signing request (CSR).

Export the client certificate from `jacek.keystore`.

```
$ keytool \
  -certreq \
  -keystore jacek.keystore \
  -alias jacek \
  -file jacek.unsigned.crt
Enter keystore password: 123456
```

Sign the certificate signing request (`jacek.unsigned.crt`) with the root CA.

```
$ openssl x509 \
  -req \
  -CA ca.crt \
  -CAkey ca.key \
  -in jacek.unsigned.crt \
  -out jacek.crt \
  -days 365 \
  -CAcreateserial
Signature ok
subject=CN = jacek
Getting CA Private Key
Enter pass phrase for ca.key: 1234
```

You should have the following file in the directory:

* `jacek.crt`

=== [[step-3]] Import Certificates to Client Keystore

Create a SSL keystore for the Kafka client. Each client gets its own unique keystore.

Import the certificate of the CA into the client keystore.

```
$ keytool \
  -import \
  -file ca.crt \
  -keystore jacek.keystore \
  -alias ca
Enter keystore password: 123456
Owner: CN=ca, O=Japila.PL, L=Warsaw, C=PL
Issuer: CN=ca, O=Japila.PL, L=Warsaw, C=PL

...removed for clarity

Trust this certificate? [no]:  yes
Certificate was added to keystore
```

Import the signed client certificate into the keystore.

```
$ keytool \
  -import \
  -file jacek.crt \
  -keystore jacek.keystore \
  -alias jacek
Enter keystore password: 123456
Certificate reply was installed in keystore
```

Use `keytool` to print out the certificates in the keystore.

```
keytool -list -v -keystore jacek.keystore
```

There should be 2 entries (one for the CA and another for the client itself).

=== [[step-4]] Import CA Certificate to Broker Truststore

Import the CA certificate to a broker truststore. All brokers in a Kafka cluster should trust the CA used to sign client certificates.

```
$ keytool \
  -importcert \
  -keystore server.truststore \
  -alias ca \
  -file ca.crt
Enter keystore password: 123456
Re-enter new password: 123456
Owner: CN=ca, O=Japila.PL, L=Warsaw, C=PL
Issuer: CN=ca, O=Japila.PL, L=Warsaw, C=PL

...removed for clarity

Trust this certificate? [no]:  yes
Certificate was added to keystore
```

Add the following configuration property to `config/server-ssl.properties`:

```
ssl.truststore.location=/tmp/kafka-ssl-demo/server.truststore
ssl.truststore.password=123456
```

=== [[step-5]] Require Client Authorization Using SSL on Kafka Brokers

Enable SSL authentication (require client authentication using SSL certificates).

Add the following configuration property to `config/server-ssl.properties`:

```
ssl.client.auth=required
```

Start the broker(s).

```
./bin/kafka-server-start.sh config/server-ssl.properties
```

TIP: Use `export KAFKA_OPTS=-Djavax.net.debug=all` to debug SSL-related issues.

Verify the SSL configuration of the broker. The following uses the Cryptography and SSL/TLS Toolkit (OpenSSL) and the client tool.

```
openssl s_client -connect localhost:9093
```

Enter `Ctrl-C` to close the session.

=== [[step-6]] Configure SSL Authentication for Kafka Client

Use the following `jacek-client.properties` as a minimal configuration of a Kafka client to use SSL authentication:

```
security.protocol=SSL
ssl.truststore.location=/tmp/kafka-ssl-demo/client.truststore
ssl.truststore.password=123456
ssl.keystore.location=/tmp/kafka-ssl-demo/jacek.keystore
ssl.keystore.password=123456
ssl.key.password=123456
```

Use `kafka-console-producer.sh` utility to send records to Kafka brokers over SSL:

```
kafka-console-producer.sh \
  --broker-list :9093 \
  --topic ssl \
  --producer.config /tmp/kafka-ssl-demo/jacek-client.properties
```

TIP: Use `export KAFKA_OPTS=-Djavax.net.debug=all` to debug SSL issues. Consult the source code of Java's https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/src/java.base/share/classes/sun/security/ssl/SSLLogger.java[SSLLogger].
