== [[Cluster]] Cluster

`Cluster` represents a subset of the nodes and topic partitions in a Kafka cluster.

NOTE: `org.apache.kafka.common.Cluster` is a `public final` class.

A special variant of a cluster is *boostrap cluster* that is made up of the <<bootstrap, bootstrap brokers>> that are mandatory (and specified explicitly) when Kafka clients are created, i.e. link:kafka-clients-admin-KafkaAdminClient.adoc#creating-instance[KafkaAdminClient], link:kafka-clients-admin-AdminClient.adoc#create[AdminClient], link:kafka-consumer-KafkaConsumer.adoc#creating-instance[KafkaConsumer] and link:kafka-producer-KafkaProducer.adoc#creating-instance[KafkaProducer].

NOTE: A bootstrap cluster does not hold all information about the cluster.

`Cluster` is <<creating-instance, created>> when:

* `AdminMetadataManager` is requested to <<kafka-clients-admin-internals-AdminMetadataManager.adoc#clearController, clearController>>

* `Cluster` is requested to create an <<empty, empty Cluster metadata>> and <<withPartitions, Cluster metadata with given partitions>>, and <<bootstrap, bootstrap>>

* `MetadataCache` is requested to <<kafka-server-MetadataCache.adoc#getClusterMetadata, getClusterMetadata>>

* `Metadata` is requested to <<kafka-clients-Metadata.adoc#getClusterForCurrentTopics, getClusterForCurrentTopics>>

* `MetadataResponse` is requested to <<kafka-common-requests-MetadataResponse.adoc#cluster, cluster>>

[[internal-registries]]
.Cluster's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[isBootstrapConfigured-flag]] `isBootstrapConfigured`
| Flag...FIXME

Used when...FIXME

| [[partitionsByTopic]] `partitionsByTopic`
|
|===

=== [[bootstrap]] `bootstrap` Factory Method

[source, java]
----
static Cluster bootstrap(List<InetSocketAddress> addresses)
----

`bootstrap`...FIXME

NOTE: `bootstrap` is used when <<kafka-clients-admin-KafkaAdminClient.adoc#, KafkaAdminClient>>, <<kafka-consumer-KafkaConsumer.adoc#, KafkaConsumer>> and <<kafka-producer-KafkaProducer.adoc#, KafkaProducer>> are created (and update their internal metadata).

=== [[isBootstrapConfigured]] `isBootstrapConfigured` Method

[source, java]
----
boolean isBootstrapConfigured()
----

`isBootstrapConfigured` gives <<isBootstrapConfigured-flag, isBootstrapConfigured>> internal flag.

NOTE: `isBootstrapConfigured` is used when...FIXME

=== [[partitionsForTopic]] Getting Partitions for Topic -- `partitionsForTopic` Method

[source, java]
----
List<PartitionInfo> partitionsForTopic(String topic)
----

`partitionsForTopic` returns a collection of zero or more partition of the input `topic` from <<partitionsByTopic, partitionsByTopic>> internal lookup table.

[NOTE]
====
`partitionsForTopic` is used when:

* `Metadata` link:kafka-clients-Metadata.adoc#getClusterForCurrentTopics[getClusterForCurrentTopics]
* `KafkaAdminClient` link:kafka-clients-admin-KafkaAdminClient.adoc#describeTopics[describeTopics]
* `KafkaConsumer` link:kafka-consumer-KafkaConsumer.adoc#partitionsFor[partitionsFor]
* `KafkaProducer` link:kafka-producer-KafkaProducer.adoc#partitionsFor[requests partitions for a topic]
* `DefaultPartitioner` link:kafka-producer-internals-DefaultPartitioner.adoc#partition[assigns the partition for a record]
====

=== [[availablePartitionsForTopic]] `availablePartitionsForTopic` Method

[source, java]
----
List<PartitionInfo> availablePartitionsForTopic(String topic)
----

`availablePartitionsForTopic`...FIXME

NOTE: `availablePartitionsForTopic` is used when...FIXME

=== [[creating-instance]] Creating Cluster Instance

`Cluster` takes the following when created:

* [[clusterId]] *Cluster ID*
* [[isBootstrapConfigured]] `isBootstrapConfigured` flag
* [[nodes]] Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/Node.html[Nodes] (`Collection<Node>`)
* [[partitions]] Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/PartitionInfo.html[PartitionInfos] (`Collection<PartitionInfo>`)
* [[unauthorizedTopics]] Names of the *unauthorized topics*
* [[invalidTopics]] Names of the *invalid topics*
* [[internalTopics]] Names of the *internal topics*
* [[controller]] *Controller* (as a Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/Node.html[Node])

`Cluster` initializes the <<internal-registries, internal registries and counters>>.

=== [[empty]] Creating Empty Cluster Metadata -- `empty` Factory Method

[source, java]
----
static Cluster empty()
----

`empty`...FIXME

[NOTE]
====
`empty` is used when:

* `Metadata` is <<kafka-clients-Metadata.adoc#cluster, created>>

* `AdminMetadataManager` is <<kafka-clients-admin-internals-AdminMetadataManager.adoc#cluster, created>>
====

=== [[withPartitions]] Creating Cluster Metadata With Given Partitions -- `withPartitions` Method

[source, java]
----
Cluster withPartitions(Map<TopicPartition, PartitionInfo> partitions)
----

`withPartitions`...FIXME

`withPartitions` is used exclusively when Kafka Streams' `StreamsPartitionAssignor` is requested to `assign` and `onAssignment`.
