== Demo: ACL Authorization Using AclAuthorizer

This demo shows how to use link:kafka-security-authorizer-AclAuthorizer.adoc[AclAuthorizer] for link:kafka-security-authorization.adoc[ACL authorization].

CAUTION: The demo is not finished yet.

=== Step X. Enable ACL Authorization

Add the following to `config/server.properties`:

```
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
```

Start a Kafka broker and observe the logs. You may find the following at the very end of the startup:

```
ERROR [KafkaApi-0] Error when handling request: clientId=0, correlationId=0, api=UPDATE_METADATA, version=6, body={controller_id=0,controller_epoch=5,broker_epoch=151,topic_states=[],live_brokers=[{id=0,endpoints=[{port=9092,host=localhost,listener=PLAINTEXT,security_protocol=0,_tagged_fields={}}],rack=null,_tagged_fields={}}],_tagged_fields={}} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=0, connectionId=127.0.0.1:9092-127.0.0.1:64483-0, session=Session(User:ANONYMOUS,/127.0.0.1), listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT, buffer=null) is not authorized.
```

That's because `User:ANONYMOUS` user is not authorized to execute `UPDATE_METADATA` action (since by default no one is allowed to execute any action).

=== Step X. Allow Everyone If No ACL Found

Add the following to `config/server.properties` and restart the broker.

```
allow.everyone.if.no.acl.found=true
```

=== Step X. Define Super Users

Add the following to `config/server.properties` and restart the broker.

```
super.users=User:Bob;User:Alice
```

=== Step X. List ACLs

Use link:kafka-tools-kafka-acls.adoc[kafka-acls] CLI to list the available ACLs.

```
kafka-acls.sh \
  --bootstrap-server :9092 \
  --list
```

=== Step X. Disable Creating Topics

Use link:kafka-tools-kafka-acls.adoc[kafka-acls] CLI to disable creating topics for anyone but super users.

```
kafka-acls.sh \
  --bootstrap-server :9092 \
  --add \
  --allow-principal User:Alice \
  --operation All \
  --topic '*' \
  --cluster
```

=== Step X. Setting Up TLS/SSL

Create a directory for SSL-related files.

```
mkdir -p /tmp/kafka-ssl
```

All the following commands are executed in the directory.

```
cd /tmp/kafka-ssl
```

Generate a private key for the CA.

```
openssl genrsa -out ca.key
```

Generating a self-signed root CA.

```
openssl req -new -x509 -key ca.key -out ca.crt
```

Generate the private key for the server.

```
openssl genrsa -out server.key
```

Create a certificate request.

```
openssl req -new -key server.key -out server_reqout.txt
```

Sign the certificate request with the root CA.

```
openssl x509 \
  -req \
  -in server_reqout.txt \
  -days 3650 \
  -sha1 \
  -CAcreateserial \
  -CA ca.crt \
  -CAkey ca.key \
  -out server.crt
```

```
openssl genrsa -out client.key
openssl req -new -key client.key -out client_reqout.txt
openssl x509 \
  -req \
  -in client_reqout.txt \
  -days 3650 \
  -sha1 \
  -CAcreateserial \
  -CA ca.crt \
  -CAkey ca.key \
  -out client.crt
```

Create a truststore file for Kafka brokers (with the root CA).

```
keytool \
  -keystore kafka.truststore.jks \
  -alias CARoot \
  -import \
  -file ca.crt
```

Create a keystore file for the Kafka broker named `kafka01`. Each broker gets its own unique keystore.

```
keytool \
  -keystore kafka01.keystore.jks \
  -alias localhost \
  -validity 365 \
  -genkey \
  -keyalg RSA \
  -ext SAN=DNS:kafka01.japila.pl
```

Export the Kafka broker's certificate so it can be signed by the root CA.

```
keytool \
  -keystore kafka01.keystore.jks \
  -alias localhost \
  -certreq \
  -file kafka01.unsigned.crt
```

Sign the Kafka broker's certificate using the root CA.

```
openssl x509 \
  -req \
  -CA ca.crt \
  -CAkey ca.key \
  -in kafka01.unsigned.crt \
  -out kafka01.signed.crt \
  -days 365 \
  -CAcreateserial
```

Import the root CA into the broker's keystore.

```
keytool \
  -keystore kafka01.keystore.jks \
  -alias CARoot \
  -import \
  -file ca.crt
```

Import the signed Kafka broker certificate into the keystore.

```
keytool \
  -keystore kafka01.keystore.jks \
  -alias localhost \
  -import \
  -file kafka01.signed.crt
```

=== Step X. Setting Up TLS/SSL

Configure a Kafka broker to use the keystore and truststore files.

Edit `config/server.properties` to include the following properties:

```
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=true
super.users=User:Bob;User:Alice

listeners=PLAINTEXT://:9092,SSL://:9093
ssl.keystore.location=/tmp/kafka-ssl/kafka01.keystore.jks
ssl.keystore.password=123456
ssl.key.password=123456
ssl.truststore.location=/tmp/kafka-ssl/kafka.truststore.jks
ssl.truststore.password=123456
ssl.client.auth=required
```

Test the Kafka configuration.

```
openssl s_client -debug -connect localhost:9093 -tls1
```

Exit out of this command using `Ctrl+C`.

=== Step X. Using SSL for Client Authentication

Create the client keystore.

```
keytool \
  -keystore client.keystore.jks \
  -alias localhost \
  -validity 365 \
  -genkey \
  -keyalg RSA \
  -ext SAN=DNS:client
```

Export the client certificate.

```
keytool \
  -keystore client.keystore.jks \
  -alias localhost \
  -certreq \
  -file client.unsigned.cert
```

Sign the client certificate with the root CA.

```
openssl x509 \
  -req \
  -CA ca.crt \
  -CAkey ca.key \
  -in client.unsigned.cert \
  -out client.signed.cert \
  -days 365 \
  -CAcreateserial
```

Add the root CA to the client keystore.

```
keytool -keystore client.keystore.jks -alias CARoot -import -file ca.crt
```

Add the signed client certificate to the keystore.

```
keytool -keystore client.keystore.jks -alias localhost -import -file client.signed.cert
```

Create `client-ssl.properties` configuration file.

```
security.protocol=SSL
ssl.truststore.location=/tmp/kafka-ssl/kafka.truststore.jks
ssl.truststore.password=123456
ssl.keystore.location=/tmp/kafka-ssl/client.keystore.jks
ssl.keystore.password=123456
ssl.key.password=123456
ssl.client.auth=required
```

Use `kafka-console-producer.sh` to send a message to the Kafka broker using SSL.

```
kafka-console-producer.sh \
  --broker-list :9093 \
  --topic test \
  --producer.config /tmp/kafka-ssl/client-ssl.properties
```
