== [[Fetcher]] Fetcher

CAUTION: FIXME

=== [[sendMetadataRequest]] `sendMetadataRequest` Internal Method

CAUTION: FIXME

=== [[beginningOffsets]] `beginningOffsets` Method

CAUTION: FIXME

=== [[retrieveOffsetsByTimes]] `retrieveOffsetsByTimes` Method

CAUTION: FIXME

=== [[getTopicMetadata]] Getting Topics Metadata -- `getTopicMetadata` Method

[source, java]
----
Map<String, List<PartitionInfo>> getTopicMetadata(MetadataRequest.Builder request, long timeout)
----

Internally, `getTopicMetadata` <<sendMetadataRequest, sends the metadata request>> and requests <<client, ConsumerNetworkClient>> to link:kafka-ConsumerNetworkClient.adoc#poll[poll] until it finishes successfully or `timeout` expires.

After `poll` finishes, `getTopicMetadata` link:kafka-MetadataResponse.adoc#cluster[takes the cluster information] from `MetadataResponse`.

When `MetadataResponse` is successful, `getTopicMetadata` link:kafka-Cluster.adoc#topics[takes topics] (from `Cluster`) and requests `Cluster` for link:kafka-Cluster.adoc#availablePartitionsForTopic[available partitions for every topic].

In the end, `getTopicMetadata` creates a collection of topic and partitions pairs.

CAUTION: FIXME Describe the failure path

[NOTE]
====
`getTopicMetadata` is used when:

* `Fetcher` is requested to <<getAllTopicMetadata, find metadata for all topics>>
* `KafkaConsumer` is requested to link:kafka-KafkaConsumer.adoc#partitionsFor[find partitions for a topic].
====

=== [[getAllTopicMetadata]] Finding Metadata for All Topics -- `getAllTopicMetadata` Method

[source, scala]
----
Map<String, List<PartitionInfo>> getAllTopicMetadata(long timeout)
----

`getAllTopicMetadata` <<getTopicMetadata, gets topic metadata>> specifying no topics (which means all topics available).

NOTE: `getAllTopicMetadata` is used exclusively when `KafkaConsumer` link:kafka-KafkaConsumer.adoc#listTopics[requests metadata for all topics].
