== [[AbstractCoordinator]] AbstractCoordinator Contract

`AbstractCoordinator` is the <<contract, base>> of <<extensions, Coordinators>> that <<FIXME, FIXME>>.

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

[[extensions]]
NOTE: <<kafka-consumer-internals-ConsumerCoordinator.adoc#, ConsumerCoordinator>> is the one and only known implementation of the <<contract, AbstractCoordinator Contract>> in Apache Kafka's Consumer API.

[[contract]]
.AbstractCoordinator Contract (Abstract Methods Only)
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| metadata
a| [[metadata]]

[source, java]
----
List<ProtocolMetadata> metadata()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, send a JoinGroupRequest to the group coordinator>>

| onJoinComplete
a| [[onJoinComplete]]

[source, java]
----
void onJoinComplete(
  int generation,
  String memberId,
  String protocol,
  ByteBuffer memberAssignment)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the request to <<initiateJoinGroup, initiateJoinGroup>> succeeded)

| onJoinPrepare
a| [[onJoinPrepare]]

[source, java]
----
void onJoinPrepare(
  int generation,
  String memberId)
----

Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the <<needsJoinPrepare, needsJoinPrepare>> flag is on)

| performAssignment
a| [[performAssignment]]

[source, java]
----
Map<String, ByteBuffer> performAssignment(
  String leaderId,
  String protocol,
  Map<String, ByteBuffer> allMemberMetadata)
----

Performs partition assignment (i.e. assigns partitions to the members of a consumer group)

Used exclusively when `AbstractCoordinator` is requested to <<onJoinLeader, perform partition assignment and notify the group coordinator>>

| protocolType
a| [[protocolType]]

[source, java]
----
String protocolType()
----

Used exclusively when `AbstractCoordinator` is requested to <<sendJoinGroupRequest, send a JoinGroupRequest to the group coordinator>>

|===

[[internal-registries]]
.AbstractCoordinator's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| coordinator
a| [[coordinator]] Group Coordinator (as a Kafka https://kafka.apache.org/21/javadoc/org/apache/kafka/common/Node.html[Node])

Initialized when `FindCoordinatorResponseHandler` is requested to <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onSuccess, onSuccess>>

| findCoordinatorFuture
| [[findCoordinatorFuture]] <<kafka-consumer-internals-RequestFuture.adoc#, ++RequestFuture<Void>++>> for <<sendFindCoordinatorRequest, sendFindCoordinatorRequest>> when <<lookupCoordinator, lookupCoordinator>>

Reset in <<clearFindCoordinatorFuture, clearFindCoordinatorFuture>>

Used in <<lookupCoordinator, lookupCoordinator>> and when `HeartbeatThread` is requested to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#run, run>>

| generation
a| [[generation]] Defaults to `NO_GENERATION`

| heartbeatThread
a| [[heartbeatThread]] <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#, HeartbeatThread>>

Initialized and immediately started when `AbstractCoordinator` is requested to <<startHeartbeatThreadIfNeeded, start a HeartbeatThread>>

| joinFuture
| [[joinFuture]] <<kafka-consumer-internals-RequestFuture.adoc#, ++RequestFuture<ByteBuffer>++>> for <<sendJoinGroupRequest, sending a JoinGroupRequest to the group coordinator>> when <<initiateJoinGroup, initiateJoinGroup>>

Reset in <<resetJoinGroupFuture, resetJoinGroupFuture>>

Used in <<rejoinNeededOrPending, rejoinNeededOrPending>> and <<initiateJoinGroup, initiateJoinGroup>>

| needsJoinPrepare
| [[needsJoinPrepare]] Flag to control whether to execute <<onJoinPrepare, onJoinPrepare>> while performing <<joinGroupIfNeeded, joinGroupIfNeeded>>

| rejoinNeeded
a| [[rejoinNeeded]]

[source, java]
----
boolean rejoinNeeded
----

Flag to control whether to <<rejoinNeededOrPending, rejoinNeededOrPending>>. Enabled (`true`) by default.

Turned off (`false`) when the <<joinFuture, joinFuture>> completed successfully in <<initiateJoinGroup, initiateJoinGroup>>

Turned on (`true`) in <<resetGeneration, resetGeneration>> and <<requestRejoin, requestRejoin>>

| sensors
a| [[sensors]] <<kafka-consumer-internals-AbstractCoordinator-GroupCoordinatorMetrics.adoc#, GroupCoordinatorMetrics>>

| state
a| [[state]] State of the member of a consumer group

Possible states:

* `UNJOINED` (when not joined in a consumer group when <<initiateJoinGroup, attempting to join a consumer group>> or <<resetGeneration, resetGeneration>>)
* `REBALANCING` (when <<initiateJoinGroup, attempting to join a consumer group>>)
* `STABLE` (when <<initiateJoinGroup, successfully joined a consumer group>>)

Default: `UNJOINED`

|===

[[logging]]
[TIP]
====
Enable `WARN`, `INFO`, or `DEBUG` logging level for `org.apache.kafka.clients.consumer.internals.AbstractCoordinator` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.consumer.internals.AbstractCoordinator=DEBUG
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[creating-instance]] Creating AbstractCoordinator Instance

`AbstractCoordinator` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] <<kafka-consumer-internals-ConsumerNetworkClient.adoc#, ConsumerNetworkClient>>
* [[groupId]] Group ID
* [[rebalanceTimeoutMs]] `rebalanceTimeoutMs`
* [[sessionTimeoutMs]] `sessionTimeoutMs`
* [[heartbeatIntervalMs]] `heartbeatIntervalMs` (or simply [[heartbeat]] a `Heartbeat` instance)
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[metricGrpPrefix]] Metric group prefix
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[leaveGroupOnClose]] `leaveGroupOnClose` flag

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

=== [[joinGroupIfNeeded]] `joinGroupIfNeeded` Method

[source, java]
----
boolean joinGroupIfNeeded(
  Timer timer)
----

`joinGroupIfNeeded`...FIXME

NOTE: `joinGroupIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[initiateJoinGroup]] Attempting to Join Consumer Group -- `initiateJoinGroup` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> initiateJoinGroup()
----

`initiateJoinGroup` <<disableHeartbeatThread, disables the HeartbeatThread>>.

`initiateJoinGroup` sets the <<state, state>> as `REBALANCING`.

`initiateJoinGroup` <<sendJoinGroupRequest, sends a JoinGroupRequest to the group coordinator>> (and initializes the <<joinFuture, joinFuture>>).

`initiateJoinGroup` registers a <<kafka-consumer-internals-RequestFutureListener.adoc#, RequestFutureListener>> to handle a response.

When the response is successful, `initiateJoinGroup` does the following:

. Prints out the following INFO message to the logs:
+
```
Successfully joined group with generation [generationId]
```

. Sets the <<state, state>> as `STABLE` (and the <<rejoinNeeded, rejoinNeeded>> flag off)

. Requests the <<heartbeatThread, HeartbeatThread>> to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#enable, enable itself>>.

When the response is a failure, `initiateJoinGroup` simply sets the <<state, state>> as `UNJOINED`

`initiateJoinGroup` exits immediately when the <<joinFuture, joinFuture>> has already been initialized (is not `null`) and gives it back.

NOTE: `initiateJoinGroup` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>.

=== [[ensureActiveGroup]] `ensureActiveGroup` Method

[source, java]
----
void ensureActiveGroup() // <1>
boolean ensureActiveGroup(final Timer timer)
----
<1> Calls the other `ensureActiveGroup` in an infinite `while` loop with an unexpiring timer

`ensureActiveGroup`...FIXME

NOTE: `ensureActiveGroup` is used exclusively when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for coordinator events>>.

=== [[lookupCoordinator]] Discovering Current Coordinator for Consumer Group -- `lookupCoordinator` Method

[source, java]
----
RequestFuture<Void> lookupCoordinator()
----

`lookupCoordinator` uses the <<findCoordinatorFuture, RequestFuture>> internal registry to know whether it was requested earlier but have not finished yet. In other words, the <<findCoordinatorFuture, RequestFuture>> is available when looking up a coordinator of a consumer group is in progress.

If the <<findCoordinatorFuture, RequestFuture>> internal registry is available (not a `null`), `lookupCoordinator` returns it immediately.

Otherwise, when the <<findCoordinatorFuture, RequestFuture>> internal registry is uninitialized (`null`), `lookupCoordinator` requests the <<client, ConsumerNetworkClient>> for the <<kafka-consumer-internals-ConsumerNetworkClient.adoc#leastLoadedNode, least-loaded Kafka broker>>. `lookupCoordinator` then <<sendFindCoordinatorRequest, sends a FindCoordinatorRequest to the Kafka broker>>.

`lookupCoordinator` prints out the following DEBUG message to the logs when no nodes are available and finishes with a `RequestFuture.noBrokersAvailable` failure.

```
No broker available to send FindCoordinator request
```

[NOTE]
====
`lookupCoordinator` is used when:

* `AbstractCoordinator` is requested to <<ensureCoordinatorReady, ensureCoordinatorReady>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsAsync, commitOffsetsAsync>>

* `HeartbeatThread` is requested to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#run, run>>
====

=== [[ensureCoordinatorReady]] `ensureCoordinatorReady` Method

[source, java]
----
boolean ensureCoordinatorReady(
  Timer timer)
----

`ensureCoordinatorReady`...FIXME

[NOTE]
====
`ensureCoordinatorReady` is used when:

* `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>> and <<joinGroupIfNeeded, joinGroupIfNeeded>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#fetchCommittedOffsets, fetchCommittedOffsets>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#close, close>>, and <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsSync, commitOffsetsSync>>
====

=== [[sendJoinGroupRequest]] Sending JoinGroupRequest to Group Coordinator (Kafka Broker) -- `sendJoinGroupRequest` Method

[source, java]
----
RequestFuture<ByteBuffer> sendJoinGroupRequest()
----

`sendJoinGroupRequest` prints out the following INFO message to the logs:

```
(Re-)joining group
```

`sendJoinGroupRequest` creates a new <<kafka-common-requests-JoinGroupRequest.adoc#JoinGroupRequest.Builder, JoinGroupRequest.Builder>> (for the <<groupId, groupId>>, the <<sessionTimeoutMs, sessionTimeoutMs>>, the <<generation, member ID>>, *consumer* protocol type, the <<metadata, supported ProtocolMetadata>>, and the <<rebalanceTimeoutMs, rebalanceTimeoutMs>>).

`sendJoinGroupRequest` prints out the following DEBUG message to the logs:

```
Sending JoinGroup ([requestBuilder]) to coordinator [coordinator]
```

In the end, `sendJoinGroupRequest` requests the <<client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#send, send>> the `JoinGroupRequest` to the <<coordinator, group coordinator>> node and then creates a new <<kafka-consumer-internals-JoinGroupResponseHandler.adoc#, JoinGroupResponseHandler>> to handle a response.

`sendJoinGroupRequest` returns immediately with a `RequestFuture.coordinatorNotAvailable()` when the <<coordinatorUnknown, coordinator has not been discovered yet>>.

NOTE: `sendJoinGroupRequest` is used exclusively when `AbstractCoordinator` is requested to <<initiateJoinGroup, initiateJoinGroup>>.

=== [[sendSyncGroupRequest]] Sending SyncGroupRequest (to Kafka Broker) -- `sendSyncGroupRequest` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> sendSyncGroupRequest(
  SyncGroupRequest.Builder requestBuilder)
----

`sendSyncGroupRequest`...FIXME

NOTE: `sendSyncGroupRequest` is used when...FIXME

=== [[sendFindCoordinatorRequest]] Sending FindCoordinatorRequest (to Kafka Broker) -- `sendFindCoordinatorRequest` Internal Method

[source, java]
----
RequestFuture<Void> sendFindCoordinatorRequest(Node node)
----

`sendFindCoordinatorRequest` prints out the following DEBUG message to the logs:

```
Sending FindCoordinator request to broker [node]
```

`sendFindCoordinatorRequest` creates a new <<kafka-common-requests-FindCoordinatorRequest.adoc#, FindCoordinatorRequest>> with `GROUP` type and the <<groupId, groupId>>.

In the end, `sendFindCoordinatorRequest` requests the <<client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#send, send>> the `FindCoordinatorRequest` (to the given Kafka node) and then creates a new <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#, FindCoordinatorResponseHandler>> to handle a response.

NOTE: `sendFindCoordinatorRequest` is used exclusively when `AbstractCoordinator` is requested to <<lookupCoordinator, lookupCoordinator>>.

=== [[maybeLeaveGroup]] `maybeLeaveGroup` Method

[source, java]
----
void maybeLeaveGroup()
----

`maybeLeaveGroup`...FIXME

NOTE: `maybeLeaveGroup` is used when...FIXME

=== [[sendHeartbeatRequest]] Sending HeartbeatRequest to Group Coordinator (Kafka Broker) -- `sendHeartbeatRequest` Method

[source, java]
----
RequestFuture<Void> sendHeartbeatRequest()
----

`sendHeartbeatRequest` prints out the following DEBUG message to the logs:

```
Sending Heartbeat request to coordinator [coordinator]
```

`sendHeartbeatRequest` creates a new <<kafka-common-requests-HeartbeatRequest.adoc#HeartbeatRequest.Builder, HeartbeatRequest.Builder>> (for the <<groupId, groupId>>, <<generation, generation>> and <<generation, member>> IDs).

In the end, `sendHeartbeatRequest` requests the <<client, ConsumerNetworkClient>> to <<kafka-consumer-internals-ConsumerNetworkClient.adoc#send, send>> the `HeartbeatRequest` to the <<coordinator, group coordinator>> node and then creates a new <<kafka-consumer-internals-HeartbeatResponseHandler.adoc#, HeartbeatResponseHandler>> to handle a response.

NOTE: `sendHeartbeatRequest` is used exclusively when `HeartbeatThread` is requested to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#run, run>>.

=== [[onJoinLeader]] Performing Partition Assignment and Notifying Group Coordinator -- `onJoinLeader` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> onJoinLeader(JoinGroupResponse joinResponse)
----

`onJoinLeader` <<performAssignment, performs partition assignment>> with the leader ID, the group protocol, and the member metadata (all from the given <<kafka-common-requests-JoinGroupResponse.adoc#, JoinGroupResponse>>).

`onJoinLeader` creates a new <<kafka-common-requests-SyncGroupRequest.adoc#SyncGroupRequest.Builder, SyncGroupRequest.Builder>> (with the <<groupId, group>>, <<generation, generation>>, and <<generation, member>> IDs as well as the group partition assignment).

`onJoinLeader` prints out the following DEBUG message to the logs:

```
Sending leader SyncGroup to coordinator [coordinator]: [requestBuilder]
```

In the end, `onJoinLeader` <<sendSyncGroupRequest, sends a SyncGroupRequest>> (to the <<coordinator, group coordinator>> node).

NOTE: `onJoinLeader` is used exclusively when `JoinGroupResponseHandler` is requested to <<kafka-consumer-internals-JoinGroupResponseHandler.adoc#handle, handle a successful response from the group coordinator>> (and the consumer is the leader of the consumer group).

=== [[resetJoinGroupFuture]] `resetJoinGroupFuture` Internal Method

[source, java]
----
void resetJoinGroupFuture()
----

`resetJoinGroupFuture` simply resets the <<joinFuture, joinFuture>> internal registry (i.e. sets it to `null`).

NOTE: `resetJoinGroupFuture` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>.

=== [[clearFindCoordinatorFuture]] Clearing FindCoordinatorFuture -- `clearFindCoordinatorFuture` Internal Method

[source, java]
----
void clearFindCoordinatorFuture()
----

`clearFindCoordinatorFuture` simply resets the <<findCoordinatorFuture, findCoordinatorFuture>> internal registry (to be `null`).

NOTE: `clearFindCoordinatorFuture` is used exclusively when `FindCoordinatorResponseHandler` is requested to <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onSuccess, onSuccess>> and <<kafka-consumer-internals-FindCoordinatorResponseHandler.adoc#onFailure, onFailure>>.

=== [[rejoinNeededOrPending]] `rejoinNeededOrPending` Internal Method

[source, java]
----
boolean rejoinNeededOrPending()
----

`rejoinNeededOrPending` is positive (`true`) when <<rejoinNeeded, rejoinNeeded>> and <<joinFuture, joinFuture>> is initialized (i.e. not `null`).

[NOTE]
====
`rejoinNeededOrPending` is used when:

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#rejoinNeededOrPending, rejoinNeededOrPending>> and <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>

* `KafkaConsumer` is requested to <<kafka-consumer-KafkaConsumer.adoc#pollForFetches, pollForFetches>>

* `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>>
====

=== [[pollHeartbeat]] `pollHeartbeat` Method

[source, java]
----
void pollHeartbeat(long now)
----

`pollHeartbeat`...FIXME

NOTE: `pollHeartbeat` is used exclusively when `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll for Coordinator events>>.

=== [[startHeartbeatThreadIfNeeded]] Starting HeartbeatThread -- `startHeartbeatThreadIfNeeded` Internal Method

[source, java]
----
void startHeartbeatThreadIfNeeded()
----

`startHeartbeatThreadIfNeeded`...FIXME

NOTE: `startHeartbeatThreadIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[needRejoin]] `needRejoin` Method

[source, java]
----
boolean needRejoin()
----

`needRejoin` simply returns the <<rejoinNeeded, rejoinNeeded>> flag.

NOTE: `needRejoin` is used when...FIXME

=== [[requestRejoin]] `requestRejoin` Method

[source, java]
----
void requestRejoin()
----

`requestRejoin` simply turns the <<rejoinNeeded, rejoinNeeded>> flag on.

[NOTE]
====
`requestRejoin` is used when:

* `HeartbeatResponseHandler` is requested to <<kafka-consumer-internals-HeartbeatResponseHandler.adoc#handle, handle a response>> that the consumer group is rebalancing

* `SyncGroupResponseHandler` is requested to <<kafka-consumer-internals-SyncGroupResponseHandler.adoc#handle, handle a response>> with an error
====

=== [[resetGeneration]] `resetGeneration` Method

[source, java]
----
void resetGeneration()
----

`resetGeneration` simply resets the following internal registries:

* <<generation, generation>> becomes `NO_GENERATION`

* <<rejoinNeeded, rejoinNeeded>> is turned on

* <<state, state>> is `UNJOINED`

[NOTE]
====
`resetGeneration` is used when:

* `AbstractCoordinator` is requested to <<maybeLeaveGroup, maybeLeaveGroup>>

* <<kafka-consumer-internals-HeartbeatResponseHandler.adoc#, HeartbeatResponseHandler>>, <<kafka-consumer-internals-JoinGroupResponseHandler.adoc#, JoinGroupResponseHandler>>, <<kafka-consumer-internals-SyncGroupResponseHandler.adoc#, SyncGroupResponseHandler>>, and <<kafka-consumer-internals-OffsetCommitResponseHandler.adoc#, OffsetCommitResponseHandler>> are requested to handle a response with an error (`UNKNOWN_MEMBER_ID`, `ILLEGAL_GENERATION`, or `REBALANCE_IN_PROGRESS`)
====

=== [[coordinatorUnknown]] `coordinatorUnknown` Method

[source, java]
----
boolean coordinatorUnknown()
----

`coordinatorUnknown`...FIXME

NOTE: `coordinatorUnknown` is used when...FIXME

=== [[disableHeartbeatThread]] `disableHeartbeatThread` Internal Method

[source, java]
----
void disableHeartbeatThread()
----

`disableHeartbeatThread` simply requests the <<heartbeatThread, HeartbeatThread>> to <<kafka-consumer-internals-AbstractCoordinator-HeartbeatThread.adoc#disable, disable>> (if available, i.e. not `null`).

NOTE: `disableHeartbeatThread` is used exclusively when `AbstractCoordinator` is requested to <<initiateJoinGroup, initiateJoinGroup>>.

=== [[checkAndGetCoordinator]] `checkAndGetCoordinator` Method

[source, java]
----
Node checkAndGetCoordinator()
----

`checkAndGetCoordinator`...FIXME

NOTE: `checkAndGetCoordinator` is used when...FIXME
