== [[ChannelBuilders]] ChannelBuilders Utility

=== [[clientChannelBuilder]] Creating ChannelBuilder (for Kafka Clients and Inter-Broker Communication) -- `clientChannelBuilder` Method

[source, java]
----
ChannelBuilder clientChannelBuilder(
  SecurityProtocol securityProtocol,
  JaasContext.Type contextType,
  AbstractConfig config,
  ListenerName listenerName,
  String clientSaslMechanism,
  Time time,
  boolean saslHandshakeRequestEnable)
----

`clientChannelBuilder`...FIXME

[NOTE]
====
`clientChannelBuilder` is used when:

* `ClientUtils` utility is used to `createChannelBuilder`

* `ControllerChannelManager` is requested to link:kafka-controller-ControllerChannelManager.adoc#addNewBroker[register a new broker]

* `TransactionMarkerChannelManager` is link:kafka-TransactionMarkerChannelManager.adoc#apply[created] (for a link:kafka-TransactionCoordinator.adoc[TransactionCoordinator])

* `KafkaServer` is requested to link:kafka-server-KafkaServer.adoc#controlledShutdown[controlledShutdown]

* link:kafka-server-ReplicaFetcherBlockingSend.adoc[ReplicaFetcherBlockingSend] is created
====

=== [[serverChannelBuilder]] `serverChannelBuilder` Method

[source, java]
----
ChannelBuilder serverChannelBuilder(
  ListenerName listenerName,
  boolean isInterBrokerListener,
  SecurityProtocol securityProtocol,
  AbstractConfig config,
  CredentialCache credentialCache,
  DelegationTokenCache tokenCache,
  Time time)
----

`serverChannelBuilder`...FIXME

NOTE: `serverChannelBuilder` is used when link:kafka-network-SocketServer-Processor.adoc[Processor] is created (and creates a link:kafka-network-SocketServer-Processor.adoc#selector[Selector]).

=== [[create]] `create` Internal Utility

[source, java]
----
ChannelBuilder create(
  SecurityProtocol securityProtocol,
  Mode mode,
  JaasContext.Type contextType,
  AbstractConfig config,
  ListenerName listenerName,
  boolean isInterBrokerListener,
  String clientSaslMechanism,
  boolean saslHandshakeRequestEnable,
  CredentialCache credentialCache,
  DelegationTokenCache tokenCache,
  Time time)
----

`create`...FIXME

NOTE: `create` is used when `ChannelBuilders` utility is requested to <<clientChannelBuilder, clientChannelBuilder>> (`CLIENT` mode) and <<serverChannelBuilder, serverChannelBuilder>> (`SERVER` mode).
