== [[LogSegment]] LogSegment

`LogSegment` is a segment of a <<kafka-log-Log.adoc#, partition log>>.

`LogSegment` has two components: a log and an index (and with the <<baseOffset, base offset>> it would be stored in two files, a [base offset].index and a [base offset].log file).

`LogSegment` is <<creating-instance, created>> (indirectly using <<open, open>>) when:

* `Log` is requested to <<kafka-log-Log.adoc#loadSegmentFiles, loadSegmentFiles>> (for every log file), <<kafka-log-Log.adoc#completeSwapOperations, completeSwapOperations>>, <<kafka-log-Log.adoc#loadSegments, loadSegments>>, <<kafka-log-Log.adoc#recoverLog, recoverLog>>, <<kafka-log-Log.adoc#roll, roll>>, and <<kafka-log-Log.adoc#truncateFullyAndStartAt, truncateFullyAndStartAt>>

* `LogCleaner` is requested to <<kafka-log-LogCleaner.adoc#createNewCleanedSegment, createNewCleanedSegment>>

=== [[creating-instance]] Creating LogSegment Instance

`LogSegment` takes the following to be created:

* [[log]] `FileRecords`
* [[lazyOffsetIndex]] `LazyOffsetIndex`
* [[lazyTimeIndex]] `LazyTimeIndex`
* [[txnIndex]] `TransactionIndex`
* [[baseOffset]] Base offset
* [[indexIntervalBytes]] `indexIntervalBytes`
* [[rollJitterMs]] `rollJitterMs`
* [[time]] `Time`

`LogSegment` initializes the <<internal-properties, internal properties>>.

=== [[recover]] `recover` Method

[source, scala]
----
recover(
  producerStateManager: ProducerStateManager,
  leaderEpochCache: Option[LeaderEpochFileCache] = None): Int
----

`recover`...FIXME

NOTE: `recover` is used exclusively when `Log` is requested to <<kafka-log-Log.adoc#recoverSegment, recover a log segment>>.

=== [[sanityCheck]] `sanityCheck` Method

[source, scala]
----
sanityCheck(
  timeIndexFileNewlyCreated: Boolean): Unit
----

`sanityCheck`...FIXME

NOTE: `sanityCheck` is used exclusively when `Log` is requested to <<kafka-log-Log.adoc#loadSegments, loadSegments>> (when <<kafka-log-Log.adoc#creating-instance-loadSegments, created>>).

=== [[open]] Creating LogSegment Instance -- `open` Utility

[source, scala]
----
open(
  dir: File,
  baseOffset: Long,
  config: LogConfig,
  time: Time,
  fileAlreadyExists: Boolean = false,
  initFileSize: Int = 0,
  preallocate: Boolean = false,
  fileSuffix: String = ""): LogSegment
----

`open` uses the <<kafka-log-LogConfig.adoc#maxIndexSize, segment.index.bytes>> (of the given <<kafka-log-LogConfig.adoc#, LogConfig>>) for the `maxIndexSize`.

`open` uses `Log` utility to <<kafka-log-Log.adoc#logFile, logFile>> (dir, baseOffset, fileSuffix)

`open` creates a new <<creating-instance, LogSegment>>.

[NOTE]
====
`open` is used when:

* `Log` is requested to <<kafka-log-Log.adoc#loadSegmentFiles, loadSegmentFiles>> (for every log file), <<kafka-log-Log.adoc#completeSwapOperations, completeSwapOperations>>, <<kafka-log-Log.adoc#loadSegments, loadSegments>>, <<kafka-log-Log.adoc#recoverLog, recoverLog>>, <<kafka-log-Log.adoc#roll, roll>>, and <<kafka-log-Log.adoc#truncateFullyAndStartAt, truncateFullyAndStartAt>>

* `LogCleaner` is requested to <<kafka-log-LogCleaner.adoc#createNewCleanedSegment, createNewCleanedSegment>>
====

=== [[deleteIfExists]] `deleteIfExists` Utility

[source, scala]
----
deleteIfExists(
  dir: File,
  baseOffset: Long,
  fileSuffix: String = ""): Unit
----

`deleteIfExists`...FIXME

NOTE: `deleteIfExists` is used when...FIXME

=== [[resizeIndexes]] `resizeIndexes` Method

[source, scala]
----
resizeIndexes(size: Int): Unit
----

`resizeIndexes`...FIXME

NOTE: `resizeIndexes` is used when...FIXME

=== [[largestTimestamp]] `largestTimestamp` Method

[source, scala]
----
largestTimestamp: Long
----

`largestTimestamp`...FIXME

NOTE: `largestTimestamp` is used when...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| created
a| [[created]] Time(stamp) when the `LogSegment` was created

Used when...FIXME

| bytesSinceLastIndexEntry
a| [[bytesSinceLastIndexEntry]]

Used when...FIXME

| rollingBasedTimestamp
a| [[rollingBasedTimestamp]]

Used when...FIXME

| _maxTimestampSoFar
a| [[_maxTimestampSoFar]]

Used when...FIXME

| _offsetOfMaxTimestampSoFar
a| [[_offsetOfMaxTimestampSoFar]]

Used when...FIXME

|===
