== Kafka Controller Election

A Kafka broker can be elected as the controller in the process known as *Kafka Controller Election*.

When `ControllerEventThread` is requested to process <<kafka-controller-ControllerEvent.adoc#Startup, Startup>> and <<kafka-controller-ControllerEvent.adoc#Reelect, Reelect>> controller events, `KafkaController` (instance that runs on every Kafka broker) is requested to <<kafka-controller-KafkaController.adoc#elect, elect>>.

Kafka Controller Election process relies heavily on the features of Apache ZooKeeper that acts as the source of truth and guarantees that only one broker can ever be elected (due to how *ephemeral nodes* work).

From https://zookeeper.apache.org/doc/current/zookeeperOver.html#Nodes+and+ephemeral+nodes[Nodes and ephemeral nodes] in the official documentation of Apache ZooKeeper:

> ZooKeeper also has the notion of ephemeral nodes. These znodes exists as long as the session that created the znode is active. When the session ends the znode is deleted.

From https://zookeeper.apache.org/doc/current/recipes.html#sc_leaderElection[Leader Election] in the official documentation of Apache ZooKeeper:

> A simple way of doing leader election with ZooKeeper is to use the SEQUENCE|EPHEMERAL flags when creating znodes that represent "proposals" of clients. The idea is to have a znode, say "/election"

TIP: Consult <<kafka-demo-controller-election.adoc#, Demo: Kafka Controller Election>> to learn about the process.

=== Controller ID Registered (in ZooKeeper)

The election process stops when <<kafka-controller-KafkaController.adoc#elect, there is a controller ID registered in Zookeeper>> (using `KafkaZkClient` that <<kafka-zk-KafkaZkClient.adoc#getControllerId, gets the ID of the active controller>> and the ID is any number but `-1`).

=== No Controller ID Registered (in ZooKeeper)

If there is no controller ID registered, every `KafkaController` instance tries to <<kafka-controller-KafkaController.adoc#elect, register itself as the controller (in Zookeeper) and increment the controller epoch>> (using <<kafka-zk-KafkaZkClient.adoc#registerControllerAndIncrementControllerEpoch, KafkaZkClient>>).

In the end, the active `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#onControllerFailover, onControllerFailover>>.
