== [[FileRecords]] FileRecords

`FileRecords` is a concrete <<kafka-common-record-AbstractRecords.adoc#, AbstractRecords>>...FIXME

`FileRecords` is <<creating-instance, created>> when...FIXME

=== [[creating-instance]] Creating FileRecords Instance

`FileRecords` takes the following to be created:

* [[file]] Underlying `File`
* [[channel]] Underlying `FileChannel`
* [[start]] Start
* [[end]] End
* [[isSlice]] `isSlice` flag

`FileRecords` initializes the <<internal-properties, internal properties>>.

=== [[open]] Opening Log File -- `open` Utility

[source, java]
----
FileRecords open(
  File file) throws IOException // <1>
FileRecords open(
  File file,
  boolean mutable) throws IOException // <2>
FileRecords open(
  File file,
  boolean mutable,
  boolean fileAlreadyExists,
  int initFileSize,
  boolean preallocate) throws IOException
FileRecords open(
  File file,
  boolean fileAlreadyExists,
  int initFileSize,
  boolean preallocate) throws IOException
----
<1> Turns `mutable` flag on (`true`)
<2> Turns `fileAlreadyExists` flag off (`false`), `initFileSize` as `0`, and `preallocate` as `false`

[[open-channel]]
`open` <<openChannel, opens a FileChannel>>.

`open` determines the <<end, end>> of a `FileRecords` to be created:

* `0` for the given `fileAlreadyExists` flag disabled (`false`) and the given `preallocate` flag enabled (`true`)

* `Integer.MAX_VALUE` otherwise

In the end, `open` creates a new `FileRecords` for the given `file`, the channel, and the <<isSlice, isSlice>> flag disabled (`false`).

[NOTE]
====
`open` is used when:

* `LogSegment` utility is used to <<kafka-log-LogSegment.adoc#open, open a log segment>>

* <<kafka-tools-DumpLogSegments.adoc#, DumpLogSegments>> tool is executed
====

=== [[readInto]] Reading Log Batches (Into ByteBuffer) -- `readInto` Method

[source, java]
----
void readInto(
  ByteBuffer buffer,
  int position) throws IOException
----

`readInto`...FIXME

[NOTE]
====
`readInto` is used when:

* `GroupMetadataManager` is requested to <<kafka-coordinator-group-GroupMetadataManager.adoc#doLoadGroupsAndOffsets, doLoadGroupsAndOffsets>>

* `TransactionStateManager` is requested to <<kafka-TransactionStateManager.adoc#loadTransactionMetadata, loadTransactionMetadata>>

* `Cleaner` is requested to <<kafka-log-Cleaner.adoc#cleanInto, cleanInto>> and <<kafka-log-Cleaner.adoc#buildOffsetMapForSegment, buildOffsetMapForSegment>>

* `LogSegment` is requested to <<kafka-log-LogSegment.adoc#appendChunkFromFile, appendChunkFromFile>>

* `AbstractFetcherThread` is requested to <<kafka-server-AbstractFetcherThread.adoc#toMemoryRecords, toMemoryRecords>>
====

=== [[sizeInBytes]] `sizeInBytes` Method

[source, java]
----
int sizeInBytes()
----

NOTE: `sizeInBytes` is part of the link:kafka-common-record-BaseRecords.adoc#sizeInBytes[BaseRecords] contract for the size of the records (in bytes).

`sizeInBytes` simply the current value of the <<size, size>> internal registry.

=== [[openChannel]] Opening FileChannel -- `openChannel` Internal Method

[source, java]
----
FileChannel openChannel(
  File file,
  boolean mutable,
  boolean fileAlreadyExists,
  int initFileSize,
  boolean preallocate) throws IOException
----

`openChannel`...FIXME

NOTE: `openChannel` is used when `FileRecords` utility is requested to <<open, open a log file>>.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| batches
a| [[batches]] (`Iterable<FileChannelRecordBatch>`)

| size
a| [[size]] Size (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/atomic/AtomicInteger.html[java.util.concurrent.atomic.AtomicInteger]) that is `end - start` for <<isSlice, isSlice>> enabled.

Used when...FIXME

|===
