== [[ConfigCommand]] ConfigCommand Standalone Application

`kafka.admin.ConfigCommand` is a <<main, standalone application>> that...FIXME

`ConfigCommand` can be executed using `kafka-configs` shell script (i.e. `bin/kafka-configs.sh` or `bin\windows\kafka-configs.bat`).

```
// Triggers alterBrokerConfig
./bin/kafka-configs.sh \
  --bootstrap-server :9092 \
  --alter \
  --entity-type brokers \
  --entity-name 0 \
  --add-config advertised.listeners=plaintext://:9092
```

```
// Triggers processBrokerConfig
./bin/kafka-configs.sh \
  --bootstrap-server :9092 \
  --describe \
  --entity-type brokers \
  --entity-name 0
```

=== [[alterBrokerConfig]] `alterBrokerConfig` Method

[source, scala]
----
alterBrokerConfig(
  adminClient: JAdminClient,
  opts: ConfigCommandOptions,
  entityName: String)
----

`alterBrokerConfig`...FIXME

NOTE: `alterBrokerConfig` is used exclusively when `ConfigCommand` is requested to <<processBrokerConfig, processBrokerConfig>> (with `alter` action).

=== [[processBrokerConfig]] `processBrokerConfig` Internal Method

[source, scala]
----
processBrokerConfig(opts: ConfigCommandOptions): Unit
----

`processBrokerConfig`...FIXME

NOTE: `processBrokerConfig` is used exclusively when `ConfigCommand` standalone application is <<main, executed>> (without `zookeeper` command-line option).

=== [[main]] Executing Standalone Application -- `main` Method

[source, scala]
----
main(args: Array[String]): Unit
----

`main` is the entry point of the <<ConfigCommand, ConfigCommand>> standalone application when launched on command line (e.g. from `bin/kafka-configs.sh`).

`main`...FIXME

=== [[processCommandWithZk]] `processCommandWithZk` Internal Method

[source, scala]
----
processCommandWithZk(zkConnectString: String, opts: ConfigCommandOptions): Unit
----

`processCommandWithZk`...FIXME

NOTE: `processCommandWithZk` is used when...FIXME

=== [[alterConfig]] `alterConfig` Internal Method

[source, scala]
----
alterConfig(
  zkClient: KafkaZkClient,
  opts: ConfigCommandOptions,
  adminZkClient: AdminZkClient): Unit
----

`alterConfig`...FIXME

NOTE: `alterConfig` is used when...FIXME
