== [[QueuedEvent]] QueuedEvent -- ControllerEvent with Enqueue Time

[[creating-instance]][[event]][[enqueueTimeMs]]
`QueuedEvent` is a <<kafka-controller-ControllerEvent.adoc#, ControllerEvent>> with the time it was enqueued (_enqueue time_) to <<kafka-controller-ControllerEventManager.adoc#, ControllerEventManager>>.

`QueuedEvent` is <<creating-instance, created>> every time `ControllerEventManager` is requested to <<kafka-controller-ControllerEventManager.adoc#put, enqueue a controller event>>.

=== [[process]] Processing ControllerEvent Using ControllerEventProcessor -- `process` Method

[source, scala]
----
process(
  processor: ControllerEventProcessor): Unit
----

`process` atomically turns the <<spent, spent>> internal registry on and simply exits when it was on already.

`process` decrements the count of the <<processingStarted, processingStarted>> internal latch.

In the end, `process` simply requests the given <<kafka-controller-ControllerEventProcessor.adoc#, ControllerEventProcessor>> to <<kafka-controller-ControllerEventProcessor.adoc#process, process the controller event>>.

NOTE: `process` is used exclusively when `ControllerEventThread` is requested to <<kafka-controller-ControllerEventThread.adoc#doWork, process controller events>>.

=== [[preempt]] Preempting ControllerEvent Using ControllerEventProcessor -- `preempt` Method

[source, scala]
----
preempt(
  processor: ControllerEventProcessor): Unit
----

`preempt` atomically turns the <<spent, spent>> internal registry on and simply exits when it was on already.

In the end, `preempt` simply requests the given <<kafka-controller-ControllerEventProcessor.adoc#, ControllerEventProcessor>> to <<kafka-controller-ControllerEventProcessor.adoc#preempt, preempt the controller event>>.

NOTE: `preempt` is used exclusively when `ControllerEventManager` is requested to <<kafka-controller-ControllerEventManager.adoc#clearAndPut, clearAndPut>>.

=== [[awaitProcessing]] `awaitProcessing` Method

[source, scala]
----
awaitProcessing(): Unit
----

`awaitProcessing` simply pauses the current thread until the <<processingStarted, processingStarted>> internal latch has counted down to zero (which happens only after <<process, processing the ControllerEvent using a ControllerEventProcessor>>).

NOTE: `awaitProcessing` is used exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#startup, start up>>.

=== [[toString]] String (Textual) Representation -- `toString` Method

[source, scala]
----
toString: String
----

NOTE: `toString` is part of the link:++https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Object.html#toString()++[java.lang.Object] Contract for a string representation of the object.

`toString` returns the following string representation:

```
QueuedEvent(event=[event], enqueueTimeMs=[enqueueTimeMs])
```

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| processingStarted
a| [[processingStarted]] Java's https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CountDownLatch.html[CountDownLatch] (with the count of `1`) to wait until...FIXME

Used when...FIXME

| spent
a| [[spent]] Java's https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/atomic/AtomicBoolean.html[AtomicBoolean] (with the initial value of `false`) to be updated atomically...FIXME

Used when...FIXME

|===
