== [[ConsumerRebalanceListener]] ConsumerRebalanceListener

`ConsumerRebalanceListener` is a <<contract, callback interface>> to be notified when the set of partitions assigned to the consumer (aka _assignment_) changes.

`ConsumerRebalanceListener` is notified about the newly-assigned partitions through <<onPartitionsAssigned, onPartitionsAssigned>> callback that happens when `ConsumerCoordinator` is requested to link:kafka-consumer-internals-ConsumerCoordinator.adoc#onJoinComplete[onJoinComplete].

`ConsumerRebalanceListener` is notified about the partitions revoked through <<onPartitionsRevoked, onPartitionsRevoked>> callback that happens when `ConsumerCoordinator` is requested to link:kafka-consumer-internals-ConsumerCoordinator.adoc#onJoinPrepare[onJoinPrepare].

CAUTION: FIXME Picture when the notifications are triggered

[[contract]]
[source, java]
----
package org.apache.kafka.clients.consumer;

interface ConsumerRebalanceListener {
  void onPartitionsAssigned(Collection<TopicPartition> partitions);
  void onPartitionsRevoked(Collection<TopicPartition> partitions);
}
----

`ConsumerRebalanceListener` is used when a Kafka `Consumer` is requested to link:kafka-consumer-Consumer.adoc#subscribe[subscribe to topics].

[source, java]
----
void subscribe(Collection<String> topics, ConsumerRebalanceListener callback);
void subscribe(Pattern pattern, ConsumerRebalanceListener callback);
----

.ConsumerRebalanceListener Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[onPartitionsAssigned]] `onPartitionsAssigned`
| Used exclusively when `ConsumerCoordinator` is requested to link:kafka-consumer-internals-ConsumerCoordinator.adoc#onJoinComplete[onJoinComplete]

| [[onPartitionsRevoked]] `onPartitionsRevoked`
| Used exclusively when `ConsumerCoordinator` is requested to link:kafka-consumer-internals-ConsumerCoordinator.adoc#onJoinPrepare[onJoinPrepare]
|===
