== [[ControllerChannelManager]] ControllerChannelManager

`ControllerChannelManager` is...FIXME

`ControllerChannelManager` is <<creating-instance, created>> exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#startChannelManager, startChannelManager>>.

[[kafka-metrics]]
.ControllerChannelManager's Metrics
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| TotalQueueSize
| [[TotalQueueSize]]

|===

[[internal-registries]]
.ControllerChannelManager's Internal Properties
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| brokerStateInfo
| [[brokerStateInfo]]

Used when...FIXME

| brokerLock
| [[brokerLock]]

Used when...FIXME
|===

[[logIdent]]
`ControllerChannelManager` uses *[Channel manager on controller [brokerId]]* as the logging prefix (aka `logIdent`).

=== [[addNewBroker]] `addNewBroker` Internal Method

[source, scala]
----
addNewBroker(broker: Broker): Unit
----

`addNewBroker`...FIXME

NOTE: `addNewBroker` is used when `ControllerChannelManager` is <<creating-instance, created>> (to connect to live brokers) and is requested to <<addBroker, addBroker>>.

=== [[addBroker]] Registering Newly-Added Broker -- `addBroker` Method

[source, scala]
----
addBroker(broker: Broker): Unit
----

`addBroker`...FIXME

NOTE: `addBroker` is used exclusively when <<kafka-controller-KafkaController.adoc#BrokerChange, BrokerChange>> controller event is processed.

=== [[removeBroker]] Deregistering Broker -- `removeBroker` Method

[source, scala]
----
removeBroker(brokerId: Int): Unit
----

`removeBroker`...FIXME

NOTE: `removeBroker` is used when...FIXME

=== [[creating-instance]] Creating ControllerChannelManager Instance

`ControllerChannelManager` takes the following when created:

* [[controllerContext]] `ControllerContext`
* [[config]] <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>
* [[time]] `Time`
* [[metrics]] <<kafka-Metrics.adoc#, Metrics>>
* [[stateChangeLogger]] `StateChangeLogger`
* [[threadNamePrefix]] Optional thread name prefix (default: `None`)

`ControllerChannelManager` initializes the <<internal-registries, internal registries and counters>>.

In the end, `ControllerChannelManager` requests the <<controllerContext, ControllerContext>> for the `liveBrokers` that it <<addNewBroker, addNewBroker>> each.
