== [[UpdateMetadataRequest]] UpdateMetadataRequest

[[UPDATE_METADATA]][[creating-instance]]
`UpdateMetadataRequest` is a <<kafka-controller-AbstractControlRequest.adoc#, controller request>> with *UPDATE_METADATA* API key and the following properties:

* [[version]] Version
* [[controllerId]] Controller ID
* [[controllerEpoch]] Controller Epoch
* [[brokerEpoch]] Broker Epoch
* [[partitionStates]] `PartitionStates` by `TopicPartition` (`Map<TopicPartition, PartitionState>`)
* [[liveBrokers]] *Live leaders* (brokers with leaders)

=== [[KafkaApis]] KafkaApis and UpdateMetadataRequest

When received, `UpdateMetadataRequest` is handled by <<kafka-server-KafkaApis.adoc#handleUpdateMetadataRequest, handleUpdateMetadataRequest>>.

=== [[UpdateMetadataRequest.Builder]][[Builder]][[build]] `UpdateMetadataRequest.Builder` Factory Object

`UpdateMetadataRequest` comes with a concrete <<kafka-common-requests-AbstractRequest.adoc#Builder, AbstractRequest.Builder>> factory object that can <<kafka-common-requests-AbstractRequest-Builder.adoc#build, build>> a <<UpdateMetadataRequest, UpdateMetadataRequest>>.

[source, java]
----
UpdateMetadataRequest build(short version)
----

`UpdateMetadataRequest.Builder` is used exclusively when `AbstractControllerBrokerRequestBatch` is requested to <<kafka-controller-AbstractControllerBrokerRequestBatch.adoc#sendUpdateMetadataRequests, send UpdateMetadata requests out to all brokers>>.
