== [[DynamicBrokerConfig]] DynamicBrokerConfig

`DynamicBrokerConfig` is <<creating-instance, created>> exclusively when `KafkaConfig` is <<kafka-server-KafkaConfig.adoc#dynamicConfig, created>>.

`DynamicBrokerConfig` is used to create a <<kafka-server-KafkaConfig.adoc#dynamicConfigOverride, KafkaConfig>>.

NOTE: `DynamicBrokerConfig` is <<creating-instance, created>> when <<kafka-server-KafkaConfig.adoc#dynamicConfig, KafkaConfig>> is, but the reverse is also true (!) Isn't it a dependency cycle? Not really since `KafkaConfig` will create a <<kafka-server-KafkaConfig.adoc#dynamicConfig, DynamicBrokerConfig>> unless one is provided.

[[kafkaConfig]]
[[creating-instance]]
`DynamicBrokerConfig` takes a single <<kafka-server-KafkaConfig.adoc#, KafkaConfig>> when created.

=== [[currentDynamicDefaultConfigs]] `currentDynamicDefaultConfigs` Method

[source, scala]
----
currentDynamicDefaultConfigs: Map[String, String]
----

`currentDynamicDefaultConfigs` simply clones the <<dynamicDefaultConfigs, dynamicDefaultConfigs>>.

NOTE: `currentDynamicDefaultConfigs` is used when `AdminManager` is requested to <<kafka-server-AdminManager.adoc#configSynonyms, configSynonyms>> and <<kafka-server-AdminManager.adoc#describeConfigs, describeConfigs>>.

=== [[addReconfigurables]] Registering (Adding) Reconfigurables For KafkaServer -- `addReconfigurables` Method

[source, scala]
----
addReconfigurables(kafkaServer: KafkaServer): Unit
----

`addReconfigurables` registers (_adds_) <<addBrokerReconfigurable, broker>> and <<addReconfigurable, regular>> reconfigurables.

Internally, `addReconfigurables` creates a <<kafka-server-DynamicThreadPool.adoc#, DynamicThreadPool>> with the input <<kafka-server-KafkaServer.adoc#, KafkaServer>> and <<addBrokerReconfigurable, addBrokerReconfigurable>>.

`addReconfigurables` <<addBrokerReconfigurable, addBrokerReconfigurable>> with the <<kafka-log-LogCleaner.adoc#, LogCleaner>> (if configured).

`addReconfigurables` creates a <<kafka-server-DynamicLogConfig.adoc#, DynamicThreadPool>> with the <<kafka-server-KafkaServer.adoc#logManager, LogManager>> and the input <<kafka-server-KafkaServer.adoc#, KafkaServer>>, and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicMetricsReporters.adoc#, DynamicMetricsReporters>> for the <<kafka-server-KafkaConfig.adoc#brokerId, broker>> and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicClientQuotaCallback.adoc#, DynamicClientQuotaCallback>> for the <<kafka-server-KafkaConfig.adoc#brokerId, broker>> and <<addReconfigurable, addReconfigurable>>.

`addReconfigurables` creates a <<kafka-server-DynamicListenerConfig.adoc#, DynamicListenerConfig>> with the input <<kafka-server-KafkaServer.adoc#, KafkaServer>> and <<addBrokerReconfigurable, addBrokerReconfigurable>>.

NOTE: `addReconfigurables` is used exclusively  when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>.

=== [[processReconfigurable]] `processReconfigurable` Method

[source, scala]
----
processReconfigurable(
  reconfigurable: Reconfigurable,
  updatedConfigNames: Set[String],
  allNewConfigs: util.Map[String, _],
  newCustomConfigs: util.Map[String, Object],
  validateOnly: Boolean): Unit
----

`processReconfigurable`...FIXME

NOTE: `processReconfigurable` is used when `DynamicBrokerConfig` is requested to <<processReconfiguration, processReconfiguration>> and <<processListenerReconfigurable, processListenerReconfigurable>>.

=== [[processListenerReconfigurable]] `processListenerReconfigurable` Internal Method

[source, scala]
----
processListenerReconfigurable(
  listenerReconfigurable: ListenerReconfigurable,
  newConfig: KafkaConfig,
  customConfigs: util.Map[String, Object],
  validateOnly: Boolean,
  reloadOnly:  Boolean): Unit
----

`processListenerReconfigurable`...FIXME

NOTE: `processListenerReconfigurable` is used when `DynamicBrokerConfig` is requested to <<reloadUpdatedFilesWithoutConfigChange, reloadUpdatedFilesWithoutConfigChange>> and <<processReconfiguration, processReconfiguration>>.

=== [[reloadUpdatedFilesWithoutConfigChange]] `reloadUpdatedFilesWithoutConfigChange` Internal Method

[source, scala]
----
reloadUpdatedFilesWithoutConfigChange(newProps: Properties): Unit
----

`reloadUpdatedFilesWithoutConfigChange`...FIXME

NOTE: `reloadUpdatedFilesWithoutConfigChange` is used exclusively when `AdminManager` is requested to <<kafka-server-AdminManager.adoc#alterConfigs, alterConfigs>> (when `KafkaApis` is requested to handle a <<kafka-server-KafkaApis.adoc#AlterConfigs, AlterConfigs>> request).

=== [[clear]] `clear` Method

[source, scala]
----
clear(): Unit
----

`clear`...FIXME

NOTE: `clear` is used exclusively when `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#shutdown, shut down>>.

=== [[validatedKafkaProps]] `validatedKafkaProps` Method

[source, scala]
----
validatedKafkaProps(
  propsOverride: Properties,
  perBrokerConfig: Boolean): Map[String, String]
----

`validatedKafkaProps`...FIXME

NOTE: `validatedKafkaProps` is used when...FIXME

=== [[addReconfigurable]] Registering Reconfigurable -- `addReconfigurable` Method

[source, scala]
----
addReconfigurable(
  reconfigurable: Reconfigurable): Unit
----

`addReconfigurable` <<verifyReconfigurableConfigs, verifyReconfigurableConfigs>> of the link:kafka-common-Reconfigurable.adoc#reconfigurableConfigs[Reconfigurable].

In the end, `addReconfigurable` adds the `Reconfigurable` to the <<reconfigurables, reconfigurables>> internal registry.

[NOTE]
====
`addReconfigurable` is used when:

* `DynamicBrokerConfig` is requested to <<addReconfigurables, addReconfigurables>>

* `KafkaConfig` is requested to link:kafka-server-KafkaConfig.adoc#addReconfigurable[add a Reconfigurable]
====

=== [[verifyReconfigurableConfigs]] `verifyReconfigurableConfigs` Internal Method

[source, scala]
----
verifyReconfigurableConfigs(
  configNames: Set[String]): Unit
----

`verifyReconfigurableConfigs`...FIXME

NOTE: `verifyReconfigurableConfigs` is used when...FIXME

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| brokerReconfigurables
a| [[brokerReconfigurables]] <<kafka-server-BrokerReconfigurable.adoc#, BrokerReconfigurables>>

New reconfigurables registered in <<addBrokerReconfigurable, addBrokerReconfigurable>>

All removed in <<clear, clear>>

Used in <<processReconfiguration, processReconfiguration>>

| currentConfig
a| [[currentConfig]] Current <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>

Initialized with the input <<kafkaConfig, KafkaConfig>>.

Used when...FIXME

| dynamicDefaultConfigs
a| [[dynamicDefaultConfigs]] Dynamic configurations

Cleared and immediately updated in <<updateDefaultConfig, updateDefaultConfig>>

Used in <<validatedKafkaProps, validatedKafkaProps>> and <<updateCurrentConfig, updateCurrentConfig>>

Cleared when `DynamicBrokerConfig` is requested to <<clear, clear>>

Available using <<currentDynamicDefaultConfigs, currentDynamicDefaultConfigs>>

| reconfigurables
a| [[reconfigurables]] link:kafka-common-Reconfigurable.adoc[Reconfigurables]

|===
