== [[BrokerReconfigurable]] BrokerReconfigurable Contract -- Reconfigurable Broker Services

`BrokerReconfigurable` is the <<contract, contract>> of <<implementations, reconfigurable broker services>> that allow for <<reconfigure, self-reconfiguration>>.

`BrokerReconfigurable` interface is used exclusively by <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>>.

[[contract]]
.BrokerReconfigurable Contract
[cols="1m,2",options="header",width="100%"]
|===
| Property
| Description

| reconfigurableConfigs
a| [[reconfigurableConfigs]]

[source, scala]
----
reconfigurableConfigs: Set[String]
----

Dynamic configurations

Used when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#addBrokerReconfigurable, addBrokerReconfigurable>> and <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>

| reconfigure
a| [[reconfigure]]

[source, scala]
----
reconfigure(
  oldConfig: KafkaConfig,
  newConfig: KafkaConfig): Unit
----

Used when `DynamicBrokerConfig` is requested to link:kafka-server-DynamicBrokerConfig.adoc#updateCurrentConfig[updateCurrentConfig]

| validateReconfiguration
a| [[validateReconfiguration]]

[source, scala]
----
validateReconfiguration(newConfig: KafkaConfig): Unit
----

Used exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>
|===

[[implementations]]
.BrokerReconfigurables
[cols="1,2",options="header",width="100%"]
|===
| BrokerReconfigurable
| Dynamic Configurations

| <<kafka-server-DynamicConnectionQuota.adoc#, DynamicConnectionQuota>>
a| [[DynamicConnectionQuota]]

<<kafka-properties.adoc#max.connections.per.ip, max.connections.per.ip>>

<<kafka-properties.adoc#max.connections.per.ip.overrides, max.connections.per.ip.overrides>>

| <<kafka-server-DynamicListenerConfig.adoc#, DynamicListenerConfig>>
a| [[DynamicListenerConfig]]

<<kafka-properties.adoc#advertised.listeners, advertised.listeners>>

<<kafka-properties.adoc#listeners, listeners>>

<<kafka-properties.adoc#listener.security.protocol.map, listener.security.protocol.map>>

<<kafka-properties.adoc#principal.builder.class, principal.builder.class>>

<<kafka-properties.adoc#ssl.protocol, ssl.protocol>>

<<kafka-properties.adoc#ssl.provider, ssl.provider>>

<<kafka-properties.adoc#ssl.cipher.suites, ssl.cipher.suites>>

<<kafka-properties.adoc#ssl.enabled.protocols, ssl.enabled.protocols>>

<<kafka-properties.adoc#ssl.keystore.type, ssl.keystore.type>>

<<kafka-properties.adoc#ssl.keystore.location, ssl.keystore.location>>

<<kafka-properties.adoc#ssl.keystore.password, ssl.keystore.password>>

<<kafka-properties.adoc#ssl.key.password, ssl.key.password>>

<<kafka-properties.adoc#ssl.truststore.type, ssl.truststore.type>>

<<kafka-properties.adoc#ssl.truststore.location, ssl.truststore.location>>

<<kafka-properties.adoc#ssl.truststore.password, ssl.truststore.password>>

<<kafka-properties.adoc#ssl.keymanager.algorithm, ssl.keymanager.algorithm>>

<<kafka-properties.adoc#ssl.trustmanager.algorithm, ssl.trustmanager.algorithm>>

<<kafka-properties.adoc#ssl.endpoint.identification.algorithm, ssl.endpoint.identification.algorithm>>

<<kafka-properties.adoc#ssl.secure.random.implementation, ssl.secure.random.implementation>>

<<kafka-properties.adoc#ssl.client.auth, ssl.client.auth>>

<<kafka-properties.adoc#sasl.mechanism.inter.broker.protocol, sasl.mechanism.inter.broker.protocol>>

<<kafka-properties.adoc#sasl.jaas.config, sasl.jaas.config>>

<<kafka-properties.adoc#sasl.enabled.mechanisms, sasl.enabled.mechanisms>>

<<kafka-properties.adoc#sasl.kerberos.service.name, sasl.kerberos.service.name>>

<<kafka-properties.adoc#sasl.kerberos.kinit.cmd, sasl.kerberos.kinit.cmd>>

<<kafka-properties.adoc#sasl.kerberos.ticket.renew.window.factor, sasl.kerberos.ticket.renew.window.factor>>

<<kafka-properties.adoc#sasl.kerberos.ticket.renew.jitter, sasl.kerberos.ticket.renew.jitter>>

<<kafka-properties.adoc#sasl.kerberos.min.time.before.relogin, sasl.kerberos.min.time.before.relogin>>

<<kafka-properties.adoc#sasl.kerberos.principal.to.local.rules, sasl.kerberos.principal.to.local.rules>>

<<kafka-properties.adoc#sasl.login.refresh.window.factor, sasl.login.refresh.window.factor>>

<<kafka-properties.adoc#sasl.login.refresh.window.jitter, sasl.login.refresh.window.jitter>>

<<kafka-properties.adoc#sasl.login.refresh.min.period.seconds, sasl.login.refresh.min.period.seconds>>

<<kafka-properties.adoc#sasl.login.refresh.buffer.seconds, sasl.login.refresh.buffer.seconds>>

| <<kafka-server-DynamicThreadPool.adoc#, DynamicThreadPool>>
a| [[DynamicThreadPool]]

<<kafka-properties.adoc#num.io.threads, num.io.threads>>

<<kafka-properties.adoc#num.network.threads, num.network.threads>>

<<kafka-properties.adoc#num.replica.fetchers, num.replica.fetchers>>

<<kafka-properties.adoc#num.recovery.threads.per.data.dir, num.recovery.threads.per.data.dir>>

<<kafka-properties.adoc#background.threads, background.threads>>

| <<kafka-log-LogCleaner.adoc#, LogCleaner>>
a| [[LogCleaner]]

<<kafka-properties.adoc#log.cleaner.threads, log.cleaner.threads>>

<<kafka-properties.adoc#log.cleaner.dedupe.buffer.size, log.cleaner.dedupe.buffer.size>>

<<kafka-properties.adoc#log.cleaner.io.buffer.load.factor, log.cleaner.io.buffer.load.factor>>

<<kafka-properties.adoc#log.cleaner.io.buffer.size, log.cleaner.io.buffer.size>>

<<kafka-properties.adoc#log.cleaner.io.max.bytes.per.second, log.cleaner.io.max.bytes.per.second>>

<<kafka-properties.adoc#log.cleaner.backoff.ms, log.cleaner.backoff.ms>>

<<kafka-properties.adoc#message.max.bytes, message.max.bytes>>

|===
