== [[TopicConfig]] TopicConfig

`TopicConfig` are the <<keys, keys>> for a topic-level configuration (and override <<kafka-server-KafkaConfig.adoc#, cluster-wide defaults>> with `log.` prefix).

[source, scala]
----
import org.apache.kafka.common.config.TopicConfig
assert(TopicConfig.CLEANUP_POLICY_CONFIG == "cleanup.policy")
----

[[keys]]
.Keys
[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| cleanup.policy
a| [[cleanup.policy]][[CLEANUP_POLICY_CONFIG]] <<kafka-log-LogConfig.adoc#CleanupPolicyProp, LogConfig.CleanupPolicyProp>>

Used when:

* `LogConfig` is requested for <<kafka-log-LogConfig.adoc#CleanupPolicyProp, LogConfig.CleanupPolicyProp>>

* (Kafka Streams) `RepartitionTopicConfig` is requested for `REPARTITION_TOPIC_DEFAULT_OVERRIDES`

* (Kafka Streams) `UnwindowedChangelogTopicConfig` is requested for `UNWINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES`

* (Kafka Streams) `WindowedChangelogTopicConfig` is requested for `WINDOWED_STORE_CHANGELOG_TOPIC_DEFAULT_OVERRIDES`

| flush.messages
a| [[flush.messages]][[FLUSH_MESSAGES_INTERVAL_CONFIG]] <<kafka-log-LogConfig.adoc#FlushMessagesProp, LogConfig.FlushMessagesProp>>

| flush.ms
a| [[flush.ms]][[FLUSH_MS_CONFIG]] <<kafka-log-LogConfig.adoc#FlushMsProp, LogConfig.FlushMsProp>>

| index.interval.bytes
a| [[index.interval.bytes]][[INDEX_INTERVAL_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#IndexIntervalBytesProp, LogConfig.IndexIntervalBytesProp>>

| min.insync.replicas
a| [[min.insync.replicas]][[MIN_IN_SYNC_REPLICAS_CONFIG]] link:kafka-properties.adoc#min.insync.replicas[min.insync.replicas]

Used when:

* link:kafka-admin-TopicCommand.adoc[TopicCommand] is executed

* Alias for link:kafka-log-LogConfig.adoc#MinInSyncReplicasProp[LogConfig.MinInSyncReplicasProp]

| retention.bytes
a| [[retention.bytes]][[RETENTION_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#RetentionBytesProp, LogConfig.RetentionBytesProp>>

| retention.ms
a| [[retention.ms]][[RETENTION_MS_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentBytesProp, LogConfig.SegmentBytesProp>>

| segment.bytes
a| [[segment.bytes]][[SEGMENT_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentBytesProp, LogConfig.SegmentBytesProp>>

Used when:

* (Kafka Streams) `StreamsConfig` is requested to `getMainConsumerConfigs`

* (Kafka Streams) `RepartitionTopicConfig` is requested for `REPARTITION_TOPIC_DEFAULT_OVERRIDES`

| segment.index.bytes
a| [[segment.index.bytes]][[SEGMENT_INDEX_BYTES_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentIndexBytesProp, LogConfig.SegmentIndexBytesProp>>

| segment.jitter.ms
a| [[segment.jitter.ms]][[SEGMENT_JITTER_MS_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentJitterMsProp, LogConfig.SegmentJitterMsProp>>

| segment.ms
a| [[segment.ms]][[SEGMENT_MS_CONFIG]] <<kafka-log-LogConfig.adoc#SegmentMsProp, LogConfig.SegmentMsProp>>

|===
