== Kafka Properties

[[properties]]
.Properties
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| advertised.listeners
a| [[advertised.listeners]] Comma-separated list of URIs to publish to ZooKeeper for clients to use, if different than the <<listeners, listeners>> config property.

Default: `null`

In IaaS environments (e.g. Docker, Kubernetes, a cloud), `advertised.listeners` may need to be different from the interface to which a Kafka broker binds. That ensures that the Kafka broker advertises an address that is accessible from both local and external hosts. If not set, the value for <<listeners, listeners>> is used.

Unlike <<listeners, listeners>> it is invalid to advertise the `0.0.0.0` non-routable meta-address.

* Use <<kafka-server-KafkaConfig.adoc#AdvertisedListenersProp, KafkaConfig.AdvertisedListenersProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#advertisedListeners, KafkaConfig.advertisedListeners>> to access the current value

<<kafka-server-DynamicListenerConfig.adoc#, Dynamic reconfigurable configuration>>

| authorizer.class.name
a| [[authorizer.class.name]] Fully-qualified class name of the <<kafka-security-Authorizer.adoc#, Authorizer>> for <<kafka-server-KafkaApis.adoc#authorize, authorization>>

Default: `(empty)`

* Use <<kafka-server-KafkaConfig.adoc#AuthorizerClassNameProp, KafkaConfig.AuthorizerClassNameProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#authorizerClassName, KafkaConfig.authorizerClassName>> to access the current value

| auto.commit.interval.ms
a| [[auto.commit.interval.ms]] How often (in milliseconds) consumer offsets should be auto-committed when <<enable.auto.commit, enable.auto.commit>> is enabled

| auto.create.topics.enable
a| [[auto.create.topics.enable]] Enables auto creation of a topic

Default: `true`

* Use `KafkaConfig.AutoCreateTopicsEnableProp` to reference the property

* Use <<kafka-server-KafkaConfig.adoc#autoCreateTopicsEnable, KafkaConfig.autoCreateTopicsEnable>> to access the current value

| auto.leader.rebalance.enable
a| [[auto.leader.rebalance.enable]] Enables auto leader balancing

Default: `true`

A <<kafka-controller-KafkaController.adoc#scheduleAutoLeaderRebalanceTask, background thread>> checks and triggers leader balance if required.

* Use `KafkaConfig.AutoLeaderRebalanceEnableProp` to reference the property

* Use <<kafka-server-KafkaConfig.adoc#autoLeaderRebalanceEnable, KafkaConfig.autoLeaderRebalanceEnable>> to access the current value

| auto.offset.reset
a| [[auto.offset.reset]] Reset policy -- what to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted):

* *earliest* -- automatically reset the offset to the earliest offset
* *latest* -- automatically reset the offset to the latest offset
* *none* -- throw an exception to the consumer if no previous offset is found for the consumer's group
* anything else: throw an exception to a consumer

Default: `latest`

| background.threads
a| [[background.threads]] The number of threads to use for various background processing tasks

Default: `10`

Must be at least `1`

<<kafka-server-DynamicThreadPool.adoc#, Dynamic reconfigurable configuration>>

| link:kafka-properties-bootstrap-servers.adoc[bootstrap.servers]
a| [[bootstrap.servers]] A comma-separated list of `host:port` pairs that are the addresses of one or more brokers in a link:kafka-brokers.adoc[Kafka cluster], e.g. `localhost:9092` or `localhost:9092,another.host:9092`.

Default: `(empty)`

| broker.id
| [[broker.id]] The broker id of a Kafka broker for identification purposes

If unset, a unique broker id will be generated. To avoid conflicts between zookeeper generated broker id's and user configured broker id's, generated broker IDs start from <<reserved.broker.max.id, reserved.broker.max.id>> + 1.

Use <<kafka-server-KafkaConfig.adoc#brokerId, KafkaConfig.brokerId>> to access the current value.

| broker.id.generation.enable
a| [[broker.id.generation.enable]] Enables *automatic broker id generation* of a Kafka broker

Default: `true`

When enabled (`true`) the value configured for <<reserved.broker.max.id, reserved.broker.max.id>> should be checked.

* Use `KafkaConfig.BrokerIdGenerationEnableProp` to reference the property

* Use <<kafka-server-KafkaConfig.adoc#brokerIdGenerationEnable, KafkaConfig.brokerIdGenerationEnable>> to access the current value

| broker.rack
| [[broker.rack]]

| check.crcs
| [[check.crcs]] Automatically check the CRC32 of the records consumed. This ensures no on-the-wire or on-disk corruption to the messages occurred. This check adds some overhead, so it may be disabled in cases seeking extreme performance.

Use `ConsumerConfig.CHECK_CRCS_CONFIG`

| link:kafka-properties-client-id.adoc[client.id]
a| [[client.id]]

Default: `(randomly-generated)`

| connection.failed.authentication.delay.ms
a| [[connection.failed.authentication.delay.ms]] Connection close delay on failed authentication: this is the time (in milliseconds) by which connection close will be delayed on authentication failure. This must be configured to be less than <<connections.max.idle.ms, connections.max.idle.ms>> to prevent connection timeout.

Default: `100`

Has to be at least `0`

| connections.max.idle.ms
a| [[connections.max.idle.ms]] Idle connections timeout: the server socket processor threads close the connections that idle more than this

Default: `10 * 60 * 1000L`

| default.replication.factor
a| [[default.replication.factor]] The default replication factor that is used for auto-created topics

Default: `1`

Increase the default value to at least `2`

| delegation.token.master.key
a| [[delegation.token.master.key]]

| delete.topic.enable
a| [[delete.topic.enable]] Enables topic deletion

NOTE: Deleting topic through the admin tool has no effect with the property disabled.

Default: `true`

| link:kafka-properties-enable-auto-commit.adoc[enable.auto.commit]
a| [[enable.auto.commit]] When enabled (i.e. `true`) consumer offsets are committed automatically in the background (aka _consumer auto commit_) every <<auto.commit.interval.ms, auto.commit.interval.ms>>

Default: `true`

When disabled, offsets have to be committed manually (synchronously using link:kafka-consumer-KafkaConsumer.adoc#commitSync[KafkaConsumer.commitSync] or asynchronously link:kafka-consumer-KafkaConsumer.adoc#commitAsync[KafkaConsumer.commitAsync]). On restart restore the position of a consumer using link:kafka-consumer-KafkaConsumer.adoc#seek[KafkaConsumer.seek].

Used when `KafkaConsumer` is link:kafka-consumer-KafkaConsumer.adoc#creating-instance[created] and creates a link:kafka-consumer-internals-ConsumerCoordinator.adoc#autoCommitEnabled[ConsumerCoordinator].

| fetch.max.bytes
| [[fetch.max.bytes]] The maximum amount of data the server should return for a fetch request. Records are fetched in batches by the consumer, and if the first record batch in the first non-empty partition of the fetch is larger than this value, the record batch will still be returned to ensure that the consumer can make progress. As such, this is not a absolute maximum. The maximum record batch size accepted by the broker is defined via <<message.max.bytes, message.max.bytes>> (broker config) or <<max.message.bytes, max.message.bytes>> (topic config). Note that the consumer performs multiple fetches in parallel.

Use `ConsumerConfig.FETCH_MAX_BYTES_CONFIG`

| fetch.max.wait.ms
| [[fetch.max.wait.ms]] The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.

Use `ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG`

| fetch.min.bytes
| [[fetch.min.bytes]] The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.

Use `ConsumerConfig.FETCH_MIN_BYTES_CONFIG`

| link:kafka-properties-group-id.adoc[group.id]
| [[group.id]] The name of the consumer group the consumer is part of.

| heartbeat.interval.ms
| [[heartbeat.interval.ms]][[heartbeat_interval_ms]] The expected time between heartbeats to the group coordinator when using Kafka's group management facilities.

| host.name
a| [[host.name]] The hostname a Kafka broker listens on

Default: `(empty)`

| inter.broker.listener.name
a| [[inter.broker.listener.name]] Name of the listener that is used for inter-broker communication

Default: <<security.inter.broker.protocol, security.inter.broker.protocol>>

It is not allowed to set `inter.broker.listener.name` and <<security.inter.broker.protocol, security.inter.broker.protocol>> properties at the same time.

| inter.broker.protocol.version
a| [[inter.broker.protocol.version]] Version of the inter-broker protocol

Default: the latest `ApiVersion` (e.g. `2.1-IV2`)

Typically bumped up after all brokers were upgraded to a new version

* Use <<kafka-server-KafkaConfig.adoc#InterBrokerProtocolVersionProp, KafkaConfig.InterBrokerProtocolVersionProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#interBrokerProtocolVersionString, KafkaConfig.interBrokerProtocolVersionString>> to access the current value

| interceptor.classes
a| [[interceptor.classes]] Comma-separated list of link:kafka-consumer-ConsumerInterceptor.adoc[ConsumerInterceptor] class names.

Default: `(empty)`

| key.deserializer
| [[key.deserializer]] How to deserialize message keys.

| leader.imbalance.check.interval.seconds
a| [[leader.imbalance.check.interval.seconds]] How often the active <<kafka-controller-KafkaController.adoc#, KafkaController>> schedules the <<kafka-controller-KafkaController.adoc#scheduleAutoLeaderRebalanceTask, auto-leader-rebalance-task>> (aka _AutoLeaderRebalance_ or _AutoPreferredReplicaLeaderElection_ or _auto leader balancing_)

Default: `300`

* Use <<kafka-server-KafkaConfig.adoc#LeaderImbalanceCheckIntervalSecondsProp, KafkaConfig.LeaderImbalanceCheckIntervalSecondsProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#leaderImbalanceCheckIntervalSeconds, KafkaConfig.leaderImbalanceCheckIntervalSeconds>> to access the current value

| leader.imbalance.per.broker.percentage
a| [[leader.imbalance.per.broker.percentage]] Allowed ratio of leader imbalance per broker. The controller would trigger a leader balance if it goes above this value per broker. The value is specified in percentage.

Default: `10`

* Use <<kafka-server-KafkaConfig.adoc#LeaderImbalancePerBrokerPercentageProp, KafkaConfig.LeaderImbalancePerBrokerPercentageProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#leaderImbalancePerBrokerPercentage, KafkaConfig.leaderImbalancePerBrokerPercentage>> to access the current value

| listeners
a| [[listeners]] Comma-separated list of URIs and listener names that a Kafka broker will listen on

Default: ``PLAINTEXT://<<host.name, host.name>>:<<port, port>>``

Use `0.0.0.0` to bind to all the network interfaces on a machine or leave it empty to bind to the default interface.

* Use <<kafka-server-KafkaConfig.adoc#ListenersProp, KafkaConfig.ListenersProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#listeners, KafkaConfig.listeners>> to access the current value

<<kafka-server-DynamicListenerConfig.adoc#, Dynamic reconfigurable configuration>>

| listener.security.protocol.map
a| [[listener.security.protocol.map]]

| log.cleaner.enable
a| [[log.cleaner.enable]]

| log.cleaner.threads
a| [[log.cleaner.threads]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleaner.dedupe.buffer.size
a| [[log.cleaner.dedupe.buffer.size]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleaner.io.buffer.load.factor
a| [[log.cleaner.io.buffer.load.factor]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleaner.io.buffer.size
a| [[log.cleaner.io.buffer.size]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleaner.io.max.bytes.per.second
a| [[log.cleaner.io.max.bytes.per.second]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleaner.backoff.ms
a| [[log.cleaner.backoff.ms]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| log.cleanup.policy
a| [[log.cleanup.policy]] <<kafka-log-cleanup-policies.adoc#, Log Cleanup Policies (Strategies) -- Log Compaction And Retention>>

Default: <<kafka-log-cleanup-policies.adoc#delete, delete>>

Included in <<kafka-server-KafkaServer.adoc#copyKafkaConfigToLog, copyKafkaConfigToLog>> (to set <<kafka-log-LogConfig.adoc#cleanup.policy, cleanup.policy>> of topics)

* Use <<kafka-server-KafkaConfig.adoc#LogCleanupPolicyProp, KafkaConfig.LogCleanupPolicyProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#logCleanupPolicy, KafkaConfig.logCleanupPolicy>> to access the current value

| log.dir
a| [[log.dir]] The directory in which the log data is kept

Default: `/tmp/kafka-logs`

| log.dirs
a| [[log.dirs]] The directories in which the log data is kept

Default: <<log.dir, log.dir>>

Use <<kafka-server-KafkaConfig.adoc#logDirs, KafkaConfig.logDirs>> to access the current value.

| log.index.size.max.bytes
a| [[log.index.size.max.bytes]] Maximum size in bytes of the offset index

Default: `10 * 1024 * 1024`

Must be at least `4`

Use <<kafka-server-KafkaConfig.adoc#logIndexSizeMaxBytes, KafkaConfig.logIndexSizeMaxBytes>> to access the current value.

| log.segment.bytes
a| [[log.segment.bytes]] The maximum size of a segment file of logs. Retention and cleaning are always done one file at a time so a larger segment size means fewer files but less granular control over retention.

Default: `1 * 1024 * 1024 * 1024`

Must be at least `14` bytes (`LegacyRecord.RECORD_OVERHEAD_V0`)

Use <<kafka-server-KafkaConfig.adoc#logSegmentBytes, KafkaConfig.logSegmentBytes>> to access the current value.

| max.block.ms
a| [[max.block.ms]]

| max.partition.fetch.bytes
a| [[max.partition.fetch.bytes]] The maximum amount of data per-partition the server will return. Records are fetched in batches by the consumer. If the first record batch in the first non-empty partition of the fetch is larger than this limit, the batch will still be returned to ensure that the consumer can make progress. The maximum record batch size accepted by the broker is defined via <<message.max.bytes, message.max.bytes>> (broker config) or <<max.message.bytes, max.message.bytes>> (topic config).

Use `ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG`

NOTE: Use <<fetch.max.bytes, fetch.max.bytes>> for limiting the consumer request size.

| max.poll.records
a| [[max.poll.records]] (KafkaConsumer) The maximum number of records returned from a Kafka `Consumer` when link:kafka-consumer-Consumer.adoc#poll[polling topics for records].

The default setting (`-1`) sets no upper bound on the number of records, i.e. `Consumer.poll()` will return as soon as either any data is available or the passed timeout expires.

`max.poll.records` was added to Kafka in https://issues.apache.org/jira/browse/KAFKA-3007[0.10.0.0] by https://cwiki.apache.org/confluence/display/KAFKA/KIP-41%3A+KafkaConsumer+Max+Records[KIP-41: KafkaConsumer Max Records].

From https://groups.google.com/d/msg/kafka-clients/5jagwTywVb8/2v7vYg9SBAAJ[kafka-clients] mailing list:

> `max.poll.records` only controls the number of records returned from poll, but does not affect fetching. The consumer will try to prefetch records from all partitions it is assigned. It will then buffer those records and return them in batches of `max.poll.records` each (either all from the same topic partition if there are enough left to satisfy the number of records, or from multiple topic partitions if the data from the last fetch for one of the topic partitions does not cover the `max.poll.records`).

Use `ConsumerConfig.MAX_POLL_RECORDS_CONFIG`.

---

Internally, `max.poll.records` is used exclusively when `KafkaConsumer` is link:kafka-consumer-KafkaConsumer.adoc#creating-instance[created] (to create a link:kafka-consumer-KafkaConsumer.adoc#fetcher[Fetcher]).

| message.max.bytes
a| [[message.max.bytes]]

<<kafka-server-LogCleaner.adoc#, Dynamic reconfigurable configuration>>

| metadata.max.age.ms
| [[metadata.max.age.ms]]

| metric.reporters
| [[metric.reporters]][[metric_reporters]] The list of fully-qualified classes names of the link:kafka-MetricsReporter.adoc[metrics reporters].

Default: <<kafka-MetricsReporter.adoc#JmxReporter, JmxReporter>>

| metrics.num.samples
| [[metrics.num.samples]][[metrics_num_samples]] Number of samples to compute metrics.

| metrics.sample.window.ms
| [[metrics.sample.window.ms]][[metrics_sample_window_ms]] Time window (in milliseconds) a metrics sample is computed over.

| min.insync.replicas
a| [[min.insync.replicas]] The minimum number of replicas in ISR that is needed to commit a produce request with `required.acks=-1` (or `all`)

Default: `1`

When a Kafka producer sets acks to `all` (or `-1`), this configuration specifies the minimum number of replicas that must acknowledge a write for the write to be considered successful.

If this minimum cannot be met, then the producer will raise an exception (either `NotEnoughReplicas` or `NotEnoughReplicasAfterAppend`).

When used together, `min.insync.replicas` and acks allow you to enforce greater durability guarantees.

A typical scenario would be to create a topic with a replication factor of 3, set `min.insync.replicas` to 2, and produce with acks of "all". This will ensure that the producer raises an exception if a majority of replicas do not receive a write.

| num.io.threads
a| [[num.io.threads]] The number of threads that link:kafka-server-KafkaServer.adoc[KafkaServer] uses for processing requests, which may include disk I/O

Default: `8`

Must be at least `1`

<<kafka-server-DynamicThreadPool.adoc#, Dynamic reconfigurable configuration>>

| max.connections.per.ip
a| [[max.connections.per.ip]] The maximum number of connections allowed from each ip address.

Default: `Int.MaxValue`

Must be at least `0` (with `0` if there are overrides configured using <<max.connections.per.ip.overrides, max.connections.per.ip.overrides>> property)

<<kafka-server-DynamicConnectionQuota.adoc#, Dynamic reconfigurable configuration>>

| max.connections.per.ip.overrides
a| [[max.connections.per.ip.overrides]] A comma-separated list of per-ip or hostname overrides to the default <<max.connections.per.ip, maximum number of connections>>, e.g. `hostName:100,127.0.0.1:200`

Default: (empty)

<<kafka-server-DynamicConnectionQuota.adoc#, Dynamic reconfigurable configuration>>

| num.network.threads
a| [[num.network.threads]] The number of threads that SocketServer uses for the link:kafka-network-SocketServer.adoc#numProcessorThreads[number of processors per endpoint] (for receiving requests from the network and sending responses to the network)

Default: `3`

Must be at least `1`

<<kafka-server-DynamicThreadPool.adoc#, Dynamic reconfigurable configuration>>

| num.partitions
| [[num.partitions]] The number of log partitions for auto-created topics

Default: `1`

Increase the default value (`1`) since it is better to over-partition a topic that leads to a better data balancing and aids consumer parallelism.

| num.recovery.threads.per.data.dir
a| [[num.recovery.threads.per.data.dir]] The number of threads per log data directory for log recovery at startup and flushing at shutdown

Default: `1`

Must be at least `1`

<<kafka-server-DynamicThreadPool.adoc#, Dynamic reconfigurable configuration>>

| num.replica.fetchers
a| [[num.replica.fetchers]] The number of fetcher threads used to replicate messages from a source broker.

Increasing this value can increase the degree of I/O parallelism in the follower broker.

Default: `1`

<<kafka-server-DynamicThreadPool.adoc#, Dynamic reconfigurable configuration>>

| port
| [[port]] The port a Kafka broker listens on

Default: `9092`

| principal.builder.class
a| [[principal.builder.class]]

| replica.fetch.backoff.ms
a| [[replica.fetch.backoff.ms]] The amount of time to sleep when fetch partition error occurs.

Default: `1000`

Must be at least `0`

* Use <<kafka-server-KafkaConfig.adoc#ReplicaFetchBackoffMsProp, KafkaConfig.ReplicaFetchBackoffMsProp>> to reference the property

* Use <<kafka-server-KafkaConfig.adoc#replicaFetchBackoffMs, KafkaConfig.replicaFetchBackoffMs>> to access the current value

| queued.max.requests
a| [[queued.max.requests]] The number of queued requests allowed before blocking the network threads

Default: `500`

Must be at least `1`

| rebalance.timeout.ms
| [[rebalance.timeout.ms]][[rebalance_timeout_ms]] The maximum allowed time for each worker to join the group once a rebalance has begun.

| receive.buffer.bytes
| [[receive.buffer.bytes]] The hint about the size of the TCP network receive buffer (SO_RCVBUF) to use (for a socket) when reading data. If the value is -1, the OS default will be used.

| replica.lag.time.max.ms
a| [[replica.lag.time.max.ms]]

| replica.socket.timeout.ms
| [[replica.socket.timeout.ms]]

| request.timeout.ms
| [[request.timeout.ms]] The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.

Use `ConsumerConfig.REQUEST_TIMEOUT_MS_CONFIG`

| reserved.broker.max.id
| [[reserved.broker.max.id]] Maximum number that can be used for <<broker.id, broker.id>>. Has to be at least `0`.

Default: `1000`

* Use `KafkaConfig.MaxReservedBrokerIdProp` to reference the property

* Use <<kafka-server-KafkaConfig.adoc#maxReservedBrokerId, KafkaConfig.maxReservedBrokerId>> to access the current value

| link:kafka-properties-retry-backoff-ms.adoc[retry.backoff.ms]
| [[retry.backoff.ms]] Time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.

Use `ConsumerConfig.RETRY_BACKOFF_MS_CONFIG`

| sasl.mechanism.inter.broker.protocol
a| [[sasl.mechanism.inter.broker.protocol]]

| sasl.jaas.config
a| [[sasl.jaas.config]]

| sasl.enabled.mechanisms
a| [[sasl.enabled.mechanisms]]

| sasl.kerberos.service.name
a| [[sasl.kerberos.service.name]]

| sasl.kerberos.kinit.cmd
a| [[sasl.kerberos.kinit.cmd]]

| sasl.kerberos.ticket.renew.window.factor
a| [[sasl.kerberos.ticket.renew.window.factor]]

| sasl.kerberos.ticket.renew.jitter
a| [[sasl.kerberos.ticket.renew.jitter]]

| sasl.kerberos.min.time.before.relogin
a| [[sasl.kerberos.min.time.before.relogin]]

| sasl.kerberos.principal.to.local.rules
a| [[sasl.kerberos.principal.to.local.rules]]

| sasl.login.refresh.window.factor
a| [[sasl.login.refresh.window.factor]]

| sasl.login.refresh.window.jitter
a| [[sasl.login.refresh.window.jitter]]

| sasl.login.refresh.min.period.seconds
a| [[sasl.login.refresh.min.period.seconds]]

| sasl.login.refresh.buffer.seconds
a| [[sasl.login.refresh.buffer.seconds]]

| send.buffer.bytes
| [[send.buffer.bytes]] The hint about the size of the TCP network send buffer (SO_SNDBUF) to use (for a socket) when sending data. If the value is -1, the OS default will be used.

| session.timeout.ms
| [[session.timeout.ms]][[session_timeout_ms]] The timeout used to detect worker failures.

Default: `10000`

| socket.request.max.bytes
a| [[socket.request.max.bytes]] The maximum number of bytes in a socket request

Default: `100 * 1024 * 1024`

Must be at least `1`

| ssl.protocol
a| [[ssl.protocol]]

| ssl.provider
a| [[ssl.provider]]

| ssl.cipher.suites
a| [[ssl.cipher.suites]]

| ssl.enabled.protocols
a| [[ssl.enabled.protocols]]

| ssl.keystore.type
a| [[ssl.keystore.type]]

| ssl.keystore.location
a| [[ssl.keystore.location]]

| ssl.keystore.password
a| [[ssl.keystore.password]]

| ssl.key.password
a| [[ssl.key.password]]

| ssl.truststore.type
a| [[ssl.truststore.type]]

| ssl.truststore.location
a| [[ssl.truststore.location]]

| ssl.truststore.password
a| [[ssl.truststore.password]]

| ssl.keymanager.algorithm
a| [[ssl.keymanager.algorithm]]

| ssl.trustmanager.algorithm
a| [[ssl.trustmanager.algorithm]]

| ssl.endpoint.identification.algorithm
a| [[ssl.endpoint.identification.algorithm]]

| ssl.secure.random.implementation
a| [[ssl.secure.random.implementation]]

| ssl.client.auth
a| [[ssl.client.auth]]

| transaction.max.timeout.ms
a| [[transaction.max.timeout.ms]] The maximum allowed timeout for transactions (in millis).

If a client's requested transaction time exceed this, then the broker will return an error in `InitProducerIdRequest`. This prevents a client from a too large timeout that can stall consumers reading from topics included in the transaction.

Default: `15 minutes`

Must be at least `1`

* Use <<kafka-server-KafkaConfig.adoc#transactionMaxTimeoutMs, KafkaConfig.transactionMaxTimeoutMs>> to access the current value

| unclean.leader.election.enable
a| [[unclean.leader.election.enable]] Controls whether to enable replicas not in the ISR set to be elected as leader as the last resort, even though doing so may result in data loss.

Default: `1`

| value.deserializer
| [[value.deserializer]][[value_deserializer]] How to deserialize message values

| zookeeper.connect
a| [[zookeeper.connect]] Comma-separated list of Zookeeper hosts (as `host:port` pairs) that brokers register to, e.g. `localhost:2181`, `127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002`

Default: `(empty)`

Zookeeper URIs can have an optional chroot path suffix at the end, e.g. `127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002/app/a`

If the optional chroot path suffix is used, all paths are relative to this path.

It is recommended to include all the hosts in a Zookeeper ensemble (cluster)

* Available as `KafkaConfig.ZkConnectProp`

* Use <<kafka-server-KafkaConfig.adoc#zkConnect, KafkaConfig.zkConnect>> to access the current value

| zookeeper.connection.timeout.ms
a| [[zookeeper.connection.timeout.ms]] The max time that the client waits to establish a connection to zookeeper

Default: <<zookeeper.session.timeout.ms, zookeeper.session.timeout.ms>>

* Available as `KafkaConfig.ZkConnectionTimeoutMsProp`

* Use <<kafka-server-KafkaConfig.adoc#zkConnectionTimeoutMs, KafkaConfig.zkConnectionTimeoutMs>> to access the current value

| zookeeper.max.in.flight.requests
a| [[zookeeper.max.in.flight.requests]] The maximum number of unacknowledged requests the client will send to Zookeeper before blocking. Has to be at least 1

Default: `10`

* Available as `KafkaConfig.ZkMaxInFlightRequestsProp`

* Use <<kafka-server-KafkaConfig.adoc#zkMaxInFlightRequests, KafkaConfig.zkMaxInFlightRequests>> to access the current value

| zookeeper.session.timeout.ms
a| [[zookeeper.session.timeout.ms]] Zookeeper session timeout

Default: `6000`

* Available as `KafkaConfig.ZkSessionTimeoutMsProp`

* Use <<kafka-server-KafkaConfig.adoc#zkSessionTimeoutMs, KafkaConfig.zkSessionTimeoutMs>> to access the current value

| zookeeper.set.acl
a| [[zookeeper.set.acl]] Enables secure ACLs

Default: `false`

* Available as `KafkaConfig.ZkEnableSecureAclsProp`

* Use <<kafka-server-KafkaConfig.adoc#zkEnableSecureAcls, KafkaConfig.zkEnableSecureAcls>> to access the current value

|===
