== [[ReplicaAlterLogDirsThread]] ReplicaAlterLogDirsThread

`ReplicaAlterLogDirsThread` is an uninterruptible <<kafka-server-AbstractFetcherThread.adoc#, AbstractFetcherThread>> that...FIXME

`ReplicaAlterLogDirsThread` uses <<kafka-properties.adoc#replica.fetch.backoff.ms, replica.fetch.backoff.ms>> configuration property for the <<kafka-server-AbstractFetcherThread.adoc#fetchBackOffMs, fetchBackOffMs>>.

`ReplicaAlterLogDirsThread` is <<creating-instance, created>> exclusively when `ReplicaAlterLogDirsManager` is requested to <<kafka-server-ReplicaAlterLogDirsManager.adoc#createFetcherThread, create a fetcher thread>> (when...FIXME).

[[isOffsetForLeaderEpochSupported]]
`ReplicaAlterLogDirsThread` has <<kafka-server-AbstractFetcherThread.adoc#isOffsetForLeaderEpochSupported, isOffsetForLeaderEpochSupported>> flag always enabled (`true`).

=== [[fetchFromLeader]] `fetchFromLeader` Method

[source, scala]
----
fetchFromLeader(
  fetchRequest: FetchRequest.Builder): Seq[(TopicPartition, FetchData)]
----

NOTE: `fetchFromLeader` is part of the <<kafka-server-AbstractFetcherThread.adoc#fetchFromLeader, AbstractFetcherThread Contract>> to...FIXME.

`fetchFromLeader`...FIXME

=== [[processPartitionData]] `processPartitionData` Method

[source, scala]
----
processPartitionData(
  topicPartition: TopicPartition,
  fetchOffset: Long,
  partitionData: PartitionData[Records]): Option[LogAppendInfo]
----

NOTE: `processPartitionData` is part of the <<kafka-server-AbstractFetcherThread.adoc#processPartitionData, AbstractFetcherThread Contract>> to...FIXME.

`processPartitionData`...FIXME

=== [[truncateFullyAndStartAt]] `truncateFullyAndStartAt` Method

[source, scala]
----
truncateFullyAndStartAt(
  topicPartition: TopicPartition,
  offset: Long): Unit
----

NOTE: `truncateFullyAndStartAt` is part of the <<kafka-server-AbstractFetcherThread.adoc#truncateFullyAndStartAt, AbstractFetcherThread Contract>> to...FIXME.

`truncateFullyAndStartAt`...FIXME

=== [[truncate]] `truncate` Method

[source, scala]
----
truncate(
  topicPartition: TopicPartition,
  truncationState: OffsetTruncationState): Unit
----

NOTE: `truncate` is part of the <<kafka-server-AbstractFetcherThread.adoc#truncate, AbstractFetcherThread Contract>> to...FIXME.

`truncate`...FIXME

=== [[buildFetch]] `buildFetch` Method

[source, scala]
----
buildFetch(
  partitionMap: Map[TopicPartition, PartitionFetchState]
): ResultWithPartitions[Option[FetchRequest.Builder]]
----

NOTE: `buildFetch` is part of the <<kafka-server-AbstractFetcherThread.adoc#buildFetch, AbstractFetcherThread Contract>> to...FIXME

`buildFetch`...FIXME

=== [[creating-instance]] Creating ReplicaAlterLogDirsThread Instance

`ReplicaAlterLogDirsThread` takes the following to be created:

* [[name]] Thread Name
* [[sourceBroker]] Source `BrokerEndPoint`
* [[brokerConfig]] <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>
* [[replicaMgr]] <<kafka-server-ReplicaManager.adoc#, ReplicaManager>>
* [[quota]] <<kafka-server-ReplicationQuotaManager.adoc#, ReplicationQuotaManager>>
* [[brokerTopicStats]] <<kafka-server-BrokerTopicStats.adoc#, BrokerTopicStats>>

`ReplicaAlterLogDirsThread` initializes the <<internal-registries, internal registries and counters>>.
