== Log Cleanup Policies (Strategies) -- Log Compaction And Retention

Kafka uses <<kafka-properties.adoc#log.cleanup.policy, log.cleanup.policy>> configuration property to define *cleanup strategies* (policy) of <<kafka-log-Log.adoc#, logs>>:

* <<log-compaction, Log Compaction>>

* <<log-retention, Log Retention>>

Kafka uses link:kafka-properties.adoc#log.retention.check.interval.ms[log.retention.check.interval.ms] configuration property as the interval between regular log checks.

=== [[log.cleanup.policy]][[cleanup.policy]] log.cleanup.policy and cleanup.policy Configuration Properties

The cluster-wide <<kafka-properties.adoc#log.cleanup.policy, log.cleanup.policy>> and the per-topic <<kafka-common-TopicConfig.adoc#cleanup.policy, cleanup.policy>> configuration properties are comma-separated lists of cleanup strategies:

* [[compact]] *compact* - enables <<log-compaction, log compaction>>

* [[delete]] *delete* - enables <<log-retention, log retention>>

Unless defined, <<kafka-common-TopicConfig.adoc#cleanup.policy, cleanup.policy>> is exactly <<kafka-properties.adoc#log.cleanup.policy, log.cleanup.policy>>.

=== [[log-compaction]] Log Compaction

*Log Compaction* is a cleanup strategy in which...FIXME

Kafka brokers use <<kafka-log-LogCleaner.adoc#, LogCleaner>> for <<compact, compact>> retention strategy.

Log compaction can be <<kafka-log-CleanerConfig.adoc#, reconfigured dynamically at runtime>>.

=== [[log-retention]] Log Retention

*Log Retention* (_Garbage Collection_) is a cleanup strategy to discard (_delete_) old log segments when their <<log-retention-time, retention time>> or <<log-retention-size, size limit>> has been reached.

By default there is only a time limit and no size limit.

[[log-retention-time]]
*Retention time* is controlled by the cluster-wide <<kafka-properties.adoc#log.retention.ms, log.retention.ms>>, <<kafka-properties.adoc#log.retention.minutes, log.retention.minutes>> or <<kafka-properties.adoc#log.retention.hours, log.retention.hours>> configuration properties (from the highest to the lowest priority) or their per-topic <<kafka-common-TopicConfig.adoc#retention.ms, retention.ms>> configuration property.

[[log-retention-size]]
*Retention size* is controlled by the cluster-wide <<kafka-properties.adoc#log.retention.bytes, log.retention.bytes>> or per-topic <<kafka-common-TopicConfig.adoc#retention.bytes, retention.bytes>> configuration property.

Enable `ALL` logging level for <<kafka-log-Log.adoc#logging, kafka.log.Log>> logger to see messages related to log retention.

Kafka brokers schedule <<kafka-server-scheduled-tasks.adoc#kafka-log-retention, kafka-log-retention>> periodic task for <<delete, delete>> retention strategy.
