== [[AbstractCoordinator]] AbstractCoordinator

`AbstractCoordinator` is a <<contract, contract>> for...FIXME

NOTE: `AbstractCoordinator` is a Java abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<extensions, concrete Coordinators>>.

[[extensions]]
NOTE: <<kafka-consumer-internals-ConsumerCoordinator.adoc#, ConsumerCoordinator>> is the one and only known implementation of the <<contract, AbstractCoordinator Contract>> in Apache Kafka's Consumer API.

[[contract]]
[source, java]
----
package org.apache.kafka.clients.consumer.internals;

abstract class AbstractCoordinator {
  void onJoinComplete(
    int generation,
    String memberId,
    String protocol,
    ByteBuffer memberAssignment);
  void onJoinPrepare(int generation, String memberId);
  Map<String, ByteBuffer> performAssignment(
    String leaderId,
    String protocol,
    Map<String, ByteBuffer> allMemberMetadata);
  ...FIXME
}
----

.AbstractCoordinator Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[onJoinComplete]] `onJoinComplete`
| Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and the request to <<initiateJoinGroup, initiateJoinGroup>> succeeded)

| [[onJoinPrepare]] `onJoinPrepare`
| Used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (and <<needsJoinPrepare, needsJoinPrepare>> flag is on)

| [[performAssignment]] `performAssignment`
|
|===

[[internal-registries]]
.AbstractCoordinator's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[joinFuture]] `joinFuture`
| `RequestFuture<ByteBuffer>` for...FIXME

| [[needsJoinPrepare]] `needsJoinPrepare`
| Controls when to execute <<onJoinPrepare, onJoinPrepare>> while performing <<joinGroupIfNeeded, joinGroupIfNeeded>>

| [[rejoinNeeded]] `rejoinNeeded`
| Controls when to...FIXME
|===

=== [[creating-instance]] Creating AbstractCoordinator Instance

`AbstractCoordinator` takes the following when created:

* [[logContext]] `LogContext`
* [[client]] link:kafka-consumer-internals-ConsumerNetworkClient.adoc[ConsumerNetworkClient]
* [[groupId]] Group ID
* [[rebalanceTimeoutMs]] `rebalanceTimeoutMs`
* [[sessionTimeoutMs]] `sessionTimeoutMs`
* [[heartbeatIntervalMs]] `heartbeatIntervalMs`
* [[metrics]] `Metrics`
* [[metricGrpPrefix]] Metric group prefix
* [[time]] `Time`
* [[retryBackoffMs]] `retryBackoffMs`
* [[leaveGroupOnClose]] `leaveGroupOnClose` flag

=== [[joinGroupIfNeeded]] `joinGroupIfNeeded` Method

[source, java]
----
void joinGroupIfNeeded()
----

`joinGroupIfNeeded`...FIXME

NOTE: `joinGroupIfNeeded` is used exclusively when `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>>.

=== [[initiateJoinGroup]] `initiateJoinGroup` Internal Method

[source, java]
----
synchronized RequestFuture<ByteBuffer> initiateJoinGroup()
----

`initiateJoinGroup`...FIXME

NOTE: `initiateJoinGroup` is used exclusively when `AbstractCoordinator` is requested to <<joinGroupIfNeeded, joinGroupIfNeeded>> (when a rejoin is <<rejoinNeeded, needed>> or <<joinFuture, still in progress and incomplete>>).

=== [[ensureActiveGroup]] `ensureActiveGroup` Method

[source, java]
----
void ensureActiveGroup()
----

`ensureActiveGroup`...FIXME

NOTE: `ensureActiveGroup` is used when `ConsumerCoordinator` is requested to link:kafka-consumer-internals-ConsumerCoordinator.adoc#poll[poll for coordinator events]

=== [[lookupCoordinator]] `lookupCoordinator` Method

[source, java]
----
RequestFuture<Void> lookupCoordinator()
----

`lookupCoordinator`...FIXME

[NOTE]
====
`lookupCoordinator` is used when:

* `AbstractCoordinator` is requested to <<ensureCoordinatorReady, ensureCoordinatorReady>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsAsync, commitOffsetsAsync>>

* `HeartbeatThread` is requested to run
====

=== [[ensureCoordinatorReady]] `ensureCoordinatorReady` Method

[source, java]
----
boolean ensureCoordinatorReady(final Timer timer)
----

`ensureCoordinatorReady`...FIXME

[NOTE]
====
`ensureCoordinatorReady` is used when:

* `AbstractCoordinator` is requested to <<ensureActiveGroup, ensureActiveGroup>> and <<joinGroupIfNeeded, joinGroupIfNeeded>>

* `ConsumerCoordinator` is requested to <<kafka-consumer-internals-ConsumerCoordinator.adoc#poll, poll>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#fetchCommittedOffsets, fetchCommittedOffsets>>, <<kafka-consumer-internals-ConsumerCoordinator.adoc#close, close>>, and <<kafka-consumer-internals-ConsumerCoordinator.adoc#commitOffsetsSync, commitOffsetsSync>>
====

=== [[sendJoinGroupRequest]] `sendJoinGroupRequest` Method

[source, java]
----
RequestFuture<ByteBuffer> sendJoinGroupRequest()
----

`sendJoinGroupRequest`...FIXME

NOTE: `sendJoinGroupRequest` is used when...FIXME

=== [[sendSyncGroupRequest]] `sendSyncGroupRequest` Internal Method

[source, java]
----
RequestFuture<ByteBuffer> sendSyncGroupRequest(
  SyncGroupRequest.Builder requestBuilder)
----

`sendSyncGroupRequest`...FIXME

NOTE: `sendSyncGroupRequest` is used when...FIXME

=== [[sendFindCoordinatorRequest]] `sendFindCoordinatorRequest` Internal Method

[source, java]
----
RequestFuture<Void> sendFindCoordinatorRequest(Node node)
----

`sendFindCoordinatorRequest`...FIXME

NOTE: `sendFindCoordinatorRequest` is used when...FIXME

=== [[maybeLeaveGroup]] `maybeLeaveGroup` Method

[source, java]
----
void maybeLeaveGroup()
----

`maybeLeaveGroup`...FIXME

NOTE: `maybeLeaveGroup` is used when...FIXME

=== [[sendHeartbeatRequest]] `sendHeartbeatRequest` Method

[source, java]
----
RequestFuture<Void> sendHeartbeatRequest()
----

`sendHeartbeatRequest`...FIXME

NOTE: `sendHeartbeatRequest` is used when...FIXME
