== [[FindCoordinatorRequest]] FindCoordinatorRequest

[[FIND_COORDINATOR]]
[[creating-instance]]
`FindCoordinatorRequest` is a concrete <<kafka-common-requests-AbstractRequest.adoc#, AbstractRequest>> with *FindCoordinator* API key and the following:

* [[coordinatorType]] Coordinator type (i.e. `GROUP` or `TRANSACTION`)
* [[coordinatorKey]] Coordinator key
* [[version]] Version

`FindCoordinatorRequest` is <<creating-instance, created>> when:

* `AbstractRequest` is requested to <<kafka-common-requests-AbstractRequest.adoc#parseRequest, parse a request>> (with the <<FIND_COORDINATOR, FindCoordinator>> API key)

* `FindCoordinatorRequest` is requested to <<parse, parse a byte buffer>>

* `FindCoordinatorRequest.Builder` is requested to <<build, build a FindCoordinatorRequest>>

=== [[FindCoordinatorRequest.Builder]][[Builder]][[build]] `FindCoordinatorRequest.Builder` Factory Object

`FindCoordinatorRequest.Builder` is a concrete <<kafka-common-requests-AbstractRequest.adoc#Builder, AbstractRequest.Builder>> factory object that can <<kafka-common-requests-AbstractRequest.adoc#build, build>> a <<FindCoordinatorRequest, FindCoordinatorRequest>>.

[source, java]
----
FindCoordinatorRequest build(short version)
----

=== [[parse]] Creating FindCoordinatorRequest from Byte Buffer -- `parse` Factory Method

[source, java]
----
FindCoordinatorRequest parse(ByteBuffer buffer, short version)
----

`parse`...FIXME

NOTE: `parse` is used when...FIXME
