== [[ConfigCommand]] ConfigCommand Standalone Application

`ConfigCommand` is a <<main, standalone application>> that...FIXME

`ConfigCommand` can be executed using `bin/kafka-configs.sh` (or `bin\windows\kafka-configs.bat` on MS Windows).

```
// Triggers alterBrokerConfig
./bin/kafka-configs.sh \
  --bootstrap-server :9092 \
  --alter \
  --entity-type brokers \
  --entity-name 0 \
  --add-config advertised.listeners=plaintext://:9092
```

```
// Triggers processBrokerConfig
./bin/kafka-configs.sh \
  --bootstrap-server :9092 \
  --describe \
  --entity-type brokers \
  --entity-name 0
```

=== [[alterBrokerConfig]] `alterBrokerConfig` Method

[source, scala]
----
alterBrokerConfig(
  adminClient: JAdminClient,
  opts: ConfigCommandOptions,
  entityName: String)
----

`alterBrokerConfig`...FIXME

NOTE: `alterBrokerConfig` is used exclusively when `ConfigCommand` is requested to <<processBrokerConfig, processBrokerConfig>> (with `alter` action).

=== [[processBrokerConfig]] `processBrokerConfig` Internal Method

[source, scala]
----
processBrokerConfig(opts: ConfigCommandOptions): Unit
----

`processBrokerConfig`...FIXME

NOTE: `processBrokerConfig` is used exclusively when `ConfigCommand` standalone application is <<main, executed>> (without `zookeeper` command-line option).

=== [[main]] Executing Standalone Application -- `main` Method

[source, scala]
----
main(args: Array[String]): Unit
----

`main` is the entry point of the <<ConfigCommand, ConfigCommand>> standalone application when launched on command line (e.g. from `bin/kafka-configs.sh`).

`main`...FIXME
