== [[Authorizer]] Authorizer

`Authorizer` is the <<contract, abstraction>> of <<implementations, Kafka authorizers>> that link:kafka-server-KafkaServer.adoc[Kafka brokers] use to <<authorize, authorize actions>> based on access-control list (ACL).

From Wikipedia's https://en.wikipedia.org/wiki/Access-control_list[Access-control list]:

====
An *access-control list (ACL)* is a list of permissions attached to an object.

An ACL specifies which users or system processes are granted access to objects, as well as what operations are allowed on given objects.

Each entry in a typical ACL specifies a subject and an operation. For instance, if a file object has an ACL that contains (Alice: read,write; Bob: read), this would give Alice permission to read and write the file and Bob to only read it.
====

`Authorizer` is configured by link:kafka-properties.adoc#authorizer.class.name[authorizer.class.name] configuration property.

[[Configurable]]
`Authorizer` is a link:kafka-common-Configurable.adoc[Configurable].

[[Closeable]]
`Authorizer` is a Java's https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/Closeable.html[Closeable] to close any resources that may have been opened (at <<start, start up>>).

NOTE: `Authorizer` abstraction is part of link:++https://cwiki.apache.org/confluence/display/KAFKA/KIP-504+-+Add+new+Java+Authorizer+Interface++[KIP-504 - Add new Java Authorizer Interface].

[[contract]]
.Authorizer Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| acls
a| [[acls]]

[source, java]
----
Iterable<AclBinding> acls(
  AclBindingFilter filter)
----

Lists ACL bindings for the provided filter (synchronously)

Used when:

* `JAuthorizerService` is requested to link:kafka-admin-AclCommand-JAuthorizerService.adoc#getAcls[list ACLs for a filter]

* `KafkaApis` is requested to link:kafka-server-KafkaApis.adoc#handleDescribeAcls[handle a DescribeAcls request]

| authorize
a| [[authorize]]

[source, java]
----
List<AuthorizationResult> authorize(
  AuthorizableRequestContext requestContext,
  List<Action> actions)
----

Authorizes the actions performed by the request (synchronously)

Used when `KafkaApis` is requested to <<kafka-server-KafkaApis.adoc#authorize, authorize>>, <<kafka-server-KafkaApis.adoc#filterAuthorized, filterAuthorized>>, and <<kafka-server-KafkaApis.adoc#authorizedOperations, authorizedOperations>>.

| createAcls
a| [[createAcls]]

[source, java]
----
List<? extends CompletionStage<AclCreateResult>> createAcls(
  AuthorizableRequestContext requestContext,
  List<AclBinding> aclBindings)
----

Creates new ACL bindings (asynchronously)

Used when:

* `JAuthorizerService` is requested to link:kafka-admin-AclCommand-JAuthorizerService.adoc#addAcls[add ACLs for a resource]

* `KafkaApis` is requested to link:kafka-server-KafkaApis.adoc#handleCreateAcls[handle a CreateAcls request]

| deleteAcls
a| [[deleteAcls]]

[source, java]
----
List<? extends CompletionStage<AclDeleteResult>> deleteAcls(
  AuthorizableRequestContext requestContext,
  List<AclBindingFilter> aclBindingFilters)
----

Deletes all ACL bindings that match the provided filters (asynchronously)

Used when:

* `JAuthorizerService` is requested to link:kafka-admin-AclCommand-JAuthorizerService.adoc#removeAcls[remove ACLs for the provided filters]

* `KafkaApis` is requested to link:kafka-server-KafkaApis.adoc#handleDeleteAcls[handle a DeleteAcls request]

| start
a| [[start]]

[source, java]
----
Map<Endpoint, ? extends CompletionStage<Void>> start(
  AuthorizerServerInfo serverInfo)
----

Starts loading authorization metadata (asynchronously)

Returns futures that can be used to wait until metadata for authorizing requests on each listener is available. The future returned for each listener must return only when authorizer is ready to authorize requests on the listener.

Used when `KafkaServer` is requested to link:kafka-server-KafkaServer.adoc#startup[start up]

NOTE: Executed after link:kafka-common-Configurable.adoc#configure[configure] (as a <<Configurable, Configurable>>).

|===

[[implementations]]
.Authorizers
[cols="30,70",options="header",width="100%"]
|===
| Authorizer
| Description

| <<kafka-security-authorizer-AclAuthorizer.adoc#, AclAuthorizer>>
| [[AclAuthorizer]] Uses Apache ZooKeeper to persist ACLs

| <<kafka-security-authorizer-AuthorizerWrapper.adoc#, AuthorizerWrapper>>
| [[AuthorizerWrapper]] Wrapper of authorizers based on the deprecated `kafka.security.auth.Authorizer` API

|===
