== [[AdminClient]] AdminClient

`AdminClient` is the <<contract, base>> of <<extensions, administrative clients>> for Apache Kafka with support for managing and inspecting topics, brokers, configurations and ACLs.

[[implementations]]
NOTE: <<kafka-KafkaAdminClient.adoc#, KafkaAdminClient>> is the default and only known implementation of the <<contract, AdminClient Contract>> in Apache Kafka.

[[contract]]
.AdminClient Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| alterReplicaLogDirs
a| [[alterReplicaLogDirs]]

[source, java]
----
AlterReplicaLogDirsResult alterReplicaLogDirs(
  Map<TopicPartitionReplica, String> replicaAssignment,
  AlterReplicaLogDirsOptions options)
----

Used when...FIXME

| close
a| [[close]]

[source, java]
----
void close(
  Duration timeout)
----

Used when...FIXME

| createAcls
a| [[createAcls]]

[source, java]
----
CreateAclsResult createAcls(
  Collection<AclBinding> acls,
  CreateAclsOptions options)
----

Used when...FIXME

| createDelegationToken
a| [[createDelegationToken]]

[source, java]
----
CreateDelegationTokenResult createDelegationToken(
  CreateDelegationTokenOptions options)
----

Used when...FIXME

| createPartitions
a| [[createPartitions]]

[source, java]
----
CreatePartitionsResult createPartitions(
  Map<String, NewPartitions> newPartitions,
  CreatePartitionsOptions options)
----

Used when...FIXME

| createTopics
a| [[createTopics]]

[source, java]
----
CreateTopicsResult createTopics(
  Collection<NewTopic> newTopics,
  CreateTopicsOptions options)
----

Used when...FIXME

| deleteAcls
a| [[deleteAcls]]

[source, java]
----
DeleteAclsResult deleteAcls(
  Collection<AclBindingFilter> filters,
  DeleteAclsOptions options)
----

Used when...FIXME

| deleteConsumerGroups
a| [[deleteConsumerGroups]]

[source, java]
----
DeleteConsumerGroupsResult deleteConsumerGroups(
  Collection<String> groupIds,
  DeleteConsumerGroupsOptions options)
----

Used when...FIXME

| deleteRecords
a| [[deleteRecords]]

[source, java]
----
DeleteRecordsResult deleteRecords(
  Map<TopicPartition, RecordsToDelete> recordsToDelete,
  DeleteRecordsOptions options)
----

Used when...FIXME

| deleteTopics
a| [[deleteTopics]]

[source, java]
----
DeleteTopicsResult deleteTopics(
  Collection<String> topics,
  DeleteTopicsOptions options)
----

Used when...FIXME

| describeAcls
a| [[describeAcls]]

[source, java]
----
DescribeAclsResult describeAcls(
  AclBindingFilter filter,
  DescribeAclsOptions options)
----

Used when...FIXME

| describeCluster
a| [[describeCluster]]

[source, java]
----
DescribeClusterResult describeCluster(
  DescribeClusterOptions options)
----

Used when...FIXME

| describeConfigs
a| [[describeConfigs]]

[source, java]
----
DescribeConfigsResult describeConfigs(
  Collection<ConfigResource> resources,
  DescribeConfigsOptions options)
----

Used when...FIXME

| describeConsumerGroups
a| [[describeConsumerGroups]]

[source, java]
----
DescribeConsumerGroupsResult describeConsumerGroups(
  Collection<String> groupIds,
  DescribeConsumerGroupsOptions options)
----

Used when...FIXME

| describeDelegationToken
a| [[describeDelegationToken]]

[source, java]
----
DescribeDelegationTokenResult describeDelegationToken(
  DescribeDelegationTokenOptions options)
----

Used when...FIXME

| describeLogDirs
a| [[describeLogDirs]]

[source, java]
----
DescribeLogDirsResult describeLogDirs(
  Collection<Integer> brokers,
  DescribeLogDirsOptions options)
----

Used when...FIXME

| describeReplicaLogDirs
a| [[describeReplicaLogDirs]]

[source, java]
----
DescribeReplicaLogDirsResult describeReplicaLogDirs(
  Collection<TopicPartitionReplica> replicas,
  DescribeReplicaLogDirsOptions options)
----

Used when...FIXME

| describeTopics
a| [[describeTopics]]

[source, java]
----
DescribeTopicsResult describeTopics(
  Collection<String> topicNames,
  DescribeTopicsOptions options)
----

Used when...FIXME

| electPreferredLeaders
a| [[electPreferredLeaders]]

[source, java]
----
ElectPreferredLeadersResult electPreferredLeaders(
  Collection<TopicPartition> partitions,
  ElectPreferredLeadersOptions options)
ElectPreferredLeadersResult electPreferredLeaders(
  Collection<TopicPartition> partitions) // <1>
----
<1> Uses the default `ElectPreferredLeadersOptions`

Used when `PreferredReplicaLeaderElectionCommand` utility is requested to <<kafka-tools-PreferredReplicaLeaderElectionCommand.adoc#electPreferredLeaders, electPreferredLeaders>>

| expireDelegationToken
a| [[expireDelegationToken]]

[source, java]
----
ExpireDelegationTokenResult expireDelegationToken(
  byte[] hmac,
  ExpireDelegationTokenOptions options)
----

Used when...FIXME

| incrementalAlterConfigs
a| [[incrementalAlterConfigs]]

[source, java]
----
AlterConfigsResult incrementalAlterConfigs(
  Map<ConfigResource,
  Collection<AlterConfigOp>> configs,
  AlterConfigsOptions options)
----

Used when...FIXME

| listConsumerGroupOffsets
a| [[listConsumerGroupOffsets]]

[source, java]
----
ListConsumerGroupOffsetsResult listConsumerGroupOffsets(
  String groupId,
  ListConsumerGroupOffsetsOptions options)
----

Used when...FIXME

| listConsumerGroups
a| [[listConsumerGroups]]

[source, java]
----
ListConsumerGroupsResult listConsumerGroups(
  ListConsumerGroupsOptions options)
----

Used when...FIXME

| listTopics
a| [[listTopics]]

[source, java]
----
ListTopicsResult listTopics(
  ListTopicsOptions options)
----

Used when...FIXME

| metrics
a| [[metrics]]

[source, java]
----
Map<MetricName, ? extends Metric> metrics()
----

Used when...FIXME

| renewDelegationToken
a| [[renewDelegationToken]]

[source, java]
----
RenewDelegationTokenResult renewDelegationToken(
  byte[] hmac,
  RenewDelegationTokenOptions options)
----

Used when...FIXME

|===

=== [[create]] Creating AdminClient Instance -- `create` Object Method

[source, java]
----
AdminClient create(Properties props)
AdminClient create(Map<String, Object> conf)
----

`create` simply requests the `KafkaAdminClient` object to <<kafka-KafkaAdminClient.adoc#createInternal, create a KafkaAdminClient>>.

NOTE: `create` is used in <<kafka-tools.adoc#, Kafka administration utilities>>.
