== [[SslChannelBuilder]] SslChannelBuilder

`SslChannelBuilder` is a `ChannelBuilder` for SSL channels on Kafka clients and brokers.

`SslChannelBuilder` is a `ListenerReconfigurable`.

`SslChannelBuilder` is <<creating-instance, created>> when `ChannelBuilders` utility is requested to link:kafka-common-network-ChannelBuilders.adoc#create[create a ChannelBuilder] for SSL security protocol.

=== [[creating-instance]] Creating SslChannelBuilder Instance

`SslChannelBuilder` takes the following to be created:

* [[mode]] `Mode` (i.e. `CLIENT` or `SERVER`)
* [[listenerName]] Listener name (only for `SERVER` channel builder)
* [[isInterBrokerListener]] `isInterBrokerListener` flag

`SslChannelBuilder` initializes the <<internal-properties, internal properties>>.

=== [[buildChannel]] Creating KafkaChannel -- `buildChannel` Method

[source, java]
----
KafkaChannel buildChannel(
  String id,
  SelectionKey key,
  int maxReceiveSize,
  MemoryPool memoryPool)
----

NOTE: `buildChannel` is part of the `ChannelBuilder` contract to build a `KafkaChannel`.

`buildChannel`...FIXME

=== [[configure]] `configure` Method

[source, java]
----
void configure(
  Map<String, ?> configs)
----

NOTE: `configure` is part of the link:kafka-common-Configurable.adoc#configure[Configurable] contract to pass configurations.

`configure` initializes the <<sslPrincipalMapper, sslPrincipalMapper>> internal registry (using link:kafka-common-security-ssl-SslPrincipalMapper.adoc#fromRules[SslPrincipalMapper] utility) if link:kafka-properties.adoc#ssl.principal.mapping.rules[ssl.principal.mapping.rules] configuration property is defined.

`configure` creates a <<sslFactory, SslFactory>> (for the <<mode, mode>> and the <<isInterBrokerListener, isInterBrokerListener>> flag) and requests it to link:kafka-common-security-ssl-SslFactory.adoc#configure[configure] (with the given `configs`).

=== [[buildTransportLayer]] `buildTransportLayer` Method

[source, java]
----
SslTransportLayer buildTransportLayer(
  SslFactory sslFactory,
  String id,
  SelectionKey key,
  String host)
----

`buildTransportLayer`...FIXME

NOTE: `buildTransportLayer` is used when `SslChannelBuilder` is requested to <<buildChannel, buildChannel>>.

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| configs
a| [[configs]] Configuration properties

| sslFactory
a| [[sslFactory]] link:kafka-common-security-ssl-SslFactory.adoc[SslFactory]

| sslPrincipalMapper
a| [[sslPrincipalMapper]] `SslPrincipalMapper`

|===
