== [[AbstractControllerBrokerRequestBatch]] AbstractControllerBrokerRequestBatch

`AbstractControllerBrokerRequestBatch` is the <<contract, base>> of <<extensions, ControllerBrokerRequestBatches>> that <<sendRequestsToBrokers, sendRequestsToBrokers>>.

[[implementations]]
NOTE: <<kafka-controller-ControllerBrokerRequestBatch.adoc#, ControllerBrokerRequestBatch>> is the default and only known implementation of the <<contract, AbstractControllerBrokerRequestBatch Contract>> in Apache Kafka.

[[contract]]
.AbstractControllerBrokerRequestBatch Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| sendEvent
a| [[sendEvent]]

[source, scala]
----
sendEvent(
  event: ControllerEvent): Unit
----

Sends a <<kafka-controller-ControllerEvent.adoc#, ControllerEvent>>

Used when `AbstractControllerBrokerRequestBatch` is requested to <<sendLeaderAndIsrRequest, sendLeaderAndIsrRequest>> and <<sendStopReplicaRequests, sendStopReplicaRequests>>

| sendRequest
a| [[sendRequest]]

[source, scala]
----
sendRequest(
  brokerId: Int,
  request: AbstractControlRequest.Builder[_ <: AbstractControlRequest],
  callback: AbstractResponse => Unit = null): Unit
----

Used when `AbstractControllerBrokerRequestBatch` is requested to <<sendLeaderAndIsrRequest, sendLeaderAndIsrRequest>>, <<sendUpdateMetadataRequests, sendUpdateMetadataRequests>>, and <<sendStopReplicaRequests, sendStopReplicaRequests>>

|===

=== [[creating-instance]] Creating AbstractControllerBrokerRequestBatch Instance

`AbstractControllerBrokerRequestBatch` takes the following to be created:

* [[config]] <<kafka-server-KafkaConfig.adoc#, KafkaConfig>>
* [[controllerContext]] <<kafka-controller-ControllerContext.adoc#, ControllerContext>>
* [[stateChangeLogger]] `StateChangeLogger`

`AbstractControllerBrokerRequestBatch` initializes the <<internal-properties, internal properties>>.

NOTE: `AbstractControllerBrokerRequestBatch` is a Scala abstract class and cannot be <<creating-instance, created>> directly. It is created indirectly for the <<implementations, concrete AbstractControllerBrokerRequestBatches>>.

=== [[sendRequestsToBrokers]] `sendRequestsToBrokers` Method

[source, scala]
----
sendRequestsToBrokers(controllerEpoch: Int): Unit
----

`sendRequestsToBrokers` <<sendLeaderAndIsrRequest, sendLeaderAndIsrRequest>>.

`sendRequestsToBrokers` <<sendUpdateMetadataRequests, sendUpdateMetadataRequests>>.

`sendRequestsToBrokers` <<sendStopReplicaRequests, sendStopReplicaRequests>>.

In case of any error (`Throwable`), `sendRequestsToBrokers`...FIXME

[NOTE]
====
`sendRequestsToBrokers` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderEpochAndSendRequest, updateLeaderEpochAndSendRequest>>, <<kafka-controller-KafkaController.adoc#sendUpdateMetadataRequest, sendUpdateMetadataRequest>> and at <<kafka-controller-KafkaController.adoc#ControlledShutdown, ControlledShutdown>> controller event

* `ZkPartitionStateMachine` is requested to <<kafka-controller-ZkPartitionStateMachine.adoc#handleStateChanges, handleStateChanges>>

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#handleStateChanges, handleStateChanges>>
====

==== [[sendLeaderAndIsrRequest]] `sendLeaderAndIsrRequest` Internal Method

[source, scala]
----
sendLeaderAndIsrRequest(
  controllerEpoch: Int,
  stateChangeLog: StateChangeLogger): Unit
----

`sendLeaderAndIsrRequest`...FIXME

NOTE: `sendLeaderAndIsrRequest` is used exclusively when `AbstractControllerBrokerRequestBatch` is requested to <<sendRequestsToBrokers, sendRequestsToBrokers>>.

==== [[sendUpdateMetadataRequests]] `sendUpdateMetadataRequests` Internal Method

[source, scala]
----
sendUpdateMetadataRequests(
  controllerEpoch: Int,
  stateChangeLog: StateChangeLogger): Unit
----

`sendUpdateMetadataRequests`...FIXME

NOTE: `sendUpdateMetadataRequests` is used exclusively when `AbstractControllerBrokerRequestBatch` is requested to <<sendRequestsToBrokers, sendRequestsToBrokers>>.

==== [[sendStopReplicaRequests]] `sendStopReplicaRequests` Internal Method

[source, scala]
----
sendStopReplicaRequests(
  controllerEpoch: Int): Unit
----

`sendStopReplicaRequests`...FIXME

NOTE: `sendStopReplicaRequests` is used exclusively when `AbstractControllerBrokerRequestBatch` is requested to <<sendRequestsToBrokers, sendRequestsToBrokers>>.

=== [[newBatch]] Preparing New Batch -- `newBatch` Method

[source, scala]
----
newBatch(): Unit
----

`newBatch` simply throws an `IllegalStateException` when any of the following internal registries are not empty: <<leaderAndIsrRequestMap, leaderAndIsrRequestMap>>, <<stopReplicaRequestMap, stopReplicaRequestMap>> and <<updateMetadataRequestBrokerSet, updateMetadataRequestBrokerSet>>.

```
Controller to broker state change requests batch is not empty while creating a new one. Some LeaderAndIsr state changes [leaderAndIsrRequestMap] might be lost
```

```
Controller to broker state change requests batch is not empty while creating a new one. Some StopReplica state changes [stopReplicaRequestMap] might be lost
```

```
Controller to broker state change requests batch is not empty while creating a new one. Some UpdateMetadata state changes to brokers [updateMetadataRequestBrokerSet] with partition info [updateMetadataRequestPartitionInfoMap] might be lost
```

[NOTE]
====
`newBatch` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderEpochAndSendRequest, updateLeaderEpochAndSendRequest>>, <<kafka-controller-KafkaController.adoc#sendUpdateMetadataRequest, sendUpdateMetadataRequest>>, and process a <<kafka-controller-KafkaController.adoc#ControlledShutdown, ControlledShutdown>> controller event

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#handleStateChanges, handleStateChanges>>

* `PartitionStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#handleStateChanges, handleStateChanges>>
====

=== [[addLeaderAndIsrRequestForBrokers]] `addLeaderAndIsrRequestForBrokers` Method

[source, scala]
----
addLeaderAndIsrRequestForBrokers(
  brokerIds: Seq[Int],
  topicPartition: TopicPartition,
  leaderIsrAndControllerEpoch: LeaderIsrAndControllerEpoch,
  replicas: Seq[Int],
  isNew: Boolean): Unit
----

`addLeaderAndIsrRequestForBrokers`...FIXME

[NOTE]
====
`addLeaderAndIsrRequestForBrokers` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderEpochAndSendRequest, updateLeaderEpochAndSendRequest>>

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#initializeLeaderAndIsrForPartitions, initializeLeaderAndIsrForPartitions>> and <<kafka-controller-PartitionStateMachine.adoc#doElectLeaderForPartitions, doElectLeaderForPartitions>>

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#doHandleStateChanges, doHandleStateChanges>>
====

=== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| leaderAndIsrRequestMap
a| [[leaderAndIsrRequestMap]] (`Map[Int, Map[TopicPartition, LeaderAndIsrRequest.PartitionState]]`)

Used when...FIXME

| stopReplicaRequestMap
a| [[stopReplicaRequestMap]] (`Map[Int, ListBuffer[StopReplicaRequestInfo]]`)

Used when...FIXME

| updateMetadataRequestBrokerSet
a| [[updateMetadataRequestBrokerSet]] (`Set[Int]`)

Used when...FIXME

|===
