== [[Partition]] Partition

A Kafka topic is spread across a Kafka cluster as a virtual group of one or more *partitions*.

A single partition of a topic (*topic partition*) can be replicated across a Kafka cluster to one or more Kafka brokers.

A topic partition has one partition leader node and zero or more replicas.

Kafka producers publish messages to topic leaders as do Kafka consumers consume them from.

*In-Sync Replicas* (ISR) are brokers that...FIXME

*Offline Replicas* are...FIXME

`Partition` is...FIXME

[[internal-registries]]
.Partition's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| inSyncReplicas
| [[inSyncReplicas]] In-sync <<kafka-cluster-Replica.adoc#, Replicas>>

| leaderReplicaIdOpt
| [[leaderReplicaIdOpt]] Optional leader replica ID

| localBrokerId
a| [[localBrokerId]] One of the following:

* `broker.id` configuration property (from the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>>

* `-1` if <<isOffline, offline>>

| logManager
a| [[logManager]] <<kafka-log-LogManager.adoc#, LogManager>> (of the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>> or `null`

| zkClient
a| [[zkClient]] <<kafka-zk-KafkaZkClient.adoc#, KafkaZkClient>> (of the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>> or `null`

| topicPartition
| [[topicPartition]] `TopicPartition` (with the <<topic, topic>> and <<partitionId, partitionId>>)
|===

=== [[maybeExpandIsr]] `maybeExpandIsr` Method

[source, scala]
----
maybeExpandIsr(replicaId: Int, logReadResult: LogReadResult): Boolean
----

`maybeExpandIsr`...FIXME

NOTE: `maybeExpandIsr` is used exclusively when `Partition` is requested to <<updateReplicaLogReadResult, updateReplicaLogReadResult>>.

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

[source, scala]
----
maybeShrinkIsr(replicaMaxLagTimeMs: Long): Unit
----

`maybeShrinkIsr`...FIXME

NOTE: `maybeShrinkIsr` is used exclusively when `ReplicaManager` link:kafka-server-ReplicaManager.adoc#maybeShrinkIsr[maybeShrinkIsr].

=== [[updateReplicaLogReadResult]] `updateReplicaLogReadResult` Method

[source, scala]
----
updateReplicaLogReadResult(replica: Replica, logReadResult: LogReadResult): Boolean
----

`updateReplicaLogReadResult`...FIXME

NOTE: `updateReplicaLogReadResult` is used exclusively when `ReplicaManager` link:kafka-server-ReplicaManager.adoc#updateFollowerLogReadResults[updateFollowerLogReadResults].

=== [[updateIsr]] `updateIsr` Internal Method

[source, scala]
----
updateIsr(newIsr: Set[Replica]): Unit
----

`updateIsr`...FIXME

NOTE: `updateIsr` is used when `Partition` is requested to <<maybeExpandIsr, expand>> or <<maybeShrinkIsr, shrink>> the ISR.

=== [[makeFollower]] `makeFollower` Method

[source, scala]
----
makeFollower(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeFollower`...FIXME

NOTE: `makeFollower` is used exclusively when `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#makeFollowers, makeFollowers>>.

=== [[leaderReplicaIfLocal]] `leaderReplicaIfLocal` Method

[source, scala]
----
leaderReplicaIfLocal: Option[Replica]
----

`leaderReplicaIfLocal` gives...FIXME

NOTE: `leaderReplicaIfLocal` is used...FIXME

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

CAUTION: FIXME

=== [[creating-instance]] Creating Partition Instance

`Partition` takes the following when created:

* [[topic]] Topic name
* [[partitionId]] Partition ID
* [[time]] `Time`
* [[replicaManager]] <<kafka-server-ReplicaManager.adoc#, ReplicaManager>>
* [[isOffline]] `isOffline` flag (default: `false`)

`Partition` initializes the <<internal-registries, internal registries and counters>>.

=== [[isUnderReplicated]] `isUnderReplicated` Predicate

[source, scala]
----
isUnderReplicated: Boolean
----

`isUnderReplicated` is `true` only if the partition <<isLeaderReplicaLocal, isLeaderReplicaLocal>> and the number of <<inSyncReplicas, in-sync replicas>> is below the <<assignedReplicas, assignedReplicas>>.

NOTE: `isUnderReplicated` is used when...FIXME

=== [[isUnderMinIsr]] `isUnderMinIsr` Predicate

[source, scala]
----
isUnderMinIsr: Boolean
----

`isUnderMinIsr` is `true` only if the partition <<isLeaderReplicaLocal, isLeaderReplicaLocal>> and the number of <<inSyncReplicas, in-sync replicas>> is below the <<kafka-properties.adoc#min.insync.replicas, min.insync.replicas>> configuration property (as configured for the <<kafka-log-Log.adoc#, Log>> of the <<leaderReplica, leader replica>>).

NOTE: `isUnderMinIsr` is used when...FIXME

=== [[checkEnoughReplicasReachOffset]] `checkEnoughReplicasReachOffset` Method

[source, scala]
----
checkEnoughReplicasReachOffset(requiredOffset: Long): (Boolean, Errors)
----

`checkEnoughReplicasReachOffset`...FIXME

NOTE: `checkEnoughReplicasReachOffset` is used when...FIXME

=== [[makeLeader]] `makeLeader` Method

[source, scala]
----
makeLeader(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeLeader`...FIXME

NOTE: `makeLeader` is used exclusively when `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#makeLeaders, makeLeaders>>.

=== [[getOrCreateReplica]] `getOrCreateReplica` Method

[source, scala]
----
getOrCreateReplica(
  replicaId: Int = localBrokerId,
  isNew: Boolean = false): Replica
----

`getOrCreateReplica`...FIXME

[NOTE]
====
`getOrCreateReplica` is used when:

* `Partition` is requested to <<maybeCreateFutureReplica, maybeCreateFutureReplica>>, <<makeLeader, makeLeader>> and <<makeFollower, makeFollower>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#becomeLeaderOrFollower, becomeLeaderOrFollower>> and <<kafka-server-ReplicaManager.adoc#makeFollowers, makeFollowers>>
====

=== [[maybeCreateFutureReplica]] `maybeCreateFutureReplica` Method

[source, scala]
----
maybeCreateFutureReplica(logDir: String): Boolean
----

`maybeCreateFutureReplica`...FIXME

NOTE: `maybeCreateFutureReplica` is used exclusively when `ReplicaManager` is requested to <<alterReplicaLogDirs, alterReplicaLogDirs>>.

=== [[appendRecordsToLeader]] `appendRecordsToLeader` Method

[source, scala]
----
appendRecordsToLeader(
  records: MemoryRecords,
  isFromClient: Boolean,
  requiredAcks: Int = 0): LogAppendInfo
----

`appendRecordsToLeader` basically requests the `Log` (of the leader <<kafka-cluster-Replica.adoc#, Replica>>) to <<kafka-log-Log.adoc#appendAsLeader, appendAsLeader>>.

Internally, `appendRecordsToLeader`...FIXME

[NOTE]
====
`appendRecordsToLeader` is used when:

* `GroupMetadataManager` is requested to <<kafka-coordinator-group-GroupMetadataManager.adoc#cleanupGroupMetadata, cleanupGroupMetadata>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#appendToLocalLog, appendToLocalLog>>
====

=== [[doAppendRecordsToFollowerOrFutureReplica]] `doAppendRecordsToFollowerOrFutureReplica` Internal Method

[source, scala]
----
doAppendRecordsToFollowerOrFutureReplica(
  records: MemoryRecords,
  isFuture: Boolean): Option[LogAppendInfo]
----

`doAppendRecordsToFollowerOrFutureReplica`...FIXME

NOTE: `doAppendRecordsToFollowerOrFutureReplica` is used exclusively when `Partition` is requested to <<appendRecordsToFollowerOrFutureReplica, appendRecordsToFollowerOrFutureReplica>>.

=== [[appendRecordsToFollowerOrFutureReplica]] `appendRecordsToFollowerOrFutureReplica` Method

[source, scala]
----
appendRecordsToFollowerOrFutureReplica(
  records: MemoryRecords,
  isFuture: Boolean): Option[LogAppendInfo]
----

`appendRecordsToFollowerOrFutureReplica`...FIXME

[NOTE]
====
`appendRecordsToFollowerOrFutureReplica` is used when:

* `ReplicaAlterLogDirsThread` is requested to `processPartitionData`

* `ReplicaFetcherThread` is requested to <<kafka-server-ReplicaFetcherThread.adoc#processPartitionData, processPartitionData>>
====

=== [[truncateTo]] `truncateTo` Method

[source, scala]
----
truncateTo(offset: Long, isFuture: Boolean): Unit
----

`truncateTo`...FIXME

[NOTE]
====
`truncateTo` is used when:

* `ReplicaAlterLogDirsThread` is requested to `truncate`

* `ReplicaFetcherThread` is requested to <<kafka-server-ReplicaFetcherThread.adoc#truncate, truncate>>
====

=== [[truncateFullyAndStartAt]] `truncateFullyAndStartAt` Method

[source, scala]
----
truncateFullyAndStartAt(newOffset: Long, isFuture: Boolean): Unit
----

`truncateFullyAndStartAt`...FIXME

[NOTE]
====
`truncateFullyAndStartAt` is used when:

* `Partition` is requested to <<appendRecordsToFollowerOrFutureReplica, appendRecordsToFollowerOrFutureReplica>>

* `ReplicaAlterLogDirsThread` is requested to `truncateFullyAndStartAt`

* `ReplicaFetcherThread` is requested to <<kafka-server-ReplicaFetcherThread.adoc#truncateFullyAndStartAt, truncateFullyAndStartAt>>
====

=== [[maybeReplaceCurrentWithFutureReplica]] `maybeReplaceCurrentWithFutureReplica` Method

[source, scala]
----
maybeReplaceCurrentWithFutureReplica(): Boolean
----

`maybeReplaceCurrentWithFutureReplica`...FIXME

NOTE: `maybeReplaceCurrentWithFutureReplica` is used exclusively when `ReplicaAlterLogDirsThread` is requested to `processPartitionData`.
