== [[DefaultMetadataUpdater]] DefaultMetadataUpdater

`DefaultMetadataUpdater` is a link:kafka-MetadataUpdater.adoc[MetadataUpdater] that `NetworkClient` uses to...FIXME

[[logging]]
[TIP]
====
Enable `DEBUG` logging level for `org.apache.kafka.clients.NetworkClient` logger to see what happens inside.

Add the following line to `config/tools-log4j.properties` (for Kafka tools):

```
log4j.logger.org.apache.kafka.clients.NetworkClient=DEBUG
```

Add the following line to `config/log4j.properties`:

```
log4j.logger.org.apache.kafka.clients.NetworkClient=DEBUG, stdout
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[isUpdateDue]] `isUpdateDue` Method

CAUTION: FIXME

=== [[maybeUpdate]] `maybeUpdate` Internal Method

[source, java]
----
long maybeUpdate(long now, Node node)
----

CAUTION: FIXME

=== [[handleAuthenticationFailure]] `handleAuthenticationFailure` Callback Method

[source, java]
----
void handleAuthenticationFailure(AuthenticationException exception)
----

NOTE: `handleAuthenticationFailure` is a part of link:kafka-MetadataUpdater.adoc#handleAuthenticationFailure[MetadataUpdater Contract].

`handleCompletedMetadataResponse` turns link:kafka-NetworkClient.adoc#metadataFetchInProgress[metadataFetchInProgress] flag off.

`handleCompletedMetadataResponse` asks <<metadata, Metadata>> whether link:kafka-Metadata.adoc#updateRequested[metadata update was requested] and if so requests it to link:kafka-Metadata.adoc#failedUpdate[record a failure] (passing on the `exception`).

=== [[handleCompletedMetadataResponse]] `handleCompletedMetadataResponse` Callback Method

[source, java]
----
void handleCompletedMetadataResponse(RequestHeader requestHeader, long now, MetadataResponse response)
----

NOTE: `handleCompletedMetadataResponse` is a part of link:kafka-MetadataUpdater.adoc#handleCompletedMetadataResponse[MetadataUpdater Contract].

`handleCompletedMetadataResponse` turns <<metadataFetchInProgress, metadataFetchInProgress>> flag off.

`handleCompletedMetadataResponse` takes the link:kafka-MetadataResponse.adoc#cluster[cluster] from the `response`.
