== [[ControllerBrokerRequestBatch]] ControllerBrokerRequestBatch

`ControllerBrokerRequestBatch` is <<creating-instance, created>> exclusively for a <<kafka-controller-KafkaController.adoc#brokerRequestBatch, KafkaController>> that uses it for the following:

* <<addLeaderAndIsrRequestForBrokers, addLeaderAndIsrRequestForBrokers>>

* <<addUpdateMetadataRequestForBrokers, addUpdateMetadataRequestForBrokers>>

* <<addStopReplicaRequestForBrokers, addStopReplicaRequestForBrokers>>

Every time `ControllerBrokerRequestBatch` is used it is first <<newBatch, newBatch>> that is then <<sendRequestsToBrokers, sendRequestsToBrokers>>.

[[creating-instance]]
`ControllerBrokerRequestBatch` takes the following to be created:

* [[controller]] <<kafka-controller-KafkaController.adoc#, KafkaController>>
* [[stateChangeLogger]] `StateChangeLogger`

[[internal-registries]]
.ControllerBrokerRequestBatch's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,3",options="header",width="100%"]
|===
| Name
| Description

| leaderAndIsrRequestMap
a| [[leaderAndIsrRequestMap]] `Map[Int, mutable.Map[TopicPartition, LeaderAndIsrRequest.PartitionState]]`

* A new entry added in <<addLeaderAndIsrRequestForBrokers, addLeaderAndIsrRequestForBrokers>>

* Cleared in <<clear, clear>> and <<sendRequestsToBrokers, sendRequestsToBrokers>>

Used when `ControllerBrokerRequestBatch` is requested to <<sendRequestsToBrokers, sendRequestsToBrokers>>

| stopReplicaRequestMap
a| [[stopReplicaRequestMap]] `Map[Int, Seq[StopReplicaRequestInfo]]`

| updateMetadataRequestBrokerSet
| [[updateMetadataRequestBrokerSet]] Broker IDs to <<sendRequestsToBrokers, send UPDATE_METADATA requests to>> (and to be removed right after a successful sending)

New broker IDs added in <<addUpdateMetadataRequestForBrokers, addUpdateMetadataRequestForBrokers>>

| updateMetadataRequestPartitionInfoMap
| [[updateMetadataRequestPartitionInfoMap]] `TopicPartitions` with their `PartitionState`

|===

=== [[newBatch]] `newBatch` Method

[source, scala]
----
newBatch(): Unit
----

`newBatch` simply throws a `IllegalStateException` if one of the <<leaderAndIsrRequestMap, leaderAndIsrRequestMap>>, <<stopReplicaRequestMap, stopReplicaRequestMap>> and <<updateMetadataRequestBrokerSet, updateMetadataRequestBrokerSet>> internal registries are not empty.

```
Controller to broker state change requests batch is not empty while creating a new one. Some LeaderAndIsr state changes [leaderAndIsrRequestMap] might be lost
```

```
Controller to broker state change requests batch is not empty while creating a new one. Some StopReplica state changes [stopReplicaRequestMap] might be lost
```

```
Controller to broker state change requests batch is not empty while creating a new one. Some UpdateMetadata state changes to brokers [updateMetadataRequestBrokerSet] with partition info [updateMetadataRequestPartitionInfoMap] might be lost
```

[NOTE]
====
`newBatch` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderEpochAndSendRequest, updateLeaderEpochAndSendRequest>>, <<kafka-controller-KafkaController.adoc#sendUpdateMetadataRequest, sendUpdateMetadataRequest>>, and process a <<kafka-controller-KafkaController.adoc#ControlledShutdown, ControlledShutdown>> controller event

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#handleStateChanges, handleStateChanges>>

* `PartitionStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#handleStateChanges, handleStateChanges>>
====

=== [[addLeaderAndIsrRequestForBrokers]] `addLeaderAndIsrRequestForBrokers` Method

[source, scala]
----
addLeaderAndIsrRequestForBrokers(
  brokerIds: Seq[Int],
  topicPartition: TopicPartition,
  leaderIsrAndControllerEpoch: LeaderIsrAndControllerEpoch,
  replicas: Seq[Int],
  isNew: Boolean): Unit
----

`addLeaderAndIsrRequestForBrokers`...FIXME

[NOTE]
====
`addLeaderAndIsrRequestForBrokers` is used when:

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#updateLeaderEpochAndSendRequest, updateLeaderEpochAndSendRequest>>

* `PartitionStateMachine` is requested to <<kafka-controller-PartitionStateMachine.adoc#initializeLeaderAndIsrForPartitions, initializeLeaderAndIsrForPartitions>> and <<kafka-controller-PartitionStateMachine.adoc#doElectLeaderForPartitions, doElectLeaderForPartitions>>

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#doHandleStateChanges, doHandleStateChanges>>
====

=== [[addUpdateMetadataRequestForBrokers]] `addUpdateMetadataRequestForBrokers` Method

[source, scala]
----
addUpdateMetadataRequestForBrokers(
  brokerIds: Seq[Int],
  partitions: collection.Set[TopicPartition]): Unit
----

`addUpdateMetadataRequestForBrokers`...FIXME

[NOTE]
====
`addUpdateMetadataRequestForBrokers` is used when:

* `ControllerBrokerRequestBatch` is requested to <<addLeaderAndIsrRequestForBrokers, addLeaderAndIsrRequestForBrokers>>

* `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#sendUpdateMetadataRequest, sendUpdateMetadataRequest>>
====

=== [[addStopReplicaRequestForBrokers]] `addStopReplicaRequestForBrokers` Method

[source, scala]
----
addStopReplicaRequestForBrokers(
  brokerIds: Seq[Int],
  topicPartition: TopicPartition,
  deletePartition: Boolean,
  callback: (AbstractResponse, Int) => Unit): Unit
----

`addStopReplicaRequestForBrokers`...FIXME

[NOTE]
====
`addStopReplicaRequestForBrokers` is used when:

* `KafkaController` is requested to process a <<kafka-controller-KafkaController.adoc#ControlledShutdown, ControlledShutdown>> controller event

* `ReplicaStateMachine` is requested to <<kafka-controller-ReplicaStateMachine.adoc#doHandleStateChanges, doHandleStateChanges>>
====

=== [[clear]] `clear` Method

[source, scala]
----
clear(): Unit
----

`clear` simply removes all bindings in the <<leaderAndIsrRequestMap, leaderAndIsrRequestMap>>, <<stopReplicaRequestMap, stopReplicaRequestMap>> and <<updateMetadataRequestBrokerSet, updateMetadataRequestBrokerSet>> internal registries.

NOTE: `clear` is used exclusively when `KafkaController` is requested to <<kafka-controller-KafkaController.adoc#handleIllegalState, handleIllegalState>>.
