== [[FindCoordinatorRequest]] FindCoordinatorRequest

[[FIND_COORDINATOR]][[creating-instance]]
`FindCoordinatorRequest` is a <<kafka-common-requests-AbstractRequest.adoc#, message request>> with *FindCoordinator* API key and the following properties:

* [[coordinatorType]] Coordinator type (i.e. `GROUP` or `TRANSACTION`)
* [[coordinatorKey]] Coordinator key
* [[version]] Version

`FindCoordinatorRequest` is <<creating-instance, created>> when:

* `AbstractRequest` is requested to <<kafka-common-requests-AbstractRequest.adoc#parseRequest, parse a request>> (with the <<FIND_COORDINATOR, FindCoordinator>> API key)

* `FindCoordinatorRequest` is requested to <<parse, parse a byte buffer>>

* `FindCoordinatorRequest.Builder` is requested to <<build, build a FindCoordinatorRequest>>

=== [[FindCoordinatorRequest.Builder]][[Builder]][[build]] `FindCoordinatorRequest.Builder` Utility

`FindCoordinatorRequest.Builder` is a <<kafka-common-requests-AbstractRequest-Builder.adoc#, request builder>> to <<kafka-common-requests-AbstractRequest-Builder.adoc#build, build>> a <<FindCoordinatorRequest, FindCoordinatorRequest>>.

[source, java]
----
FindCoordinatorRequest build(short version)
----

`FindCoordinatorRequest.Builder` is used when...FIXME

=== [[parse]] Creating FindCoordinatorRequest from Byte Buffer -- `parse` Utility

[source, java]
----
FindCoordinatorRequest parse(ByteBuffer buffer, short version)
----

`parse`...FIXME

NOTE: `parse` is used when...FIXME
