== [[CleanerThread]] CleanerThread

`CleanerThread` is <<creating-instance, created>> and immediately <<doWork, started>> when `LogCleaner` is requested to <<kafka-log-LogCleaner.adoc#startup, start up>>.

=== [[cleaner]] CleanerThread and Cleaner

When <<creating-instance, created>>, `CleanerThread` creates a <<kafka-log-Cleaner.adoc#, Cleaner>> (with the <<kafka-log-Cleaner.adoc#id, ID>> as the given <<threadId, threadId>>).

`CleanerThread` uses the `Cleaner` exclusively for <<cleanLog, cleaning up a log>>.

=== [[doWork]] Cleaning Up Dirty Logs -- `doWork` Method

[source, scala]
----
doWork(): Unit
----

NOTE: `doWork` is part of the <<kafka-ShutdownableThread.adoc#doWork, ShutdownableThread Contract>> to do the work.

`doWork` simply <<cleanFilthiestLog, cleanFilthiestLog>>.

If there was no dirty log cleaned up, `doWork` <<kafka-ShutdownableThread.adoc#pause, pauses>> for the <<kafka-log-LogCleaner.adoc#backOffMs, backOffMs>> (of the <<kafka-log-LogCleaner.adoc#config, CleanerConfig>> of the parent <<kafka-log-LogCleaner.adoc#, LogCleaner>>) (default: 15 seconds).

=== [[cleanFilthiestLog]] `cleanFilthiestLog` Internal Method

[source, scala]
----
cleanFilthiestLog(): Boolean
----

`cleanFilthiestLog` requests the <<kafka-log-LogCleaner.adoc#cleanerManager, LogCleanerManager>> to <<kafka-log-LogCleanerManager.adoc#grabFilthiestCompactedLog, grabFilthiestCompactedLog>>.

If there is any filthiest log to work on, `cleanFilthiestLog` <<cleanLog, cleanLog>> and turns the `cleaned` flag on.

With no logs to work on, `cleanFilthiestLog` simply turns the `cleaned` flag off.

NOTE: The value of `cleaned` flag is what `cleanFilthiestLog` returns.

`cleanFilthiestLog` requests the <<kafka-log-LogCleaner.adoc#cleanerManager, LogCleanerManager>> for the <<kafka-log-LogCleanerManager.adoc#deletableLogs, deletable logs>> and then requests every `Log` to <<kafka-log-Log.adoc#deleteOldSegments, deleteOldSegments>>.

In the end, `cleanFilthiestLog` requests the <<kafka-log-LogCleaner.adoc#cleanerManager, LogCleanerManager>> to <<kafka-log-LogCleanerManager.adoc#doneDeleting, doneDeleting>> (with the `TopicPartitions` of the deletable logs).

In case of an exception, `cleanFilthiestLog`...FIXME

NOTE: `cleanFilthiestLog` is used exclusively when `CleanerThread` is requested to <<doWork, doWork>>.

=== [[cleanLog]] Cleaning Log -- `cleanLog` Internal Method

[source, scala]
----
cleanLog(cleanable: LogToClean): Unit
----

`cleanLog` requests the <<cleaner, Cleaner>> to <<kafka-log-Cleaner.adoc#clean, clean>> the given <<kafka-log-Log.adoc#, Log>> (as `LogToClean`) followed by <<recordStats, recordStats>>.

In the end, `cleanLog` requests the <<kafka-log-LogCleaner.adoc#cleanerManager, LogCleanerManager>> to <<kafka-log-LogCleanerManager.adoc#doneCleaning, doneCleaning>>.

NOTE: `cleanLog` is used exclusively when `CleanerThread` is requested to <<cleanFilthiestLog, cleanFilthiestLog>>.

=== [[recordStats]] `recordStats` Internal Method

[source, scala]
----
recordStats(
  id: Int,
  name: String,
  from: Long,
  to: Long,
  stats: CleanerStats): Unit
----

`recordStats`...FIXME

NOTE: `recordStats` is used exclusively when `CleanerThread` is requested to <<cleanLog, cleanLog>>.
