== [[KafkaConfig]] KafkaConfig

`KafkaConfig` is the configuration of a Kafka server and the services.

`KafkaConfig` is <<creating-instance, created>> when:

* `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#initialize, initialize>> and <<kafka-server-DynamicBrokerConfig.adoc#processReconfiguration, processReconfiguration>>

* `KafkaConfig` is requested to <<fromProps, fromProps>> and <<apply, apply>>

[[configuration-values]]
.KafkaConfig's Configuration Values
[cols="1m,2",options="header",width="100%"]
|===
| Value
| Kafka Property

| advertisedListeners
a| [[advertisedListeners]] <<kafka-properties.adoc#advertised.listeners, advertised.listeners>>

Used when:

* `DynamicListenerConfig` is requested to <<kafka-server-DynamicListenerConfig.adoc#validateReconfiguration, validateReconfiguration>>

* `KafkaConfig` is requested to <<validateValues, validateValues>>

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#createBrokerInfo, createBrokerInfo>> (when <<kafka-KafkaServer.adoc#startup, started>>)

| autoLeaderRebalanceEnable
a| [[autoLeaderRebalanceEnable]] <<kafka-properties.adoc#auto.leader.rebalance.enable, auto.leader.rebalance.enable>>

Used exclusively when `KafkaController` is requested to <<kafka-KafkaController.adoc#onControllerFailover, onControllerFailover>>

| backgroundThreads
| [[backgroundThreads]] <<kafka-properties.adoc#background.threads, background.threads>>

| brokerId
| [[brokerId]] <<kafka-properties.adoc#broker.id, broker.id>>

| brokerIdGenerationEnable
a| [[brokerIdGenerationEnable]] <<kafka-properties.adoc#broker.id.generation.enable, broker.id.generation.enable>>

Used exclusively when `KafkaServer` is requested to <<kafka-KafkaServer.adoc#getBrokerIdAndOfflineDirs, getBrokerIdAndOfflineDirs>>

| deleteTopicEnable
| [[deleteTopicEnable]] link:kafka-properties.adoc#delete.topic.enable[delete.topic.enable]

| hostName
| [[hostName]] link:kafka-properties.adoc#host.name[host.name]

| leaderImbalanceCheckIntervalSeconds
a| [[leaderImbalanceCheckIntervalSeconds]] <<kafka-properties.adoc#leader.imbalance.check.interval.seconds, leader.imbalance.check.interval.seconds>>

Used exclusively when `ControllerEventThread` is requested to process a <<kafka-ControllerEvent.adoc#AutoPreferredReplicaLeaderElection, AutoPreferredReplicaLeaderElection>> event (while <<kafka-ControllerEventThread.adoc#doWork, processing controller events>>)

| listeners
| [[listeners]] link:kafka-properties.adoc#listeners[listeners] (see <<getListeners, getListeners>>)

| logDirs
a| [[logDirs]] <<kafka-properties.adoc#log.dirs, log.dirs>> or <<kafka-properties.adoc#log.dir, log.dir>>

At least one log directory must be defined via <<kafka-properties.adoc#log.dirs, log.dirs>> or <<kafka-properties.adoc#log.dir, log.dir>> properties.

Used when:

* `LogManager` is <<kafka-LogManager.adoc#logDirs, created>>

* `LogDirFailureChannel` is created (when `KafkaServer` is requested to <<kafka-KafkaServer.adoc#startup, start up>>)

* `KafkaConfig` is requested to <<getNumReplicaAlterLogDirsThreads, getNumReplicaAlterLogDirsThreads>>

* `KafkaServer` is <<kafka-KafkaServer.adoc#brokerMetadataCheckpoints, created>> and is requested to <<kafka-KafkaServer.adoc#getBrokerIdAndOfflineDirs, getBrokerIdAndOfflineDirs>> and <<kafka-KafkaServer.adoc#checkpointBrokerId, checkpointBrokerId>>

* `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#describeLogDirs, describeLogDirs>>

| maxReservedBrokerId
a| [[maxReservedBrokerId]] <<kafka-properties.adoc#reserved.broker.max.id, reserved.broker.max.id>>

Used exclusively when `KafkaServer` is requested to <<kafka-KafkaServer.adoc#generateBrokerId, generateBrokerId>>

| numNetworkThreads
| [[numNetworkThreads]] link:kafka-properties.adoc#num.network.threads[num.network.threads]

| port
| [[port]] link:kafka-properties.adoc#port[port]

| replicaLagTimeMaxMs
| [[replicaLagTimeMaxMs]]

| zkConnect
a| [[zkConnect]] <<kafka-properties.adoc#zookeeper.connect, zookeeper.connect>>

Used when:

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkEnableSecureAcls
a| [[zkEnableSecureAcls]] <<kafka-properties.adoc#zookeeper.set.acl, zookeeper.set.acl>>

Used when:

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkSessionTimeoutMs
a| [[zkSessionTimeoutMs]] <<kafka-properties.adoc#zookeeper.session.timeout.ms, zookeeper.session.timeout.ms>>

Used when:

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkConnectionTimeoutMs
a| [[zkConnectionTimeoutMs]] <<kafka-properties.adoc#zookeeper.connection.timeout.ms, zookeeper.connection.timeout.ms>> when set or <<kafka-properties.adoc#zookeeper.session.timeout.ms, zookeeper.session.timeout.ms>>

Used when:

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>

| zkMaxInFlightRequests
a| [[zkMaxInFlightRequests]] <<kafka-properties.adoc#zookeeper.max.in.flight.requests, zookeeper.max.in.flight.requests>>

Used when:

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#initZkClient, initZkClient>>

* `SimpleAclAuthorizer` is requested to <<kafka-security-SimpleAclAuthorizer.adoc#configure, configure>>
|===

[[internal-registries]]
.KafkaConfig's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| dynamicConfig
a| [[dynamicConfig]] <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>> (that could be <<dynamicConfigOverride, provided>> or is going to be <<kafka-server-DynamicBrokerConfig.adoc#creating-instance, created from scratch>>)

Used when:

* `AdminManager` is requested to <<kafka-AdminManager.adoc#describeConfigs, describeConfigs>> (for `BROKER` resources), <<kafka-AdminManager.adoc#alterConfigs, alterConfigs>> and <<kafka-AdminManager.adoc#configSynonyms, configSynonyms>>

* `BrokerConfigHandler` is requested to <<kafka-server-BrokerConfigHandler.adoc#processConfigChanges, processConfigChanges>>

* `DynamicMetricsReporters` is <<kafka-server-DynamicMetricsReporters.adoc#dynamicConfig, created>>

* `DynamicClientQuotaCallback` is <<kafka-server-DynamicClientQuotaCallback.adoc#reconfigure, reconfigure>>

* `KafkaConfig` is requested to <<addReconfigurable, addReconfigurable>>

* `KafkaServer` is requested to <<kafka-KafkaServer.adoc#startup, start up>>
|===

=== [[getListeners]] Creating Listeners -- `getListeners` Internal Method

[source, scala]
----
getListeners: Seq[EndPoint]
----

`getListeners` creates the `EndPoints` if defined using link:kafka-properties.adoc#listeners[listeners] Kafka property or defaults to `PLAINTEXT://[hostName]:[port]` (for <<hostName, hostName>> and <<port, port>> Kafka properties).

NOTE: `getListeners` is used when `KafkaConfig` is <<listeners, created>> and for <<getAdvertisedListeners, getAdvertisedListeners>>.

=== [[getNumReplicaAlterLogDirsThreads]] `getNumReplicaAlterLogDirsThreads` Method

[source, scala]
----
getNumReplicaAlterLogDirsThreads: Int
----

`getNumReplicaAlterLogDirsThreads`...FIXME

NOTE: `getNumReplicaAlterLogDirsThreads` is used when...FIXME

=== [[creating-instance]] Creating KafkaConfig Instance

`KafkaConfig` takes the following when created:

* [[props]] Key-value properties
* [[doLog]] `doLog` flag
* [[dynamicConfigOverride]] <<kafka-server-DynamicBrokerConfig.adoc#, DynamicBrokerConfig>>

`KafkaConfig` initializes the <<internal-registries, internal registries and counters>>.

=== [[fromProps]] Creating KafkaConfig From Java Properties -- `fromProps` Object Method

[source, scala]
----
fromProps(props: Properties): KafkaConfig // <1>
fromProps(props: Properties, doLog: Boolean): KafkaConfig
fromProps(defaults: Properties, overrides: Properties): KafkaConfig // <2>
fromProps(defaults: Properties, overrides: Properties, doLog: Boolean): KafkaConfig // <3>
----
<1> Seems to be used in tests only
<2> Seems to be used in tests only
<3> Seems to be used in tests only

`fromProps`...FIXME

[NOTE]
====
`fromProps` is used when:

* `KafkaServerStartable` is requested to <<kafka-KafkaServerStartable.adoc#fromProps, create a KafkaServerStartable from Java Properties>>

* `SimpleAclAuthorizer` is requested to `configure` itself
====

=== [[apply]] Creating KafkaConfig -- `apply` Factory Method

[source, scala]
----
apply(props: java.util.Map[_, _]): KafkaConfig
----

`apply` simply creates a <<creating-instance, KafkaConfig>> with the `props` and the <<doLog, doLog>> flag on.

NOTE: `apply` seems to be used in tests only.

=== [[addReconfigurable]] `addReconfigurable` Method

[source, scala]
----
addReconfigurable(reconfigurable: Reconfigurable): Unit
----

`addReconfigurable`...FIXME

NOTE: `addReconfigurable` is used when...FIXME

=== [[validateValues]] `validateValues` Internal Method

[source, scala]
----
validateValues(): Unit
----

`validateValues`...FIXME

NOTE: `validateValues` is used when...FIXME
