== [[Partition]] Partition

A Kafka topic is spread across a Kafka cluster as a virtual group of one or more *partitions*.

A single partition of a topic (*topic partition*) can be replicated across a Kafka cluster to one or more Kafka brokers.

A topic partition has one partition leader node and zero or more replicas.

Kafka producers publish messages to topic leaders as do Kafka consumers consume them from.

*In-Sync Replicas* (ISR) are brokers that...FIXME

*Offline Replicas* are...FIXME

`Partition` is...FIXME

[[internal-registries]]
.Partition's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| inSyncReplicas
| [[inSyncReplicas]] In-sync <<kafka-cluster-Replica.adoc#, Replicas>>

| leaderReplicaIdOpt
| [[leaderReplicaIdOpt]] Optional leader replica ID

| localBrokerId
a| [[localBrokerId]] One of the following:

* `broker.id` configuration property (from the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>>

* `-1` if <<isOffline, offline>>

| logManager
a| [[logManager]] <<kafka-LogManager.adoc#, LogManager>> (of the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>> or `null`

| zkClient
a| [[zkClient]] `KafkaZkClient` (of the <<replicaManager, ReplicaManager>>) if not <<isOffline, offline>> or `null`

| topicPartition
| [[topicPartition]] `TopicPartition` (with the <<topic, topic>> and <<partitionId, partitionId>>)
|===

=== [[maybeExpandIsr]] `maybeExpandIsr` Method

[source, scala]
----
maybeExpandIsr(replicaId: Int, logReadResult: LogReadResult): Boolean
----

`maybeExpandIsr`...FIXME

NOTE: `maybeExpandIsr` is used exclusively when `Partition` is requested to <<updateReplicaLogReadResult, updateReplicaLogReadResult>>.

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

[source, scala]
----
maybeShrinkIsr(replicaMaxLagTimeMs: Long): Unit
----

`maybeShrinkIsr`...FIXME

NOTE: `maybeShrinkIsr` is used exclusively when `ReplicaManager` link:kafka-server-ReplicaManager.adoc#maybeShrinkIsr[maybeShrinkIsr].

=== [[updateReplicaLogReadResult]] `updateReplicaLogReadResult` Method

[source, scala]
----
updateReplicaLogReadResult(replica: Replica, logReadResult: LogReadResult): Boolean
----

`updateReplicaLogReadResult`...FIXME

NOTE: `updateReplicaLogReadResult` is used exclusively when `ReplicaManager` link:kafka-server-ReplicaManager.adoc#updateFollowerLogReadResults[updateFollowerLogReadResults].

=== [[updateIsr]] `updateIsr` Internal Method

[source, scala]
----
updateIsr(newIsr: Set[Replica]): Unit
----

`updateIsr`...FIXME

NOTE: `updateIsr` is used when `Partition` is requested to <<maybeExpandIsr, expand>> or <<maybeShrinkIsr, shrink>> the ISR.

=== [[makeFollower]] `makeFollower` Method

[source, scala]
----
makeFollower(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeFollower`...FIXME

NOTE: `makeFollower` is used...FIXME

=== [[leaderReplicaIfLocal]] `leaderReplicaIfLocal` Method

[source, scala]
----
leaderReplicaIfLocal: Option[Replica]
----

`leaderReplicaIfLocal` gives...FIXME

NOTE: `leaderReplicaIfLocal` is used...FIXME

=== [[maybeShrinkIsr]] `maybeShrinkIsr` Method

CAUTION: FIXME

=== [[creating-instance]] Creating Partition Instance

`Partition` takes the following when created:

* [[topic]] Topic name
* [[partitionId]] Partition ID
* [[time]] `Time`
* [[replicaManager]] <<kafka-server-ReplicaManager.adoc#, ReplicaManager>>
* [[isOffline]] `isOffline` flag (default: `false`)

`Partition` initializes the <<internal-registries, internal registries and counters>>.

=== [[isUnderReplicated]] `isUnderReplicated` Predicate

[source, scala]
----
isUnderReplicated: Boolean
----

`isUnderReplicated` is `true` only if the partition <<isLeaderReplicaLocal, isLeaderReplicaLocal>> and the number of <<inSyncReplicas, in-sync replicas>> is below the <<assignedReplicas, assignedReplicas>>.

NOTE: `isUnderReplicated` is used when...FIXME

=== [[isUnderMinIsr]] `isUnderMinIsr` Predicate

[source, scala]
----
isUnderMinIsr: Boolean
----

`isUnderMinIsr` is `true` only if the partition <<isLeaderReplicaLocal, isLeaderReplicaLocal>> and the number of <<inSyncReplicas, in-sync replicas>> is below the <<kafka-properties.adoc#min.insync.replicas, min.insync.replicas>> configuration property (as configured for the <<kafka-Log.adoc#, Log>> of the <<leaderReplica, leader replica>>).

NOTE: `isUnderMinIsr` is used when...FIXME

=== [[checkEnoughReplicasReachOffset]] `checkEnoughReplicasReachOffset` Method

[source, scala]
----
checkEnoughReplicasReachOffset(requiredOffset: Long): (Boolean, Errors)
----

`checkEnoughReplicasReachOffset`...FIXME

NOTE: `checkEnoughReplicasReachOffset` is used when...FIXME

=== [[makeLeader]] `makeLeader` Method

[source, scala]
----
makeLeader(
  controllerId: Int,
  partitionStateInfo: LeaderAndIsrRequest.PartitionState,
  correlationId: Int): Boolean
----

`makeLeader`...FIXME

NOTE: `makeLeader` is used exclusively when `ReplicaManager` is requested to <<kafka-server-ReplicaManager.adoc#makeLeaders, makeLeaders>>.
