== [[KafkaScheduler]] KafkaScheduler

`KafkaScheduler` is a concrete <<kafka-Scheduler.adoc#, task scheduler>> that allows for <<schedule, scheduling tasks>> using Java's <<executor, ScheduledThreadPoolExecutor>>.

`KafkaScheduler` uses the requested <<threads, number of threads>> that is usually `1` except for `KafkaServer` that uses <<kafka-properties.adoc#backgroundThreads, background.threads>> configuration property (default: `10`).

`KafkaScheduler` is <<creating-instance, created>> when:

* `KafkaController` is <<kafka-controller-KafkaController.adoc#, created>> (and initializes <<kafka-controller-KafkaController.adoc#kafkaScheduler, kafkaScheduler>> and <<kafka-controller-KafkaController.adoc#tokenCleanScheduler, tokenCleanScheduler>>)

* `GroupMetadataManager` is <<kafka-coordinator-group-GroupMetadataManager.adoc#scheduler, created>>

* `KafkaServer` is requested to <<kafka-server-KafkaServer.adoc#startup, start up>>

* `ZooKeeperClient` is <<kafka-server-KafkaServer.adoc#expiryScheduler, created>>

`KafkaScheduler` is used to create a <<kafka-log-LogManager.adoc#apply, LogManager>> and a <<kafka-TransactionCoordinator.adoc#apply, TransactionCoordinator>>.

[[internal-registries]]
.KafkaScheduler's Internal Properties (e.g. Registries and Counters)
[cols="1m,2",options="header",width="100%"]
|===
| Name
| Description

| executor
| [[executor]] Java's https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html[ScheduledThreadPoolExecutor] that <<schedule, schedules tasks>>.

Initialized when <<startup, `KafkaScheduler` starts up>> and shut down when <<shutdown, `KafkaScheduler` shuts down>>.

| schedulerThreadId
| [[schedulerThreadId]] Java's https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicInteger.html[AtomicInteger] with initial value 0.
|===

[[logging]]
[TIP]
====
Enable `INFO`, `DEBUG` or `TRACE` logging level for `kafka.utils.KafkaScheduler` logger to see what happens in `KafkaScheduler`.

Add the following line to `config/log4j.properties`:

```
log4j.logger.kafka.utils.KafkaScheduler=TRACE
```

Refer to link:kafka-logging.adoc[Logging].
====

=== [[startup]] Starting Up -- `startup` Method

[source, scala]
----
startup(): Unit
----

NOTE: `startup` is part of the <<kafka-Scheduler.adoc#startup, Scheduler Contract>> to initialize the scheduler so it is ready to schedule tasks.

When executed, `startup` prints out the following DEBUG message to the logs:

```
Initializing task scheduler.
```

`startup` creates a <<executor, ScheduledThreadPoolExecutor>> with the <<threads, requested number of threads>>.

`startup` requests the <<executor, ScheduledThreadPoolExecutor>> to disable executing existing link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#setContinueExistingPeriodicTasksAfterShutdownPolicy-boolean-++[periodic] and link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#setExecuteExistingDelayedTasksAfterShutdownPolicy-boolean-++[delayed] tasks after the executor has been shutdown.

`startup` requests the <<executor, ScheduledThreadPoolExecutor>> to link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html#setThreadFactory-java.util.concurrent.ThreadFactory-++[use a custom thread factory] that creates a new `KafkaThread` with the <<threadNamePrefix, threadNamePrefix>> followed by the <<schedulerThreadId, schedulerThreadId>> whenever requested for a new thread (e.g. `kafka-scheduler-0`).

`startup` throws an `IllegalStateException` when the `KafkaScheduler` <<isStarted, has already been started>>:

```
This scheduler has already been started!
```

=== [[shutdown]] `shutdown` Method

[source, scala]
----
shutdown(): Unit
----

NOTE: `shutdown` is part of the <<kafka-Scheduler.adoc#shutdown, Scheduler Contract>> to...FIXME.

`shutdown`...FIXME

=== [[ensureRunning]] `ensureRunning` Internal Method

[source, scala]
----
ensureRunning(): Unit
----

`ensureRunning`...FIXME

NOTE: `ensureRunning` is used when...FIXME

=== [[schedule]] Scheduling Tasks -- `schedule` Method

[source, scala]
----
def schedule(
  name: String,
  fun: () => Unit,
  delay: Long = 0,
  period: Long = -1,
  unit: TimeUnit = TimeUnit.MILLISECONDS)
----

NOTE: `schedule` is part of the <<kafka-Scheduler.adoc#schedule, Scheduler Contract>> to schedule a task.

When `schedule` is executed, you should see the following DEBUG message in the logs:

```
DEBUG Scheduling task [name] with initial delay [delay] ms and period [period] ms. (kafka.utils.KafkaScheduler)
```

NOTE: `schedule` uses Java's link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html#convert-long-java.util.concurrent.TimeUnit-++[java.util.concurrent.TimeUnit] to convert `delay` and `period` to milliseconds.

`schedule` first <<ensureRunning, makes sure that `KafkaScheduler` is running>> (which simply means that the internal <<executor, executor>> has been initialized).

`schedule` creates an execution thread for the input `fun`.

For positive `period`, `schedule` schedules the thread every `period` after the initial `delay`. Otherwise, `schedule` schedules the thread once.

NOTE: `schedule` uses the internal <<executor, executor>> to schedule `fun` using link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.scheduleAtFixedRate] and link:++https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#schedule-java.lang.Runnable-long-java.util.concurrent.TimeUnit-++[ScheduledThreadPoolExecutor.schedule] for periodic and one-off executions, respectively.

Whenever the thread is executed, and before `fun` gets triggerred, you should see the following TRACE message in the logs:

```
Beginning execution of scheduled task '[name]'.
```

After the execution thread is finished, you should see the following TRACE message in the logs:

```
Completed execution of scheduled task '[name]'.
```

In case of any exceptions, the execution thread catches them and you should see the following ERROR message in the logs:

```
Uncaught exception in scheduled task '[name]'
```

=== [[creating-instance]] Creating KafkaScheduler Instance

`KafkaScheduler` takes the following when created:

* [[threads]] Number of threads
* [[threadNamePrefix]] Thread name prefix (default: `kafka-scheduler-`)
* [[daemon]] `daemon` flag (default: `true`)

`KafkaScheduler` initializes the <<internal-registries, internal registries and counters>>.

=== [[scheduleOnce]] `scheduleOnce` Method

[source, scala]
----
scheduleOnce(name: String, fun: () => Unit): Unit
----

`scheduleOnce`...FIXME

NOTE: `scheduleOnce` is used when...FIXME

=== [[resizeThreadPool]] `resizeThreadPool` Method

[source, scala]
----
resizeThreadPool(newSize: Int): Unit
----

`resizeThreadPool`...FIXME

NOTE: `resizeThreadPool` is used exclusively when `DynamicThreadPool` is requested to <<kafka-server-DynamicThreadPool.adoc#reconfigure, reconfigure>>.
