== [[KafkaConsumerGroupService]] KafkaConsumerGroupService

`KafkaConsumerGroupService` is a link:kafka-ConsumerGroupService.adoc[ConsumerGroupService] that link:kafka-ConsumerGroupCommand.adoc[ConsumerGroupCommand] uses for <<listGroups, listing>>, <<describeGroup, describing>> and <<resetOffsets, resetting offsets>> of consumer groups.

`KafkaConsumerGroupService` is <<creating-instance, created>> exclusively when `ConsumerGroupCommand` is link:kafka-ConsumerGroupCommand.adoc#main[executed] (as a standalone command-line application, i.e. using link:kafka-tools-kafka-consumer-groups.adoc[kafka-consumer-groups.sh] shell script).

`KafkaConsumerGroupService` is used by link:kafka-ConsumerGroupCommand.adoc#main[ConsumerGroupCommand] for consumer groups that use the new Java consumer API (and hence do not use Zookeeper to store information).

[[adminClient]]
`KafkaConsumerGroupService` uses link:kafka-AdminClient.adoc[AdminClient] for the actions.

=== [[listGroups]] Listing All Consumer Groups -- `listGroups` Method

[source, scala]
----
listGroups(): List[String]
----

NOTE: `listGroups` is a part of link:kafka-ConsumerGroupService.adoc#listGroups[ConsumerGroupService Contract].

`listGroups` requests <<adminClient, AdminClient>> for link:kafka-AdminClient.adoc#listAllConsumerGroupsFlattened[all consumer groups] and takes their group ids.

NOTE: `listGroups` is used exclusively when `ConsumerGroupCommand` is requested for link:kafka-ConsumerGroupCommand.adoc#list[all consumer groups] using `--list` option.

=== [[describeGroup]] `describeGroup` Method

CAUTION: FIXME

=== [[resetOffsets]] `resetOffsets` Method

CAUTION: FIXME

=== [[creating-instance]] Creating KafkaConsumerGroupService Instance

`KafkaConsumerGroupService` takes the following when created:

* [[opts]] `ConsumerGroupCommandOptions`

`KafkaConsumerGroupService` initializes the <<internal-registries, internal registries and counters>>.

=== [[prepareOffsetsToReset]] `prepareOffsetsToReset` Method

[source, scala]
----
FIXME
----

`prepareOffsetsToReset`...FIXME

NOTE: `prepareOffsetsToReset` is used when...FIXME

=== [[getPartitionsToReset]] `getPartitionsToReset` Method

[source, scala]
----
FIXME
----

`getPartitionsToReset`...FIXME

NOTE: `getPartitionsToReset` is used when...FIXME

=== [[collectGroupAssignment]] `collectGroupAssignment` Method

[source, scala]
----
FIXME
----

`collectGroupAssignment`...FIXME

NOTE: `collectGroupAssignment` is used when...FIXME
