== [[DynamicLogConfig]] DynamicLogConfig

`DynamicLogConfig` is a <<kafka-common-Reconfigurable.adoc#, Reconfigurable>> that...FIXME

`DynamicLogConfig` is <<creating-instance, created>> exclusively when `DynamicBrokerConfig` is requested to <<kafka-server-DynamicBrokerConfig.adoc#addReconfigurables, register Reconfigurables for a KafkaServer>> (when requested to <<kafka-server-KafkaServer.adoc#startup, start up>>).

[[KafkaConfigToLogConfigName]]
`DynamicLogConfig` defines `KafkaConfigToLogConfigName` that are...FIXME...that is used for <<reconfigure, reconfigure>>.

=== [[creating-instance]] Creating DynamicLogConfig Instance

`DynamicLogConfig` takes the following when created:

* [[logManager]] <<kafka-log-LogManager.adoc#, LogManager>>
* [[server]] <<kafka-server-KafkaServer.adoc#, KafkaServer>>

`DynamicLogConfig` initializes the <<internal-registries, internal registries and counters>>.

=== [[ReconfigurableConfigs]][[reconfigurableConfigs]] `reconfigurableConfigs` Method and `ReconfigurableConfigs` Value

[source, scala]
----
reconfigurableConfigs: Set[String]
----

NOTE: `reconfigurableConfigs` is part of the link:kafka-server-BrokerReconfigurable.adoc#reconfigurableConfigs[BrokerReconfigurable] contract to...FIXME.

`reconfigurableConfigs` simply returns the `ReconfigurableConfigs` that are the values of the link:kafka-log-LogConfig.adoc#TopicConfigSynonyms[TopicConfigSynonyms] (of `LogConfig`) except link:kafka-server-KafkaConfig.adoc#LogMessageFormatVersionProp[log.message.format.version].

[NOTE]
====
`ReconfigurableConfigs` is used when:

* `DynamicBrokerConfig` utility is requested for the link:kafka-server-DynamicBrokerConfig.adoc#AllDynamicConfigs[AllDynamicConfigs]

* `DynamicLogConfig` is requested for the <<reconfigurableConfigs, reconfigurableConfigs>> and to <<reconfigure, reconfigure>>
====

=== [[reconfigure]] Reconfiguring -- `reconfigure` Method

[source, scala]
----
reconfigure(
  oldConfig: KafkaConfig,
  newConfig: KafkaConfig): Unit
----

NOTE: `reconfigure` is part of the <<kafka-server-BrokerReconfigurable.adoc#reconfigure, BrokerReconfigurable Contract>> to change (_reconfigure_) the value of a Kafka dynamic configuration.

`reconfigure`...FIXME
