== [[KafkaStreams]] KafkaStreams

`KafkaStreams` is the entry point for *continuous message processing* in Kafka Streams.

NOTE: `KafkaStreams` is "merely" a <<clientSupplier, Kafka client>> that consumes messages from one or many Kafka source topics and publishes the processing results to zero, one or more Kafka target topics.

[[topology]]
`KafkaStreams` processes records through a topology.

NOTE: A Kafka Streams developer defines the processing logic either using a link:kafka-streams-Topology.adoc[Topology] directly (and define a DAG topology of `Processor`s) or indirectly through a link:kafka-streams-StreamsBuilder.adoc[StreamsBuilder] that provides the high-level DSL to define transformations.

[source, scala]
----
import org.apache.kafka.streams.KafkaStreams
val topology: Topology = ...
val config: StreamsConfig = ...
val ks = new KafkaStreams(topology, config)
----

Once <<creating-instance, created>>, you should <<start, start>> `KafkaStreams` to start consuming, processing, and producing records (described in <<topology, Topology>>).

[source, scala]
----
ks.start()
----

[[internal-registries]]
.KafkaStreams's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[globalStreamThread]] `globalStreamThread`
| Global stream thread (`GlobalStreamThread`) that...FIXME

| [[stateDirectory]] `stateDirectory`
| `StateDirectory`

| [[threads]] `threads`
a| Collection of link:kafka-streams-StreamThread.adoc[StreamThread] stream processor threads

NOTE: The number of `threads` is controlled using link:kafka-streams-properties.adoc#num.stream.threads[num.stream.threads] configuration property with the default being 1 thread.

* Created when `KafkaStreams` is <<creating-instance, created>>
* Started when `KafkaStreams` is <<start, started>>
* Shut down when `KafkaStreams` is <<close, closed>>
|===

[[logging]]
[TIP]
====
Enable `DEBUG` logging level for `org.apache.kafka.streams.KafkaStreams` logger to see what happens inside.

Add the following line to `log4j.properties`:

```
log4j.logger.org.apache.kafka.streams.KafkaStreams=DEBUG
```

Refer to link:../kafka-logging.adoc#log4j.properties[Application Logging Using log4j].
====

=== [[start]] Starting KafkaStreams -- `start` Method

[source, java]
----
public synchronized void start()
  throws IllegalStateException, StreamsException
----

`start` starts <<topology, Topology>> (and so consuming, processing, and producing records).

NOTE: `start` is called and is actually when a Kafka Streams application starts processing records.

Internally, `start` prints out the following DEBUG message to the logs:

```
Starting Streams client
```

`start` <<setRunningFromCreated, sets state to running>> (and notifies link:kafka-streams-StateListener.adoc[StateListeners]).

`start` starts <<globalStreamThread, global stream thread>> if defined (which is when...FIXME)

`start` starts <<threads, stream threads>>.

`start` schedules a thread that requests <<stateDirectory, StateDirectory>> to `cleanRemovedTasks` every link:kafka-streams-properties.adoc#state.cleanup.delay.ms[state.cleanup.delay.ms] milliseconds.

You should see the following DEBUG message in the logs:

```
Started Streams client
```

In case the <<setRunningFromCreated, changing state to running>> fails, `start` merely prints out the following ERROR message to the logs:

```
Already stopped, cannot re-start
```

=== [[close]] Closing KafkaStreams -- `close` Method

[source, scala]
----
void close()  // <1>
synchronized boolean close(final long timeout, final TimeUnit timeUnit)
----
<1> Calls `close(final long timeout, final TimeUnit timeUnit)` with 0 timeout

`close`...FIXME

NOTE: `close` is used when...FIXME

=== [[localThreadsMetadata]] `localThreadsMetadata` Method

[source, scala]
----
Set<ThreadMetadata> localThreadsMetadata()
----

`localThreadsMetadata`...FIXME

NOTE: `localThreadsMetadata` is used when...FIXME

=== [[creating-instance]] Creating KafkaStreams Instance

[source, java]
----
// public API
KafkaStreams(
  final Topology topology,
  final Properties props) // <1>
KafkaStreams(
  final Topology topology,
  final StreamsConfig config) // <2>

// public API (mostly for testing)
KafkaStreams(
  final Topology topology,
  final StreamsConfig config,
  final KafkaClientSupplier clientSupplier) // <3>
KafkaStreams(
  final Topology topology,
  final StreamsConfig config,
  final Time time)  // <4>

// private/internal API
KafkaStreams(
  final InternalTopologyBuilder internalTopologyBuilder,
  final StreamsConfig config,
  final KafkaClientSupplier clientSupplier) // <5>
KafkaStreams(
  final InternalTopologyBuilder internalTopologyBuilder,
  final StreamsConfig config,
  final KafkaClientSupplier clientSupplier,
  final Time time)  // <6>
----
<1> Calls `KafkaStreams` (2) with `StreamsConfig` with the input `props`
<2> Calls `KafkaStreams` (3) with `DefaultKafkaClientSupplier`
<5> Calls the internal `KafkaStreams` (6) with `SystemTime`

`KafkaStreams` takes the following when created:

* [[internalTopologyBuilder]] link:kafka-streams-InternalTopologyBuilder.adoc[InternalTopologyBuilder]
* [[config]] link:kafka-streams-StreamsConfig.adoc[StreamsConfig]
* [[clientSupplier]] link:kafka-streams-KafkaClientSupplier.adoc[KafkaClientSupplier]
* [[time]] `Time`

`KafkaStreams` initializes the <<internal-registries, internal registries and counters>>.

`KafkaStreams` is <<creating-instance, created>> when...FIXME

=== [[setRunningFromCreated]] `setRunningFromCreated` Internal Method

[source, java]
----
boolean setRunningFromCreated()
----

`setRunningFromCreated`...FIXME

NOTE: `setRunningFromCreated` is used exclusively when `KafkaStreams` is <<start, started>>.
