== [[InternalTopologyBuilder]] InternalTopologyBuilder

`InternalTopologyBuilder` is...FIXME

[[internal-registries]]
.InternalTopologyBuilder's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[nodeFactories]] `nodeFactories`
| Collection of named link:kafka-streams-NodeFactory.adoc[NodeFactories]

Used when...FIXME

| [[nodeGrouper]] `nodeGrouper`
| Names of...FIXME

Used when...FIXME

| [[nodeToSourceTopics]] `nodeToSourceTopics`
| Names of source nodes and their topics

Used when...FIXME

| [[sourceTopicNames]] `sourceTopicNames`
| Collection of <<addSource, registered>> topic names

Used when...FIXME
|===

=== [[addSource]] Registering New Source Topic -- `addSource` Method

[source, scala]
----
void addSource(
  final Topology.AutoOffsetReset offsetReset,
  final String name,
  final TimestampExtractor timestampExtractor,
  final Deserializer keyDeserializer,
  final Deserializer valDeserializer,
  final String... topics)
----

For every topic name in the input `topics`, `addSource`:

1. <<validateTopicNotAlreadyRegistered, validateTopicNotAlreadyRegistered>>
1. <<maybeAddToResetList, maybeAddToResetList>>
1. Adds the topic name to <<sourceTopicNames, sourceTopicNames>>

`addSource` registers a link:kafka-streams-SourceNodeFactory.adoc[SourceNodeFactory] under the `name` in <<nodeFactories, nodeFactories>> registry.

`addSource` registers `topics` under the `name` in <<nodeToSourceTopics, nodeToSourceTopics>> registry.

`addSource` adds `name` to <<nodeGrouper, nodeGrouper>> registry.

[NOTE]
====
`addSource` is used when:

* `Topology` is rquested to link:kafka-streams-Topology.adoc#addSource[add a source node]
* `InternalStreamsBuilder` is requested to link:kafka-streams-InternalStreamsBuilder.adoc#createKTable[createKTable] or link:kafka-streams-InternalStreamsBuilder.adoc#stream[stream]
* `KGroupedTableImpl` is requested to `buildAggregate`
* `KStreamImpl` is requested to link:kafka-streams-KStreamImpl.adoc#createReparitionedSource[createReparitionedSource]
====

=== [[maybeAddToResetList]] `maybeAddToResetList` Internal Method

[source, scala]
----
void maybeAddToResetList(
  final Collection<T> earliestResets,
  final Collection<T> latestResets,
  final Topology.AutoOffsetReset offsetReset,
  final T item)
----

`maybeAddToResetList`...FIXME

NOTE: `maybeAddToResetList` is used when...FIXME

=== [[validateTopicNotAlreadyRegistered]] `validateTopicNotAlreadyRegistered` Internal Method

[source, scala]
----
void validateTopicNotAlreadyRegistered(final String topic)
----

`validateTopicNotAlreadyRegistered`...FIXME

NOTE: `validateTopicNotAlreadyRegistered` is used when...FIXME

=== [[build]] Building Processor Task Topology -- `build` Factory Method

[source, java]
----
synchronized ProcessorTopology build()
synchronized ProcessorTopology build(final Integer topicGroupId)
ProcessorTopology build(final Set<String> nodeGroup)
----

`build`...FIXME

[NOTE]
====
`build` is used internally when:

* `InternalTopologyBuilder` is requested to <<buildGlobalStateTopology, build a global processor task topology>>
* `StandbyTaskCreator` is requested to create a `StandbyTask`
* `TaskCreator` is requested to create a `StreamTask`
====

=== [[buildGlobalStateTopology]] Building Global Processor Task Topology -- `buildGlobalStateTopology` Method

[source, java]
----
synchronized ProcessorTopology buildGlobalStateTopology()
----

`buildGlobalStateTopology`...FIXME

[NOTE]
====
`buildGlobalStateTopology` is used when:

* `KafkaStreams` is link:kafka-streams-KafkaStreams.adoc#creating-instance[created]
* `ProcessorTopology` is requested to `buildGlobalStateTopology`
====

=== [[sourceTopicPattern]] `sourceTopicPattern` Method

[source, java]
----
synchronized Pattern sourceTopicPattern()
----

`sourceTopicPattern`...FIXME

NOTE: `sourceTopicPattern` is used when...FIXME
