== [[KStreamImpl]] KStreamImpl

`KStreamImpl` is...FIXME

[[internal-registries]]
.KStreamImpl's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[defaultKeyValueMapper]] `defaultKeyValueMapper`
| link:kafka-streams-KeyValueMapper.adoc[KeyValueMapper]
|===

=== [[createReparitionedSource]] `createReparitionedSource` Method

[source, scala]
----
String createReparitionedSource(
  final InternalStreamsBuilder builder,
  final Serde<K1> keySerde,
  final Serde<V1> valSerde,
  final String topicNamePrefix,
  final String name)
----

`createReparitionedSource`...FIXME

NOTE: `createReparitionedSource` is used when...FIXME

=== [[creating-instance]] Creating KStreamImpl Instance

`KStreamImpl` takes the following when created:

* [[builder]] link:kafka-streams-InternalStreamsBuilder.adoc[InternalStreamsBuilder] that created the `KStreamImpl`
* [[name]] Name of the stream processor node
* [[sourceNodes]] Source nodes
* [[repartitionRequired]] Flag whether repartitioning is required or not

`KStreamImpl` initializes the <<internal-registries, internal registries and counters>>.

`KStreamImpl` is <<creating-instance, created>> when...FIXME
