== [[StreamsBuilder]] StreamsBuilder

[[topology]]
`StreamsBuilder` is the *high-level stream processing DSL* in Kafka Streams to define transformations of a message stream that all together create a link:kafka-streams-Topology.adoc[topology].

[[internalStreamsBuilder]]
`StreamsBuilder` uses link:kafka-streams-InternalStreamsBuilder.adoc[InternalStreamsBuilder] for...FIXME

=== [[stream]] `stream` Factory Method

[source, java]
----
synchronized <K, V> KStream<K, V> stream(final String topic)  // <1>
synchronized <K, V> KStream<K, V> stream(final Pattern topicPattern)
synchronized <K, V> KStream<K, V> stream(final Collection<String> topics) // <2>
synchronized <K, V> KStream<K, V> stream(
  final Collection<String> topics,
  final Consumed<K, V> consumed)
synchronized <K, V> KStream<K, V> stream(
  final Pattern topicPattern,
  final Consumed<K, V> consumed)
----
<1> Calls `stream(final Collection<String> topics)`
<2> Calls `stream(final Collection<String> topics, final Consumed<K, V> consumed)` with `Consumed` with all fields `null`

`stream` creates a link:kafka-streams-KStream.adoc[KStream] (of keys of type `K` and values of type `V`) for the defined topic(s) and the parameters in the input link:kafka-streams-Consumed.adoc[consumed].

Internally, `stream` requests <<internalStreamsBuilder, InternalStreamsBuilder>> to link:kafka-streams-InternalStreamsBuilder.adoc#stream[create a KStream] for the input `topics` and a `ConsumedInternal` for the input `consumed`.
