== [[TaskManager]] TaskManager

`TaskManager` is...FIXME

=== [[addStreamTasks]] `addStreamTasks` Internal Method

[source, java]
----
void addStreamTasks(final Collection<TopicPartition> assignment)
----

`addStreamTasks`...FIXME

NOTE: `addStreamTasks` is used exclusively when `TaskManager` is requested to <<createTasks, create processor tasks for assigned topic partitions>>.

=== [[createTasks]] Creating Processor Tasks for Assigned Topic Partitions -- `createTasks` Method

[source, java]
----
void createTasks(final Collection<TopicPartition> assignment)
----

`createTasks`...FIXME

NOTE: `createTasks` is used exclusively when `RebalanceListener` handles link:kafka-streams-StreamThread-RebalanceListener.adoc#onPartitionsAssigned[onPartitionsAssigned].

=== [[addStandbyTasks]] `addStandbyTasks` Internal Method

[source, java]
----
void addStreamTasks(final Collection<TopicPartition> assignment)
----

`addStandbyTasks`...FIXME

NOTE: `addStandbyTasks` is used exclusively when `TaskManager` is requested to <<createTasks, create tasks for assigned topic partitions>>.

=== [[process]] `process` Method

[source, java]
----
int process()
----

`process`...FIXME

NOTE: `process` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#processAndMaybeCommit[processAndMaybeCommit].

=== [[updateNewAndRestoringTasks]] `updateNewAndRestoringTasks` Method

[source, java]
----
boolean updateNewAndRestoringTasks()
----

`updateNewAndRestoringTasks`...FIXME

NOTE: `updateNewAndRestoringTasks` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#runOnce[consume records once].

=== [[activeTask]] Getting Active Stream Processor Task for Topic Partition -- `activeTask` Method

[source, java]
----
StreamTask activeTask(final TopicPartition partition)
----

`activeTask`...FIXME

NOTE: `activeTask` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#addRecordsToTasks[addRecordsToTasks].

=== [[hasActiveRunningTasks]] `hasActiveRunningTasks` Method

[source, java]
----
boolean hasActiveRunningTasks()
----

`hasActiveRunningTasks`...FIXME

NOTE: `hasActiveRunningTasks` is used exclusively when `StreamThread` is requested to link:kafka-streams-StreamThread.adoc#runOnce[consume records once].
